### ISSUE TITLE
Crash on initial save

### ISSUE THREAD

**Issue by snauth** [olivierkes/manuskript#1]
On Arch linux (Python 3.5.1) both with the latest release and the git version I start the program, select research paper (or whatever) and press "create". The program crashes after I have selected a file name and press "save".

>manuskript git:(master) ./bin/manuskript 
>Failed to load translator for en_US...
>True
>['/home/username/.icons', '/usr/share/icons', '/usr/share/pixmaps', ':/icons', '/tmp/manuskript/icons']
>Traceback (most recent call last):
>  File "/tmp/manuskript/bin/../manuskript/ui/welcome.py", line 154, in createFile
>    self.mw.loadProject(filename, loadFromFile=False)
>  File "/tmp/manuskript/bin/../manuskript/mainWindow.py", line 309, in loadProject
>    self.makeConnections()
>  File "/tmp/manuskript/bin/../manuskript/mainWindow.py", line 665, in makeConnections
>    self.treeWorld.setModel(self.mdlWorld)
>AttributeError: 'MainWindow' object has no attribute 'mdlWorld'
>Fatal Python error: Aborted
>
>Current thread 0x00007f1326e67700 (most recent call first):
>  File "/tmp/manuskript/bin/../manuskript/main.py", line 63 in launch
>  File "/tmp/manuskript/bin/../manuskript/main.py", line 54 in run
>  File "./bin/manuskript", line 13 in <module>
>[1]    22955 abort (core dumped)  ./bin/manuskript

**Comment by olivierkes** [comment]
Thanks a lot for posting the first issue :)
I corrected it in the last commit.
Please try again the latest git version.

**Comment by snauth** [comment]
Thanks! Works as advertized now.
