### ISSUE TITLE
Multiple selections of items sometimes gets Notes/references field to be ereased

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#10]
In outline or index cards mode, when selecting multiple items with different values for notes/references sometimes get them to be erased, while the placeholder text keeps indicating "Various" even when selecting single item.

**Comment by gedakc** [comment]
In **Redaction** mode if I select several scenes, **Various** is shown under **Notes / References**.

Then if I click in the **Notes / References** section, I can type some _text_.  This _text_ then overwrites any previous notes for all the scenes currently selected.

Perhaps this is similar to the behaviour you witnessed?

Some writers might like this behaviour, whereas others might not.  I tried to use **Ctrl+Z** to undo the changes, but the _text_ I manually typed remained in the **Notes / References** section of the selected scenes.

**Comment by olivierkes** [comment]
This is intended behavior, and allows to change values for multiple items. I think it's necessary for POV, Status, Label, Goal and so on. 

I think it might still be useful for **Notes / References**.

Maybe a warning should be added, instead of *Various*, something like *Various (Warning: entering text now will override all values)* ?

**Comment by gedakc** [comment]
Thanks @olivierkes for the extra description of this behaviour.  I agree that the _multiple-select-and-change_ behaviour makes sense for POV, Status, Label, Compile, and Goal.  In fact it could be very useful for a write to quickly update these items across many scenes at once.

Regarding Summary or Notes / References, my significant other (a writer) and I do not think that this behaviour provides value for Summary or Notes / References.  These two items can contain much more information.  This information is not easy to reproduce, and should not be easy to overwrite all-at-once.

Our vote would be to disable this _multiple-select-and-change_ behaviour for **Summary** and **Notes / References** (if possible).

While demonstrating the behaviour, I encountered the issue as mentioned in the title.  It seems that simply selecting multiple scenes can cause the **Notes / References** to be erased.  Hence we do indeed have a bug somewhere that we'll need to fix.

**Comment by olivierkes** [comment]
Seems right to me, I'll do that.
