### ISSUE TITLE
Setting the language to German deletes shortcut-functions like "Ctrl+S" 

### ISSUE THREAD

**Issue by HeldHannes** [olivierkes/manuskript#1012]
Hi I'm form Germany and tested manuscript for writing.

Unfortunatelly the Shortcuts for quick saving (Ctrl+S) and others (less important functions) are not working when choosing german interface language.

I always have to use the mouse clicking on "Datei" and "Speichern". 
(This was in version 0.9.x so I updated to 0.13.1, but the issue remains)

Software Versions in Use:
     Python 3.6.9
     PyQt 5.10.1
     Qt 5.9.5
under Linux Mint 19.1

How can I fix the translation to be able to use these shortcuts?

Thanks for answering.

**Comment by TheJackiMonster** [comment]
Functionality and language should actually be independent. So I think this requires some debugging. This might be a bug.

**Comment by TheJackiMonster** [comment]
I can definitely reproduce that. I think some strings defining the key bindings got translated for some reason. I'll try to look into it. ^^'

**Comment by TheJackiMonster** [comment]
I've removed the translation from all shortcuts ( [cc8924a](https://github.com/olivierkes/manuskript/commit/cc8924ada6e6164730fa19e1b6e117ba06b39868) ). So this issue should be fixed for the upcoming release.
