### ISSUE TITLE
Creating empty language file hr-HR

### ISSUE THREAD

**Issue by ElizabethWega** [olivierkes/manuskript#1023]
Hello! I've been trying for hours to generate the language file myself, but with no success. I would want to translate Manuskript into Croatian and I'd be really thankful for the file. Thanks in advance!

**Comment by TheJackiMonster** [comment]
You can technically use `make i18n` to generate all .ts files from the .qm files in the "i18n" subdirectory from the repository. So you can use the Qt Linguist tool to edit the .qm files, generate the .ts files and commit those changes files via Github as PR. However it is far easier to commit translations via our page on Weblate [here](https://hosted.weblate.org/projects/manuskript/translations/). So I'd suggest to use that. (The first option would only be really valuable for people without good internet connection to make changes offline, I assume.)
Before each release I will go through all the changes on Weblate and merge them into Manuskript here on Github. So it will take a little longer to see your changes over here but that shouldn't be an issue.
Thanks for helping us!

**Comment by ElizabethWega** [comment]
Translating Manuskript into Croatian is officially done!

**Comment by TheJackiMonster** [comment]
I've merged the latest changes from Weblate now. So the next version will include your efforts. Big thanks.
