### ISSUE TITLE
manuskript cannot find xelatex on Ubuntu 20.04

### ISSUE THREAD

**Issue by victorkane** [olivierkes/manuskript#1024]
Hi there, thanks for great open source project! Using Manuskript on Ubuntu 20.04. Exports working fine, and although on the command line I can invoke pandoc fine (path configured in Manuskript fine) both in Manuskript and on the command line without manuscript (where I can invoke pdf-engine xelatex with no problem) I cannot find a place to let Manuskript know it should use the xelatex pdf-engine instead of the (hard-coded?) `--pdf-engine=pdflatex` option mentioned in the error message:

Error message in full:

```bash
ERROR on export
Return code: 43
Command and parameters:
['pandoc', '--from=markdown', '--standalone', '--toc-depth=3', '--base-header-level=1', '--pdf-engine=pdflatex', '--variable=papersize:letter', '--variable=fontsize:12pt', '--variable=documentclass:article', '--variable=linestretch:1', '--to=latex', '--output=/mnt/DATOS/Dropbox/Dropbox/PraxisPoetica/resources/tools-n-worksheets/writing-tools/manuskript/book-of-acts-m.pdf', '--variable=title:The Acts of the Apostles', '--variable=author:Luke', '--metadata=title:The Acts of the Apostles']
Stderr content:
Error producing PDF.
! Package inputenc Error: Unicode character ✡ (U+2721)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.283 among the people.'✡

Try running pandoc with --pdf-engine=xelatex.
```

Note last line reference to xelatex pdf-engine.

The rest of the error is (using the Manuskript demo file) `Error: Unicode character ✡ (U+2721) (inputenc) not set up for use with LaTeX. 

On the command line, invoking pdf-engine xelatex, even though this error was mentioned, the pdf was successfully created

Thanks in anticipation!!!

**Comment by TheJackiMonster** [comment]
Which version do you use on Ubuntu? I think 0.13.1 is still not in the usual repositories. There's the snap version but it has some own limitations and the flatpak has some different quirks. ^^'

Because there should be a dropdown to select different pdf engines in the PDF export. Maybe I haven't implemented all options in the snap version yet for example (the flatpak seems to have three options to choose from).

Currently I would recommend to use the LaTeX export, so you can invoke pandoc manually with those files to adjust parameters as requested. The error about the unicode character with inputenc should be fixed on develop branch at least, I think. Sounds familiar to me (#590).

**Comment by victorkane** [comment]
ah, thanks so much for answering, definitely using Manuskript!!! 

Using install from ...

```text
Version 0.13.1
     [ http://www.theologeek.ch/manuskript/ ](http://www.theologeek.ch/manuskript/)
     Copyright © 2015-2020 Olivier Keshavjee
      GNU General Public License Version 3
Software Versions in Use:
     Python 3.8.10
     PyQt 5.14.1
     Qt 5.12.8
```
I did:

```bash
sudo apt list | grep manuskript

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

manuskript/now 0.13.1-1 all [installed,local]
```

I did a `history` and grepped to find I downloaded from [github releases](https://github.com/olivierkes/manuskript/releases/tag/0.13.1)  and followed instructions for Debian based:

```bash
sudo apt update
sudo dpkg -i manuskript-0.13.1-1.deb
```

> Currently I would recommend to use the LaTeX export, so you can invoke pandoc manually with those files to adjust parameters as requested. 

Yes, did that and it worked fine using xelatex from command line on `html` file compiled from Manuskript app, nice clean export of chapters and scenes in html, excellent for pdf, excellent for sigil edit for epub. So no hurry or worry on operative level.

Thanks again for your prompt response.

**Comment by victorkane** [comment]
> Because there should be a dropdown to select different pdf engines in the PDF export. 

Just to clarify, selecting PDF from the Compile popup, then going to "Manage exporters"; clicking on Pandoc permits entering the Pandoc binary executable (which was done fine); clicking on PDF only shows a message `PDF: Needs LaTeX to be installed.`, clicking on LaTeX only shows message `LaTeX: LaTeX is a word processor and document markup language used to create beautiful documents.`. 

I cannot find anywhere to specify pdf engine.

**Comment by victorkane** [comment]
Stop the presses! Found the dropdown permitting configuration of pdf engine!!! And got pdf with no problem!

1. Choose `PDF` for `Export to`
2. In lower left hand corner, a fourth option `Pandoc` appears in bluish grey along with `Separations, Transformations, Preview` !!!
3. Wonderful assortment of options, I choose LaTeX engine `xelatex`, class `book`, toc including base level, and...

Works like a charm! :+1: :100:  Exported PDF BEAUTIFUL, with title page, toc, and book format ready to print.

(note: preview doesn't work but that's a detail)

So, doubly thank you!!! Sorry I didn't find that config adjustment initially. :(

**Comment by TheJackiMonster** [comment]
Alright then. If you are using the .deb package, you might be able to get the pdf preview working by installing the required QtWebKit or QtWebEngine components. I don't know the exact packages on Ubuntu apt repositories but in the snap package they are called: `python3-pyqt5.qtwebkit` (and I think `libqt5svg5` might be required as well).

Otherwise I would close this issue then.
