### ISSUE TITLE
How to open manuskript

### ISSUE THREAD

**Issue by asianmathematics** [olivierkes/manuskript#1037]
I've downloaded the 0.13.1 windows package from https://www.theologeek.ch/manuskript/download/
But I couldn't find manuskript.exe
Am I supposed to use something else?

**Comment by TheJackiMonster** [comment]
The `manuskript.exe` file should be inside the .zip-file. So if you extract it you should find it. Maybe you have some antivirus installed which immediately puts the executable into quarantine. But that's just a guess.
