### ISSUE TITLE
Crash when attempting to add an inexistent reference

### ISSUE THREAD

**Issue by AKANexus** [olivierkes/manuskript#1042]
How to reproduce:

On a "World" entry, click a word on the "Description" text field that doesn't have a reference entry.
Press `Ctrl+Space` (or open the context menu, and select "Insert Reference").
Press Enter.

**Comment by TheJackiMonster** [comment]
I've applied a fix for the issue. The next release will solve the problem.

The issue is that you press Enter while no item is selected to be added as reference.

**Comment by Moris1991** [comment]
> The issue is that you press Enter while no item is selected to be added as reference.

You dont need to press enter.
Create reference than in other reference use that reference and click it or hover over it. That will make things blow up.

**Comment by TheJackiMonster** [comment]
> > The issue is that you press Enter while no item is selected to be added as reference.
> 
> You dont need to press enter. Create reference than in other reference use that reference and click it or hover over it. That will make things blow up.
> 
> I made video record of a problem just in case https://files.fm/u/83kvmwzkv#/view/ry9y5afzt

This seems to be a different issue. Please open it as another issue. The video is very helpful and I'll try to fix that. Thank you.
