### ISSUE TITLE
Type error on launch

### ISSUE THREAD

**Issue by rquinlivan** [olivierkes/manuskript#1043]
I just installed the package and upon launching the app see the following:

```
Jun 22 22:27:42 socrates gnome-shell[3062]: message repeated 8 times: [ Received error from D-Bus search provider io.elementary.appcenter.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.appcenter was not provided by any .service files]
Jun 22 22:27:43 socrates systemd[2759]: Started Application launched by gnome-shell.
Jun 22 22:27:43 socrates manuskript.desktop[272979]: CRITICAL> An unhandled exception has occurred!
Jun 22 22:27:43 socrates manuskript.desktop[272979]: Traceback (most recent call last):
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   File "/usr/bin/manuskript", line 30, in <module>
Jun 22 22:27:43 socrates manuskript.desktop[272979]:     main.run()
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   File "/usr/share/manuskript/manuskript/main.py", line 292, in run
Jun 22 22:27:43 socrates manuskript.desktop[272979]:     app, MW = prepare(arguments)
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   File "/usr/share/manuskript/manuskript/main.py", line 171, in prepare
Jun 22 22:27:43 socrates manuskript.desktop[272979]:     from manuskript.mainWindow import MainWindow
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   File "/usr/share/manuskript/manuskript/mainWindow.py", line 23, in <module>
Jun 22 22:27:43 socrates manuskript.desktop[272979]:     from manuskript.models.worldModel import worldModel
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   File "/usr/share/manuskript/manuskript/models/worldModel.py", line 11, in <module>
Jun 22 22:27:43 socrates manuskript.desktop[272979]:     from manuskript.ui import style as S
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   File "/usr/share/manuskript/manuskript/ui/style.py", line 36, in <module>
Jun 22 22:27:43 socrates manuskript.desktop[272979]:     highlightLight = F.mixColors(highlight, window, .3)
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   File "/usr/share/manuskript/manuskript/functions/__init__.py", line 197, in mixColors
Jun 22 22:27:43 socrates manuskript.desktop[272979]:     return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
Jun 22 22:27:43 socrates manuskript.desktop[272979]: TypeError: arguments did not match any overloaded call:
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   QColor(int): argument 1 has unexpected type 'float'
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   QColor(QRgba64): argument 1 has unexpected type 'float'
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   QColor(Any): too many arguments
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   QColor(): too many arguments
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   QColor(str): argument 1 has unexpected type 'float'
Jun 22 22:27:43 socrates manuskript.desktop[272979]:   QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
Jun 22 22:27:43 socrates systemd[2759]: app-gnome-manuskript-272979.scope: Deactivated successfully.
```

It looks like a type coercion error.

**Comment by hhemken** [comment]
Same:

PyQt5	5.15.6+dfsg-1ubuntu3
Ubuntu 22.04 LTS
manuskript_0.12.0-1_all.deb

$ manuskript 
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 292, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/manuskript/main.py", line 171, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 23, in <module>
    from manuskript.models.worldModel import worldModel
  File "/usr/share/manuskript/manuskript/models/worldModel.py", line 11, in <module>
    from manuskript.ui import style as S
  File "/usr/share/manuskript/manuskript/ui/style.py", line 36, in <module>
    highlightLight = F.mixColors(highlight, window, .3)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 197, in mixColors
    return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'

**Comment by CLJP85** [comment]
same here :| 



.
,
,
.,
,
,


---------------------------------
v
v



StandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/user/1000/runtime-demo'
Gtk-Message: 18:22:14.004: Failed to load module "appmenu-gtk-module"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/user/1000/runtime-demo'
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 292, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/manuskript/main.py", line 171, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 23, in <module>
    from manuskript.models.worldModel import worldModel
  File "/usr/share/manuskript/manuskript/models/worldModel.py", line 11, in <module>
    from manuskript.ui import style as S
  File "/usr/share/manuskript/manuskript/ui/style.py", line 36, in <module>
    highlightLight = F.mixColors(highlight, window, .3)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 197, in mixColors
    return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
























demo@minipc:~
$ manuskript | sudo tee manuskript_debugging.txt
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/user/1000/runtime-demo'
Gtk-Message: 18:22:42.329: Failed to load module "appmenu-gtk-module"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/user/1000/runtime-demo'
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 292, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/manuskript/main.py", line 171, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 23, in <module>
    from manuskript.models.worldModel import worldModel
  File "/usr/share/manuskript/manuskript/models/worldModel.py", line 11, in <module>
    from manuskript.ui import style as S
  File "/usr/share/manuskript/manuskript/ui/style.py", line 36, in <module>
    highlightLight = F.mixColors(highlight, window, .3)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 197, in mixColors
    return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'

**Comment by CLJP85** [comment]
i am interested but dont have time right now - great writing program btw <3 it ;)

though - i dont know if this helps but ill leave ethis here

**Comment by CLJP85** [comment]
https://stackoverflow.com/questions/40139445/python-arguments-and-passing-floats-in-arguments#40139491

**Comment by TheJackiMonster** [comment]
This issue is caused by newer versions of Python being less friendly with type mismatches. You can just update/upgrade Manuskript because this issue has already been solved in the newest version.

**Comment by hhemken** [comment]
Thanks!

**Comment by TheJackiMonster** [comment]
> Am I reading this correctly that this issue results in Debian package database not being updated? https://packages.debian.org/bullseye/manuskript

Yeah, pretty much. I assume it would be necessary to update to version 0.14.0 to have all those conversion errors cleared but then the .deb file of this version has another issue #1047 (so I assume, I would need to repackage probably).
