### ISSUE TITLE
Manuskript no longer opening

### ISSUE THREAD

**Issue by abizrihays** [olivierkes/manuskript#106]
I have tried on both 0.3.0 and 0.4.0 (it started last week on 0.3.0 before I downloaded 0.4.0).  Both times, the Command opening screen will open, and then it just shuts down.  I can see that there are about six or seven lines of some kind of error code, but it disappears before I can try to screenshot.  Restarting the computer does nothing, uninstalling and reinstalling does nothing.  I haven't seen any computer updates (doesn't mean there aren't any) and nothing has changed.  One night it opened, the next day it didn't.

Thankfully I can still get into the project files and open up the .md files to continue working, but if you want to see project paranoia, this is it.

OS: Windows 10 (64-bit I think)

And as a minor issue that I've always seen, it always says "failed to load translator for en_US"  It's always said that even when it worked, just thought I'd mention it.

**Comment by gedakc** [comment]
Thank yo9u @abizrihays for you interest in Manuskript.

To capture the message, could you try opening a command prompt and then run the manuskript.exe executable from there?

Then copy and paste the messages into this issue thread so we can try to get to the root of the problem.

**Comment by abizrihays** [comment]
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Shaffer>C:\Users\Shaffer\Documents\Brooke\manuskript_0.3.0-win32\manuskript_0.3.0_win32\manuskript.exe
Found translation in settings: C:\Users\Shaffer\Documents\Brooke\manuskript_0.3.0-win32\manuskript_0.3.0_win32\i18n\
Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 64, in showEvent
  File "manuskript\mainWindow.py", line 311, in loadProject
  File "manuskript\mainWindow.py", line 497, in loadDatas
  File "manuskript\loadSave.py", line 58, in loadProject
ValueError: invalid literal for int() with base 10: '\x00'

C:\Users\Shaffer>

**Comment by gedakc** [comment]
Thanks @abizrihays for posting the error messages.

The last two message lines indicate the location of the problem and the issue encountered.
[manuskript\loadSave.py - line](https://github.com/olivierkes/manuskript/blob/master/manuskript/loadSave.py#L58)

To reach this line 58 of code, the project must not be in zip form.
(**Settings -> General**: _Save to single file_ **disabled**.)

Line 58 is trying to read a text number (currently should be a "0" or a "1") to determine the version format style of the project save file(s).  If you started with Manuskript 0.3.0, then your "*.msk" file should be "1".
The project file will have a name like "MyProject.msk".

On my system, the file looks like the following.
**File**:  sample-book.msk
**Length**: 1 byte
**Contents**:
`1`

If the **Settings -> General**: _Save to single file_ is **enabled** then this would be a large file containing all of the project content.

Can you open your "*.msk" file in a text editor, then cut and paste the first few lines of content in this thread?

There should only be one line.

**Comment by abizrihays** [comment]
I open up the file in Notepad++ and it says "NULL"

That's it

**Comment by gedakc** [comment]
An empty / NULL file would certainly cause the problem.

The unanswered question is how the file became "NULL" in the first place.  There could be several causes, such as a software bug, accidental editing, or a failing disk drive.  For now let's see if we can get the project to load into manuskript again.

To try to get it running again, you might try the following.

1.  Ensure that manuskript is closed (not running).
2.  Edit the "*.msk" file, insert the number one "1" and save the file.
3.  Try to open the project in manuskript.

Let us know how you make out.

**Comment by abizrihays** [comment]
I changed the NULL to 1 and everything works again :) Everything is in tact and just how I left it, including all the work I did in the files.

**Comment by gedakc** [comment]
'Glad to hear you have regained access to all your data.  :+1: 

I highly recommend using the latest version of Manuskript (currently 0.4.0) because it contains many fixes to address issues in earlier releases.

Thanks also for closing this issue report.
