### ISSUE TITLE
Crash on start-up under Ubuntu 22.04

### ISSUE THREAD

**Issue by Biep** [olivierkes/manuskript#1076]
I thought I already reported this, but I don't see it.  I reported it [to the Ubuntu devs](https://bugs.launchpad.net/bugs/1989203).  See there for details.

It makes Manuskript unusable under Ubuntu 22.04.

**Comment by TheJackiMonster** [comment]
The issue has already been solved in newer versions. Here's the original report: #1043

You can install the newer versions via your Store as snap or from the official releases as .deb package.
