### ISSUE TITLE
Use on smaller resolution screens

### ISSUE THREAD

**Issue by StuartLeonard** [olivierkes/manuskript#108]
The application is not able to be resized for viewing on smaller screens. I use an older netbook as a dedicated writing machine and on the 1024x600 screen the bottom of the Redaction screen, including the Words Target is not visible. I can work around by holding the alt key down and clicking and dragging the application off the screen, and the distraction free mode works fine, but is it possible to allow resizing to a smaller size? 

I appreciate this is a limited use case, but I'm sure there are others out there using older hardware for writing.

**Comment by gedakc** [comment]
Hi @StuartLeonard, I'm just learning about the source code so the following hypothesis might be incorrect.

As best I can tell, the minimal vertical size of the mainWindow is constrained by the height of the Dock Widgets on the right hand side (Cheat sheet, Search, ..., Story line).  At least this is my hypothesis.  @olivierkes please feel free to correct me if I am wrong.

Using the default English language, the smallest I was able to make the screen with all of the text still visible in a vertical column was 808 px wide X 758 px high.  Unfortunately this is still much taller than your 1024x600 screen.  ;-(

![Manuskript Welcome - Dock Widgets Visible - Minimum Size](http://gparted.org/curtis/manuskript/Manuskript-Welcome-DockWidgets-Visible.png)

Each Dock Widget is defined as a *verticalButton* with the vertical component size policy set to *Minimum*.  The relevant code is [Line 112 of the file manuskript/ui/collapsibleDockWidgets.py](https://github.com/olivierkes/manuskript/blob/master/manuskript/ui/collapsibleDockWidgets.py#L112).

Possible work-arounds might be either to shorten the text names of these Dock Widgets, or to somehow make the Dock Widgets scrollable (I'm not sure if this is even an option).

**Comment by StuartLeonard** [comment]
Thanks @gedakc , very helpful. Shortening the name would be great, particularly if the tool tip when mousing over the button remained with the full name. How would I go about changing the button labels? I've searched collapsibleDockWidgets.py and the labels aren't in there (sorry my Python knowledge is pretty much zero!).

**Comment by gedakc** [comment]
I was able to rename the Dock Widgets.  The lines containing the Dock Widget text are:

[manuskript/mainWindow.py line 841](https://github.com/olivierkes/manuskript/blob/master/manuskript/mainWindow.py#L841)
[manuskript/ui/mainWindow.py line 1297](https://github.com/olivierkes/manuskript/blob/master/manuskript/ui/mainWindow.py#L1297)

The smallest I was able to make the screen was 882 px wide X 740 px high.
This picture has the Navigation pane open which adds to the minimum width of the screen.

![Manuskript Welcome Dock Widgets Renamed](http://gparted.org/curtis/manuskript/Manuskript-Welcome-DockWidgets-Renamed.png)

It would seem that something else is preventing the main window from shrinking much further in height.

**Comment by trivers** [comment]
Hi @StuartLeonard, 
I also like writing on my old school netbook and had the same issue..

I've resorted to a somewhat ugly xrandr hack which tricks the graphics card into using a higher resolution. It's an old Samsung netbook running Lubuntu 16.04.

Running this in the terminal maybe works for you too:
`xrandr --output LVDS1 --fb 1229x720 --panning 1229x720 --scale-from 1229x720`

The following will reset your resolution:
`xrandr --output LVDS1 --fb 1024x600 --panning 1024x600 --scale 1x1`

**Comment by StuartLeonard** [comment]
Thanks again @gedakc. Yes, even in Simple mode with shortened right side buttons I can't resize the window enough to fit my screen - I wonder if the separator line to the left of the right hand side buttons is at a set length? I have found a work-around: if I turn on the Story Line at the bottom of the page I can see the bottom of the edit screen and the word count/target, so I'm now comfortable working on my netbook in Manuskript! 

@trivers using xrandr does work for my Asus, thanks for the tip. It's a little ugly to try and work in full time, but useful to know for needing to see a larger resolution in the short term.

**Comment by gedakc** [comment]
Thank you @StuartLeonard and @trivers for posting the work-around methods you use.

Longer term it would be nice if the UI could be resized or redesigned to fit a 1024x600 screen.

**Comment by olivierkes** [comment]
Fixed. Can now be used down to ~770x470:

![image](https://user-images.githubusercontent.com/1192933/31575507-e70596cc-b0e8-11e7-979e-8330b75e37ed.png)

The problem came from the *Character's Basic Infos* tab. It has been morphed into a scroll area:

![image](https://user-images.githubusercontent.com/1192933/31575534-80c3033a-b0e9-11e7-839c-70e4842e12c2.png)

Thanks for the report, and the xrandr tip :)

**Comment by gedakc** [comment]
Thank you @olivierkes for enabling the manuskript screen to be shrunk much further.

Would it be possible to shrink the main manuskript screen even further?

The reason I ask is because with the _Storyline_ pane disabled the smallest I could make the screen was 764x628.  Old netbook computers often have 1024x600 screens.

![Manuskript Small Main Window](https://gparted.org/curtis/manuskript/Manuskript-Main-Window-Small.png)

**Comment by olivierkes** [comment]
That's strange, I'm able to shrink it down to 770x470.

Are you able to identify where it resists?

**Comment by gedakc** [comment]
The size restriction seems to be related me selecting the **Editor** icon.  Once this pane is selected I am no longer able to shrink the Manuskript window below 1024x600.  The key problem being that I cannot shrink the vertical size below 628.

Does that help?  If not then I can try investigating further.

**Comment by olivierkes** [comment]
Ah yes, the metadata pane was taking space, when all elements are open and with enough content to display scroll bars.

With previous commit, I was able to gain about 75 pixels on my setup (from 537 to 462 no counting window decoration).

![image](https://user-images.githubusercontent.com/1192933/31676382-bf642ada-b367-11e7-89a2-20ad941801af.png)

**Comment by gedakc** [comment]
Excellent work @olivierkes !  I can now resize Manuskript smaller than 1024x600 when I have _storyline_ disabled.  And that is including the window decorations.  :+1:

**Comment by olivierkes** [comment]
Great, thanks !
