### ISSUE TITLE
Crashes on hitting "+" while editing plot step summary

### ISSUE THREAD

**Issue by Zstehura** [olivierkes/manuskript#1081]
Steps to reproduce:
1) Create new plot
2) Go to "Resolution Steps"
3) Create new step
4) Click to edit the summary box
5) Click the "Add new" (+) button underneath
6) Crash

**Comment by TheShadowOfHassen** [comment]
What version are you using? I tried it with the latest source and 0.14.0 and I didn't get the error.

**Comment by Zstehura** [comment]
I went to check the version (its latest 0.14.0) and then tried to recreate the error and it wouldn't do it again. I guess it resolved itself?
