### ISSUE TITLE
Ability to always show word target in distraction free mode

### ISSUE THREAD

**Issue by StuartLeonard** [olivierkes/manuskript#109]
Would it be possible to add a setting to allow the word target to always show when in distraction free mode? It could just be allowing auto hide of the bottom bar to be turned off, but ideally just the word count / target would be shown (not the Theme). 

I can work around currently by leaving the mouse at the bottom of the screen but having this setting available would be ideal.

**Comment by olivierkes** [comment]
Right-click on panel now allows to disable auto hide.
It's for the whole panel though.
