### ISSUE TITLE
mouse over goes blank in fiction

### ISSUE THREAD

**Issue by scriptor-pro** [olivierkes/manuskript#1093]
hello, here is a pastebin with my system info : 

https://pastebin.com/CjBE9S2H

and here is a screen recording showing the problem 

https://imgur.com/gallery/fzFAPUh

In Fiction mode, when my mouse is over the World, Character, Plot etc. the rectangular thingy that has some details about that section (I guess) is displayed with absolutely no text.

I will open another issue for the crash inducing problem that happens in the video.

**Comment by TheJackiMonster** [comment]
This could be an issue related to a missing Qt5 package on your system. At least this doesn't happen on other distros I've tested on and it doesn't seem to depend on the language/translation either.
