### ISSUE TITLE
click on "Plan" makes Manuskript 0.14.0 crash

### ISSUE THREAD

**Issue by scriptor-pro** [olivierkes/manuskript#1094]
my system info : https://pastebin.com/CjBE9S2H

screen recording of the incident : https://imgur.com/gallery/fzFAPUh

Whenever I click on the second from bottom icon ("Plan" in french maybe "Plot" in English ?) my copy of Manuskript 0.14.0 crashes. 

This is not an isolated incident. It happens every time I click on that menu item. Manuskript quits instantly with no error messager nor warning. It just *poof* disappears, Houdini-style.

Thanks in advance !

**Comment by TheJackiMonster** [comment]
Can you start Manuskript from terminal and try it again? When it crashes there should be the stacktrace and error message from Python stating what's exactly the issue. I assume you are missing a required package for some Qt5 widgets.

**Comment by scriptor-pro** [comment]
when launching manuskript from terminal this happened : 

`Gtk-Message: 12:44:08.611: Failed to load module "gail"

** (python3:39816): WARNING **: 12:44:08.635: (../atk-adaptor/bridge.c:1018):atk_bridge_adaptor_init: runtime check failed: (root)
`
when clicking on the menu item (and crashing) this was written in the terminal  :  

CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/outlineDelegates.py", line 32, in paint
    iconRect = style.subElementRect(style.SE_ItemViewItemDecoration, opt)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Fatal Python error: Segmentation fault

Current thread 0x00007fadb6758740 (most recent call first):
  File "/usr/share/manuskript/manuskript/main.py", line 243 in launch
  File "/usr/share/manuskript/manuskript/main.py", line 309 in run
  File "/usr/bin/manuskript", line 30 in <module>
Erreur de segmentation

Does it shed a better light on the problem ?

**Comment by TheJackiMonster** [comment]
I think you seem to use a different PyQt version which has either made changes to the API or it's hasn't made the proper changes yet.

The applications is calling a method which expects three parameters on your system but the third should actually be optional. If possible I would recommend upgrading PyQt5 to solve this. If that doesn't work the best option is probably trying to use the flatpak version of Manuskript since it uses the exact versions of dependencies it's packaged with.

**Comment by scriptor-pro** [comment]
upgrading PyQt5 to the latest version did the trick - both bugs are gone :)
