### ISSUE TITLE
Minor Python error during Installation - Linux Mint 20.3

### ISSUE THREAD

**Issue by paulwpoteete** [olivierkes/manuskript#1097]
# During an apt-get install manuskript, the following three python files threw errors.
Thank you for all you do! Excellent software!

## snip...
Setting up manuskript (0.10.0-1) ...
/usr/share/manuskript/manuskript/exporter/pandoc/abstractPlainText.py:78: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.formats is "":
/usr/share/manuskript/manuskript/importer/opmlImporter.py:124: SyntaxWarning: "is" with a literal. Did you mean "=="?
  return len(s) is 0
/usr/share/manuskript/manuskript/main.py:104: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if platform.system() is not 'Windows':

## System
- Description:	Linux Mint 20.3
- Release:	20.3
- Codename:	una
- Linux zfoo 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by TheShadowOfHassen** [comment]
So those errors won't hurt anything it's just python being picky about syntax wording. Actually, the error is gone as of the development branch and running. It must have been fixed between 0.10.0-1 and the 0.14.0 that I'm running on my Ubuntu system.

I'm assuming that you got the package through mint's software repository? If you like installing through the repository but want a more up to date version of Manuskript you could try upgrading linux mint or you could also try the flatpak Manuskript or install the .deb file. I've gotten both to work. I'd recommend the .deb file so you can get language tool

Here is the link to the latest Manuksript and install instructions.

[https://github.com/olivierkes/manuskript/releases/tag/0.14.0](url)

**Comment by paulwpoteete** [comment]
That is great. I'm so happy to hear that those minor annoyances have been
fixed.  Yes. You are absolutely correct - there is no impact to the
operation of the software that I could determine.

Also, I should mention that your attention to tickets and support requests
is greatly appreciated. Thank you for all you do.

Happy New Year,
Paul

**Comment by TheShadowOfHassen** [comment]
So now the truth comes out. I am not a contributor or anything special, I am just another Manuskript user so I cannot close the issue. There should be a button near where you can add a comment that says close. If you would hit that it'd be great.

And thank you for using Manuskript and reporting any issues you find.  That helps a lot.

**Comment by TheJackiMonster** [comment]
> So those errors won't hurt anything it's just python being picky about syntax wording. Actually, the error is gone as of the development branch and running. It must have been fixed between 0.10.0-1 and the 0.14.0 that I'm running on my Ubuntu system.
> 
> I'm assuming that you got the package through mint's software repository? If you like installing through the repository but want a more up to date version of Manuskript you could try upgrading linux mint or you could also try the flatpak Manuskript or install the .deb file. I've gotten both to work. I'd recommend the .deb file so you can get language tool
> 
> Here is the link to the latest Manuksript and install instructions.
> 
> [https://github.com/olivierkes/manuskript/releases/tag/0.14.0](url)

That's pretty much correct. Unfortunately we have little control over the versions provided in each Linux distro's repository. So it's recommended to install the flatpak or snap package because otherwise you have to make sure all dependencies are installed and compatible (depending on the versions).

In most cases the provided .deb package or .rpm package from the newest release should work on current distros (depending on the used packaging variant of course). But if you are looking for most convenience (automatic updates and compatible dependencies out of the box), you should try the flatpak version on Linux Mint.

**Comment by paulwpoteete** [comment]
Thank you so much for your help!
