### ISSUE TITLE
AttributeError in editorWidget

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#11]
Happens, it seems, if a tab is closed, and something is edited in an other tab:

```
Traceback (most recent call last):
  File "/home/olivier/Dropbox/Documents/Travail/Geekeries/Python/PyCharmProjects/manuskript/bin/../manuskript/ui/editors/editorWidget.py", line 219, in modelDataChanged
    if not self.currentIndex:
AttributeError: 'NoneType' object has no attribute 'currentIndex'
```

Seems like editorWidget is deleted, but signal is still emited. Case of [foot-shooting](http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html)? 

Probably needs to disconnect signals explicitely when closing tabs.

**Comment by gedakc** [comment]
Using 0.4.0 I have been unable to reproduce this issue.

I tried various combinations of typing text into scenes, opening, and closing tabs containing different scenes, and the only message occasionally displayed in the terminal prompt was:

_Project /home/gedakc/tmp/MyTestProject.msk saved._

**Comment by olivierkes** [comment]
Thanks, I'll close it then.
