### ISSUE TITLE
I can't click boxes to edit them

### ISSUE THREAD

**Issue by Or1ginal-Username** [olivierkes/manuskript#1104]
I just downloaded the Windows version of this app. I'm trying to build a character for my book. When trying to click any of the boxes to write in them other than on the screen where you write the title, subtitle, etc. it does not enter the box and I cannot write in them. Do I just not understand the software? Please help!

**Comment by TheJackiMonster** [comment]
Did you find a solution yourself or closed the issue by accident?

**Comment by Or1ginal-Username** [comment]
I figured it out, sorry about that. I just clicked the main character slot
thinking that itself was a character, and didnt know i had to actually
create one. Sorry about that.

**Comment by TheJackiMonster** [comment]
No problem. ^^
