### ISSUE TITLE
Gtk Port: Getting the Gtk port so that other people can contribute.

### ISSUE THREAD

**Issue by TheShadowOfHassen** [olivierkes/manuskript#1106]
So I got bored the other day, so I looked at the Gtk and decided to do some work on it. I’ve done some work for it doing some minor improvements and implementing a feature that I’ve wanted for Manuskript for years. But while I got a closer look I also found a few bugs and have a suggestion to make the UI porting easier.

This brings me to my point @TheJackiMonster if you are OK with people collaborating could you please set the Gtk fork so that I can contribute to it? I believe before you said you'd push it to a different branch. I'll have to open issues to ask design questions/ report bugs and so on, but I’ll clearly  mark it as for the Gtk rewrite like this one is. Also, it may be a good Idea to add a Gtk Label so these issues can easily be filtered and that the bugs of the Gtk rewrite and the qt version aren't confused.

If someone thinks that the issues I open would be distracting to the qt developers I think there is another way to do it like the Lord of Test people did it and have a different repository for the rewrite. The problems with that idea is that the Gtk version was supposed to replace the qt version not two different versions maintained at the same time as two repositorys would make you think. Also they'd have to be in the same place so @olivierkes would have to create the other repository, unless we turned manuskript into an github organization. From what I read that would also make it easier for more people to collaborate and the developers to manage it.

**Comment by TheJackiMonster** [comment]
Ok, so I created the branch in the original repository [here](https://github.com/olivierkes/manuskript/tree/gtk). If you create a PR, you can choose to merge into that rather than the `develop` branch. It's also fine to fork it starting to contribute anything.

I've also created a label for any issue regarding the GTK port/rewrite. So I will just tag it to the issues coming up.

**Comment by TheShadowOfHassen** [comment]
Done: so I'm closing the issue (I should have done this earlier)
