### ISSUE TITLE
Gtk Port:Discussion

### ISSUE THREAD

**Issue by TheShadowOfHassen** [olivierkes/manuskript#1108]
So I have a few questions and comments about this gtk port.

Firstly I noticed that the way you set up the code is as follows(In sort of psudo code):
```
Button = Builder.loadfromfile()
Button.connect('clicked', whenbuttonpressed)
````
But there's an easier way that I found here: https://python-gtk-3-tutorial.readthedocs.io/en/latest/builder.html
It uses signals and if you set in the glade file that button gives the signal

```
handlers = {
    "onButtonPressed": hello
}
builder.connect_signals(handlers
````
That's taken directly from the docs. It's more lines of code in this example but in the long run. Sixteen Button load and setting or just adding sixteen things to the handler dictionary.

It works either way but I wanted to know which to use. My vote is the second one. I can rewrite the code and UIs to use it or we can just leave it be and make it on the way out.

So the second question I have with the design choice. @TheJackiMonster you said you wanted this to be mobile supported for phones like pine-phone. I don't have a pine phone so I don't know if my UI will work on small screens. I'll keep working but you'll have to tell me if my UI is wrong. I am assuming also that that's a nice-to-have feature and is lower priority to an easy desktop port  with all the features.

So finally in the main porting I can't do much because the next thing that's needed is drag and drop for the outline, editor. and world tabs. That requires custom treeview drag and drop and I can't figure that out. If someone could give me a working example of a file/folder based drag and drop then I could but I can't figure it out myself. And when I tried to add drag and drop to world but it threw errors so I think it needs custom also.

I will be able to get bugs fixed and there are some other features I thought of adding(Namely a sort of tip of the day/ news fetcher for the General tab). When the drag and drop is done though I'll be able to do a lot more.

**Comment by TheJackiMonster** [comment]
So the reason why I prefer to use this syntax is that it causes less potential confusion for other contributors. If I have a button and I bind a function to its "clicked" signal, the code tells me exactly what's happening. However when using the handlers syntax, I can name my handlers/events any way I want in the UI files (so they essentially include partial logic of the application this way) and the code needs to follow. I don't think that's good. If possible I think it makes sense to separate logic, data and UI as much as possible. So when any contributor is trying to change stuff in the future, they will find it and understand it with opening the least amount of files as possible.

There are also ways of defining UI widgets in Python using object oriented syntax. But I avoid that for similar reasons. It might only make changes in the future more difficult. So yes, there are ways to reduce lines of code but I don't think it's worth doing that here.
