### ISSUE TITLE
add suport Fountain fromat

### ISSUE THREAD

**Issue by Reaper10** [olivierkes/manuskript#111]
add support Fountain format

https://fountain.io/
https://github.com/nyousefi/Fountain

**Comment by gedakc** [comment]
Thank you @Reaper10 for you interest.

Currently Manuskript supports entering text such as fountain.

Were you looking for fountain syntax highlighting and a fountain export?

If so then this is already covered under the issue #32 request and hence this request could be closed.
If not, then please clarify what you are seeking regarding fountain.

**Comment by Reaper10** [comment]
sorry I didn't on the fountain supported apps page. could you add support for Trelby , adobe story fade in celix,  movie magic screen writer, final draft? I would all so be nice to add the ability write comic scipts.

**Comment by gedakc** [comment]
'Looks like this request is a duplicate.  The questions were asked in a separate issue.

**Comment by olivierkes** [comment]
Duplicate of #32.
