### ISSUE TITLE
Adding Discussions to Manuskript

### ISSUE THREAD

**Issue by TheShadowOfHassen** [olivierkes/manuskript#1110]
So this is a potentially stupid question but why do we have our discussions in the issues instead of github discussions? (https://docs.github.com/en/discussions) I found it while looking at repository settings and it looks sort of useful.

**Comment by TheJackiMonster** [comment]
Honestly I'm not sure how new this feature from Github is but I think the issues work good enough, don't they? I certainly don't have time to look through a forum, maintain it, moderate it and such anyway. ^^'

So I don't see a huge advantage...

**Comment by TheShadowOfHassen** [comment]
Yeah this works fairly well enough for now... I just thought it was a cool feature

As a aside though I'm not the best at programming I can do things like moderating to help. I know there's permissions and stuff but I'm willing to help if enough people want it.

I'll close this issue now.
