### ISSUE TITLE
New search bug

### ISSUE THREAD

**Issue by jrstrick** [olivierkes/manuskript#1125]
Search now searches chapter summaries. Yay! However, if you get a hit in one and click it, there's no way to close the resulting block. Suspect some window controls are missing.
![new_search_bug](https://user-images.githubusercontent.com/14007950/215626081-b831deb1-fb47-4b8f-8c7f-11605e28ebe2.png)

**Comment by TheJackiMonster** [comment]
You should be able to click once on "Metadata" in the buttons on the right of the application window. Triggering this once will "open" the view for metadata and chapter summaries usually... then clicking it again should close it.

I can definitely reproduce the issue that the state of the metadata view being open/closed is not correctly updated. I'll take a look whether this is trivially fixable. However you should be able to close it either way with those buttons on the right.

**Comment by TheJackiMonster** [comment]
I've pushed a commit ( eeb98a8 ) which will address that the "Metadata" button will change its state when you open a search result in this view.

**Comment by jrstrick** [comment]
That seems to have resolve the problem. Thanks!
-JRS
Get BlueMail <https://bluemail.me> for Desktop
Tobias Frisch wrote:
I've pushed a commit ( eeb98a8 <https://github.com/olivierkes/manuskript/commit/eeb98a8ccd28eb4e90d2365632e0b5eb1eb0f6d6> ) which will address that the "Metadata" button will change its state when you open a search result in this view.
