### ISSUE TITLE
Update files about languages

### ISSUE THREAD

**Issue by milotype** [olivierkes/manuskript#1133]
Update files about languages according to the translations data at https://hosted.weblate.org/widgets/manuskript/?lang=&component=translations. They haven't been updated for a long time!
- https://github.com/olivierkes/manuskript/blob/develop/i18n/languages.txt
- https://github.com/olivierkes/manuskript/blob/develop/i18n/manuskript.pro

**Comment by TheJackiMonster** [comment]
I've deleted the `languages.txt` now. The `manuskript.pro` file can now be generated and update via a script:
- https://github.com/olivierkes/manuskript/blob/develop/util/update_lang_meta.sh

I've also merged newest changes from Weblate and updated all files.
