### ISSUE TITLE
[0.15]HTML Export Missing

### ISSUE THREAD

**Issue by AlanDunaway** [olivierkes/manuskript#1149]
I just got 0.15 and it seems that the Native HTML Export is missing. The native HTML is much better than the Pandoc HTML for exporting to eBooks and also for online exporting(exporting to publish on a website). Is it coming back in the next version? I'm considering to stay in 0.14 if it's not brought back.
Thanks.

**Comment by TheJackiMonster** [comment]
Honestly, I can't reproduce your issue. I've started 0.15.0 on my system, clicked "Compile" to export and selected HTML... works for me.

**Comment by AlanDunaway** [comment]
If you have pandoc, of course it will be there.

**Comment by AlanDunaway** [comment]
Here(0.15)
![image](https://user-images.githubusercontent.com/96152972/228650708-4cd0cfdb-f518-4ecd-b4fd-19ce31843be0.png)

0.14
![image](https://user-images.githubusercontent.com/96152972/228650959-5c46ff74-1908-4ecb-baea-767f4910d4e9.png)
I thought it was my PC acting up, so I downloaded 0.14 to be sure and there it is.

**Comment by TheJackiMonster** [comment]
Which operating system is that? (Which package exactly if it's Linux?)

**Comment by TheJackiMonster** [comment]
I think I found the issue. I assume it's Windows.

**Comment by AlanDunaway** [comment]
Windows 10 Professional 22H2(19045)

**Comment by TheJackiMonster** [comment]
Yes, okay. I'm gonna fix that. Then Github should automatically build a new binary for Windows which you can use.

**Comment by AlanDunaway** [comment]
Wait, what happened? Is it related to Windows or a bug on Manuskript?

**Comment by TheJackiMonster** [comment]
We changed to automatically build the Windows release using Github actions because with 0.14.0 and before I had to manually build a Windows release with a custom script on Linux. However the build from Github didn't include the `python-markdown` package when running PyInstaller.

So that's easily fixable but I should missed that before the last release.

**Comment by AlanDunaway** [comment]
> Once the action completes, here should be a binary for Windows which fixes the issue: https://github.com/olivierkes/manuskript/actions/runs/4557450131

Ok, so I download from there and switch out my existing binary for it?
And thanks. I thought it was something that was removed. Didn't knew it was an accident. Mishaps happen, thank you for fixing it. I'll download the exe and test it.
