### ISSUE TITLE
Kubuntu 20.40.6 getting undefined symbol: krb5_ser_context_init, version krb5_3_MIT

### ISSUE THREAD

**Issue by dlarue** [olivierkes/manuskript#1155]
After installing dependencies, then the deb, running manuskript getting pyqt5 import error, then running pip install pyqt5, followed by pip install lxml. I now get the following when trying to run manuskript:

(base) maker@MacBookAir:~/StoryLineEditing$ manuskript                       
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 308, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/manuskript/main.py", line 177, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 24, in <module>
    from manuskript.settingsWindow import settingsWindow
  File "/usr/share/manuskript/manuskript/settingsWindow.py", line 20, in <module>
    from manuskript.ui.editors.themes import createThemePreview
  File "/usr/share/manuskript/manuskript/ui/editors/themes.py", line 13, in <module>
    from manuskript.ui.views.MDEditView import MDEditView
  File "/usr/share/manuskript/manuskript/ui/views/MDEditView.py", line 588, in <module>
    from PyQt5.QtNetwork import QNetworkRequest, QNetworkAccessManager, QNetworkReply
ImportError: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2: undefined symbol: krb5_ser_context_init, version krb5_3_MIT

**Comment by TheShadowOfHassen** [comment]
So it looks like it's a system thing... 

Are you running Linux or mac os? If you're running Mac OS are you using the python you installed or are you somehow accidentally using the python that mac os has? (It's just a thought)

I have no idea, but maybe one of our bundled executables would work.

**Comment by dlarue** [comment]
Running Linux, specifically Kubuntu version 20.40.6 which is Qt5 based version of Ubuntu(also Linux).  Python 3.9 is what's installed and where I installed requirements into.

I can try booting a 22.04 version of Kubuntu from ISO and see if Manuskript will run there.  Supplying an appimage can often help with running on many versions of Linux since they contain all the required libraries and their required versions.

**Comment by dlarue** [comment]
Manuskript was easily installed after booting a LUbuntu LiveISO( v22.10 ) so I googled on the error again and an issue comment listed in another application mentioned de-activating conda base. I should have thought about that as Manuskript install used lots of system python modules. 

So I just ran 'conda deactivate' and manuskript ran without error.
