### ISSUE TITLE
More Character Categories

### ISSUE THREAD

**Issue by kiwipen** [olivierkes/manuskript#1156]
It would be useful to be able to sort characters by more than the three given us.
I have a large document with a large swath of minor characters that are still rather important. I'm using it to organize my massive shared open world with a friend. Having 20-30+ 'minor characters' would be easier to organize in folders similar to the World organization system, without using the World organization system.

**Comment by TheShadowOfHassen** [comment]
So this looks like two different issues. You're saying that you first would like more character sorting and  Second you Wish it'd be sorted in the folders as well that are heriarical like the world tab.

This looks pretty similar to the discussion in #1141

**Comment by obw** [comment]
> It would be useful to be able to sort characters by more than the three given us. I have a large document with a large swath of minor characters that are still rather important. I'm using it to organize my massive shared open world with a friend. Having 20-30+ 'minor characters' would be easier to organize in folders similar to the World organization system, without using the World organization system.

Lucky Author, with only so few!

I have actual more than 180 Characters in the database! 9 Main, a dozen Secondary...

My dream would be that we could use the '**Detail Info**' to group!

I have there things like race (It's something like a fantasy story), Family, Friends and so on....

Group by Family
Group by friend (Filter alone, would be a helpful dream)

And so an...

And the Grouping in three categories of importance is for enough, but also there should be other ways to group and filter, with '**Detail Info**' we have a place to store it!

**Comment by kiwipen** [comment]
> > It would be useful to be able to sort characters by more than the three given us. I have a large document with a large swath of minor characters that are still rather important. I'm using it to organize my massive shared open world with a friend. Having 20-30+ 'minor characters' would be easier to organize in folders similar to the World organization system, without using the World organization system.
> 
> Lucky Author, with only so few!
> 
> I have actual more than 180 Characters in the database! 9 Main, a dozen Secondary...
> 
> My dream would be that we could use the '**Detail Info**' to group!
> 
> I have there things like race (It's something like a fantasy story), Family, Friends and so on....
> 
> Group by Family Group by friend (Filter alone, would be a helpful dream)
> 
> And so on...
> 
> And the Grouping in three categories of importance is for enough, but also there should be other ways to group and filter, with '**Detail Info**' we have a place to store it!

It should be noted, I'm not an author; I'm actually using this document to track my TTRPG world with a friend. Right now it's 20-30 characters....but that's only the 'main' ones. I want to expand it to include every NPC, hence why I need the sorters...otherwise secondary would be just a nightmare. And minor etc.

**Comment by FlakFerret** [comment]
What if during the project setup, we could tick a box to "show characters panel as a hierarchy"?  That would allow us to create a system very similar to the one seen in the Worlds tab.
