### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by Reaper10** [olivierkes/manuskript#1161]
I mite be stupid but I remember the hot key is. Can you add a button? Is it F11?

**Comment by alfar** [comment]
The button to open full screen editing is in the bottom right corner of the scene view:
<img width="147" alt="image" src="https://github.com/olivierkes/manuskript/assets/128553/2d2b30af-80b4-4a0e-a004-18ac10cbf534">
It's not very obvious, I agree. Also, F11 is indeed the hot key :)

**Comment by taw00** [comment]
It's been a year. Please close this @Reaper10. ;)
