### ISSUE TITLE
Done.

### ISSUE THREAD

**Issue by jrstrick** [olivierkes/manuskript#1167]
After two data loss events in 24 hours (which I recovered the data from), I'm done with manuskript. I'm sorry, but it's eaten my writing time too many times.

**Comment by TheShadowOfHassen** [comment]
I've heard a lot of issues with people. That's completely fine. Realistically, Manuksript needs a lot of work. You don't have to apologize, The important thing is you can write your stories.

I do hope if things ever get sorted out you'd be willing to give it another try.

**Comment by TheJackiMonster** [comment]
That's the whole reason I started the rewrite for the IO part of Manuskript. But then the problem was that IO was way too interconnected with the Qt UI for me to merge it. Unfortunately I don't have as much time to work on Manuskript as I'd wish. ^^'
