### ISSUE TITLE
Link to website not working

### ISSUE THREAD

**Issue by Quirinea** [olivierkes/manuskript#1184]
The contribute link 

"https://www.theologeek.ch/manuskript/contribute/" gives

Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in /home/clients/90412ec2d8e55d60c960a48d035ee4d5/web/manuskript/wp-includes/compat.php on line 502

This is linked also from e.g. AlternativeTo

I thought of recommending Manuskript on a forum and checking the source gave me this mess!

(see if this gets posted now, and not gives 404)

**Comment by TheJackiMonster** [comment]
We are already aware. I'll close this as duplicate of issue https://github.com/olivierkes/manuskript/issues/1175.

Information to get binary downloads are already mentioned on that issue in case it's needed.

**Comment by Quirinea** [comment]
OK I tried to search if this was reported but did not find the issue. Sorry for duplicate.
