### ISSUE TITLE
cannot download to ubuntu

### ISSUE THREAD

**Issue by maroofahmed1985** [olivierkes/manuskript#1199]
Hi,

i cannot download to ubuntu. i have followed the instructions i get this error message:

dpkg: error: cannot access archive 'manuskript-0.15.0-1.deb': No such file or directory

thank you

**Comment by TheShadowOfHassen** [comment]
Drag the deb file from downloads to the home folder, then open the terminal app then try running the program.

**Comment by maroofahmed1985** [comment]
thank you. that worked
