### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by QosmosTheQ** [olivierkes/manuskript#1211]
When I scroll through the templates a few times in the opening section, the program closes on its own without any error message

**Comment by librafrog** [comment]
same for me. Still it happens when I select all, except Thrilogy template. Very strange. let me know if you need some log details.

**Comment by charliemartinez** [comment]
I apologize, I speak Spanish and I don't fully master English, although I believe I just referred to the same issue: https://github.com/olivierkes/manuskript/issues/1238

**Comment by TheJackiMonster** [comment]
This seems to be another duplicate of #1163 which has been addressed.
