### ISSUE TITLE
Request for Bullets and Numbering option

### ISSUE THREAD

**Issue by Weej1** [olivierkes/manuskript#123]
This is more of a feature request and I do apologize if I'm making too many posts (do let me know if I am). 
But basically what it says in the title is what I'm requesting. Since I'm writing a non-fiction / technical document options such as Font sizes, quotes, bullets ..images are what I'm needing. 

~~Perhaps implementing github Markdown into the software?(this would include the ASCII tables too which would be great)~~ I stand corrected, Manuskript DOES have Markdown implemented.

 In which case can I request that hotkeys/buttons be added to go along with the hotkeys/buttons for Bold, Italic and underline? Preferably at the top? (or perhaps giving the user the option to place the buttons where they like? )

Im a frequent user of another Qt5 based open source project that uses markdown called QownNotes - It has the functional look and feel down (customizable toolbar at top, user selectable panels etc) but Manuskript has many features that QoN doesn't have.   

[Screenshot](http://i.imgur.com/A3WgvJk.png)

By no means am I demanding all of this but just making suggestions. I appreciate everything you've done! 

   If these are implemented already do let me know. thanks!

**Comment by olivierkes** [comment]
I added basic support for lists:

- You can add them in the menu
- If you are in a bullet list and type enter, it will create an item of the same level.
- If you are in a numbered list and type enter, it will create an item of the same level and of incremented value (1 → 2, a → b, ...)

![image](https://user-images.githubusercontent.com/1192933/33431533-f6f0d392-d5d4-11e7-912d-f20cf4511d53.png)

I won't add buttons to keep the interface light. It's quite easy anyway to start a list ("- "). But I could add a keyboard shortcut. What do you think?

**Comment by olivierkes** [comment]
Closing this. If you think a keyboard shortcut is useful, please tell me. And what shortcut.

**Comment by Weej1** [comment]
Hi Olivier, How've you been?

Wonderful to see progress happening! You're absolutely right in saying that a simple `-` or `1.` should be enough to start the list. This is great DURING the process of typing the list. but If I had already typed up a few lines I need to convert to a list, I'd usually highlight that batch of sentences, and then click on the "Bullets and Numbering" icon OR hit  `Ctrl+Shift+B` as a hotkey.   

So hopefully that answers your question about which keyboard shortcut and why I still think it would be useful!  

Having said that I understand if you dont implement this at all because It *may* need a lot more coding on your part, I mean, hypothetically speaking, what about lines that are "nested" under the "parent"? 

````
This is the parent line that needs to be bulleted/numbered.
    This is a nested line that needs to be bulleted/numbered. 
````
i.e. if I highlight a batch of sentences/lines with that kind of structure and hit `Ctrl+Shift+B` would it automatically add the necessary bullet points AND indent correctly for both parent and child?  etc. So yeah whatever you see fit. :)
