### ISSUE TITLE
"pandoc: Could not parse YAML header" error

### ISSUE THREAD

**Issue by Weej1** [olivierkes/manuskript#124]
I've been trying to export my current project into DocX but nothing seems to work - I randomly tried epub, markdown, HTML, LaTex etc. all gave the same error. 

Of note however is that Manuskript's own exporter is working fine for both preview / and export. (Markdown/Plaintext/HTML...all work)

[Screenshot of Pandoc Error](http://i.imgur.com/cMHyBdL.png)

**Comment by gedakc** [comment]
This sounds like a bug in _pandoc_.

Perhaps you could try to find the text that is causing the error message to display?

To see if pandoc works, you might create a new project, type in some text, and then see if this simple text will compile to a _pandoc - docx_?

**Comment by Weej1** [comment]
I've actually written quite a lot and am not entirely sure where the issue lies now. Just that it still happens (sadly). For now I'm exporting to MarkDown and then using another MD editor to finalize the document(s).

**Comment by gedakc** [comment]
Can you provide a sample Manuskript project that exhibits this issue?

It is very difficult for us to identify and fix a problem when we can't reproduce the issue.

**Comment by Weej1** [comment]
Hi @gedakc 
I've attached the actual file I'm working on - the number of errors have actually increased (see image) 
[OSM_StepByStep_020.msk.zip](https://github.com/olivierkes/manuskript/files/1112832/OSM_StepByStep_020.msk.zip)
![2017-06-29-220741_502x275_scrot](https://user-images.githubusercontent.com/6381159/27699709-cad15348-5d18-11e7-82c3-7f3ad20addec.png)

I detected SOME of the issues (the initial error I reported I was using unicode which was this: ⤷ 
But now I have no clue what the other errors are, thanks for taking a look!

**Comment by gedakc** [comment]
Hi @Weej1, I finally got some time to look into this issue.  Unfortunately the OSM_StepByStep_020.msk.zip file appears to be missing the top level "*.msk" file.  It does have the subdirectory for "outline" plus various other manuskript information files.

Would you be able to zip the "project.msk" file along with the "project" directory and subdirectories?

**Comment by gedakc** [comment]
Hi @Weej1.  I have done my best to recreate the missing top level "*.msk" file.  Now I am able to recreate the issue or a similar issue to the one you encountered.

To see if the issue occurred within **pandoc** alone, I compiled (exported) the document to **plain text** using Manuskript's built-in exporter.  Then I ran **pandoc** directly on the exported text.  The error from pandoc remains.

```
$ pandoc -s -o output.html OSM-export-plain-text.txt 
pandoc: YAML header is not an object "source" (line 130, column 1)
pandoc: YAML header is not an object "source" (line 17, column 1)
$
```

When I checked column 1 of lines 17 and 130 I discovered that both contained a single line of three dashes (`---`) at the top of the respective scene or "*.md" file.

The snippets containing these lines are:

- Under **The Scanning Web Portal**:

```
---
One of the benefits of the eScan Web Portal is that prior to the test....
```

- Under **The eScan Process**:

```
If eScan detects and error in the scan it will highlight the damaged capture in Red. It will also not allow you to upload your batch till the error has been fixed. 

---
When a batch has been scanned and is being uploaded, you can continue to capture the next batch immediately - there's no need to wait for a batch upload.
```

If I add blank lines around these three dashes (`---`), or if I delete the three dashes (`---`) then I am able to create the export.

This issue appears to exist within **pandoc**, and could be related to pandoc's special handling of em-dashes.  Search for em-dash in the [Pandoc - Manual](http://pandoc.org/MANUAL.html).

At the moment I don't think there is anything that we should change in Manuskript regarding this issue.

**Comment by olivierkes** [comment]
On my end, this is just a warning, so it should'nt prevent pandoc from working:

> [pandoc warning] YAML header is not an object "source" (line 19, column 1)

But anyway, it might be confusing. It is possible to disable YAML metadata block by default:

```
diff --git a/manuskript/exporter/pandoc/abstractPlainText.py b/manuskript/exporter/pandoc/abstractPlainText.py
index bd5da95..cd664a4 100644
--- a/manuskript/exporter/pandoc/abstractPlainText.py
+++ b/manuskript/exporter/pandoc/abstractPlainText.py
@@ -264,7 +264,7 @@ class pandocSettings(markdownSettings):
         return self.settings
 
     def runnableSettings(self):
-        r = ["--from=markdown",
+        r = ["--from=markdown-yaml_metadata_block",
              "--to={}".format(self.format)]
 
         for name in self.settingsList:
```

This would allow manuskript to get the job done without warning/error message. But it would also prevent people from using YAML metadata blocks.

**Comment by gedakc** [comment]
Personally I think we should keep the [YAML metadata block](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block) functionality.
In other words we should not change Manuskript's current behaviour.

**Comment by Weej1** [comment]
Hi @gedakc and @olivierkes 
My apologies for the large stints of silence (life etc). I agree with @gedakc.  As he initially confirmed, it seems to be an issue with pandoc. 

I think if anything should be done on manuskripts side it would be to add a slightly more indepth error message that says:  
```
pandoc: YAML header is not an object "source" (line 130, column 1)
pandoc: YAML header is not an object "source" (line 17, column 1)

Manuskript says: This might be a pandoc issue, which is a separate tool. 
Try exporting your document with the standalone version of pandoc, 
see if the issue persists. 
```
 
Or something to that effect (please feel free to do whatever, I'm just making suggestions).

**Comment by olivierkes** [comment]
OK I'll leave it at that, maybe add a more detailed error message, and also offer the option to disable YAML metadata block just in case.
