### ISSUE TITLE
Story Line unavailable

### ISSUE THREAD

**Issue by LoveIsGrief** [olivierkes/manuskript#1241]
Hi,

I found out about the story line feature described in the [blog post](https://www.theologeek.ch/manuskript/2016/02/28/story-line/), but I can't find a way to activate it. I thought I was doing something something wrong in my own book, so the demo project was opened, but that doesn't seem to have a the feature either.

Supposedly the feature was introduced in 0.2.0. I have 0.14.0 from [nixpkgs](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=manuskript) ([package recipe](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/editors/manuskript/default.nix#L44)) is there a feature flag missing or something?

Cheers

**Comment by paulkater** [comment]
Hi,
What is missing? On the very right, the lowest tab, is called Story Line. You click that, and the story line window should open at the bottom. On the left of that, there's a slider which will let you zoom in on the chapters. If you have a reference to a character and you want to see that in the story line use the tiny dropdown below the slider, where you can select to show plots, characters or both.
Does that help?

**Comment by LoveIsGrief** [comment]
Oh yes, it does! The blog entry shows it on the left and I completely missed it on the right. Cheers
