### ISSUE TITLE
Keyboard shortcuts aren't functioning, No undo feature.  

### ISSUE THREAD

**Issue by Weej1** [olivierkes/manuskript#125]
Ctrl+B , Ctrl+i, ctrl+u currently do nothing. Neither does clicking on the little buttons meant for the same purpose. Also Ctrl+Z, while not implemented  (and please **do** implement it) - does a strange hopping forward action (it goes down by 4 or 5 lines).

**Comment by gedakc** [comment]
Thanks @Weej1 for your interest in improving Manuskript.

If you would like to help save developer time for fixing bugs please also check other currently raised issues as this report contains duplicate mentions of the following issues:

- Issue #34.  Undo/redo works in some text areas but not others.
- Issue #59.  Format buttons in text editor window not working.

**Comment by Weej1** [comment]
Hi @gedakc 
Im not a programmer (a teacher really) but I tried to follow along t see if I could help fix the bugs you linked. Sadly I have no clue what a "QTextCursor(self.currentBlock()).setBlockFormat(bf)" is :(

However if you're talking about this being a duplicate issue , then I'll just close this issue. Thanks for replying!

**Comment by gedakc** [comment]
Hi @Weej1.  No worries about not being a programmer.  We benefit from help in many areas and different people.  In fact sometimes programmers miss issue that others find quite easily.  :-)

You might wish to add to the format buttons issue that the keyboard shortcuts Ctrl+B , Ctrl+I, Ctrl+U do not work either.  That way these two things should get fixed at the same time.
