### ISSUE TITLE
Crash when opening old projects

### ISSUE THREAD

**Issue by FastusBellrune** [olivierkes/manuskript#1250]
This problem only happens when the project is not saved on a single file.

If I try opening an old project from version 0.15.0 that wasn't saved in a single file, the program crashes. Otherwise, it works fine.

Here's the log:

> 2023-12-14 18:42:21,966 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
> Traceback (most recent call last):
>   File "manuskript\mainWindow.py", line 1206, in saveDatas
>   File "manuskript\loadSave.py", line 23, in saveProject
>   File "manuskript\load_save\version_1.py", line 358, in saveProject
> OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: 'C:/Users/crist/Documents\\Tutorial\\characters\\0-Cool_MC.txt' -> 'C:/Users/crist/Documents\\Tutorial\\characters\\0\r-Cool_MC_.txt'

OS: Windows 11
Manuskript version: 0.16.0

**Comment by TheShadowOfHassen** [comment]
This I believe was an issue, but now there is a version 0.16.1 that ought to fix it.

**Comment by FastusBellrune** [comment]
Ok, it's working in version 0.16.1.
