### ISSUE TITLE
Filter in Character and World doesn't work

### ISSUE THREAD

**Issue by FastusNumen** [olivierkes/manuskript#1253]
As the title say, the filter in those sections doesn't work. When I write, it doesn't change anything.

The filter in Plots works, though.

OS: Windows 11
Manuskript version: 0.16.1

**Comment by TheJackiMonster** [comment]
I've implemented a fix for the characters filter today (50b9fd4980d932bc1bc54977b7bf7aaf0cf5f3b5). However the filter for world items needs a bit more work because it is using other UI components underneath. Should be possible to address with the next release though.

**Comment by FastusBellrune** [comment]
The filter in Characters is working now, thanks.
