### ISSUE TITLE
I have too many Characters for selection!

### ISSUE THREAD

**Issue by obw** [olivierkes/manuskript#1255]
![problem_too_much_characters](https://github.com/olivierkes/manuskript/assets/3050806/d941d463-ec18-47db-955d-922aca909883)

I am adding a new Plot, when I see this, when I try too select a Minor Character for the Plot, about 15 are Missing!

A search field in this select box would be my preferred solution! Also, a Scrollable selection would help here.

I have more than 140 Characters at the moment, around twenty more are coming in the next 10 to 20 Chapters.

Regards

P.S.: these are the minor Characters, Secondary and Main, have a lot less Characters, I also only add recurrence Characters to the database!
P.P.S.: The screenshot is the full screen I use!

**Comment by TheJackiMonster** [comment]
I assume this could be combined with #1253, right? So you could use a filter to search. I think in the GTK port filtering and scrolling works already. But not yet in Qt... ^^'

**Comment by TheJackiMonster** [comment]
I've implemented a fix since the filter was mostly in place in the source code already but it wasn't connected yet, lol. (50b9fd4980d932bc1bc54977b7bf7aaf0cf5f3b5)
