### ISSUE TITLE
Manuskript closing unexpectedly

### ISSUE THREAD

**Issue by Marion2607** [olivierkes/manuskript#1271]
Hello, 
I'm trying to use Manuskript (0.11.0-2) to write a short story (I'm a beginner), but Manuskript is closing unexpectedly. I have the impression that closure occurs after using the copy/paste function. Do you know why? Should I avoid copy/paste?
Thank you for your feedback, 
ML

**Comment by TheShadowOfHassen** [comment]
Hi. You are using a very out of date version of msnuskript. My guess is if you update to the latest (0.16.1) that the problem could be solved.

You'll find the packages for latest Manuskript here: https://github.com/olivierkes/manuskript/releases/tag/0.16.1 what you need to do depends on your operating system. If help with installing or if the issue persists with the updated version, please let me know.

**Comment by Marion2607** [comment]
Thanks for your feedback, I'll give it a try with the version you shared with me. Thanks a lot !
