### ISSUE TITLE
'Save as' only partly works

### ISSUE THREAD

**Issue by Dreamy-pen** [olivierkes/manuskript#128]
When I want to save the project under a new name by 'save as', the files under the new map only contain Characters (an empty map, though in the original map there are several characters). There is no map called Outline (though the original project does have an outline) and none of the other files of the original map of the project.

I am working with Windows 7.

**Comment by gedakc** [comment]
Thank you @Dreamy-pen for reporting this issue.  I have confirmed this issue using Kubuntu 16.04, so the issue appears common to all OSes.

With _Save to one single file_ **disabled** (accessible via **Edit -> Settings** under the **General** tab), then using **File -> Save as...** creates a skeleton project without the prior project contents.

With _Save to one single file_ **enabled** then using **File -> Save as...** works as expected.  More specifically it creates a backup of the project that does contain the prior project contents.

**Comment by Dreamy-pen** [comment]
Thanks @gedakc  for analyzing this issue.

I usually work with Ywriter5 and one of the things I like about that writing program is the fact that every scene gets it's own (rtf)-file. I wonder whether Manuskript could handle a complete novel in one single file. Do you perphaps have any insights in that matter? I get the impression you prefer using the single file option, is that correct?

**Comment by gedakc** [comment]
> I wonder whether Manuskript could handle a complete novel in one single file. Do you perphaps have any insights in that matter?

I have tested placing my partner's entire first novel called [The Medusa Deception](https://lindatemple.com/) in both a single file, and in multiple files.  So far I have not observed any difficulties with either setting.

> I get the impression you prefer using the single file option, is that correct?

Actually my preference is to have the novel stored in separate files for each scene.  Having each component of the novel in a separate text file enables using external editors in addition to adding source code control of the files, such as with [git](https://git-scm.com/).

In fact @olivierkes, the creator of manuskript, expressed a preference for the new file format which supports storing the novel components in multiple files.  See the news item for [Manuskript 0.3.0](http://www.theologeek.ch/manuskript/2016/03/31/manuskript-0-3-0/).

**Comment by gedakc** [comment]
@Dreamy-pen, would you be able to test a fix for this issue?

To setup a test environment, follow the instructions at [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) with two changes.

The changes are:
- instead of cloning @olivierkes respository, clone @gedakc repository with
  `git clone git@github.com:gedakc/manuskript.git`
- Instead of using **master** or **develop** branch, switch to **fix-file-save-as** branch with
   `git checkout fix-file-save-as`

**Comment by Dreamy-pen** [comment]
Hi @gedakc  , I am sorry, I had a look at the instructions, and I am sure they are fine for people with some basic knowledge of this kind of stuff, but for me installing several programs and using command language, is a bit too far a stretch.  
When there will be a new bèta version of Manuskript available, which I could download in the same simple way as I did the current 'normal' version, I am gladly willing to try that version and report my findings.

**Comment by gedakc** [comment]
No worries @Dreamy-pen.  I appreciate you letting me know that currently you are not ready to set up a test environment.

I will test some more, and if the fix passes all my tests then I will send a Push Request to @olivierkes.

**Comment by gedakc** [comment]
I tested the fix in the **fix-file-save-as** git branch and compared the project files and directory contents using a comparison tool called _kdiff3_.  The **Save as** project filename contents were exactly the same as the original project for both single and non-single project file settings.  As such I created a Pull Request.

**Comment by gedakc** [comment]
The above referenced fix has been committed to the **develop** branch for inclusion in the upcoming 0.5.0 release.

**Comment by Dreamy-pen** [comment]
Thanks!

**Comment by olivierkes** [comment]
Should we close this?

**Comment by Dreamy-pen** [comment]
Sounds good. Thanks for helping out.
