### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by user-of-github-123** [olivierkes/manuskript#1290]
Python version: 3.12.1
When i tried to run the following code:
import language_tool_python
tl = language_tool_python.LanguageTool('en-US')

txt = "good mooorning sirr and medam my namee vincent i am from amerecia !"
m = tl.check(txt)
print(len(m))

i get this error:ModuleNotFoundError: No module named 'distutils'

**Comment by TheShadowOfHassen** [comment]
How exactly does this pertain to Manuscript? Are you having problems running the program with language tool?

**Comment by user-of-github-123** [comment]
It’s working now. I fixed the problem by downgrading my python version

**Comment by TheShadowOfHassen** [comment]
That's good. I don't suppose you could close this issue so the developers know there's nothing they have to do about it?
