### ISSUE TITLE
Crashing when creating a new project - locale C

### ISSUE THREAD

**Issue by JurgenG** [olivierkes/manuskript#130]
I installed (unzipped) the linux file and when launching, I get the start screen where I can choose between the different styles of work. When clicking on, the application crashes.

Here's the error message I'm getting on the terminal:
```
$ ./manuskript 
Running manuskript version 0.4.0.
Warning: failed to load translator for locale C...
Traceback (most recent call last):
  File "manuskript/ui/welcome.py", line 204, in changeTemplate
  File "manuskript/ui/welcome.py", line 267, in updateTemplate
  File "manuskript/ui/welcome.py", line 299, in updateWordCount
  File "/usr/lib/python3.5/locale.py", line 194, in format
    return _format(percent, value, grouping, monetary, *additional)
  File "/usr/lib/python3.5/locale.py", line 215, in _format
    formatted, seps = _group(formatted, monetary=monetary)
  File "/usr/lib/python3.5/locale.py", line 139, in _group
    conv = localeconv()
  File "/usr/lib/python3.5/locale.py", line 110, in localeconv
    d = _localeconv()
UnicodeDecodeError: 'locale' codec can't decode byte 0xe2 in position 0: Invalid or incomplete multibyte or wide character
Fatal Python error: Aborted

Current thread 0x00007f0a511cc700 (most recent call first):
  File "manuskript/main.py", line 73 in launch
  File "manuskript/main.py", line 64 in run
  File "manuskript", line 13 in <module>
Aborted (core dumped)
```
Because I believe it has to do with the locale setup, I'm dumping my locale here too:
```
$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC=nl_BE.UTF-8
LC_TIME=nl_BE.UTF-8
LC_COLLATE="POSIX"
LC_MONETARY=nl_BE.UTF-8
LC_MESSAGES="POSIX"
LC_PAPER=nl_BE.UTF-8
LC_NAME=nl_BE.UTF-8
LC_ADDRESS=nl_BE.UTF-8
LC_TELEPHONE=nl_BE.UTF-8
LC_MEASUREMENT=nl_BE.UTF-8
LC_IDENTIFICATION=nl_BE.UTF-8
LC_ALL=
```

**Comment by gedakc** [comment]
Thank you @JurgenG for providing the terminal output in addition to the locale information.

I think your hypothesis about a problem with the locale is correct.

Would you be able to try setting the following and then starting manuskript?

```
LANG=nl_BE.UTF-8
LANGUAGE=nl_BE.UTF-8
```

For reference my locale is as follows:
```
$ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
```

**Comment by JurgenG** [comment]
Hi, when I manually export the values, it seems to work. But I didn't succeed in adding those permanently.

**Comment by gedakc** [comment]
Thank you for performing the test.

I would have thought that using the language preference setting tools that come with the GNU/Linux distribution _should_ have set **LANG* and **LANGUAGE** accordingly.  However this does not seem to be the case.

To set values for the user permanently, you can edit `~/.profile` to add the language setting commands.

**Comment by olivierkes** [comment]
Is this a system error, or something manuskript should be able to handle?

**Comment by gedakc** [comment]
In my opinion having an application crash is never a good behaviour to have occur.  If possible it would be better if Manuskript informed the user of the issue, and then closed down after the user acknowledged the issue.

**Comment by TheJackiMonster** [comment]
I can't reproduce a crash. So I think this has been solved some way.
