### ISSUE TITLE
never mind this because not reproducible for the time being

### ISSUE THREAD

**Issue by rzw** [olivierkes/manuskript#1309]
Somehow an item seemed to have been locked and was not renamable. This caused crashes regularly when saving after an attempt to reorder or split at cursor, which necessitates renaming all elements within the folder as well. Anyhow, I can't reproduce at the moment. Of course there was no other application open which locked any item. The next time this happens I will check for locking processes.

Windows 10
Manuskript Version 0.16.1-5a10925

But as an urgent advice: Never risk losing content. This means: 

Avoid having unsaved edits before doing anything that could necessitate a renaming of the prefixes
===
examples
1. Split
2. Merge
3. New
4. Rearrange/Reorder
5. etc

**Comment by TheJackiMonster** [comment]
Instead of renaming the issue I would recommend closing it and in case the issue can be reproduced, you can reopen it.

**Comment by rzw** [comment]
In fact I actually wanted to delete it (and couldn't find out how). Could it be a matter of permissions? Are you sure I can close? Because again, I didn't see where and how. 

Am 10-Aug-2024 18:21:12 +0200 schrieb ***@***.***: 

Instead of renaming the issue I would recommend closing it and in case the issue can be reproduced, you can reopen it. 

--
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:   

-------------------------------------------------------------------------------------------------
FreeMail powered by mail.de - MEHR SICHERHEIT, SERIOSITÄT UND KOMFORT

**Comment by TheJackiMonster** [comment]
Ah, that might be a thing on Github. I assumed that an author should be able to close it. Nevermind then.
