### ISSUE TITLE
Indent not saved in custom full screen theme

### ISSUE THREAD

**Issue by bartart3d** [olivierkes/manuskript#133]
When creating a new theme for the full screen text editor, the enable/disable option of paragraphs is not saved.

**Comment by gedakc** [comment]
Hi @olivierkes,

I think the issue being mentioned is that the indent is not displayed in _distraction free_ full screen mode.

Following is a screen shot that demonstrates the missing indent in full screen mode (highlighted with green ink).

![Manuskript Full Screen Versus Editor Window](https://gparted.org/curtis/manuskript/Manuskript-Full-Screen-Versus-Editor-Window.png)

**Comment by olivierkes** [comment]
These are two different settings:

- **Settings → Views → Text Editor → Indent 1st line:** for the text editors, not fullscreen
- **Settings → Fullscreen → Edit theme → Paragraph options → Indent 1st line:** this is for that specific fullscreen theme.

There was a bug that prevented the setting of fullscreen's theme to be saved, but this as been corrected. I think now things work as expected (as I will brillantly demonstrate with the following animated gift):

![test](https://user-images.githubusercontent.com/1192933/31685871-d1c3de24-b384-11e7-9ac3-cdfde0949c62.gif)

At the same time, I see that this creates a confusion. Yet it seems legitimate to have a different display for in-manuskript-editing, and fullscreen themes.

**Comment by vithiri** [comment]
@olivierkes When setting "Indent 1st line" in the full screen settings, it's displayed correctly in the preview until clicking Apply, after which it goes back to being non-indented in the preview in the Settings screen.

**Comment by olivierkes** [comment]
Strange. Are you running the lastest version from develop?

Because I cannot reproduce. And you can see on my screencast above that the preview is correctly updated, as is the fullscreen theme.

**Comment by gedakc** [comment]
First, cool animated gif @olivierkes :+1: 

I can confirm the same behaviour that @vithiri experiences.  I am using the _develop_ branch with last commit cbc02b15d9.  I created a new theme and enabled **Paragraph Options -> Indent 1st line**.  This shows correctly in the preview.

However, when I click **Apply** I lose the _enabled_ setting for **Paragraph Options -> Indent 1st line**.  Full screen mode then is missing the indent.

**Comment by olivierkes** [comment]
I tried everything to reproduce, but I can't. I deleted every system wide config file I could think of, cloned the repo, started with a new project (found and fixed a bug doing thus), created a new theme, but when I click apply, the setting stays… Don't understand…

**Comment by gedakc** [comment]
@olivierkes it looks like you very recently pushed a new commit 2c36902d46.  With this new commit on the _develop_ branch the indent worked once, and once only.  After that whenever I set **Paragraph Options -> Indent 1st line** and then **apply**, the **apply** action seems to disable the setting as seen when I click on the **Edit** theme button again.

This happens even if I create a brand new project.

**Comment by olivierkes** [comment]
I have an idea why. It might be that bool values are stored differently on your system than they are on mine. I used a hack to determine bool values, but now I'm letting PyQt handle QSettings types.

Does that work?

**Comment by vithiri** [comment]
The full screen indent works for me in the latest dev branch this morning.

**Comment by gedakc** [comment]
Great work @olivierkes :+1: 

Using the _develop_ branch with last commit 3b1a3f7fde I am able to change the full screen indent setting and have it persist.  The full screen indent setting is also respected by the new theme I created and displayed properly.
