### ISSUE TITLE
possible Trojan?

### ISSUE THREAD

**Issue by InsaneAwesomeTony** [olivierkes/manuskript#1342]
I tried to download this program. the latest version but my BitDefender is straight up stopping me from doing it. it doesn't have any other problems with stuff from github so this is a the outliner. 

this is what it says:
Feature:
Online Threat Prevention

We blocked this dangerous page for your protection:
https://objects.githubusercontent.com/github-production-release-asset-2e65be/37879342/45f8834e-f774-44f0-91e0-eef681369f13?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241123%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241123T204003Z&X-Amz-Expires=300&X-Amz-Signature=30e7da7c320151cc7b4b0ade8785c635d7bb87c13b5ffebb88b5b08fd872a138&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dmanuskript-0.16.1-windows.zip&response-content-type=application%2Foctet-stream

Threat name: Trojan.GenericKD.72385697
Dangerous pages attempt to install software that can harm the device, gather personal information or operate without your consent.

either way if this is a false positive or not, it is hella weird :S

**Comment by InsaneAwesomeTony** [comment]
read some more in the download link and it explained it was a false positive... due to it being something to do with Pyinstaller.
issue #112 
so my bad...

**Comment by TheJackiMonster** [comment]
No problem. To prevent it, it's still possible to [run Manuskript from source](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) if it's annoying or difficult to workaround.
