### ISSUE TITLE
A Humble Request for an 32bit version

### ISSUE THREAD

**Issue by Edwardphantom** [olivierkes/manuskript#1344]
Please, I'm not skilled enough to make the things work using the tutorial, that appear (maybe) to be a bit outdated.

I'm using a small netbook that have a 64bits processor, but only accept 32 bits operational systems, so I'm locked here with a w10-32bits netbook, using just the old version “14” and begging for help. 

I tried the tutorial and even a tip to try to use the pyinstaller, but in the end, I'm still getting errors.

So, if anyone can provide a working release of a 32bit version of 16.1 (or the latest possible) I will be very glad.

I know that It's not much, but I promise to place the name of the hero that help me on the credits of my book, of course.

Thanks a lot for reading my request.

**Comment by TheJackiMonster** [comment]
You probably want to try [running it from source](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) because that way you can skip building an executable. You should only need to install Python for 32bit Windows 10 (look [here](https://www.python.org/downloads/windows/) for the latest Python version that's compatible).

Otherwise the guide from the wiki should still work, I assume.

**Comment by Edwardphantom** [comment]
i`m fighting here all my day off and still got only error messages on cmd, trying to use the pip to install dependencies and still getting more errors. 

the first thing that i try is run from source.

**Comment by Edwardphantom** [comment]
Sometimes is the CPP / make, other times is pyqt, other times is ... ok i think that you can understand my point, I just can't compile it successfully here .

**Comment by Edwardphantom** [comment]
During the python tutorial when trying to make pip work to install pyqt5 at some moment I got a message requesting CPP working. 

Straightforwardly following the old tutorial not work, I really tried. I print the errors here, if you like, but I'm after a 32bits version, because run from source also not work here either.

**Comment by Edwardphantom** [comment]
Traceback (most recent call last):
  File "D:\Extras\manuskript\bin\manuskript", line 11, in <module>
    from manuskript import main
  File "D:\Extras\manuskript\bin\..\manuskript\main.py", line 256
    LOGGER.info(f'{sig} received. Quitting...')
                                             ^
SyntaxError: invalid syntax

**Comment by Edwardphantom** [comment]
which more i can post ? please, can you just, compile an 32-bit version pleeease ???

**Comment by Edwardphantom** [comment]
C:\>C:\Python34\python "D:\Extras\manuskript\bin\manuskript"
Traceback (most recent call last):
  File "D:\Extras\manuskript\bin\manuskript", line 11, in <module>
    from manuskript import main
  File "D:\Extras\manuskript\bin\..\manuskript\main.py", line 256
    LOGGER.info(f'{sig} received. Quitting...')
                                             ^
SyntaxError: invalid syntax

**Comment by Edwardphantom** [comment]
These are the error that I got when I do the tutorial steps, using an 32 bits version of Windows 10. My portable netbook don't accept 64-bit OS, even with the processor going 64 bit capable.

**Comment by peter88213** [comment]
The offending line of code contains a so-called “f-string”, which, if I'm not mistaken, is only supported from Python version 3.6 onwards. With Python 3.4, as you can see, the line generates a syntax error. 

You can try to patch this line, hoping that there are no more version incompabilities.

In `D:\Extras\manuskript\bin..\manuskript\main.py"` on line 256, replace
```Python
LOGGER.info(f'{sig} received. Quitting...')
```
with
```Python
LOGGER.info('{} received. Quitting...').format(sig)
```
Good luck and Merry Christmas, 
Peter

**Comment by Edwardphantom** [comment]
thanks, i will give a try this weekend

**Comment by Edwardphantom** [comment]
Hi, just closing the thread. After hire a python programmer they spend between 1 at 2 hours and finally make the latest version run successfully. 

ATM we are trying to backtrack the steps and see what we do that make thing happen. 

Edit the code causes some funny thing here, but not work as intended.

Just one last question, if I compile it in 32 bits executable, can I post it here ?

**Comment by TheJackiMonster** [comment]
> Just one last question, if I compile it in 32 bits executable, can I post it here ?

Technically I won't block a link posted here. But I think to make it more trustworthy for others to use, the best option would be to create a script to reproduce your build on other systems. Such a script could be merged and upstreamed into the Manuskript repository, allowing others to use it. Potentially we could even add an executable built with that to regular releases then.
