### ISSUE TITLE
Ajouter intégration de grammalecte

### ISSUE THREAD

**Issue by fran6t** [olivierkes/manuskript#137]
Un correcteur grammatical open source dédié à la langue française existe, pensez-vous qu'il serait possible de l'intégrer dans manuskript ? De ce que j'ai pu en voir il existe un plugin pour libre office écrit en python il y aurait donc peut-être une facilité d'intégration. A priori les plugins pour firefox, libre office ont été programmés par les dev de grammalecte peut-être faudrait-il que je fasse le cheminement inverse c-a-d faire connaitre manuskript au dev grammalecte afin que ce soit eux qui fassent ce travail.
Pour l'heure je découvre encore manuskript que je trouve génial bravo pour ce magnifique travail et ce partage. ( https://www.dicollecte.org/ )

**Comment by olivierkes** [comment]
J'étais tombé dessus par le passé, et effectivement à terme ce serait super de l'intégrer !

Peut-être pourriez vous poser la question aux développeurs de grammalecte s'il y a une documentation pour l'intégrer dans un projet python?

**Comment by fran6t** [comment]
Le temps a passé, je viens de changer mon ordi du coup une petite réinstallation d’un peu tous les outils et ce fameux manuskript même si je m’en suis pas resservi depuis 2017 et que mon petit essai de bouquin n’a pas non plus avancé depuis cette date. Je pense qu’il y du nouveau du côté de grammalecte avec maintenant je cite "CLI & Serveur Interface en ligne de commande, serveur et package pour Python. Prérequis : Python 3.7+ "  un petit thread me semble intéressant ici https://grammalecte.net/thread.php?prj=fr&t=374 encore merci pour tous le travail sur manuskript.
Il semble qu’il faut  télécharger https://grammalecte.net/grammalecte/zip/Grammalecte-fr-v1.5.0.zip puis de lancer setup ensuite on peut parser du texte avec quelque chose du genre cli.py -f test.txt et des options qui permettent de retourner des jsons des différents résultats des options passés.  Par contre je trouve pas de documentation je viens de poser la question ici https://grammalecte.net/thread.php?prj=fr&t=835

**Comment by gedakc** [comment]
We no longer have any people fluent in French currently working on the project.  If you can edit this issue to be English then please do and re-open.
