### ISSUE TITLE
Site of Manuskript is not in the air at the moment

### ISSUE THREAD

**Issue by Dreamy-pen** [olivierkes/manuskript#139]
http://www.theologeek.ch/manuskript gives  an error message at the moment. Hope it wil be fixed soon.
Is there (also) another link to go to a place to download the software?

**Comment by gedakc** [comment]
Thank you @Dreamy-pen for reporting this issue.  I will try to contact @olivierkes regarding the site being unavailable.

In the meantime the software can also be downloaded from [GitHub - Manuskript Releases](https://github.com/olivierkes/manuskript/releases).

**Comment by olivierkes** [comment]
Thanks for reporting and contacting me, it's fixed.

**Comment by Dreamy-pen** [comment]
Thanks, guys!
