### ISSUE TITLE
Contrast Problem in Notes/Refences with Dark Background

### ISSUE THREAD

**Issue by obw** [olivierkes/manuskript#143]
Example:
![contrast](https://user-images.githubusercontent.com/3050806/29885476-49f0c734-8db7-11e7-9cc4-5f61a2a18665.png)

**Comment by gedakc** [comment]
Thank you @obw for your interest in Manuskript.

Would you be able to describe the Operating System used and the steps that demonstrate the contrast issue?

**Comment by obw** [comment]
Under KDE with Dark Settings under 4.4.0-93-generic #116-Ubuntu

**Comment by gedakc** [comment]
Do you have a custom theme?

On my Kubuntu 16.04 (kernel 4.4.0-93-generic) both the **Breeze** and **Breeze Dark** Workspace Themes have sufficient contrast -- at least on my display.  I changed the Workspace Theme with the following menu:  **K -> System Settings -> Workspace Theme**

Breeze Dark
![Kubuntu 16.04 with KDE Workspace Theme - Breeze Dark](https://gparted.org/curtis/manuskript/Manuskript-KDE-Workspace-Theme-Breeze-Dark-Setting.png)

Breeze
![Kubuntu 16.04 with KDE Workspace Theme - Breeze](https://gparted.org/curtis/manuskript/Manuskript-KDE-Workspace-Theme-Breeze-Setting.png)

**Comment by obw** [comment]
Yes use a custom theme: Obsidian Coast

**Comment by gedakc** [comment]
First let me stat that I'm not an expert on workspace themes, so I don't know for sure what is occurring.

One thought I had is that because both **Breeze** and **Breeze Dark** work well with Manuskript it is possible that the problem lies with the custom theme.  You might consider trying to adjust the custom theme or using a different theme.

**Comment by tildagail** [comment]
I think the problem identified by @obw is going to happen in all dark themes. The text colour is set by the OS theme, but the highlight for links/references is set by Manuskript in the file basicHighlighter.py (lines 57-69).

        # References
        for txt in re.finditer(Ref.RegEx, text):
            fmt = self.format(txt.start())
            fmt.setFontFixedPitch(True)
            fmt.setFontWeight(QFont.DemiBold)
            if txt.group(1) == Ref.TextLetter:
                fmt.setBackground(QBrush(QColor(Qt.blue).lighter(190)))
            elif txt.group(1) == Ref.CharacterLetter:
                fmt.setBackground(QBrush(QColor(Qt.yellow).lighter(170)))
            elif txt.group(1) == Ref.PlotLetter:
                fmt.setBackground(QBrush(QColor(Qt.red).lighter(170)))
            elif txt.group(1) == Ref.WorldLetter:
                fmt.setBackground(QBrush(QColor(Qt.green).lighter(170)))

So, normal text will look fine, but references will display as light text on a light background. It needs to be either the text is forced to black, or these colours can be customised somehow.

**Comment by olivierkes** [comment]
Thanks !

I hardcoded the text color in black. Is that acceptable?

![image](https://user-images.githubusercontent.com/1192933/31574973-b5ba4764-b0db-11e7-960c-6d7e209f01a4.png)
