### ISSUE TITLE
How to start a new project from scratch? 

### ISSUE THREAD

**Issue by Reaper10** [olivierkes/manuskript#146]
Can you add a way in manuskript  to start from square on new project. it seems like right now with manuskript  all you can do is open a project that is already started. I see manuskript  becoming the open source alternative to Adobe Story and more so when #120 is added.

**Comment by gedakc** [comment]
To "_start from from square on a new project_":

1)  Start Manuskript
2)  If you have a project currently open, close the project with **File -> Close project**.
3)  You should now be at the welcome screen.  Select a project template from under the titles Fiction, and Non-fiction.
4)  Click **Create** button.
5)  Choose a directory to store the project, enter a filename, and click **Save**.
6)  You should have an empty project created wherein you can fill in the details such as title, etc.

**Comment by olivierkes** [comment]
@Reaper10 , do you think this is enough, or you feel we should change something to make thinkgs easier?

**Comment by vithiri** [comment]
Just chiming in here. The addition of a **File --> New Project** option leading to the Welcome screen could be a less confusing approach.

**Comment by olivierkes** [comment]
@vithiri The **New project** would be in place of **Close project**, or there would be both? (yet doing the same thing)

**Comment by gedakc** [comment]
Closing this question as answered.  Additionally the [Wiki](https://github.com/olivierkes/manuskript/wiki) contains links to articles on how to start a project.
