### ISSUE TITLE
Spell checking works but does not underline misspelled words

### ISSUE THREAD

**Issue by peufeu** [olivierkes/manuskript#147]
Hello!

This is on Linux Mint 18.1 Serena 64 bits.
I downloaded from source and installed the required packages (enchant, aspell, and the dictionary).
In fullscreen mode, spell check works well.

In the standard editor inside the window, spelling errors are **not highlighted**.

But if I right-click on a misspelled word, then I get the context menu with "add to dictionary" and spelling suggestion. This must mean that the spell checker works, and it must be a display bug (ie, the red line under the word is not displayed).

Or something. Bold/italic format does not work either, might be linked to this..

I've traced through the code, and it does seem to setup the highlighter, but so far haven't found the culprit. Any suggestions?

Thanks ;)

**Comment by gedakc** [comment]
Have you tried enabling spellcheck with the menu option **Tools -> Spellcheck**, or by selecting a language with **Tools -> Dictionary -> _language_**?

After I enable spellcheck it underlines mispelled words in red.

You might find the source of the issue by checking the code near these menu options.

**Comment by peufeu** [comment]
Thanks!

Yes, spellcheck is enabled (and it works in the fullscreen editor). As I said, in the normal editor, it does the spellcheck (when I right click on a misspelled word, corrections are proposed in the context menu) however it does not display the red underline marker under misspelled words...

**Comment by gedakc** [comment]
Have you tried checking the dictionary to make sure that the correct one is highlighted?

For example in the following screen shot I have the **en_CA** dictionary highlighted and incorrectly spelled words are highlighted with a red underline.

![Manuskript Menu: Tools Spellcheck Dictionary](https://gparted.org/curtis/manuskript/Manuskript-Menu-Tools-Spellcheck-Dictionary.png)

**Comment by peufeu** [comment]
OK, I just tried this: I went extreme and set the dictionary to French. Since the text is English, when I switch to fullscreen mode, every word is highlighted. No highlight in windowed mode though (but the context menu gives suggestions in French). So my guess is that the spellcheck works, but the red highlighting does not...

...and... writing this gave me an idea:

I'm using the font "Liberation Sans" so I changed it to "Liberation Serif" and... the highlighting is now displayed!

I tried various fonts, and some result in the bug, while some work fine. So it's a display issue. Weird!

**Comment by gedakc** [comment]
Good sleuth work @peufeu to determine that the issue is related to the font chosen.

On my installation I am using the default font chosen by Manusrkipt on my computer, namely **Noto Sans**.  This font seems to work with the red underline to indicate spelling mistakes.

**Comment by peufeu** [comment]
Yes, Noto Sans also makes it work here.

OK, so until it's fixed in the code, for anyone who has the same issue, the workaround would be to change the font ;) not too much of a problem IMO.

**Comment by gedakc** [comment]
Recently I came across a similar sounding bug report:  
[gImageReader: Issue 187 - No red undelinings in the output area for misspelled words](https://github.com/manisandro/gImageReader/issues/187).

The fix involved changing the **UnderlineStyle** from _SpellCheckUnderline_ to _WaveUnderline_.

Unfortunately I have been unable to reproduce the red underline missing for mispelled words.

I have tried:

- Changing **Settings -> Views -> Text editor -> Font Family** from _Noto Sans_ to _Liberation Sans_
- Testing each **Setting -> General -> Application Style**  (Breeze, Oxygen, QtCurve, Windows, GTK+, Fusion)

In every case the red underline was visible below mispelled words.

**Comment by olivierkes** [comment]
I was able to reproduce with font **Ubuntu**, and @gedakc 's fix works.

According to [Qt's doc](http://doc.qt.io/qt-5/qtextcharformat.html#UnderlineStyle-enum), the only difference is that`SpellCheckUnderline` uses `DashDotLine` on macOS instead of `WaveUnderline`.
I think this is a minor disagreement (sorry macOS users), so I'll commit that to develop.
