### ISSUE TITLE
Request: Justified formatting of text

### ISSUE THREAD

**Issue by andersstroem** [olivierkes/manuskript#148]
Being able to [justify text](https://en.wikipedia.org/wiki/Typographic_alignment#Justified) in both the standard editing view and the full screen mode would be highly appreciated.

**Comment by andersstroem** [comment]
The option does seem to exist in a file, but I can't locate it anywhere in the UI, and CTRL+J does not seem to have any effect in the editor or in the fullscreen editor either:

`manuskript/ui/editors/textFormat.py:            "Justify": [self.btnJustify, "format-justify-fill", self.tr("CTRL+J")],`

**Comment by olivierkes** [comment]
Why do you want to justify? Is it: 

 1. For the comfort of writing? 
 2. For the final result after export? 

The button you mentioned exists because at first manuskript was usable in rich text, but we decided to switch to markdown only (plain text). Exporting would have been a headache otherwise. And markdown does not support text alignment in its markup. 

Which means: 

1. If it's 1 you want, it has to be implemented not has a formatting setting, but as a general display setting (like font size or text indent)
2. If it's 2 you want, it has to be added as an export style, like a css for html. But that'd be for the whole text. 
3. If you want only part of you text to be justified, then you have to do that in markdown, for example in [adding an html tag](https://stackoverflow.com/questions/35077507/how-to-right-align-and-justify-align-in-markdown).

**Comment by andersstroem** [comment]
For the comfort of writing. Attaching a screenshot of my setup that I use across both Focuswriter (https://github.com/gottcode/focuswriter) and Scrivener. In Focuswriter, I lack the planning features. :smiley: 

![focuswriter](https://user-images.githubusercontent.com/3118182/31649730-a6db4d70-b314-11e7-8bc7-2fcaa655b72e.png)

**Comment by olivierkes** [comment]
I've made some tests, and I can't get the justify alignment to work. But according to the doc, it should.

Can you try the following test case? (save the code below in a `test.py` file, and run `python3 test.py`)

On my machine, left center and right align work. But not justify.

``` python
#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import Qt

TXT = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis efficitur tempor est, at vestibulum neque fermentum id. Integer tristique molestie nibh eget suscipit. Suspendisse egestas, est in mattis suscipit, nibh ipsum congue libero, ut bibendum turpis dolor vel erat. Integer vehicula nisl a faucibus rutrum. Nulla eu ultrices lectus, eu lobortis lectus. Vestibulum a ipsum quis tellus ultricies dignissim at in dui. In at maximus tortor, sed varius risus. Curabitur quis pretium quam, sit amet eleifend dolor. Duis dignissim justo ac est volutpat, sed efficitur nisi tincidunt. Mauris tempus neque urna, non ornare augue feugiat sit amet. Donec neque libero, feugiat et tortor at, eleifend porttitor felis. Etiam vestibulum nec tortor convallis molestie.

Fusce leo neque, ultrices quis ullamcorper id, eleifend vel mauris. Donec dignissim orci justo, at rutrum ligula pretium id. Vivamus pharetra mauris ante, nec tristique orci lobortis tempor. Nunc sed ultrices odio, et luctus nibh. Phasellus dictum, leo id sollicitudin vestibulum, magna quam convallis velit, ut luctus augue mi eu turpis. Pellentesque aliquet convallis tellus in posuere. Suspendisse eu mauris lacus. Nam id fermentum neque. Phasellus consequat, quam vel hendrerit auctor, dolor urna tempus justo, eu eleifend nulla nulla posuere ipsum.

Pellentesque nec justo diam. Integer suscipit congue feugiat. Proin vulputate lorem eget lorem fermentum facilisis. Nam lacinia vehicula nibh. Quisque ex purus, luctus vitae pretium vitae, fringilla efficitur velit. Sed ut elit vitae arcu aliquam imperdiet quis nec leo. Ut ante lacus, pretium in convallis id, interdum quis quam. Morbi eu metus luctus risus dignissim mattis vel ac metus. Mauris interdum, libero nec suscipit tristique, massa nisl fermentum risus, in lacinia lorem orci quis tortor. Duis sollicitudin dui sed varius tempor. Proin nec tempus augue. Suspendisse ante nulla, dignissim in luctus at, accumsan a arcu.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris mollis turpis quam, nec pulvinar ipsum sodales vitae. Phasellus volutpat, ipsum non convallis convallis, nisl nisi sodales nisi, vitae vestibulum nisi mauris ac metus. Donec blandit, lectus pharetra maximus porttitor, nisl dolor feugiat est, ut lobortis lectus sapien et nisl. Etiam sit amet eros in lacus cursus fermentum ac at est. Vestibulum nec vulputate felis. In dignissim turpis at tortor tempus, ullamcorper tempus risus tincidunt.

Aenean at massa porta, sollicitudin nibh sit amet, mollis justo. Sed pharetra lectus in libero maximus, vel finibus sem malesuada. Curabitur et ante vitae augue imperdiet tincidunt. Nulla ut mollis erat, ac rhoncus nunc. Vestibulum efficitur pellentesque augue, ultricies elementum tortor tristique vel. Suspendisse egestas sem ut nulla tristique, vitae faucibus dolor tempor. Maecenas efficitur vulputate dictum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis rhoncus faucibus mi."""


class MyWidget(QWidget):
    def __init__(self):
        QWidget.__init__(self)
        l = QVBoxLayout()
        self.cmb = QComboBox()
        self.cmb.addItems(["Left", "Center", "Right", "Justify"])
        self.cmb.currentIndexChanged.connect(self.setTextAlign)
        self.text = QTextEdit()
        self.text.setText(TXT)
        l.addWidget(self.cmb)
        l.addWidget(self.text)
        self.setLayout(l)
    
    def setTextAlign(self, v):
        
        al = [Qt.AlignLeft, Qt.AlignCenter, Qt.AlignRight, Qt.AlignJustify][v]
        
        self.text.moveCursor(QTextCursor.Start)
        lastPosition = -1
        currPosition = self.text.textCursor().position()
        while lastPosition != currPosition :
            self.text.setAlignment(al)
            self.text.moveCursor(QTextCursor.Down)
            lastPosition = currPosition
            currPosition = self.text.textCursor().position()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = MyWidget()
    w.show()
    sys.exit(app.exec_())

```

**Comment by olivierkes** [comment]
I just tested [this code](http://thecodeinn.blogspot.ch/2013/07/fully-functional-pyqt-text-editor.html) where AlignJustify works in PyQt4. When I [ported it to PyQt5](https://gist.github.com/olivierkes/a5ed456fb4313d248042b3ff29f5e754) it doesn't. So this might be a bug with Qt5 or PyQt5 ?

**Comment by The-Compiler** [comment]
Works fine here with Qt 5.7.1 / Qt 5.8 / Qt 5.9.1.

**Comment by olivierkes** [comment]
Ok, so there's a problem on my end.

Please try branch `feature/justify` and tell me if things work as expected.

![image](https://user-images.githubusercontent.com/1192933/31661867-8cb8308e-b33c-11e7-83c0-4c16bfe1b0bb.png)


![image](https://user-images.githubusercontent.com/1192933/31661842-73d1ce72-b33c-11e7-9996-6f3eda16c6d7.png)

**Comment by gedakc** [comment]
Great work @olivierkes on the justification feature.  On my Kubuntu 16.04 computer, all alignments worked as expected (left, center, right, justify).  Following is a screen shot using the _feature/justify_ branch with Manuskript alignment set to _justify_.

![Manuskript with Justify Alignment](https://gparted.org/curtis/manuskript/Manuskript-Alignment-Justify.png)

**Comment by olivierkes** [comment]
Great, thanks for the feedback, I'll merge it then !

**Comment by andersstroem** [comment]
This looks great!

Just an observation, the "Indent 1st line" option seems to get unticked again for Fullscreen mode once Apply is clicked even though the setting persists in the normal editor.
