### ISSUE TITLE
Redaction view navigation improvements

### ISSUE THREAD

**Issue by camstevenson** [olivierkes/manuskript#157]
I became lost and frustrated attempting to navigate in the Redaction view:

- It wasn't obvious how to get from the editor view back to the card view
- It wasn't obvious how to get to the root card view

My suggestion would be to add a "Root" node to the Project Tree, and an "Up level" button to the tab view (see crude mockup).

(If I'm misunderstanding something fundamental, feel free to correct me :-))

![redaction-nav](https://user-images.githubusercontent.com/692807/31576348-1d8dd514-b0c7-11e7-97a6-b24e44457606.jpg)

**Comment by olivierkes** [comment]
Hi Cam,

Thanks for the feedback, most useful. I'm not satisfied with the navigation either.

For now, to do what you want to do, you can simply click on the tree view in the background (under items). I feel that once you know it it's enough, but you have to know it.

I'd like to avoir overload interface as much as possible, therefore I'd like to avoir adding too much buttons, so if we can find another solution I'm happy. Keyboard navigation? Pressing "Escape" to go up? But if others agree with you on those buttons, I'll do it.

I already added the above commit that let you double click on the back ground in index card view to go up.

**Comment by camstevenson** [comment]
Understood.  Thanks  Olivier!

**Comment by olivierkes** [comment]
I added a "Go Up" button (shortcut: ALT+Up)

![image](https://user-images.githubusercontent.com/1192933/31578719-7bec0062-b127-11e7-8abe-25bb1965d43d.png)

**Comment by camstevenson** [comment]
Awesome!

**Comment by gedakc** [comment]
The _go up button_ is a great addition.  Thank you @camstevenson for bringing this issue to light.

**Comment by gedakc** [comment]
Closing this issue as we prepare for the 0.5.0 release.
