### ISSUE TITLE
New flash card design

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#158]
There are a few blog post that review manuskript, and a common reaction that comes often is that the interface is ugly. "Tthe kind of UI that drives people away from open source." says [one](http://www.omgubuntu.co.uk/2016/12/manuskript-promising-scrivener-alternative#comment-3037247739). That's frustrating because I try as much as possible to keep the interface clean.

Recently I had a mail exchange with @camstevenson and came upon is own writing software, [eclecdec](http://camstevenson.com/2017/08/12/eclecdec-beta/). I liked the way he did his flash cards ([see here](https://www.microsoft.com/fr-ch/store/p/eclecdec/9n37m6jllw2q?rtc=1#)), a sober flat design, so i shamelessly copied it:

![image](https://user-images.githubusercontent.com/1192933/31584149-f1c54952-b1a8-11e7-8a56-021d2ccb9ac8.png)

Compared to the old style:

![image](https://user-images.githubusercontent.com/1192933/31585308-e6b8a7ea-b1bf-11e7-9473-1d00ad13e682.png)

It's already been pushed to develop so people can try it. You can easily switch in the preference dialog.

As the old one, it can be customized: background color, border, text color, icon and corner.

![image](https://user-images.githubusercontent.com/1192933/31584163-3d8e54c8-b1a9-11e7-9e43-f3a218709ee2.png)

**What do you think of it ?** Is that an improvement? What else could be improved?

**Comment by camstevenson** [comment]
Cool, and I'm flattered ;-)
You're welcome to all of the eclecdec image assets if you decide to go this route and you want them.

**Comment by gedakc** [comment]
Both the old and the new styles look good to me.
