### ISSUE TITLE
New navigation icon design

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#159]
As in #158, trying to improve Manuskript first impression. I'm already using Numisk icons in the software, so I tried to find some that would work for the Navigation bar. Here is the result:

![image](https://user-images.githubusercontent.com/1192933/31584635-81f61b06-b1b2-11e7-98ad-f3c07ad63f78.png)

Compared to:

![image](https://user-images.githubusercontent.com/1192933/31584650-b0e645f8-b1b2-11e7-9b9f-f0f00ad86bfa.png)

Is that an improvement? Do you have other ideas?

**Comment by camstevenson** [comment]
I've found a good source of icons is https://material.io/icons/
I generally base mine on those.  They're Apache licensed, which I understand is compatible with the GPL.  I don't know enough about Python (yet!) to know if there's svg support, but if there is, svg is great because it's device resolution independent and colourable.

**Comment by gedakc** [comment]
I like all of the new icons.  However I personally found the old world icon more representative.  This is a minor point though.  More important is that all icons are of the same style and that most are easily recognizable.

**Comment by olivierkes** [comment]
Thanks @camstevenson , I'll have a look.

Changed the world icon:

![image](https://user-images.githubusercontent.com/1192933/31588823-e1ef4fc4-b1f7-11e7-96ab-b63e0829994b.png)

**Comment by gedakc** [comment]
Thanks @olivierkes for updating the world icon.  I think this will help our users with recognition.

**Comment by andersstroem** [comment]
The new theme looks great, and I'm happy to see all the recent activity here. :smiley:
