### ISSUE TITLE
Windows installation issue

### ISSUE THREAD

**Issue by ltgalloway** [olivierkes/manuskript#16]
Hello, trying to install Manuskript on Windows 7 and running into some issues. I'm not technically adept so I am not sure how to troubleshoot this issue. Am I missing some other application prerequisites? I was able to capture the installation window and I've attached it here. 

![manuskript](https://cloud.githubusercontent.com/assets/18120049/14081148/66b3dc8e-f4c6-11e5-908d-2060df2e4f02.png)

**Comment by olivierkes** [comment]
Thanks, this is a known bug, and it has been corrected in branch develop.
You'll need to wait a few days for release 0.3.0 of manuksript.

**Comment by olivierkes** [comment]
Or try again with this package: https://github.com/olivierkes/manuskript/releases/download/0.2.0/manuskript-0.2.0-windows.zip

**Comment by ltgalloway** [comment]
Looks like this works. I'm able to launch the application. Thanks! Looking forward to checking it out. I'll be making a contribution.
