### ISSUE TITLE
As a Linux user, I want to be able to just run 'manuskript' globally.

### ISSUE THREAD

**Issue by EricPonvelle** [olivierkes/manuskript#161]
Currently, to run Manuskript, as a Linux user I must run either 'bin/manuskript' or navigate to the bin folder and run manuskript there.  Can you add the manuskript bin to the Linux root folder so that it can be accessed from anywhere in the terminal?

**Comment by gedakc** [comment]
I added the `bin/manuskript` directory to the PATH variable.  That way I can type `manuskript` while in any directory to invoke manuskript.

To make the change permanent, I edited my `~/.profile` file and added the following lines:
```
# Extend path with manuskript
if [ -d "$HOME//manuskript/bin" ] ; then
    PATH="$HOME//manuskript/bin:$PATH"
fi
```
In the above example manuskript is located in my home folder.  Be sure to replace `$HOME/manuskript/bin` with the location of your manuskript bin directory.

Does that answer your question?

**Comment by EricPonvelle** [comment]
Perfect. I'm guessing there's no way to add this as a commit so that all
users get this by default? But, maybe I'll test it out and add it to the
instructions / readme and attribute proper credit?

It was super frustrating, and this is exactly what I wanted.

**Comment by gedakc** [comment]
While the solution I mentioned addresses the issue, it is not something that everyone would want.

Longer term a better method of packaging Manuskript is required.  More specifically the binary package should create a desktop menu entry upon installation.

If anyone knows how to create a proper Python project binary package with GUI menu and such, then I'm all ears.  :-)

**Comment by vithiri** [comment]
Just speculating here -- wouldn't this be best handled through an installation script or by the package manager for the relevant distribution?

**Comment by gedakc** [comment]
@vithiri yes.  The challenge is finding out how.

**Comment by olivierkes** [comment]
Packaging is really the issue here… And that's out of my depths :)

For now, I added this question and answer to [the wiki](https://github.com/olivierkes/manuskript/wiki/How-to-run-manuskript-globally%2C-from-anywhere). Thanks to both of you.

**Comment by vithiri** [comment]
http://build.snapcraft.io could be worth looking into if distributing the application as a snap package would be acceptable. No experience with using it however.

**Comment by olivierkes** [comment]
I guess a `make install` could be used on linux plateform running from source, similar to this: https://github.com/dae/anki/blob/master/Makefile

**Comment by gedakc** [comment]
The work-around I suggested is not something I would recommend be built into a makefile.

In my opinion the proper way forward is for Manuskript to be packaged so it can be easily installed using the commonly accepted methods for each OS.  For Windows this is usually an executable file that installs the program along with menu icons.  For GNU/LInux this varies by distro:  for Fedora this is a .RPM package, and for Debian based distros this is a .DEB package.  Often a volunteer familiar with a given distro will step up to package the application for the distro.

In the meantime I think our efforts are better spent on improving Manuskript.  And while the PyInstaller packages are not a great solution, these do make it easier for many users to be able to use Manuskript.

**Comment by olivierkes** [comment]
>Often a volunteer familiar with a given distro will step up to package the application for the distro.

I discovered that an AUR package (for Archlinux) had been created: https://aur.archlinux.org/packages/manuskript-git/
 It's for 0.3.0, flagged out of date, but it shouldn't require much work to update it.

>In the meantime I think our efforts are better spent on improving Manuskript.

This is wise :)

**Comment by olivierkes** [comment]
Closing this since we have .deb and .rpm packages.
