### ISSUE TITLE
Suggestion: Block insertion cursor.

### ISSUE THREAD

**Issue by vithiri** [olivierkes/manuskript#163]
Focuswriter and Scrivener both offer the option to enable a block insertion cursor, ~9px wide (Scrivener allows you to decide the width, Focuswriter does not).

Would it be possible to offer this as an option?

![block_insertion_cursor](https://user-images.githubusercontent.com/3118182/31687928-ea53a1b2-b38a-11e7-805d-7dcb859fbd4c.png)

**Comment by olivierkes** [comment]
Yes it's quite easy (`QTextEdit.`[setCursorWidth](http://doc.qt.io/qt-5/qtextedit.html#cursorWidth-prop)).

But I'm not sure.. what's the point of it?

Also: would you like to see that in fullscreen, normal text editor, or both?

**Comment by vithiri** [comment]
@olivierkes It's purely an aesthetic preference. I'd like to see it in both views.

**Comment by olivierkes** [comment]
Here it is:

![image](https://user-images.githubusercontent.com/1192933/31709354-1168d5e4-b3f2-11e7-9075-3bdc1c167d35.png)

![image](https://user-images.githubusercontent.com/1192933/31709411-39ff0ac8-b3f2-11e7-93b0-9d50c33359c0.png)

Just to be sure, it is supposed to keep blinking?

![test](https://user-images.githubusercontent.com/1192933/31709583-b82b01a4-b3f2-11e7-9803-1a1a59bbf7ab.gif)

**Comment by vithiri** [comment]
That looks perfect. I use https://github.com/igogo/qt5noblink to disable the blinking, but adding a toggle for that if possible wouldn't hurt either.

**Comment by olivierkes** [comment]
Great. And thanks for the link, that's easy to implement too. I'll probably do that too.
(Though now I should concentrate on relasing 0.5.0 instead of adding new features ^^)

**Comment by vithiri** [comment]
Thanks again, and fair enough. :smile:
