### ISSUE TITLE
Feature request: disable cursor blinking

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#165]
Disable cursor blinking in order to reduce distractions. See #163.

That can be easily done with `QApplication::cursorFlashTime` and `QStyleHints::cursorFlashTime`.

**Comment by olivierkes** [comment]
You can now disable cursor blinking in settings:

![image](https://user-images.githubusercontent.com/1192933/31766920-826a0416-b4c9-11e7-8be2-e680e1524db3.png)

It doesn't work on my system, but I've been calling `qApp.setCursorFlashTime(0)` just like many other coders do. It might be my qt version that is buggy (same as for text alignment/justify). 

Please tell me if it works for you (it's on branch **future**)

**Comment by olivierkes** [comment]
Thanks, fixed. Though I thought I tested that, strange... Anyway, I'm going to check if I can install a newer version of Qt.

**Comment by gedakc** [comment]
Using the latest feature/future branch with last commit d78b81 I confirm that enabling and disabling of the blinking cursor works.

Regarding different versions of Qt, I find it useful to have Virtual Machines with different distro versions each containing the default Qt version for that distro version.

**Comment by vithiri** [comment]
Confirmed as above here as well. :smiley:

**Comment by olivierkes** [comment]
Updated my Qt version and was able to confirm as well. Thanks for testing !

> Regarding different versions of Qt, I find it useful to have Virtual Machines with different distro versions each containing the default Qt version for that distro version.

Good idea. But right now I only have a cheap chromebook running ubuntu with crouton, and less than 1gb disk free, so this is unfortunately not an option. :)

**Comment by gedakc** [comment]
Regarding no room for virtual machines:  No worries.  It was just a suggestion, and yes you are correct that it would required significantly more resources than "1GB disk free".

Kudos to you developing on an inexpensive chromebook.  It speaks well for Manuskript running on low spec computers if Manuksript can also be developed on the same.  :-)

**Comment by gedakc** [comment]
Changing milestone to **0.5.0** because the enhancement was committed on Oct. 19, 2017 and hence included in the **0.5.0** release on Oct. 31, 2017.  This milestone correction is being done to ensure that the [github_changelog_generator](https://github.com/skywinder/github-changelog-generator) functions properly to automatically create CHANGELOG.md.
