### ISSUE TITLE
Some panels require initial two clicks of RHS tab to hide

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#167]
Panels that require initial two clicks of Right-Hand-Side tab to hide are:

* Plots     -> Book summary
* Redaction -> Project Tree
* Redaction -> Story line

Test Steps:

1.  Start manuskript with no auto-open of any existing project
2.  Create new manukript project
    Try with Novella, Novel, non-fiction, etc as start point.
3.  Select Redaction/Editor on Left-Hand-Side Navigation panel
4.  Click once on "Project tree".   (Shown by default)
    *** Notice no change to display ***
5.  Click once more on "Project tree".
    *** Notice that "Project tree" panel hidden ***
6.  Click once on "Metadata".       (Hidden by default)
    *** Notice that "Metadata" panel is shown.

Four panels use custom widgets on the Right-Hand-Side tabs to control visibility.  These panels are:
```
  PANEL NAME     VIEWABLE ON NAVIGATION TAB   DEFAULT VISIBILITY
  ------------   --------------------------   ------------------
  Book summary   Plots                        Shown
  Project tree   Redaction                    Shown
  Metadata       Redaction                    Hidden
  Story line     Redaction                    Shown
```
**EDIT**:  The default setting for visibility seems to be affected by the settings of the previous project.

HYPOTHESIS:

When the custom widget is created, the method [widget.isVisible()](https://github.com/olivierkes/manuskript/blob/7a83ac28d991231fd748554ec7965887a63a448a/manuskript/ui/collapsibleDockWidgets.py#L64) always returns false.  Due to this return value, the initial RHS tab QAction setChecked() value is set to the wrong value when the widget is shown by default.  The user must then click the RHS tab twice to get the QAction to properly align with the widget visibility.

**Comment by olivierkes** [comment]
> When the custom widget is created, the method widget.isVisible() always returns false.

That was right, thanks for your detailed analysis, it helped me pinpoint the issue. Please confirm that it works as expected.

Also, while working on that, I realized that toolbars should not be displayed on the welcome screen. Not only is it unnecessarily distracting, but also it could cause a crash if the user open the search dock or cheatsheet, and searched for some value before models are loaded.

I think this commit fixed that too, by hiding the dock widgets, and then restoring them to their previous visibility state after opening or creating a project. This was a bit more frustrating to do than expected, but I think/hope it works alright now.

> The default setting for visibility seems to be affected by the settings of the previous project.

Yes. The state of the window — visibility of panels, size and position of main window, panels and splitters — is not stored in the project file, but on the system wide settings. (On my Ubuntu 14.04, it is in `~/.config/manuskript/manuskript.conf`) The rationale behind that was to have as less changes as possible in the project folder, so that when versioning it it's not cluttered with not-so-meaningful stuff.

**Comment by gedakc** [comment]
Good work @olivierkes on solving this issue.  I had tried to fix it myself, but was unable to find an elegant solution.  Your approach worked well in all my testing.  :-)

Would you consider including this improvement in the 0.5.0 release?

The reason I ask is because it fixes a potential crash by hiding the dock widgets.  Also it makes Manuskript work like a professional application because all clicks on the RHS tab cause a change in pane visibility.  Further I checked the code changes and did not observe any new or changed translation strings so including this fix should not adversely impact language translations.

**Comment by olivierkes** [comment]
Thanks for testing !

> Would you consider including this improvement in the 0.5.0 release?

Yes good idea. (Even if it added translations strings, since the translators haven't started to work yet I would just send them updated files). Technically, we do this by cherry-picking this commit, or is there a better way? Would you mind doing it?

**Comment by gedakc** [comment]
Sure I can give it a try.  I'm familiar with cherry-picking a commit, but haven't tried pushing directory to your repository -- that will be new for me.

**Comment by gedakc** [comment]
This enhancement has been cherry-picked into the _develop_ branch for inclusion in the 0.5.0 release of Manusrkipt.

In case I did anything wrong, following are the steps I used to cherry-pick and push the commit:
```
$ git checkout develop
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
$ git cherry-pick 4484423ace3e0c4e99d0868848750bb3512af606
[develop d95c3f8] Fixes: Some panels require initial two clicks of RHS tab to hide #167
 Author: Olivier Keshavjee <olivier.keshavjee@gmail.com>
 Date: Thu Oct 19 22:21:15 2017 +0200
 3 files changed, 109 insertions(+), 19 deletions(-)
$ git push
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 2.41 KiB | 0 bytes/s, done.
Total 7 (delta 6), reused 1 (delta 1)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
To git@github.com:olivierkes/manuskript.git
   3b1a3f7..d95c3f8  develop -> develop
$ 
```
