### ISSUE TITLE
Suggestion: Configurable editor margins.

### ISSUE THREAD

**Issue by vithiri** [olivierkes/manuskript#168]
While it's possible to expand the Metadata and Project Tree panes and configure them to be wider than necessary, the text area in the editor can become very wide.

Having a way to enforce the margins in the editor (either by % or px) could mitigate this issue. The same functionality is present for the full screen editor under the Text Background settings (width).

**Comment by olivierkes** [comment]
Good suggestion. It looks much nicer. You can now set a max-width, and/or margins:

![image](https://user-images.githubusercontent.com/1192933/31767097-20429ce8-b4ca-11e7-9512-9918bf0c83b4.png)

You can test it on branch **future**.

**Comment by vithiri** [comment]
This looks great! Something to consider could be preventing implausible values from being entered or applied. I am able to specify 2000px margins on a 1366x768 screen. :smiley:

**Comment by olivierkes** [comment]
Yeah I wasn't sure how much I should put, since some people have high density screens.. I'll leave it at that for now :)
