### ISSUE TITLE
Does not run on Ubuntu 17.10

### ISSUE THREAD

**Issue by docaltmed** [olivierkes/manuskript#170]
I had Manuskript running successfully on 17.04. The manuskript folder had been extracted into my home folder, and the application has been running properly for months. After upgrading to Ubuntu 17.10, the program will not start.  It looks like this:

**user@computer: ~$** cd home/user/manuskript
**user@computer:home/user/manuskript$** manuskript
**manuskript: command not found**

I have checked, and the manuskript executable is in that folder, and the permissions are correct. I cannot think of why the upgrade to 17.10 would have changed any of that anyway. Suggestions?

EDIT: I resolved the problem by deleting my old manuskript folder, re-installing with the source code, and launching with bin/manuskript. 

I don't know why that worked, but it did, and I'm happy.

**Comment by gedakc** [comment]
Thanks @docaltmed for reporting the issue you experienced and how you resolved it.

Do you recall which install method (binary or source code) and which file you downloaded to install manuskript on ubuntu 17.04?

**Comment by olivierkes** [comment]
> Perhaps you had the manuskript folder in your PATH environment variable, and that setting was lost on upgrade???

That was my thought too.

Anyway, thanks for reporting @docaltmed. If you know the answer to gedakc's questions above that could be useful for us. I'll close this in the meantime.
