### ISSUE TITLE
Create new project ignores changes made to template levels before Create

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#171]
Steps to reproduce:

1. Start manuskript (with no auto-load of previous project)
2. Click on **Novel** template.  This pre-populates 20 Chapter, 5 Scene, of 500 words each.
3. Increase the number of chapters to 25, scenes to 10, and words to 600.
4. Click **Create**, select a folder, enter a filename, and click **Save**.
5. Click on **Outline** or **Editor** and notice that only 20 chapter, 5 scene, 500 words each exists in new project.

**Comment by olivierkes** [comment]
Done.

**Comment by gedakc** [comment]
Good work @olivierkes.  Using the _feature/future_ branch I confirmed that the fix permits changes to the template and these changes are reflected in the created project.

I noticed that you updated the milestone to 0.5.0.  I am in agreement with including this enhancement in the upcoming 0.5.0 release.
