### ISSUE TITLE
Pandoc output: add more custom settings

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#173]
Notably:

# General

  - ~Option to disable YAML metadata block (`--from=markdown-yaml_metadata_block`)
    Because sometimes it causes troubles (see #124)]]~

# Epub

  - ~ePUB2 (default) / ePUB3 (`pandoc -t epub3`)~
  - Custom stylesheet (`--epub-stylesheet`)
    The CSS could be contained in a text item not compiled

**Comment by Weej1** [comment]
I was JUST going to make this suggestion myself! Right now I'm using a combination of Markdown apps to achieve the "look" I need for my documents (in PDF mostly).

I've touched upon the issues I faced here: https://github.com/Skrifa/Skrifa/issues/11 it mentions Manuskript and others and how I use them to achieve my goal. It's a long post so hope you have a glass of water at hand :P 

The point being that if I can get this ability I'd be one step closer to reducing the no. of apps I use. I like Manuskript - its look and feel just works, here's to hoping it only gets better!

**Comment by olivierkes** [comment]
> (…) if I can get this ability (…)

You mean the custom CSS, right? Would you mind sending me one you like for your doc, to use in my test? And/or can you show me an export of PDF through typora?

Also, if I understood correctly your post, you use manuskript to organize your snippets, but you edit them in skrifa. Is that right? Out of curiosity, why is that? What editing capabilities are you missing in manuskript?

**Comment by olivierkes** [comment]
Added:

- epub3
- option to disable YAML metadata block
