### ISSUE TITLE
Spanish transalation for manuskript 0.5.0

### ISSUE THREAD

**Issue by vmpajares** [olivierkes/manuskript#174]
Hi Olivier,

I finish the spanish translation for the 0.5.0 as you ask in twitter.
I wanted to generate a pull request, but I'm a little busy at work this week and attaching it is faster to me.
I hope it helps.

[manuskript_es.ts.zip](https://github.com/olivierkes/manuskript/files/1417577/manuskript_es.ts.zip)

**Comment by olivierkes** [comment]
You're awesome, thanks !

**Comment by olivierkes** [comment]
Pushed to develip, will be released in 0.5.0 very soon.
Thanks again :)

**Comment by vmpajares** [comment]
Your welcome :)

**Comment by vithiri** [comment]
@olivierkes Is there a guide available for how to contribute translations?

**Comment by olivierkes** [comment]
> Is there a guide available for how to contribute translations?

Now there is, thanks for the suggestion: https://github.com/olivierkes/manuskript/wiki/Translate-Manuskript

Are you interrested in translating? If so, please tell me if the guide makes sense or not.

**Comment by vithiri** [comment]
@olivierkes Thanks, the guide made perfect sense! I would be able to contribute a Swedish translation if needed. I can't promise too much about ongoing maintenance moving forward, but at least there'd be a base body of material for someone to pick up.

**Comment by olivierkes** [comment]
Awesome!
