### ISSUE TITLE
Swedish translation (sv-SE).

### ISSUE THREAD

**Issue by vithiri** [olivierkes/manuskript#177]
Attaching my proposed Swedish translations.

I accidentally translated against the feature-future branch, so please let me know if I should start over with the development branch instead if there's no easy way to merge this into the relevant branch.

The name of Swedish in Swedish is "Svenska".

`Removing old link to prevent mix-ups`

Edit: This ticket should be good to go again now. The latest package is included further down.

**Comment by olivierkes** [comment]
Thank you very much, you've been fast !
I'll be waiting for your corrections.

Just a question in the meantime, should this be `sv` or `se` or `sv-se`? Is `sv-se` (Swedish from Sweden) very different from `sv-fi` (Swedish from Finland)? (I'm using [this table](https://www.science.co.il/language/Locale-codes.php) as reference) The simplest would be `sv`, if it is acceptable for both.

**Comment by vithiri** [comment]
I ended up remaking it from scratch based on the `develop` branch as suggested by the instructions since there were quite a few strings that could be made more standards compliant in my translation already. :smiley: 

This should be fine for both sv-SE and sv-FI, so presumably that would also mean that it's fine for SV in general.

There were some strings that seemed incomplete or didn't seem to fully make sense in the original English translation, so I made some comments while translating -- hopefully those can be reviewed at some convenient point, but none of them seemed to be of any real blocking status.

I also noticed that when loading the SV translation the left hand pane in the general settings window (Edit - Settings) becomes so narrow that most text is unreadable; the issue is there in English as well, but not as pronounced, so I suspect that one of the Swedish strings became longer than the longest English string at some point in this window.

**Left hand pane too narrow**

![settings_window](https://user-images.githubusercontent.com/3118182/32148323-91049700-bcf5-11e7-803a-e349ea8646d5.png)

**New translations based on the `development` branch:**

[manuskript_se.zip](https://github.com/olivierkes/manuskript/files/1425494/manuskript_se.zip)

**Comment by olivierkes** [comment]
Nice work ! It's been pushed to develop.

Actually, you could have translated from `future`, I'm sorry I should have told you. When we merge it into develop (and possibly 0.5.0), I might ask you to update it ;) (but only then, in case there are some new strings)

**Comment by vithiri** [comment]
Awesome, and please let me know once it needs updating -- I can't commit fully to ongoing maintenance, but will try to do my best on a request basis. :smiley:

**Comment by olivierkes** [comment]
>I also noticed that when loading the SV translation the left hand pane in the general settings window (Edit - Settings) becomes so narrow that most text is unreadable; the issue is there in English as well, but not as pronounced, so I suspect that one of the Swedish strings became longer than the longest English string at some point in this window.
>
>**Left hand pane too narrow**
>
> …

Thanks for reporting. I added an arbitrary fixed size to the left hand pane. Testing with all the available translations it seemed ok to me. Maybe in the future this fixed size could be calculated from the length of the translated strings,  but for now this should suffice.

**Comment by vithiri** [comment]
@olivierkes I can see that some new strings were pulled into 0.5.0 which were previously in feature-future I believe, two I noticed right away were the cursor blinking ones and the margin ones. Shall I submit a new update based on the 0.5.0 files perhaps, and should it go to a new ticket or this one?

**Comment by olivierkes** [comment]
Thanks @vithiri. Yes they should be translatable, I just did it with the French translation. Possibly I already updated the ts files, even for Swedish, and you should see the new untranslated strings.

**Comment by vithiri** [comment]
@olivierkes When I look at the French translation, I am able to search for "blinking", but that doesn't return any results in the Swedish one after running `pylupdate5 -noobsolete i18n/manuskript.pro`.

Perhaps I'm misunderstanding how to bring the new English words into the SV file if it shouldn't be the command above, but there are 1754 English base words in the SV file and 1808 English base words in the FR file.

There's of course no major breakage since mostly everything is translated, but I wouldn't mind translating the few missing pieces.

**Comment by olivierkes** [comment]
I've seen the problem: I forgot to commit the change in i18n/manuskript.pro.

Add `TRANSLATIONS     += manuskript_sv.ts` at the end, and re-run `pylupdate5 -noobsolete i18n/manuskript.pro`

Sorry for that :)

**Comment by vithiri** [comment]
@olivierkes Well spotted. We're rolling again. I'll upload the new strings in a bit.

**Comment by gedakc** [comment]
@olivierkes are you planning to include these updated translations in the 0.5.0 release?

If so then I will hold off on building the Linux and Windows PyInstaller packages.

**Comment by vithiri** [comment]
[manuskript_sv.zip](https://github.com/olivierkes/manuskript/files/1432416/manuskript_sv.zip)

Updated SV translations attached. There's a single warning, but it seems to be caused by an encoding issue in the source text.

**Comment by olivierkes** [comment]
Maybe we make a 0.5.1 when we get the German translation as well?

**Comment by vithiri** [comment]
Just for reference, for the SV translation either approach should be fine. I only translated newly added strings though, I'm not sure if QT Linguist can track modified source texts that already had translations and did not review the entire file.

**Comment by gedakc** [comment]
> Maybe we make a 0.5.1 when we get the German translation as well?

Sure, we can do that when we have all the translations ready to be bundled into a package.

**Comment by olivierkes** [comment]
> … I'm not sure if QT Linguist can track modified source texts that already had translations and did not review the entire file.

Yes I think it does something like that. I updated the translation in develop, so we'll take it from there if we want to make a new release with it and other translations.

Thanks again !

**Comment by vithiri** [comment]
@olivierkes Are the Swedish translations due for a review again soon? It looks like at least 0.6.0 has already been released which is likely lacking some translations. 😃 

Please let me know when the best time to review them again would be to ensure that the next official release is as complete as possible.

**Comment by olivierkes** [comment]
Thanks @vithiri !

It's difficult to answer, since I don't have a clear release schedule.

When we are about to make a release, I'll call upon the translator to check whether they can update the translation, and give a time frame. The thing is that last time this happened, one of the translator had no time at the moment, so either we delay the release only for one translation, or we publish it not properly translate. I'm not sure what the best way to go would be.

To my mind, a good compromise would be: whenever you have some time you can update the translation in `develop`, to keep this one as complete as possible, so that when we start the new release, the translation is not to far behind.

What do you think?

By the way, weblate's admin just activated a free account for manuskript, today: https://hosted.weblate.org/projects/manuskript/translations/
