### ISSUE TITLE
Untranslatable strings.

### ISSUE THREAD

**Issue by vithiri** [olivierkes/manuskript#178]
If you right click an object in the editor, you have the option to set a POV.

The list that pops up seems to use hard coded values since they're still showing up in my translated interface but cannot be found amongst the translations in my Swedish .ts file:

![pov](https://user-images.githubusercontent.com/3118182/32148751-bcd0afda-bcfb-11e7-9aae-41ab46b0d677.png)

The strings are `Main`, `Secondary` and `Minor`, and seem to show up correctly in other places where they've been translated. I've confirmed that the issue is present for at least German as well.

Version: `development` branch as of October 29th

**Comment by olivierkes** [comment]
Well spotted, thanks. Fixed.
