### ISSUE TITLE
random shutdown

### ISSUE THREAD

**Issue by WildCerebrus** [olivierkes/manuskript#184]
randomly (on win10) Manuskript shutdown (at least, almost everything stay in memory)

**Comment by olivierkes** [comment]
Thanks for reporting !
Though like that such a report lacks useful informations. Please state:

- What version of manuskript you are running
- Is it from source or a package (which one)
- Do you get any error message in the console
- What are you doing when the crash happen, in what part of manuskript, can you reproduce it, and if so could you describe how?

Thanks :)

**Comment by WildCerebrus** [comment]
0.5.0 Win10
source
the console shut down (by the way, why a visible console on Windows ?)
sometimes I litterally do nothing, it allready happens when I go on another
menu or when I change the word objective of a scene

2017-11-01 15:46 GMT+01:00 Olivier <notifications@github.com>:

**Comment by gedakc** [comment]
@WildCerebrus can you provide the exact steps and versions of software that were installed to run from source?

I'm running from the `manuskript-0.5.0-win32.zip` binary and so far I have been unable to replicate the problems you experienced.

**Comment by WildCerebrus** [comment]
Bonjour olivierkes/manuskript,
Mathieu ALTHUSER vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/ESl0VP/nrk/?hg=1Gr8MF3yoq pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=89eb4f8a&email=reply@reply.github.com.&hg=1Gr8MF3yoq
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by WildCerebrus** [comment]
Bonjour olivierkes/manuskript,


Mathieu ALTHUSER vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/ESl0VP/nrk/?hg=VkJSPWb3K9 pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=89eb4f8a&email=reply@reply.github.com.&hg=VkJSPWb3K9
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by gedakc** [comment]
Closing this issue as the problem with the spell check crash (issue #273) was fixed with the 0.7.0 release on Aug 15, 2018.
