### ISSUE TITLE
Personnal structure

### ISSUE THREAD

**Issue by WildCerebrus** [olivierkes/manuskript#185]
When you change structure of project (like number of scenes per chapter or add an higher level of files) it's just like you did nothing (both on Ubuntu 16.04 and Win10)

**Comment by olivierkes** [comment]
Hi !
Thanks for reporting. This is a duplicate of #171 , and it has been fixed in 0.5.0, so I guess you're running an older version.
Please try the [latest packages](https://github.com/olivierkes/manuskript/releases/tag/0.5.0).
++

**Comment by WildCerebrus** [comment]
I downloaded 0.5.0 and discovered Manuskript lately (to change from yWriter
for the NaNoWriMo)

2017-11-01 15:43 GMT+01:00 Olivier <notifications@github.com>:

**Comment by WildCerebrus** [comment]
Bonjour olivierkes/manuskript,
Mathieu ALTHUSER vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/ESl0VP/fay/?hg=txIK0DwrNJ pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=1b1d3c34&email=reply@reply.github.com.&hg=txIK0DwrNJ
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by WildCerebrus** [comment]
Bonjour,

mathieu  vient de s'inscrire sur IQ Elite. Il vous a écrit un message. 

Pour lire ce message avant qu'il n'expire, il suffit de cliquer sur le lien suivant : a.iqelite.com/entry/new_message/2fdaa2edae1c63444a9f72edb3627c61fc2d3fda9e1f544b80bfb/320c612f7502e515190907b587b6eaf909052cb74669067b0af907ca859c48991a9a9b7c4518952af5f6d91b0a87b7b7ccb59a9ccc5b69060b7cb5151515151515158587b585891cca86d9060a8587b91b7c4585159b66d75a9bdc320c612f75044d3e22edb35af44b80bfb/?hg=GhYdAl8fRJ

Lisez votre message avant qu'il ne disparaisse !            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=1b1d3c34&email=reply@reply.github.com.&hg=GhYdAl8fRJ
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by gedakc** [comment]
@WildCerebrus please do not spam this issue with comments that to not add value, and cannot be read and acted upon by all manuskript users.

I will delete the comment.

**Comment by olivierkes** [comment]
I think it was unintentional from his part, unfortunately for him. :)

**Comment by WildCerebrus** [comment]
Bonjour,

Votre ami mathieu vous a envoyé un message il y a 36h jours, mais vous ne l'avez toujours pas lu. 

Le message sera supprimé dans 24 heures. 

Pour savoir ce que mathieu vous a écrit, cliquez ici : a.iqelite.com/entry/new_message/2fdaa2edae1c63444a9f72edb3627c61fc2d3fda9e1f544b80bfb/320c612f7502e515190907b587b6eaf909052cb74669067b0af907ca859c48991a9a9b7c4518952af5f6d91b0a87b7b7ccb59a9ccc5b69060b7cb5151515151515158587b585891cca86d9060a8587b91b7c4585159b66d75a9bdc320c612f75044d3e22edb35af44b80bfb/?hg=tHEIBzWC0e            

Cordialement, 
L'équipe IQ Elite 



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=1b1d3c34&email=reply@reply.github.com.&hg=tHEIBzWC0e
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by WildCerebrus** [comment]
Bonjour olivierkes/manuskript,


Mathieu ALTHUSER vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/ESl0VP/fay/?hg=S8IhCJTQlZ pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=1b1d3c34&email=reply@reply.github.com.&hg=S8IhCJTQlZ
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
