### ISSUE TITLE
Manuskript does not start with PyEnchant on MacOS

### ISSUE THREAD

**Issue by katafrakt** [olivierkes/manuskript#188]
This happens with PyEnchant enabled on MacOS.

```
Debug: Web rendering engine used: QWebEngineView
Running manuskript version 0.5.0.
Note: No translator found or loaded for locale en_US.
Traceback (most recent call last):
  File "bin/manuskript", line 13, in <module>
    main.run()
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/main.py", line 64, in run
    launch()
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/main.py", line 70, in launch
    main = MainWindow()
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/mainWindow.py", line 54, in __init__
    self.setupUi(self)
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/ui/mainWindow.py", line 169, in setupUi
    self.txtSummarySentence = textEditView(self.tabSummaryPage1)
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/ui/views/textEditView.py", line 79, in __init__
    self._dict = enchant.Dict(self.currentDict if self.currentDict else enchant.get_default_language())
  File "/Users/pawel/.pyenv/versions/3.5.3/Python.framework/Versions/3.5/lib/python3.5/site-packages/enchant/__init__.py", line 555, in __init__
    raise Error(err)
enchant.errors.Error: No tag specified and default language could not be determined.
```

Brief investigation indicates that this is because PyEnchant cannot detect default language. In fact, when running a simple script:

```
import enchant;
print(enchant.list_dicts())
default = enchant.get_default_language()
print(default)
enchant.Dict(default)
```

The result is:

```
[('de_DE', <Enchant: Myspell Provider>), ('en_AU', <Enchant: Myspell Provider>), ('en_GB', <Enchant: Myspell Provider>), ('en_US', <Enchant: Myspell Provider>), ('fr_FR', <Enchant: Myspell Provider>)]
None
Traceback (most recent call last):
  File "package/dependency_test.py", line 14, in <module>
    enchant.Dict(default)
  File "/Users/pawel/.pyenv/versions/3.5.3/Python.framework/Versions/3.5/lib/python3.5/site-packages/enchant/__init__.py", line 555, in __init__
    raise Error(err)
enchant.errors.Error: No tag specified and default language could not be determined.
```

**Comment by gedakc** [comment]
Thanks @katafrakt for providing extra details with this report, especially the sample code and output.

This problem looks like something we should at least be able to work around.  It is also similar to issue #130 which caused a crash when the locale environment variables **LANG** and **LANGUAGE** were not set in Linux.

Is there a way in OS X to access the language setting directly instead of using `enchant.get_default_language()`?

**Comment by olivierkes** [comment]
Is this in the package you made, or even running from source?

The simplest fix would be to use the first of `enchant.list_dicts()` if `enchant.get_default_language()` is None. But if we can use the system's local to determine the default dict it would be best.

Can you run that simple script and see if that works?

```python
from PyQt5.QtCore import QLocale
print(QLocale.system().name())  # Should return something like: en_US
```

**Comment by katafrakt** [comment]
It's in both: the package with PyEnchant included and from source. I also tried running after setting `LANG` or `LANGUAGE` env variables to `en_US`, but it did not change anything. Apparently it's working differently in MacOS (again, I underline that I'm not expert in MacOS, I just have to use it for work, normally I prefer Linux).

Your script returns "en_US", as you expected:

```
Python 3.5.3 (default, Oct 12 2017, 22:59:41)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtCore import QLocale
>>> print(QLocale.system().name())
en_US
```

So I took liberty to edit `[textEditView.py](https://github.com/olivierkes/manuskript/blob/master/manuskript/ui/views/textEditView.py#L78-L79)` and change it to:

```
try:
   defaultLanguage = enchant.get_default_language() if enchant.get_default_language() else QLocale.system().name()
   self._dict = enchant.Dict(self.currentDict if self.currentDict else defaultLanguage)
```

After that, Manuskript starts normally.

**Comment by olivierkes** [comment]
Great, do you want to make a pull request? Or do you want me to make the change?

But before that, I'm just thinking: what would happen if `QLocale.system().name()` is not listed in `enchant.list_dicts()`? Could you try to run manuskript with your modified code, but after setting `LANG` or `LANGUAGE` env variables to something that is not in `enchant.list_dicts()`?  I guess it would call the `enchant.errors.DictNotFoundError` that will be caught next line, and then spellcheck would be disabled.

If that's the case, it's a bug, and it might be better to select randomly a dict in `enchant.list_dicts()`, that the user can then change.

**Comment by katafrakt** [comment]
@olivierkes `LANGUAGE` env variable is ignored, however if I set `LANGa to something outside `enchant.list_dicts()`, the application crashes with following stacktrace:

```
Debug: Web rendering engine used: QWebEngineView
Running manuskript version 0.5.0.
Note: No translator found or loaded for locale fi_FI.
Traceback (most recent call last):
  File "bin/manuskript", line 13, in <module>
    main.run()
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/main.py", line 64, in run
    launch()
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/main.py", line 68, in launch
    from .mainWindow import MainWindow
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/mainWindow.py", line 15, in <module>
    from manuskript import loadSave
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/loadSave.py", line 10, in <module>
    import manuskript.load_save.version_1 as v1
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/load_save/version_1.py", line 26, in <module>
    from manuskript.models.outlineModel import outlineItem
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/models/outlineModel.py", line 20, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/Users/pawel/.pyenv/versions/3.5.3/Python.framework/Versions/3.5/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

So probably it should be secured against it too. I can try to work on a pull request later today or tomorrow.

**Comment by olivierkes** [comment]
@katafrakt It's a different problem indeed, and this one is fixed (at least ignored) with commit https://github.com/olivierkes/manuskript/commit/0a0649a0db6c98de56ed2f2b82a0978784594bb2.
Thanks for reporting !

So now how does pyEnchant behave?

**Comment by gedakc** [comment]
FYI:  I think that issue [130 - Crashing when creating a new project](https://github.com/olivierkes/manuskript/issues/130) is similar to this issue as it has to do with a missing locale.

**Comment by gedakc** [comment]
FYI:  I think that issue [130 - Crashing when creating a new project](https://github.com/olivierkes/manuskript/issues/130) is similar to this issue as it has to do with a missing locale.

**Comment by gedakc** [comment]
I think that issue [130 - Crashing when creating a new project](https://github.com/olivierkes/manuskript/issues/130) is similar to this issue as it has to do with a missing locale.

**Comment by gedakc** [comment]
Doh!  It appears that a glitch in github or my web browser caused multiple entries of the same comment.  Hence I deleted the duplicates

**Comment by olivierkes** [comment]
It is similar, but the error message is different:

- here, `locale.Error: unsupported locale setting`, when importing **locale** and calling `locale.setlocale(locale.LC_ALL, '')`.
- In the other case, `UnicodeDecodeError: 'locale' codec can't decode byte 0xe2 in position 0: Invalid or incomplete multibyte or wide character`, when using **locale**.

Maybe #130 does behave differently with previous commit ?

**Comment by gedakc** [comment]
The error message is indeed different.  Fortunately there is an easy workaround to #130 -- set LANG to a valid locale.

**Comment by katafrakt** [comment]
@olivierkes Now it behaves like you predicted:

> I guess it would call the enchant.errors.DictNotFoundError that will be caught next line, and then spellcheck would be disabled.

So I think I know more or less everything to create a pull request.
