### ISSUE TITLE
[Feature Suggestion] Add a "Rename Item" option to context menu in the Tree view

### ISSUE THREAD

**Issue by vithiri** [olivierkes/manuskript#189]
It seems like renaming items (folders and texts) isn't fully intuitive currently.

The only way I found to do so was to click the text under Properties in the metadata frame -- and it's not obvious that this text is even editable before clicking it and getting a cursor.

Perhaps adding an option to the context menu for folders/texts in the Tree view to rename the item would be a better approach, unless I'm missing out on some existing functionality?

![rename_item](https://user-images.githubusercontent.com/3118182/32406229-02779526-c175-11e7-9740-b4a51098d67d.png)

**Comment by gedakc** [comment]
Good suggesstion @vithiri.

I discovered in the **Outline** pane that I can can double-click on a folder or text to enter an edit mode to change the name.

Using double-click in the **Navigation** tree of the **Editor** pane might not be possible because the double-click action is used to expand or collapse folders.  Your suggestion of a menu item should work.  If we wish to assign a shortcut key, then I suggest **F2** since this is one used for renaming in many file managers.

**Comment by olivierkes** [comment]
Good idea.

(Right now, manuskript *shoud* use the default's system key as trigger. So on Linux I can rename with **F2** everywhere. In some places, double-click is also a trigger: in folder's outline view, and index cards).

Do you think it would be useful to have a more powerful "renamer"? Like:

- if we select just one item, it calls the system rename trigger (like if you double-clicked or pressed F2).
- if we select multiple items, we can rename them all (for example entering "Scene ##" in a text input, which would number them)
- if we select a folder, then we can rename the whole structure of the folder's subitems, opening an *ad hoc* dialog

**Comment by vithiri** [comment]
Confirming that F2 works fine under Windows. Haven't had a chance to test in Ubuntu yet, but I don't doubt that it works there -- I just didn't think of trying it.

If there's a "default" Rename action, perhaps it even deserves to be listed in the Edit menu and grayed out if there's nothing selected that can be renamed? Otherwise, the context menu should be good enough.

I'm fairly neutral on the more advanced functionality, but the suggestions do sound useful. 😃

**Comment by gedakc** [comment]
> Do you think it would be useful to have a more powerful "renamer"?

Yes, I agree that a more powerful "renamer" would be useful.  It is not important to me if the action of editing a single folder or text is different than a global or multiple selection rename.  If it's difficult to combine the functionality then having it available via two different methods is okay with me.

**Comment by olivierkes** [comment]
Simple "Rename" context-menu entry added:

![image](https://user-images.githubusercontent.com/1192933/32414848-87ca43c6-c22f-11e7-8282-965ae044ba5b.png)

New issue opened for a more powerful "renamer".

**Comment by gedakc** [comment]
Wow that was quick!  :-)  Thank you @olivierkes for adding this feature.

Using the _develop_ branch I tested and confirmed that I can rename folders and text using the **F2** key, or right-click and selecting **Rename** from the menu.
