### ISSUE TITLE
Compiling Manuskript in windows

### ISSUE THREAD

**Issue by vmpajares** [olivierkes/manuskript#19]
This is a little guide to generate the Windows binaries of manuskript.

I installed this versions and it worked, but you can try newers versions if you want or can't find the older ones. You need to install:
- Python 3.4.4, x86 version: https://www.python.org/downloads/windows/
- PyQT 5.5.1 for python v3.4 (Windows 32 bit installer): https://www.riverbankcomputing.com/software/pyqt/download5
- lxml with pip
- pyinstaller with pip
- pyenchant with pip

Get python and pyqt 5 installers and execute both on your windows system choosing the default options. 
When everything is installed, open a command line windows and go to C:\Python34\Scripts
Execute this commands to install lxml, pyenchant and pyinstaller:
pip install lxml
pip install pyenchant
pip install pyInstaller

If some of them fails, maybe you need to upgrade pip. You need to open another command line as Administrator. Press Right click on the Command Line icon and choose Execute as Administrator. Go to C:\Python32\scripts and run:
pip install --upgrade pip

Now, you can download the last code of manuskript from the download page:
http://www.theologeek.ch/manuskript/download/

Unzip it in any folder and in your command line window go to that folder, for example C:\manuskript. Then execute:
C:\Python34\Scripts\pyInstaller manuskript.spec

After some minutes it will create two folders: build and dist. The dist folder contains your main manuskript folder. Try to open dist\manuskript\manuskript.exe and check if everything looks ok.

The log file with the warnings and errors is at build\manuskript\warnmanuskript.txt

Happy writing!

**Comment by olivierkes** [comment]
Thanks, I put it in [the wiki](https://github.com/olivierkes/manuskript/wiki/[Packaging]-Generate-Windows-binaries-with-pyInstaller-%28HowTo%29) :)
