### ISSUE TITLE
Editor tab should trim long titles

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#194]
Signaled by @camstevenson. We should trim long titles in tabs:

![image](https://user-images.githubusercontent.com/1192933/32418007-73632eec-c262-11e7-9067-905dee2b49a9.png)

**Comment by olivierkes** [comment]
Fixed. The max length is set to 24 (for now, open to discussion if needed) here:

https://github.com/olivierkes/manuskript/blob/170c8ef4045ea621fd6f1ecf5259cdbe71feaea7/manuskript/ui/editors/editorWidget.py#L43

![image](https://user-images.githubusercontent.com/1192933/32793881-7ea0961c-c967-11e7-9019-965c1b0ad584.png)

**Comment by camstevenson** [comment]
Works great!
