### ISSUE TITLE
Manuskript crashes when creating new document on Ubuntu

### ISSUE THREAD

**Issue by fishdavidson** [olivierkes/manuskript#198]
I'm running Ubuntu 17.04 with the Cinnamon Desktop. When I try to run Manuskript, the application displays the new project window. But if I try to create any document other than blank fiction or the demo book of acts, the application crashes. Below is the contents of my terminal output:

(manuskript:2440): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(manuskript:2440): Gtk-WARNING **: Loading IM context type 'ibus' failed

(manuskript:2440): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(manuskript:2440): Gtk-WARNING **: Loading IM context type 'ibus' failed

(manuskript:2440): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(manuskript:2440): Gtk-WARNING **: Loading IM context type 'ibus' failed

** (manuskript:2440): WARNING **: Error loading plugin: /home/fish/Downloads/manuskript/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/enchant/libenchant_myspell.so)

** (manuskript:2440): WARNING **: Error loading plugin: /home/fish/Downloads/manuskript/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/enchant/libenchant_ispell.so)

libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
/usr/lib/x86_64-linux-gnu/libgnutls.so.30: symbol asn1_decode_simple_ber, version LIBTASN1_0_3 not defined in file libtasn1.so.6 with link time reference
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/home/fish/Downloads/manuskript/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
Fatal Python error: Aborted

Current thread 0x00007f2f9c1bf700 (most recent call first):
  File "manuskript/ui/welcome.py", line 157 in createFile
  File "manuskript/main.py", line 76 in launch
  File "manuskript/main.py", line 64 in run
  File "manuskript", line 13 in <module>

**Comment by olivierkes** [comment]
What version of manuskript?

**Comment by fishdavidson** [comment]
Linux 64-Bit 0.5.0

**Comment by olivierkes** [comment]
Thanks for reporting :)

Can you please try removing the file `manuskript/libstdc++.so.6` ? (or renaming it to something else), and run manuskript again?

(@gedakc will probably give you better advice.)

In the meantime, you can [run manuskript from source](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux).

**Comment by gedakc** [comment]
Thanks @olivierkes for responding with the file removal suggestion.  I think this will fix the issue.

@fishdavidson please let us know if removing the file works.  This will help us building future manuskript packages.

**Comment by fishdavidson** [comment]
@gedakc Renaming the file as well as deleting the file resulted in the same crashing behavior both times. I'll try compiling from source later. The error output is slightly different, though, which is listed below:

---------------------------------------------


(manuskript:2608): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(manuskript:2608): Gtk-WARNING **: Loading IM context type 'ibus' failed

(manuskript:2608): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(manuskript:2608): Gtk-WARNING **: Loading IM context type 'ibus' failed

(manuskript:2608): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(manuskript:2608): Gtk-WARNING **: Loading IM context type 'ibus' failed
/usr/lib/x86_64-linux-gnu/libgnutls.so.30: symbol asn1_decode_simple_ber, version LIBTASN1_0_3 not defined in file libtasn1.so.6 with link time reference
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
Fatal Python error: Aborted

Current thread 0x00007fb772591700 (most recent call first):
  File "manuskript/ui/welcome.py", line 157 in createFile
  File "manuskript/main.py", line 76 in launch
  File "manuskript/main.py", line 64 in run
  File "manuskript", line 13 in <module>

**Comment by fishdavidson** [comment]
@olivierkes @gedakc Thanks for your help with this issue. It looks like running it from source works (I chose the Git method). Apparently I was missing some dependencies. In case it helps with future packaging efforts, here's what I had to install: 

python3-pyqt5 python3-pyqt5.qtwebkit 

Plus I installed all the optional dependencies, from python3-enchant to latex-recommended, and it seems to be running fine now.

**Comment by gedakc** [comment]
Thank you @fishdavidson for testing and reporting back with the console messages, and that running from source code worked for you.

I am working on a new package in an effort to address problems like these.

Would you be open to test a new package when I have it ready?

**Comment by gedakc** [comment]
@fishdavidson with the existing binary package, would you be able to try removing another file and then test?

`rm manusrkipt/libgcc_s.so.1`

**Comment by fishdavidson** [comment]
@gedakc I will test when I get back to my laptop tomorrow. Is there a certain way you would like me to attempt to run the test though, since I've already got the program running via source? Do I need to remove some of the dependencies I installed last time?

**Comment by gedakc** [comment]
@fishdavidson if you don't mind removing the depencies for the source version then that would help.  No need to remove `pandoc` or `texlive-latex-recommended`.

To remove the dependencies try a command like the following:

```
sudo apt-get remove python3 python3-pyqt5 python3-pyqt5.qtwebkit python3-lxml python3-enchant python3-markdown 
```

Your help is greatly appreciated.  So far I have been unable to recreate the issue using my 64-bit Ubuntu 17.04 Virtual Machine.

**Comment by fishdavidson** [comment]
Okay @gedakc now things are getting a little weird. Using the download from the website, and purging the dependencies you mentioned above, I deleted the requested files and the crashing behavior was still present. However, if I deleted 

```
manuskript/libgcc_s.so.1
manuskript/libtasn1.so.6
```
the program would still crash the FIRST time I chose and option, but if I chose it again, I would be prompted for a save location for the file and everything seems like it would work from that point forward. This behavior is observed with or without libstdc++.so.6 being deleted, but if libstdc++.so.6 is present at the same time as libgcc_s.so.1and libtasn1.so.6, the program crashes every time a selection is made (unless it's an empty document or the demo)

**Comment by fishdavidson** [comment]
As an addendum to my previous post, removing some of the python packages caused a bunch of stuff to break and now my DE isn't working properly. I'll probably end up doing a nuke and pave on my laptop this weekend, so it'll be a little bit before I can continue doing any testing.

**Comment by olivierkes** [comment]
I'll let @gedakc answer on the technical informations. But I'm sorry for your laptop !! Hope you won't lose to much time with that :( And once again, thanks for your precious work for manuskript !

**Comment by gedakc** [comment]
@fishdavidson I'm sorry about your Desktop Environment becoming unstable, my bad.  ;-(

Your help to improve the Manuskript package is appreciated and it is unfortunate that this has resulted in the DE not working properly.  

In an effort to try to identify the possible missing packages I entered the `... apt-get remove ...` command on my Ubuntu 17.04 amd64 Virtual Machine and it indicated the following:

```
$ sudo apt-get remove python3 python3-pyqt5 python3-pyqt5.qtwebkit python3-lxml python3-enchant python3-markdown 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  accountsservice-ubuntu-schemas accountsservice-ubuntu-touch-schemas
  address-book-service apg app-install-data apport-symptoms aptdaemon-data
  avahi-utils bamfdaemon biometryd-bin command-not-found-data compiz-core
  compiz-plugins-default cups-pk-helper dc diffstat
  evolution-data-server-utouch folks-common geoclue geoclue-2.0
  geoclue-ubuntu-geoip gettext gir1.2-accounts-1.0 gir1.2-appindicator3-0.1
  gir1.2-atspi-2.0 gir1.2-dee-1.0 gir1.2-gdata-0.0 gir1.2-gnomekeyring-1.0
  gir1.2-goa-1.0 gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0
  gir1.2-gtksource-3.0 gir1.2-gudev-1.0 gir1.2-javascriptcoregtk-4.0
  gir1.2-json-1.0 gir1.2-notify-0.7 gir1.2-packagekitglib-1.0 gir1.2-rb-3.0
  gir1.2-secret-1 gir1.2-signon-1.0 gir1.2-soup-2.4 gir1.2-totem-1.0
  gir1.2-totem-plparser-1.0 gir1.2-udisks-2.0 gir1.2-unity-5.0 gir1.2-vte-2.91
  gir1.2-webkit2-4.0 gir1.2-wnck-3.0 gkbd-capplet gnome-software-common
  gnome-terminal-data history-service hud iio-sensor-proxy indicator-network
  indicator-transfer intel-gpu-tools intltool-debian ippusbxd
  libaccount-plugin-generic-oauth libapparmor-perl libapt-pkg-perl
  libarchive-zip-perl libart-2.0-2 libbiometryd1 libboost-log1.62.0
  libboost-regex1.62.0 libboost-serialization1.62.0 libboost-system1.61.0
  libcgi-fast-perl libcgi-pm-perl libcgmanager0 libclass-accessor-perl
  libclick-0.4-0 libclone-perl libcolumbus1-common libcolumbus1v5
  libcompizconfig0 libconnectivity-qt1 libdbus-cpp5 libdbusmenu-qt5
  libdecoration0 libdmapsharing-3.0-2 libemail-valid-perl
  libexporter-tiny-perl libfcgi-perl libfolks-eds25 libfolks25 libframe6
  libgeis1 libgeoclue-2-0 libgeoclue0 libgeonames-common libgeonames0
  libgflags2v5 libglewmx1.13 libgnome-keyring-common libgnome-keyring0
  libgnome-menu-3-0 libgnomekbd8 libgoogle-glog0v5 libgpod-common libgpod4
  libgrail6 libgsettings-qt1 libgspell-1-1 libgspell-1-common libgtkspell3-3-0
  libhistoryservice0 libhud2 libhybris libindicator-transfer0 libio-pty-perl
  libio-string-perl libipc-run-perl libleveldb1v5 liblightdm-qt5-3-0
  liblirc-client0 liblist-moreutils-perl liblttng-ust-ctl2 liblttng-ust0
  libmedia1 libmediascanner-2.0-4 libmetacity1 libmiral2
  libmission-control-plugins0 libnet-cpp2 libnet-dns-perl
  libnet-domain-tld-perl libnet-ip-perl libnih-dbus1 libnux-4.0-0
  libnux-4.0-common libonline-accounts-client1 libonline-accounts-daemon1
  libonline-accounts-qt1 liboxideqt-qmlplugin liboxideqtcore0 liboxideqtquick0
  libpango1.0-0 libparse-debianchangelog-perl libperlio-gzip-perl
  libpkcs11-helper1 libpoppler-qt5-1 libprocess-cpp3 libqdjango-db0
  libqgsttools-p1 libqmenumodel0 libqofono-qt5-0 libqt5clucene5
  libqt5concurrent5 libqt5contacts5 libqt5designer5 libqt5feedback5
  libqt5help5 libqt5multimedia5 libqt5multimedia5-plugins
  libqt5multimediaquick-p5 libqt5multimediawidgets5 libqt5organizer5
  libqt5positioning5 libqt5quicktest5 libqt5sensors5 libqt5systeminfo5
  libqt5test5 libqt5versit5 libqt5xmlpatterns5 libsane-hpaio libsgutils2-2
  libsnapd-glib1 libsub-name-perl libsystemsettings1 libtelepathy-qt4-2
  libtelepathy-qt5-0 libtext-levenshtein-perl libthumbnailer-qt1.0
  libtimezonemap-data libtimezonemap1 libtrust-store2
  libubuntu-download-manager-client1 libubuntu-download-manager-common1
  libubuntu-location-service3 libubuntugestures5 libubuntumetrics5
  libubuntutoolkit5 libudm-common1 libudm-priv-common1 libunity-action-qt1
  libunity-api0 libunity-core-6.0-9 libunity-misc4 libunity-scopes1.0
  libunwind8 liburcu4 libusermetricsinput1 libusermetricsoutput1
  libyaml-libyaml-perl libzeitgeist-1.0-1 libzmqpp4 lintian mediascanner2.0
  metacity-common mir-client-platform-mesa5 mir-graphics-drivers-desktop
  mir-platform-graphics-mesa-kms12 mir-platform-graphics-mesa-x12
  mir-platform-input-evdev6 mscompress network-manager-openvpn nux-tools
  openvpn patchutils plainbox-secure-policy policykit-unity8 python-apt-common
  qmenumodel-qml qml-module-biometryd qml-module-ofono
  qml-module-pamauthentication0.1 qml-module-qmltermwidget1.0
  qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings
  qml-module-qtfeedback qml-module-qtgraphicaleffects qml-module-qtmultimedia
  qml-module-qtqml-models2 qml-module-qtqml-statemachine
  qml-module-qtquick-layouts qml-module-qtquick-window2
  qml-module-qtquick-xmllistmodel qml-module-qtquick2 qml-module-qtsysteminfo
  qml-module-qttest qml-module-ubuntu-components
  qml-module-ubuntu-components-labs qml-module-ubuntu-connectivity
  qml-module-ubuntu-layouts qml-module-ubuntu-onlineaccounts
  qml-module-ubuntu-onlineaccounts-client qml-module-ubuntu-onlineaccounts2
  qml-module-ubuntu-performancemetrics qml-module-ubuntu-settings-components
  qml-module-ubuntu-test qml-module-ubuntu-thumbnailer0.1
  qml-module-ubuntu-web qmlscene qtcontact5-galera
  qtdeclarative5-accounts-plugin qtdeclarative5-dev-tools
  qtdeclarative5-gsettings1.0 qtdeclarative5-qtquick2-plugin
  qtdeclarative5-ubuntu-download-manager0.1
  qtdeclarative5-ubuntu-settings-components qtdeclarative5-ubuntu-telephony0.1
  qtdeclarative5-ubuntu-ui-extras0.2 qtdeclarative5-ubuntu-ui-toolkit-plugin
  qtdeclarative5-unity-action-plugin qtdeclarative5-unity-notifications-plugin
  qtubuntu-appmenutheme session-shortcuts signon-keyring-extension
  snapd-login-service sqlite3 suru-icon-theme syslinux syslinux-common
  syslinux-legacy telepathy-mission-control-5 telephony-service
  thumbnailer-service tone-generator ubuntu-app-launch
  ubuntu-application-api3-desktop ubuntu-download-manager ubuntu-keyboard-data
  ubuntu-mobile-icons ubuntu-terminal-app ubuntu-touch-sounds
  ubuntu-ui-toolkit-theme unity-control-center-faces unity-lens-applications
  unity-lens-files unity-lens-music unity-lens-video unity-plugin-scopes
  unity-schemas unity-scope-mediascanner2 unity-scope-video-remote
  unity-scopes-master-default unity-scopes-runner unity-webapps-qml upstart
  usermetricsservice xbrlapi xmir
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  gcc-6-base:i386 gnome-user-guide libbz2-1.0:i386 libc6:i386 libdb5.3:i386
  libexpat1:i386 libgcc1:i386 libgpm2:i386 liblzma5:i386 libmpdec2:i386
  libncursesw5:i386 libpython3-stdlib:i386 libpython3.5-minimal:i386
  libpython3.5-stdlib:i386 libreadline7:i386 libsqlite3-0:i386
  libssl1.0.0:i386 libtinfo5:i386 python3:i386 python3-minimal:i386
  python3.5:i386 python3.5-minimal:i386 xvfb zlib1g:i386
Suggested packages:
  glibc-doc:i386 locales:i386 gpm:i386 python3-doc:i386 python3-tk:i386
  python3-venv:i386 python3.5-venv:i386 python3.5-doc:i386 binutils:i386
  binfmt-support:i386
The following packages will be REMOVED:
  apparmor apport apport-gtk aptdaemon apturl apturl-common checkbox-converged
  command-not-found compiz compiz-gnome content-hub firefox
  flashplugin-installer foomatic-db-compressed-ppds gedit gedit-common
  gir1.2-ibus-1.0 gnome-menus gnome-orca gnome-software
  gnome-software-plugin-snap gnome-terminal hplip hplip-data ibus ibus-table
  indicator-bluetooth indicator-datetime indicator-transfer-download-manager
  language-selector-common language-selector-gnome libcontent-hub0
  libertine-xmir-tools libertined liblibertine1 libubuntu-app-launch4
  libunity-webapps0 lsb-release nautilus-share nplan onboard onboard-common
  onboard-data openprinting-ppds plainbox-provider-checkbox
  plainbox-provider-resource-generic plymouth-theme-ubuntu-text
  printer-driver-foo2zjs printer-driver-foo2zjs-common
  printer-driver-postscript-hp printer-driver-ptouch printer-driver-pxljr
  python3 python3-apport python3-apt python3-aptdaemon
  python3-aptdaemon.gtk3widgets python3-blinker python3-brlapi python3-bs4
  python3-cairo python3-cffi-backend python3-chardet python3-checkbox-support
  python3-commandnotfound python3-crypto python3-cryptography python3-cups
  python3-cupshelpers python3-dbus python3-debian python3-defer
  python3-distro-info python3-distupgrade python3-enchant python3-feedparser
  python3-gdbm python3-gi python3-gi-cairo python3-guacamole python3-html5lib
  python3-httplib2 python3-idna python3-jinja2 python3-jwt python3-keyring
  python3-keyrings.alt python3-launchpadlib python3-lazr.restfulclient
  python3-lazr.uri python3-libertine python3-louis python3-lxml python3-mako
  python3-markdown python3-markupsafe python3-minimal python3-oauth
  python3-oauthlib python3-padme python3-pexpect python3-pil
  python3-pkg-resources python3-plainbox python3-problem-report python3-psutil
  python3-ptyprocess python3-pyasn1 python3-pyatspi python3-pygments
  python3-pyparsing python3-pyqt5 python3-pyqt5.qtwebkit python3-renderpm
  python3-reportlab python3-reportlab-accel python3-requests
  python3-secretstorage python3-setuptools python3-simplejson python3-sip
  python3-six python3-software-properties python3-speechd python3-systemd
  python3-uno python3-update-manager python3-urllib3 python3-wadllib
  python3-webencodings python3-xdg python3-xkit python3-xlsxwriter
  python3-yaml python3-zope.interface python3.5 python3.5-minimal
  qml-module-io-thp-pyotherside qtdeclarative5-qtmir-plugin
  qtdeclarative5-ubuntu-content1 qtmir-desktop qtubuntu-desktop qtubuntu-print
  rhythmbox-plugin-zeitgeist rhythmbox-plugins sessioninstaller snapd
  software-properties-common software-properties-gtk system-config-printer
  system-config-printer-common system-config-printer-udev totem-plugins
  ubuntu-desktop ubuntu-drivers-common ubuntu-minimal ubuntu-printing-app
  ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk ubuntu-software
  ubuntu-standard ubuntu-system-service ubuntu-system-settings
  ubuntu-system-settings-online-accounts ufw unattended-upgrades unity
  unity-control-center unity-control-center-signon
  unity-greeter-session-broadcast unity-lens-photos unity-scope-calculator
  unity-scope-chromiumbookmarks unity-scope-colourlovers unity-scope-devhelp
  unity-scope-firefoxbookmarks unity-scope-gdrive unity-scope-home
  unity-scope-manpages unity-scope-openclipart unity-scope-texdoc
  unity-scope-tomboy unity-scope-virtualbox unity-scope-yelp
  unity-scope-zotero unity-webapps-common unity-webapps-service unity8
  unity8-common unity8-desktop-session unity8-private update-manager
  update-manager-core update-notifier update-notifier-common url-dispatcher
  url-dispatcher-tools usb-creator-common usb-creator-gtk webapp-container
  webbrowser-app xdiagnose
The following NEW packages will be installed:
  gcc-6-base:i386 gnome-user-guide libbz2-1.0:i386 libc6:i386 libdb5.3:i386
  libexpat1:i386 libgcc1:i386 libgpm2:i386 liblzma5:i386 libmpdec2:i386
  libncursesw5:i386 libpython3-stdlib:i386 libpython3.5-minimal:i386
  libpython3.5-stdlib:i386 libreadline7:i386 libsqlite3-0:i386
  libssl1.0.0:i386 libtinfo5:i386 python3:i386 python3-minimal:i386
  python3.5:i386 python3.5-minimal:i386 xvfb zlib1g:i386
0 upgraded, 24 newly installed, 202 to remove and 0 not upgraded.
Need to get 21.8 MB of archives.
After this operation, 317 MB disk space will be freed.
Do you want to continue? [Y/n] 
```

This to me indicates that much of Ubuntu 17.04 is based on python3, so it was definitely my bad to suggest removing python3.

You might try re-installing the above list of packages, but it is difficult to be sure that none of the needed packages was missed.

A fresh install may be the best way to ensure that all needed packages are installed.

**Be sure to backup all of your data before the re-install.**  I'd hate for any important data to be lost.

My sincere apologies for breaking your DE.
