### ISSUE TITLE
Save file doesn't automatically add .msk

### ISSUE THREAD

**Issue by jimmysjolund** [olivierkes/manuskript#2]
When I started my first file I just wrote the file name in field "manuskript-test". When I later tried to open the file it didn't show up in the open window as the .msk was not added automatically to the file name. The "Files of type" did not allow to show all files either, so I could click on it anyway. I could write the file name though and press enter which opens the file.

**Comment by olivierkes** [comment]
Thanks for reporting. This has been corrected in latest commit.

**Comment by jimmysjolund** [comment]
Works like charm now.
