### ISSUE TITLE
Ideas needed: importer

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#200]
The branch `feature/importers` has been created based on @camstevenson's work on OPML import (#192). Long life and prosperity to him !

I'll will now work on that branch to create an Importer similar to the Exporter. If I create only a Markdown import, then using pandoc we can import [all the formats listed here](https://github.com/olivierkes/manuskript/wiki/Import-and-Export-capabilities).

**Current ideas:**

- [x] Being able to preview the import (by creating a temporary model, and showing the import in outline view / tree view / flash cards), before actually importing it.
- [x] Having an option to create a "scene split" or "folder split" by string expression or regular expression
- [x] Import a whole folder structure, each text file is a scene
- [x] Markdown import

**So my questions for you:**

- What ideas do you have for the importer? What is necessary, what is to avoid?
- How should a markdown document be imported? My current idea:
    - A title with subtitles in it is a folder
    - A title without subtitles is a scene

Thanks for your feedbacks :)

**Comment by anicede** [comment]
I've been wanting the ability to import either markdown or plain text.

I do use \#Chapter and \##scene fairly often, so your current idea would work for me, and I could adjust my workflow to do that consistently if required for importing.

Another thought is the ability to cut a scene at a selected point and create a new scene containing the text below that point. One of the few functions I do miss from Scrivener. It made the importing of a single file containing everything quite manageable.

I do sometimes end up with work simply as markdown files within folders, though (I did that *a lot* in an attempt to emulate Scrivener as best I could before I discovered Manuskript). The ability to import folders (=chapters) and files (=scenes) in this format directly would be extremely useful.

**Comment by olivierkes** [comment]
Thank you for your feedback and ideas !

>Another thought is the ability to cut a scene at a selected point and create a new scene containing the text below that point. One of the few functions I do miss from Scrivener. It made the importing of a single file containing everything quite manageable.

How do you signal the cut?

>I do sometimes end up with work simply as markdown files within folders, though (I did that a lot in an attempt to emulate Scrivener as best I could before I discovered Manuskript). The ability to import folders (=chapters) and files (=scenes) in this format directly would be extremely useful.

Good idea !

**Comment by gedakc** [comment]
>> @anicede Another thought is the ability to cut a scene at a selected point and create a new scene containing the text below that point. One of the few functions I do miss from Scrivener. It made the importing of a single file containing everything quite manageable.

> @olivierkes How do you signal the cut?

What about using three "-" (dash / hyphens)?  For example "\-\-\-"?

In Markdown these become a \<hr\> tag in HTML.

---

^ See horizonal line above.

In my [EBookGenTools](http://ebookgentools.sourceforge.net) project I use three hyphens to indicate POV/scene breaks.

**Comment by anicede** [comment]
@olivierkes 
> How do you signal the cut?

In Scrivener it was done piece by piece from the menu: Split at cursor/Split with selection as title were the options, if I recall. I mostly just Ctrl-K'd through my file until it was cut up to my requirements :)

An automated 'cut this entire file up into scenes at the defined signal' function is intriguing, however. How to title the scenes, though? Perhaps take x number of characters from the beginning of the scene to name them?

@gedakc The three hyphens would make the most sense as a cut signal, but the ability for the cut signal to be user defined would be useful also (as I use *** for my scene breaks/horizontal rule so I can search & replace any instances of -- in my writing with an emdash).

**Comment by olivierkes** [comment]
Thanks for your ideas. I'll work on that next.

I now have a somewhat working OPML importer:

![image](https://user-images.githubusercontent.com/1192933/32498871-2ec69bbe-c3d1-11e7-9fd4-ead91033772d.png)

It allows to chose format (only OPML for now), then a file, then preview the import, and finally do the import.

@camstevenson I had to remove the `{lf}` trick for now, because it would fail with OPML files containing line breaks (for example [this one](https://github.com/Microsoft/rss-reader-wp/blob/master/RSSReader_WP7/sample-opml.xml)). We need to find a different solution to preserve line breaks in xml attributes.

Also, with OPML, is there any consensus with the names, except the `<outline>` tag? I've seen you used `_note` attributes, but other will do otherwise, right?

**Comment by olivierkes** [comment]
> We need to find a different solution to preserve line breaks in xml attributes.

Actually, if I convert your document through pandoc (`pandoc "End Plan 2.opml" --standalone -o EndPlan.opml`), then we can import it with lxml and it preserves line breaks. They are stored as `&#10;` in the attributes.

(By the way, pandoc also uses `_note` so this is a standard?)

**Comment by camstevenson** [comment]
@olivierkes your dialog is awesome.

I'll look later and see why the {{lf}} trick isn't working for your test doc.  Maybe it's simply a matter of using &#10; instread of {{lf}}.  Not sure though until I look.

_note seems to be a _de facto_ standard.  Scrivener uses it, along with every other outliner I've used.  The only other one I'm aware if is a color one (I don't remember offhand what the actual attribute name is).  It's used to select the color of a card for organization.  Scrivener emits this, or at least it did last time I looked.

On a side note, I'm debating releasing my eclecdec Android version as GPL, in which case we could collaborate on what additional useful attributes we could agree on to allow for a rich interchange.  The idea would be quick cards written on the phone and fed into Manuskript for heavy lifting.

**Comment by olivierkes** [comment]
Thanks !

>On a side note, I'm debating releasing my eclecdec Android version as GPL, in which case we could collaborate on what additional useful attributes we could agree on to allow for a rich interchange.

That sounds great !

**Comment by olivierkes** [comment]
I realised that using @camstevenson OPML importer, I could use pandoc to convert any format to OPML and import it. So now we have:

![image](https://user-images.githubusercontent.com/1192933/32513328-2db92c5e-c3fa-11e7-8e27-56372f2d5ebf.png)

Import from: markdown, ePub, ODT, HTML, DocX, LaTeX, ReST.

There are probably many bugs. 

**And it's broken in some situations.** For example, if importing a document without heading, only text (whatever the format), pandoc produces an empty OPML file (since there is no structure):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
  <head>
    <title></title>
    <dateModified></dateModified>
    <ownerName></ownerName>
  </head>
  <body>

  </body>
</opml>
```

Maybe there's an option to avoid that, or it should be hacked. Or maybe going through pandoc's OPML to import *everything* is not the best way (but it's convenient!).

Yet, I'm quite happy that this was easily possible, and with well formatted source document, import is possible :)

**Comment by olivierkes** [comment]
@anicede : you can now import from folders and files :)

![image](https://user-images.githubusercontent.com/1192933/32573056-06824606-c4cd-11e7-868b-ad3389e852e6.png)

**Comment by anicede** [comment]
This is awesome! Manuskript is rapidly turning into that one must-have piece of software.

**Comment by olivierkes** [comment]
And now **we have an internal markdown importer**. Very basic: simple searches for headers, and creates folders and texts. I tried with some tricky document and it got through. But as always, still much debugging to do.

So now, we have two plain text import format: opml and markdown.

Which means we can use pandoc to convert to either. Since I already [mentioned a limit](https://github.com/olivierkes/manuskript/issues/200#issuecomment-342599231) when going through opml, it's good to have both. For now, users can chose which one they want to use:

![image](https://user-images.githubusercontent.com/1192933/32579111-07cd494e-c4e0-11e7-8243-c6d728c120c0.png)

We might need to see if this is too much and we should simplify.

Anyway, only the "scene split" to implement, and we have a first draft of a working importer ! As soon as this is done, I'll merge it to develop.

(I'm still open to ideas of course, UI-wise including.)

**Comment by olivierkes** [comment]
And now we can split scenes at import:

![image](https://user-images.githubusercontent.com/1192933/32609799-23ef00aa-c561-11e7-9554-92dabec19e4c.png)

The `feature/Imports` branch has been merged into `develop` for wider testing.

**Comment by olivierkes** [comment]
> Another thought is the ability to cut a scene at a selected point and create a new scene containing the text below that point. One of the few functions I do miss from Scrivener. It made the importing of a single file containing everything quite manageable.

@anicede I just added this function to manuskript. It's in the develop branch.

In the new **Documents** menu:

![image](https://user-images.githubusercontent.com/1192933/32669389-a69dde1a-c640-11e7-90fb-991ca09c1921.png)

- **Split at cursor** (`CTRL+K`) will split the current text at cursor. If there is a selection, it will be used for the title of the newly created item.

- **Split…** (`CTRL+SHIFT+K`) will open a dialog, in which you can chose a "split" mark. The text will be splitted at every occurences. If you call that while having selected multiple items, it will be applied to all. If you call that on a folder, it will be applied to every children.

![image](https://user-images.githubusercontent.com/1192933/32669494-099416ce-c641-11e7-94d9-95414662e6e0.png)

**Comment by anicede** [comment]
@olivierkes This is wonderful stuff, I can't believe you did all this in less than a week!

**Comment by olivierkes** [comment]
@anicede Thanks ! (I had a unexpected week of grace because of health issues, so i had more time to code :p)

**Comment by gedakc** [comment]
I agree with @anicede.  @olivierkes you have been very productive this week adding significant features to Manuskript.

Good health is important so I wish a speedy recovery from such issues.
