### ISSUE TITLE
Changing The Distraction Free Editor Background

### ISSUE THREAD

**Issue by fishdavidson** [olivierkes/manuskript#204]
Apologies if this is answered elsewhere, but I didn't see any documentation for doing so inside the program or browsing the open issues. Is there a way to change the background of the distraction-free editor? The space background is pretty, but it hurts my eyes when I stare at it too long.

**Comment by anicede** [comment]
@fishdavidson Under settings  > full screen, you can chose another theme or make your own :)

**Comment by olivierkes** [comment]
You can also change the current theme by moving your mouse cursor to the bottom of the screen.

See [the wiki](https://github.com/olivierkes/manuskript/wiki/Full-screen-mode) for more details (I just added it).
