### ISSUE TITLE
Creating manuskript binay for Android and IOS

### ISSUE THREAD

**Issue by vmpajares** [olivierkes/manuskript#21]
I'm posting a little notes about creating a manuskript binary for Android or IOS. So somebody can try to make an apk when manuskript reach version 1.0

The buildozer project creates binaries for mobile platforms, just like pyInstaller creates Linux and Windows binaries:
https://buildozer.readthedocs.org/en/latest/index.html

Actually, Buildozer works with Linux and MacOsX, but not Windows. It's included in pip so installing it is easy, but you need to add some dependencies (read them in the official docs):
`pip install --upgrade buildozer`

I tried to generate binaries for manuskript 0.3.0 in Linux Mint DE, but it fails. I don't know if there are a problem with my cython installation (It doesn't install with the docs instructions, so I installed the packaged one and it seems to compile with python2.7 not python3) or there are other issue. 

I add my buildozer.spec and logs as attached files because the markdown transform them in a mess, even with the quote o code marks.
There are 2 logs. The first one with requeriments commented:
`#requirements = lxml,pyenchant`

The second one with requeriments uncommented:
`requirements = lxml,pyenchant`

[buildozer.spec.txt](https://github.com/olivierkes/manuskript/files/202034/buildozer.spec.txt)

[log.txt](https://github.com/olivierkes/manuskript/files/202038/log.txt)
[log_with_requeriments.txt](https://github.com/olivierkes/manuskript/files/202039/log_with_requeriments.txt)

**Comment by olivierkes** [comment]
Thanks, but moved to [the wiki](https://github.com/olivierkes/manuskript/wiki/Creating-manuskript-binay-for-Android-and-IOS) :)
