### ISSUE TITLE
One white pixel visible in full screen mode

### ISSUE THREAD

**Issue by vithiri** [olivierkes/manuskript#210]
I've noticed in the 0.5.0 master branch at least that there's one white pixel visible in the right hand side bottom corner both under Ubuntu 17.10 and Windows 10 (and across machines, just for good measure to rule out dead pixels).

The best way to reproduce this is to set the background to black or another dark color.

Clicking the picture below should bring it up to full size and allow for the pixel to be seen (at least in Chrome).

![white_pixel](https://user-images.githubusercontent.com/3118182/32702558-373d5a82-c7e9-11e7-9f57-918c385747e6.png)

**Comment by olivierkes** [comment]
This look like a old pong game :)

And you have crazy eyes to have spotted that ! Thanks.

**Comment by vithiri** [comment]
Thanks for the swift fix! The pixel is/was actually not that hard to spot with the only other light source around being the input cursor. 😃

**Comment by olivierkes** [comment]
=)
When you go distraction free, you really go distraction free ^^
