### ISSUE TITLE
Make http links clickable in markdown editor

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#215]
Asked by @darrelwright:

>It would be cool if web links were active after importing. I just imported \"Four Key Principles of Exegesis\" which has a web link in \"BiblicalTraining Home Page\" and it displays as \"https://www.biblicaltraining.org/library/four-key-principles-exegesis/essentials-hermeneutics/mark-strauss\". Any chance of having it be active after importing?

See https://github.com/olivierkes/manuskript/issues/208#issuecomment-344170441.

**Comment by olivierkes** [comment]
Links are now clickable. You have to hold CTRL while clicking to open the link.

![clickable_links](https://user-images.githubusercontent.com/1192933/33996217-d4b2ec18-e0e0-11e7-97d8-65c7d2ea471d.gif)

This works also with images.

**Comment by darrelwright** [comment]
That is cool! Thanks Olivier
Darrel
