### ISSUE TITLE
Moving World Items

### ISSUE THREAD

**Issue by bartart3d** [olivierkes/manuskript#219]
I now encountered a moment where I'd love to see the ability to move world items. It would make reorganizing the world items a lot easier. Now it is removing an item, then recreating it elsewhere as a sub-item of another, which can be cumbersome.

**Comment by olivierkes** [comment]
Thanks for reporting this @bartart3d !
Yes this is absolutely suboptimal. I will have to add this when possible.

**Comment by thoronaug** [comment]
I was about to make the same suggestion. +1 here!.

**Comment by gedakc** [comment]
Thanks to the efforts of @JackXVII World items can now be moved if one is using the latest **develop** branch.
