### ISSUE TITLE
File Corrupted

### ISSUE THREAD

**Issue by ajlee** [olivierkes/manuskript#222]
Hi I just started using Manuskript today for a uni assignment, but I have been working for a few hours but I can no longer open my work. On the command line it says:

<pre>

Debug: Web rendering engine used: QWebView
Running manuskript version 0.5.0.
Note: No translator found or loaded for locale en_GB.
Traceback (most recent call last):
  File "/home/ankles/software/manuskript-msater/bin/../manuskript/ui/welcome.py", line 65, in showEvent
    self.mw.loadProject(last)
  File "/home/ankles/software/manuskript-msater/bin/../manuskript/mainWindow.py", line 406, in loadProject
    self.loadDatas(project)
  File "/home/ankles/software/manuskript-msater/bin/../manuskript/mainWindow.py", line 629, in loadDatas
    errors = loadSave.loadProject(project)
  File "/home/ankles/software/manuskript-msater/bin/../manuskript/loadSave.py", line 58, in loadProject
    version = int(f.read())
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

</pre>

I would appreciate if I can get someone's email address if I can't open it, so that someone else can see if it opens on their machine?

**Comment by ajlee** [comment]
Actually no need to send the file to someone else, thankfully I remembered my nextcloud file storage has version control!

**Comment by gedakc** [comment]
@ajlee are you able to compare your working document with the non-working version to try to determine what text or characters might be causing the issue?

If so then this would help us to better understand the problem.

**Comment by olivierkes** [comment]
Hi @ajlee. Thanks for reporting!
If you could send me the corrupted file that would be REALLY helpful. We need to fix this bad.
I've sent you an email.

**Comment by olivierkes** [comment]
After having received the corrupted file (Thank you @ajlee), I wasn't able to do anything. Most probably the system froze just when manuskript was saving. Closing this.

**Comment by gedakc** [comment]
Marking this as **invalid** to prevent it from being included in the CHANGELOG.
