### ISSUE TITLE
Add: command line parameter to open project

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#223]
>> @olivierkes: I guess now that they are treated as system files because they are not registered. I don't know how that works in windows, but there must be some kind of "file association" settings, and maybe if/when we provide a proper manuskript installer on windows, we can associate .msk files with manuskript, and they would not be treated as sysstem files anymore.
>
>I'm not sure, but I think these "file associations" are similar to MIME types and are "registered" with the operating system.
>
>To support these "file associations" we probably need to enhance manuskript to take a `filename.msk` as a parameter so that it will open the file in manuskript.  For example `manuskript filename.msk` on the command line, or from a file manager a user double-clicks `filename.msk`. (from https://github.com/olivierkes/manuskript/issues/217#issuecomment-346074410)

**Comment by shwertt** [comment]
Great idea. I actually tried to do that and was surprised to see that it didn't work out of the box.

+1 from me!

**Comment by olivierkes** [comment]
Just added to develop.

Not sure how that will work with PyInstaller packages, though.
(As always, closing it, and we can reopen if something doesn't work as expected)
