### ISSUE TITLE
Manuskript fails to run in Ubuntu 14.04

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#225]
From @gedakc in https://github.com/olivierkes/manuskript/issues/207#issuecomment-346105225:

Manuskript doesn't even run from source on 64-bit Ubuntu 14.04!   The messages are as follows:

```
user@ubuntu1404:~/manuskript-0.5.0$ bin/manuskript 
Debug: Web rendering engine used: QWebView
Running manuskript version 0.5.0.
Note: No translator found or loaded for locale en_CA.
Traceback (most recent call last):
  File "bin/manuskript", line 13, in <module>
    main.run()
  File "/home/user/manuskript-0.5.0/bin/../manuskript/main.py", line 64, in run
    launch()
  File "/home/user/manuskript-0.5.0/bin/../manuskript/main.py", line 70, in launch
    main = MainWindow()
  File "/home/user/manuskript-0.5.0/bin/../manuskript/mainWindow.py", line 63, in __init__
    self.welcome.updateValues()
  File "/home/user/manuskript-0.5.0/bin/../manuskript/ui/welcome.py", line 47, in updateValues
    autoLoad, last = self.getAutoLoadValues()
  File "/home/user/manuskript-0.5.0/bin/../manuskript/ui/welcome.py", line 69, in getAutoLoadValues
    autoLoad = sttgns.value("autoLoad", type=bool)
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 1
user@ubuntu1404:~/manuskript-0.5.0$ 
```

Strangely all three methods (source, PyInstaller, deb) run correctly on 64-bit **X**ubuntu 14.04.

**EDIT**: I'm going to try updating my Ubuntu 14.04 to see if it is a problem that is fixed in a more recent system package.

**EDIT 2**:  Even with an up-to-date 64-bit Ubuntu 14.04, it fails to run manuskript from any of the three methods (source, PyInstaller, deb).  I wonder what is causing the issue with Ubuntu 14.04 but not **X**ubuntu 14.04.

------------------------

Can you please:

1. Check in the manuskript settings file what the `autoLoad` value is (probably in `~/.config/manuskript/manuskript.conf`)
2. Remove the the config file and run manuskript again

---------------

Strangely there is no `~/.config/manuskript/manuskript.conf` file or even the `~/.config/manuskript/` folder.

**Comment by olivierkes** [comment]
I'll have to check that. Can you post your version of Qt and python?

That's strange, because it builds on SemaphoreCi which runs 14.04, though maybe with updated versions of python and Qt.

**Comment by gedakc** [comment]
@olivierkes good idea creating a separate issue for this problem.


From some more investigating I've learned that manuskript will run on 64-bit Xubuntu 14.04 if the `~/.config/manukskript/manuskript.conf` file pre-exists.

When the file is removed manuskript fails to run on 64-bit Xubuntu 14.04.

See following log for both cases.

```
user@xubuntu1404:~$ ls -l ~/.config/manuskript/manuskript.conf 
-rw-rw-r-- 1 user user 2111 Nov 21 14:10 /home/user/.config/manuskript/manuskript.conf
user@xubuntu1404:~$ manuskript
Debug: Web rendering engine used: QWebView
Running manuskript version 0.5.0.
Note: No translator found or loaded for locale en_CA.
Loading: /home/user/deleteme-manuskript.msk
Detected file format version: 1. Zip: True.
Project /home/user/deleteme-manuskript.msk loaded.
Project /home/user/deleteme-manuskript.msk saved.
user@xubuntu1404:~$ rm -rf ~/.config/manuskript
user@xubuntu1404:~$ manuskript
Debug: Web rendering engine used: QWebView
Running manuskript version 0.5.0.
Note: No translator found or loaded for locale en_CA.
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 64, in run
    launch()
  File "/usr/share/manuskript/manuskript/main.py", line 70, in launch
    main = MainWindow()
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 63, in __init__
    self.welcome.updateValues()
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 47, in updateValues
    autoLoad, last = self.getAutoLoadValues()
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 69, in getAutoLoadValues
    autoLoad = sttgns.value("autoLoad", type=bool)
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 1
user@xubuntu1404:~$ 
```

Version information follows:

```
user@xubuntu1404:~$ dpkg -l | egrep "python3-pyqt5|libqt5svg"
ii  libqt5svg5:amd64                            5.2.1-1                                    amd64        Qt 5 SVG module
ii  python3-pyqt5                               5.2.1+dfsg-1ubuntu2                        amd64        Python 3 bindings for Qt5
ii  python3-pyqt5.qtwebkit                      5.2.1+dfsg-1ubuntu2                        amd64        Python 3 bindings for Qt5's WebKit module
user@xubuntu1404:~$ 
```

I'll try running from the git master next.

**Comment by gedakc** [comment]
Hmm... same issues occur when running from git **master**, **develop**, and **0.4.0** on 64-bit Xubuntu 14.04.

**Comment by olivierkes** [comment]
Strange, can't reproduce here:

```bash
olivier:~/.../manuskript/dist$ rm -rf ~/.config/manuskript
olivier:~/.../manuskript/dist$ manuskript 
Debug: Web rendering engine used: QWebEngineView
Running manuskript version 0.5.0.
Loaded translation: /usr/share/manuskript/i18n/manuskript_fr_FR.qm.
```
What's your python version?

**Comment by gedakc** [comment]
Python version is 3.4.3, which is what is installed by default.

```
user@xubuntu1404:~$ dpkg -l | grep python3 | grep -v python3- | grep -v lib
ii  python3                                     3.4.0-0ubuntu2                             amd64        interactive high-level object-oriented language (default python3 version)
ii  python3.4                                   3.4.3-1ubuntu1~14.04.5                     amd64        Interactive high-level object-oriented language (version 3.4)
ii  python3.4-minimal                           3.4.3-1ubuntu1~14.04.5                     amd64        Minimal subset of the Python language (version 3.4)
user@xubuntu1404:~$ 
```

What version of Python3 are you running?

**Comment by olivierkes** [comment]
I think that's not the problem. I was able to build a package on Ubuntu 14.04. When installing and running it in my laptop (16.04), I encoutered an issue similar to yours. Manuskript would always load the same project (and fail). I checked and the .conf file it uses is in: `~/.config/www.theologeek.ch/manuskript.conf`

Is is the same for you?

**Comment by gedakc** [comment]
> Is is the same for you?

I'm not sure I understand.

I gave up building a `.deb` package on Ubuntu 14.04 because the package wouldn't install and run on the same Ubuntu 14.04.  I don't know if it would run on other distros.

I do remember running into issues with PyInstaller packages built on Ubuntu 14.04.  In the end I gave up and moved to Debian 8 Jessie.

If we are to use Travis CI I think we only have a choice of Ubuntu 12.04 Precise (too old) or Ubuntu 14.04 Trusty.

**Comment by olivierkes** [comment]
>I'm not sure I understand.

Yep wasn't clear, sorry. Do you have a conf file in `~/.config/www.theologeek.ch/manuskript.conf`?

**Comment by gedakc** [comment]
I wonder how `~/.config/manukskript/manuskript.conf` came to exist on my 64-bit Xubuntu 14.04 VM?

I would not have manually created the file.  That leads me to think that some previous version of manuskript must have successfully run....

And yes, I'm right!  Manuskript 0.3.0 will run if I pick `book-of-acts` under **Demo projects**.

After I do that, I can checkout the git master and manuskript will run.

**Comment by olivierkes** [comment]
I don't understand. I thought you did not have a conf file, but when you create one manuskript runs.

**Comment by gedakc** [comment]
My apologies for the confusion.  I've been using 32-bit and 64-bit Kubuntu, Ubuntu, and Xubuntu 14.04.

The only one that would run Manuskript was 64-bit Xubuntu 14.04.  It is this VM that had a pre-existing conf file which must have been created using manuskript 0.3.0.

If I first run manuskript 0.3.0 and open the `book-of-acts` (or 0.4.0 and create a project), this creates a conf file.  After that I can successfully run other versions of manuskript.

If the conf file does not pre-exist, then I cannot run manuskript 0.5.0 or **develop**.

This suggests there must be some code change between 0.4.0 and 0.5.0 that broke manuskript running on *buntu 14.04.

I'll need to run git bisect to find the offending commit.

**Comment by gedakc** [comment]
If I have run git bisect correctly, the commit that introduces the issue is:

```
4484423ace3e0c4e99d0868848750bb3512af606 is the first bad commit
commit 4484423ace3e0c4e99d0868848750bb3512af606
Author: Olivier Keshavjee <olivier.keshavjee@gmail.com>
Date:   Thu Oct 19 22:21:15 2017 +0200

    Fixes: Some panels require initial two clicks of RHS tab to hide #167
```

**Comment by gedakc** [comment]
To undo the problem I reverted the following portion of the above commit:

```
user@xubuntu1404:~/manuskript.git$ git diff
diff --git a/manuskript/ui/welcome.py b/manuskript/ui/welcome.py
index c6d4c68..53e4a81 100644
--- a/manuskript/ui/welcome.py
+++ b/manuskript/ui/welcome.py
@@ -66,7 +66,10 @@ class welcome(QWidget, Ui_welcome):
 
     def getAutoLoadValues(self):
         sttgns = QSettings()
-        autoLoad = sttgns.value("autoLoad", type=bool)
+        if sttgns.contains("autoLoad"):
+            autoLoad = True if sttgns.value("autoLoad") in ["true", True] else 
+        else:
+          autoLoad = False
         if autoLoad and sttgns.contains("lastProject"):
             last = sttgns.value("lastProject")
         else:
user@xubuntu1404:~/manuskript.git$ 
```

@olivierkes do you foresee any issues if we make this change to the code?

**Comment by olivierkes** [comment]
Yes, that code fixed a bug or two, so it would reintroduce them.

Can you try either: `autoLoad = sttgns.value("autoLoad", defaultValue=False, type=bool)`

**Comment by gedakc** [comment]
Excellent suggestion @olivierkes.  This change worked splendidly on my 64-bit Xubuntu 14.04.

```
user@xubuntu1404:~/manuskript.git$ git diff
diff --git a/manuskript/ui/welcome.py b/manuskript/ui/welcome.py
index c6d4c68..e11732c 100644
--- a/manuskript/ui/welcome.py
+++ b/manuskript/ui/welcome.py
@@ -66,7 +66,7 @@ class welcome(QWidget, Ui_welcome):
 
     def getAutoLoadValues(self):
         sttgns = QSettings()
-        autoLoad = sttgns.value("autoLoad", type=bool)
+        autoLoad = sttgns.value("autoLoad", defaultValue=False, type=bool)
         if autoLoad and sttgns.contains("lastProject"):
             last = sttgns.value("lastProject")
         else:
user@xubuntu1404:~/manuskript.git$ 
```

Now manuskript runs regardless of whether `~/.config/manuskript/manuskript.conf` exists.  :-)

**Comment by olivierkes** [comment]
Once more @gedakc, thanks for your thorough reports :)

**Comment by gedakc** [comment]
Thanks also for your help to identify and fix the problem.

This issue is serious enough to prevent users of *buntu 14.04 from using manuskript 0.5.0.  I think this justifies a release soon.

I think we have two choices.

- Create 0.5.1 which includes this fix plus the PyEnchant fixes for Mac OS X (so OS X version can be automatically built), and also updated language translations.
- Create 0.6.0 which would include the current **develop** branch

Do you agree we should have another release?

If so which path would you prefer to take (0.5.1, or 0.6.0)?

**Comment by olivierkes** [comment]
Yes good idea. I think it will be easier to go for 0.6.0. 
Do you think we can release it like that, or is there anything to do before?

**Comment by gedakc** [comment]
Right now there are some commits in master that are not in develop and vice versa.

I think it would be wise to pull all the 0.6.0 stuff into master.  Then we can run some basic testing in an effort to reduce the chance of regressions.

When we are content the master can be labelled with 0.6.0.

From there we can build the packages, make the announcements, etc.

**Comment by olivierkes** [comment]
Ok, I merged develop into master. I'll do some testing.

**Comment by gedakc** [comment]
I'll do some testing too and let you know if I encounter any issues.

**Comment by gedakc** [comment]
Things are looking good so far.

If you don't mind I'll work on some minor word changes and spelling corrections and create a PR.

**Comment by olivierkes** [comment]
Nice! Work from `master`, as you might have seen I've merged some stuff in `develop`.

**Comment by gedakc** [comment]
Thanks for the tip.  I'm going to try to fix the odd word choices and test manuskript at the same time.
