### ISSUE TITLE
Translation automation

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#228]
Right now I have to add manually every form and file that contain translatable string. If I could write a script to do it automatically it would be much easier, and we could have translatable files always up to date.

**Comment by olivierkes** [comment]
I added a script in `i18n/print_project.sh`.

Run it (from within i18n, important, because I haven't proofed that), and it will print a `manuscript.pro` file to console. After checking it, it can be saved over `manuskript.pro`.

And now, the list of translation has been moved to `i18n/languages.txt`, since `manuskript.pro` gets erased.

**Comment by gedakc** [comment]
Good work.  The more automation we have the less chance for human errors to creep in.
