### ISSUE TITLE
Add markdown support of other tabs

### ISSUE THREAD

**Issue by vinsifroid** [olivierkes/manuskript#232]
It's something I've been wondering a bit, markdown works perfectly fine for writing in **Editor** tab but why not include it in other tabs, like **World**, **Characters** or **Plots**?
It would be especially useful in the *description* panel of **Worlds** and *summary* panel in **Characters**, where there are a lot of space to write and, for example, the use of titles would be great.

It's not a very urgent feature (and i guess it wouldn't be so easy to implement), it's just something i think would be nice for user experience.

**Comment by olivierkes** [comment]
Done :)
(It's in a local branch for now, I added a new and better markdown highlighter. I'll push it probably in a few days.) 
Thanks for the suggestion.

**Comment by vinsifroid** [comment]
Oh great ! And you're very welcome. :)

**Comment by olivierkes** [comment]
You can now test it in develop.
