### ISSUE TITLE
Making Fullscreen Mode Great Again

### ISSUE THREAD

**Issue by hugo-id** [olivierkes/manuskript#234]
Fullscreen is where I spend most of my time in the app, as I think most writers probably would, and feel like this view is a bit half-baked in comparison to the other options.

Plume Creator:
![image](https://user-images.githubusercontent.com/30918735/33254061-171d1838-d39b-11e7-98c5-ad0ffbaa154b.png)
In the bottom-right you can see the super-simple interface that makes plume-creator one of the best to simply be productive.
The small green arrow, when pressed, shows all scenes/chapters/books, allowing easy navigation.
The left / right arrows allow you to simply change between the adjacent scenes (allowing distraction-free proof-reading)
The button to the right of those, creates a new scene after the current one. (Cannot believe that plume creator is the ONLY writing app to allow this function)
Then:
Words in current scene,
Time,
Goal progress.
The three buttons underneath are basically broken (notes, settings, close)

Focuswriter:
![b_focuswriter](https://user-images.githubusercontent.com/30918735/33254232-d19b784e-d39b-11e7-9d43-3fea23a92936.png)
In the bottom-right is an incredibly basic implementation of a simple status indicator.

Focuswriter's general workflow and interface is awesome, but perhaps his focus on focus has made it less functional. It is infuriating that to check the time I need to alt+tab, or that the only way I can get a nice update on how much I've written is to check in with an alarm (which is what i posted a screenshot of).

Overall, it feels like fullscreen mode in Manuskript has been "implemented" but not fleshed-out. I feel that between Plume and Focus, there is a perfect fullscreen mode that writers are all waiting for.

Things I feel are invaluable:
The time
Goal Progression
Current words
New Scene
Type-following (either typewriter, or via virtual pages)
The whole "lock screen" concept is bizarre. If I don't want to type, I'll just walk away. That whole interface may be better served by turning it into a basic goal setting widget. (And once you've started it, there is no feedback or way to passively monitor progress)

In case I wasn't clear, the "distraction-free" mode is incredibly personal to the individual in question. Please keep in mind that any option, no matter how widely-requested will be kryptonite to someone, and that as many options as possible in fullscreen mode should be customisable.

Manuskript is genuinely amazing, and I genuinely prefer it over scrivener 1.9. Hopefully you can keep up the good work, and linux will have yet another best-in-class app!

**Comment by olivierkes** [comment]
Thanks for this detailed feedback.

Have you seen that you can right-click on a panel, and **disable "auto-hide"**?
So at least you can have: current word & goal progression, and the progression on the current lock (time or word goal).

But I take your input into consideration, and will add several of those things you asked, they make sense!

**Comment by anicede** [comment]
For the record I quite like the lock screen concept, and have been making use of it. I appreciate quirky little helpers like this.

**Comment by hugo-id** [comment]
Glad I could be of service!

Yes, I realised you could disable auto-hide, but the spinner in the bottom that lets you easily change themes is a massive eyesore to me, and unlike the rest of your app, it doesn't appear to be affected by themeing, which might actually be a bug?

I'd file it as a separate bug, but I already feel like I'm giving you too much work!

Although on that note I believe I've created an incredibly elegant method to monitor a word goal (or even a time goal):
![screenshot c_edit](https://user-images.githubusercontent.com/30918735/33432542-766f894a-d62c-11e7-9527-f5b84458f586.png)
The program gets an average of how many words per line, then projects where that will be, and draws a simple, colour-customisable, "finish line" so you can literally race to the finish line!
(Relies on either dynamic pages [pagination] or typewriter-mode otherwise there's no look-ahead)

Also this screenshot shows "focus mode" which is definitely going to be another feature you're going to get requested repeatedly. Focus mode is when text, either current line, current + below + above, or whatever other variations of text are normal, but all other text fades out.

And because GIMP was open, a super simple mock-up of a HUD that would have absolutely everything I would want (that I can think of right now)
![screenshot d_edit](https://user-images.githubusercontent.com/30918735/33432571-9cc09bde-d62c-11e7-88db-e09ef479398d.png)

From the top:
Current Time
Current document word count
Daily goal word count (only visible if currently tracking)
Current timer (only visible if currently tracking)
The <- and -> are dodgy symbols to represent forwards and back. The + is for new page directly following current file under same parent. 

Another potential solution to allow Manuskript to work perfectly for people like me, is to enable external text editors. It seems like it may take a bunch of dev time you'd rather not spend to simply replicate Focuswriter, calmly writer, or even Open Office, why not just allow it to be set to an external editor?

This is currently how I'm using it Manuskript. Set to **not** save as a single file, I create the chapter, then open with Focuswriter to actually write. It doesn't really like to work like that though, as I haven't yet found a nice way to update Manuskript beyond cycling the app (closing and reopening)

Once again, you're really doing an amazing job, and I'm incredibly excited to see where this project goes!

Addendum:
A & B are most definitely bugs. A is a very bad highlight of where it occurs, and B is the same thing blown up so it can be more easily seen. Basically, no matter what settings you tweak, text will never continue to the actual top of the page, there is always some padding left.

**Comment by hugo-id** [comment]
![screenshot_j](https://user-images.githubusercontent.com/30918735/33515844-5e8a9e50-d7bc-11e7-8c41-0fa78ec01136.png)
This layout is awesome, and would alleviate several of concerns I've brought up regarding fullscreen mode, but obviously there's no fullscreen option for this view. Is there a reason for that, or is it an oversight?
(This would become my default work-view for sure)

Also, I've finished moving from scrivener to manuskript, and the only big thing I'm missing is an app shortcut because CBF figuring out how to get app-launcher to launch the dev branch. Awesome progress so far!
:heart: :heart:

**Comment by hugo-id** [comment]
lol, didn't know what that did, hopefully I haven't borked anything

**Comment by olivierkes** [comment]
>And because GIMP was open, a super simple mock-up of a HUD that would have absolutely everything I would want (that I can think of right now)

OK i'll add that. Does it have to be on a new panel in the bottom right, or could it be in the top panel?

Otherwise I'll have to make it movable I guess, since depending on the theme the writing area can be on the right.

> Although on that note I believe I've created an incredibly elegant method to monitor a word goal

That's a great idea! But I don't see how code that... I'll keep that has an idea for a possible future.

>Also this screenshot shows "focus mode" which is definitely going to be another feature you're going to get requested repeatedly. Focus mode is when text, either current line, current + below + above, or whatever other variations of text are normal, but all other text fades out.

That I want to do. I already tried something, but it was much more difficult than I expected. I'll try again.

**Comment by olivierkes** [comment]
Just added focus mode. See #259.
Ready in develop branch.

**Comment by olivierkes** [comment]
Oh by the way @hugo-id , you like fullscreen mode AND folder text mode (all texts in a folder in the same view), AND that you want a "new scene" button in fullscreen mode. As a semi-workaround you can write in fullscreen mode, and when you want a new scene you add a separator (whatever, could be "~~~" or anything), and then when you're done writing you use **Organize > Split …** to split the scene in several scenes at the mark you indicate:

![](https://user-images.githubusercontent.com/1192933/32669494-099416ce-c641-11e7-94d9-95414662e6e0.png)

(hope you can understand).

I know it doesn't fulfill everything you want, but it could be a workaround in the meantime.

**Comment by thoronaug** [comment]
If you are trying to implement a "focus mode", it would be great, besides the other options, to have all the text faded out but the current sentence. Not one, or three page lines (as focuswriter does), but the text between dots.
I use iaWriter on my android tablet and it has this cool feature.

![ia-writer-focus-mode](https://user-images.githubusercontent.com/6547707/34039141-67cff5a4-e186-11e7-94ee-af71517b0456.png)

Greetings!

**Comment by olivierkes** [comment]
Hi @thoronaug. Focus mode has been added 10 days ago.

I just added the sentence mode. See issue #259 "Focus Mode".

**Comment by thoronaug** [comment]
Sorry for that. I was outdated. On develop now. It's great!

**Comment by kakaroto** [comment]
so... I wrote a comment here yesterday but it seems I never submitted it and now it's lost :(
Since I realized you don't get a notification when I push a commit or PR referencing this issue, I'm commenting to ask for feedback. I've implemented some improvements to fullscreen mode, and I'm hoping it pleases everyone here.

You can see more details on what features I added and how it works in #509 and here are a couple of screenshots of the new fullscreen window : 

![image](https://user-images.githubusercontent.com/27990/53460279-8cedf600-3a0a-11e9-957a-f51da58f0e7d.png)


You can notice above the 'new document' that was requested here as well as left/right navigation buttons (you can also navigate with hotkeys), and the ability to customize the top/bottom panels however you want, removing/adding items from them.

The top panel has the full path (folder->folder->text) of the text being modified, and you can click on either folder/text to get the full list of all its siblings to jump directly to a different scene or a different chapter, as shown in the screenshot below (note how I customized the panels different between the two screenshots) :
![image](https://user-images.githubusercontent.com/27990/53460094-f4f00c80-3a09-11e9-8b77-93aa58c43332.png)

Note that the 'folder path' in the top panel can also be changed into a non-clickable scene title only, or removed of course.
All the features work, but there is still work to do in terms of UI design, to make it nicer, maybe different icon, maybe change the ">" into an actual image, or maybe the flat path buttons more visible, or a different arrangment/position of buttons. So if anyone has any comments, opinions, or requests, please let me know!
I hope everyone likes it!

**Comment by gedakc** [comment]
Closing this issue because many of the items requested have been implemented in the **develop** branch.  New requests for fullscreen enhancements should be based on the **develop** branch or the upcoming [0.9.0](https://github.com/olivierkes/manuskript/milestone/8) release.
