### ISSUE TITLE
Hebrew text is exported without "new line" character

### ISSUE THREAD

**Issue by aizenimr** [olivierkes/manuskript#235]
When a Hebrew text containing a chapter of several paragraphs is exported via Pandoc, the exported text does not include "new line", so it is being exported as one single very long paragraph.
The new line does exist between acts and chapters, but inside a chapter all the paragraphs are printed without any new line.
I believe it is something caused by the way Pandoc handles Hebrew text, or possibly RTL in general.
(Originally tested on version 0.3).

**Comment by aizenimr** [comment]
Addition: Reproduced on version 0.5, with Pandoc 2.0.3 on Windows 7 Pro.
I originally encountered it on Linux LXLE with version 0.3.

**Comment by olivierkes** [comment]
Thanks for reporting. I tested it and saw no difference between hebrew and english output.

**Do you know that markdown used double line break for paragraph break?** So for example:

    בְּרֵאשִׁית
    בָּרָא
    
    אֱלֹהִים

will render as:

    בְּרֵאשִׁית בָּרָא

    אֱלֹהִים

(yep sorry my hebrew repertoire is limited to the classics ^^)


**If this is the behavior you observed, then there is two workarounds:**

 1. You get used to use \n\n (double line break) for paragraph break
 2. In the exporter widget, in settings under **transformations** you add a **custom replacement**:
    
    ![image](https://user-images.githubusercontent.com/1192933/33339378-2ef88012-d479-11e7-8d03-2c1f9c371471.png)

**If this is not the behavior you observed,** then please show me a specific example.

Regards,

**Comment by aizenimr** [comment]
Thank you, it seems to solve it :)
One last question: any possibility to add page breaks between folders, or between folders and texts?

**Comment by olivierkes** [comment]
There is no page breaks in markdown. Just like there is no page breaks in html. So it depends of your export format : if for example it is LaTeX, you can add a `\pagebreak` or whatever the command is. Or `----` which will be transformed into an horizontal line (`<hr>` in html).

You can do it in the export settings, under **Separations**.

Does that answer?

**Comment by aizenimr** [comment]
OK, I understand - do you know which character should be used when exporting to DOCX or ODT format?

**Comment by olivierkes** [comment]
I think the easiest is to simply export to DocX or ODT, and then you style the document, and for example for Header Level 1 you style with a page break before.

For example in LibreOffice:

![image](https://user-images.githubusercontent.com/1192933/33371527-569ba70c-d4fb-11e7-83b4-e34511330132.png)

**Comment by aizenimr** [comment]
Thank you so much! From my side it is solved with these work-arounds :)

**Comment by olivierkes** [comment]
Great! Happy writing :)
