### ISSUE TITLE
new dalolog icon

### ISSUE THREAD

**Issue by Reaper10** [olivierkes/manuskript#237]
i have a new dalolog icon i think makes cense 
![dalolog](https://user-images.githubusercontent.com/8137561/33353214-4b6c6ae4-d472-11e7-83f2-9b6f42ca8663.png)

[dalolog.zip](https://github.com/olivierkes/manuskript/files/1512232/dalolog.zip)
the bubbles i think i like better
<img width="111" alt="sketch" src="https://user-images.githubusercontent.com/8137561/33353408-44e0c8e0-d473-11e7-909a-1ba57fb7c0dc.png">

**Comment by olivierkes** [comment]
Hi,
thanks for your work. But this is a "debug" icon, not "dialog" :)
