### ISSUE TITLE
Cannot write a summary on a plot resolution step

### ISSUE THREAD

**Issue by hugo-id** [olivierkes/manuskript#240]
![d](https://user-images.githubusercontent.com/30918735/33438749-cf176b22-d63f-11e7-8df1-786a2239c915.png)

As can be seen in picture, I've added all necessary pieces, and am in correct mode to add text, but I'm unable to actually input any text. Pasting doesn't work either.

(Plot has linked characters, description, and result)

**Edit:**
Also, after adding the step into the "Outline" tab, and filling the summary there, it does not back-populate into the "Plots" tab, or have any bearing on anything.

**Comment by anicede** [comment]
Yeah, this just happened to me, too. I can get my cursor into the summary box, but every time I try to type, the application closes.

This is new behaviour, because it was working fine a handful of days ago. 

I'm using the develop branch, and just updated it this evening.

**Comment by olivierkes** [comment]
Thanks for reporting, it should be fixed.

@hugo-id, please include in your bug reports in the future what version of manuksript you're running and how. It helps :) Thanks!
