### ISSUE TITLE
Index card status can spillover

### ISSUE THREAD

**Issue by hugo-id** [olivierkes/manuskript#246]
If you have a status over 17 characters (Ready for feedback), the red pseudo-stamp visual effect on the index cards will be clipped.

**Comment by olivierkes** [comment]
What would be the desired behavior? Smaller font?

**Comment by hugo-id** [comment]
![screenshot_g](https://user-images.githubusercontent.com/30918735/33514874-f6f514b2-d7ae-11e7-99a6-64b2f21cc683.png)
Picture because I've got one handy..

Honestly, no idea.

Haha, you could clamp the string to like 14 characters, and add "..." on the end (easiest), or
Change the stamp aesthetics  (size, new lines, rotation) but that would look bad, or
Center it a little better and just let it disappear. In real life, if the stamp's too big, stamp's too big! I think it just looks off atm because it's the first letter getting cut off, yet there's obviously extra room on the tail end.

**Comment by olivierkes** [comment]
Good point. I've centered it better, though it's not perfect.
Please test develop branch to tell me what you think.
