### ISSUE TITLE
Ctrl+tab gets trapped in Debug tab

### ISSUE THREAD

**Issue by hugo-id** [olivierkes/manuskript#249]
Ctrl+tab seems to allow me to change between the main navigation tabs, but then it becomes "trapped" in the child-tabs in the main-tab "Debug". Once it's become buried in the debug child-tabs, I can no longer use ctrl+tab at all.

Fix:
ctrl+tab either cycles through open things in editor, OR
it cycles through the main navigation tabs (General, Summary, etc.), OR
Disable it completely

**Comment by olivierkes** [comment]
Thanks @hugo-id. I've hidden the debug tab altogether. Does that fix it for you?
