### ISSUE TITLE
Focus mode

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#259]
As suggested by @hugo-id in https://github.com/olivierkes/manuskript/issues/234#issuecomment-348190348 : 

![](https://user-images.githubusercontent.com/30918735/33432542-766f894a-d62c-11e7-9527-f5b84458f586.png)

**Comment by olivierkes** [comment]
![focus_mode](https://user-images.githubusercontent.com/1192933/33634177-9986b864-da13-11e7-9612-f173362c8c13.gif)

Just added focus mode!

You can chose between "Line" or "Paragraph".

![image](https://user-images.githubusercontent.com/1192933/33634223-c76d58be-da13-11e7-96d1-9926fd11aa6f.png)

Supports Markdown markup:

![focus_mode_2](https://user-images.githubusercontent.com/1192933/33634834-dd3f39e4-da15-11e7-9730-7dbeffb20248.gif)

And works in full screen mode:

![image](https://user-images.githubusercontent.com/1192933/33634896-17b08d4e-da16-11e7-893d-6e38e6d7fafe.png)

**Comment by olivierkes** [comment]
Added Sentence mode, based on a suggestion by @thoronaug here https://github.com/olivierkes/manuskript/issues/234#issuecomment-351976803.

![image](https://user-images.githubusercontent.com/1192933/34058125-28f79914-e1da-11e7-9492-8977d3f78f77.png)

Tell me if this is not how you expect it to behave.

**Comment by thoronaug** [comment]
Awesome! It's exactly what I mean. It works perfectly.
Thank you!

**Comment by thoronaug** [comment]
I've discovered an error in Sentence Focus mode. When starting a sentence with a "-" sign, everything is grayed out after the first sentence end (dot, ! mark, etc). 

If I write:
**- Hello!**
It works ok, and the word Hello! is focused. But if I keep writing in the same line:
- Hello!Who are you?
the whole line appears unfocused.
