### ISSUE TITLE
Bug: File doesn't open if spellcheck is active and dictionary is missing

### ISSUE THREAD

**Issue by vmpajares** [olivierkes/manuskript#26]
If spellcheck is active in your file and you try to open the .msk in another machine without the dictionary, manuskript raises an error in the log/terminal but doesn't open the file and doesn't say anything in the main application.

IMHO the program must open the file, and warning that spellcheck will be disabled because the dictionary is missing.

**Comment by olivierkes** [comment]
Thanks, that is corrected in develop.
