### ISSUE TITLE
Organize Menu is not disabled on startup

### ISSUE THREAD

**Issue by siliconserf** [olivierkes/manuskript#260]
A very minor anomaly - On loading a project selected at startup, the menu bar item Organize is not greyed out regardless the current mode selection in the Navigation column. As soon and anything is clicked in the Navigation column, the menu bar wakes and notices if Organize should be greyed out. But, if the project starts with Character, you can select one of the characters and the menu bar doesn't get the word. When I first saw this I thought maybe I could move character entries up or down. No such luck. Not sure if this should be fixed before the implementation of the new Navigation control scheme, where it will become moot.

**Comment by olivierkes** [comment]
Well spotted. Thanks!
It's fixed in develop.
