### ISSUE TITLE
Manuskript response slow with recent addition of focus mode

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#261]
Recently I updated my **develop** branch of manuskript.

While working on my document I immediately noticed that the recent update made manuskript much slower to respond to my keystokes and navigating in the editor.

I have included the git update command to help in identifying the change that caused the slowdown.

```
$ git pull upstream develop
From git://github.com/olivierkes/manuskript
 * branch            develop    -> FETCH_HEAD
Updating 9c63530..5e2ac47
Fast-forward
 manuskript/mainWindow.py                          | 53 ++++++------------
 manuskript/settings.py                            |  2 +
 manuskript/settingsWindow.py                      |  9 +++
 manuskript/ui/highlighters/markdownHighlighter.py | 67 ++++++++++++++++++++++-
 manuskript/ui/settings_ui.py                      | 32 ++++++++++-
 manuskript/ui/settings_ui.ui                      | 42 +++++++++++++-
 manuskript/ui/views/MDEditCompleter.py            |  1 +
 manuskript/ui/views/MDEditView.py                 |  6 +-
 manuskript/ui/views/corkDelegate.py               |  8 +--
 manuskript/ui/views/textEditView.py               |  6 +
 $
 ```

If you need more information then let me know.

**EDIT**  I just confirmed that manuskript operation used to be very responsive by reverting to my prior **develop** branch version with: `git checkout -b olddev 9c63530`

**Comment by olivierkes** [comment]
Thanks!

(With the new focus mode, I called for a full rehighlight of the whole document whenever cursor position changed. Now it only rehighlight two paragraphs (current cursor position and previous), and only if focus mode is enabled.)

Please tell me if you observe an improvement.

**Comment by gedakc** [comment]
Thank you @olivierkes for the prompt response.  Your recent change has made typing and navigating in the manuskript editor to be responsive again.  :-)

**Comment by olivierkes** [comment]
Oops, my change introduced a bug (crash when trying to open settings). Last commit fixes that.
It's strange, because this is something unit tests should have picked up :-/

**Comment by gedakc** [comment]
Interesting.  On my amd64 Kubuntu 16.04 computer I did not experience a crash when opening **Edit -> Settings**.  Perhaps this bug only occurred on certain architectures or distros.
