### ISSUE TITLE
Status bar distracting when saving with current develop branch

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#262]
Previously the manuskript status bar was static.  When automatic saves were performed the status bar would indicate the save had occurred and then return to an empty status bar.

With the current **develop** branch the status bar is not normally visible.  When a save occurs the status bar pops up which shrinks the editor pane and obscures the bottom line of text.  This is annoying.

My recommendation is to make the status bar static again.

**Comment by siliconserf** [comment]
I'd like to see it show up on the title bar where the current project file name is located. There is a lot of unused space there and it does hold the file name, so there is some reasonable association.

**Comment by olivierkes** [comment]
**Observations:**

1. Space is wasted with a static status bar
2. Dynamic bar is annoying, and a real pain if writing with no bottom margin and without typewriter mode (bottom line gets hidden)

**Suggestions:**

1. Get back to static status bar
2. Write message in title bar
3. Get back to status bar and use the empty space (see @Reaper10's ideas: #255).

If we get to "single page mode" (cf. https://github.com/olivierkes/manuskript/issues/252#issuecomment-348965926, every items in the same view), then the status bar can be merged with the bottom bar (the one with buttons for new items and full screen, word count, etc.). But that's for the future.

Right now, I like @siliconserf 's idea (suggestion n°2.), what do you think @gedakc ?

Or what do you both think of suggestion n°3, is there useful information we should add to the status bar?

**Comment by olivierkes** [comment]
Here is a patch if you want to try suggestion n°2:

```
diff --git a/manuskript/functions.py b/manuskript/functions.py
index 0b3451e..1e313f9 100644
--- a/manuskript/functions.py
+++ b/manuskript/functions.py
@@ -357,9 +357,13 @@ def statusMessage(message, duration=5000):
     """
     Shows a message in MainWindow's status bar.
     """
-    mainWindow().statusBar().show()
-    mainWindow().statusBar().showMessage(message, duration)
-    QTimer.singleShot(duration, mainWindow().statusBar().hide)
+    # mainWindow().statusBar().show()
+    # mainWindow().statusBar().showMessage(message, duration)
+    # QTimer.singleShot(duration, mainWindow().statusBar().hide)
+    mainWindow().statusBar().hide()
+    mainWindow().setWindowTitle(message)
+    QTimer.singleShot(duration, lambda: mainWindow().setWindowTitle(
+        os.path.split(mainWindow().currentProject)[1] +  " - Manuskript"))
 
 def openURL(url):
     """
```

**Comment by gedakc** [comment]
Personally I don't like to see status updates being displayed in the title bar.

My preference is for either (1) restore the status bar, or (3) make better use of the status bar.

Another option is to not display "saving file..." at all.

**Comment by anicede** [comment]
Perhaps a toggle in the settings as to whether to show the status bar or not.

I must admit the bouncing up and down of it (I Ctrl-S *a lot*) is massively distracting.

**Comment by olivierkes** [comment]
Trying something else, and if that doesn't work I'll revert to the static status bar.

Now, status bar appears at the bottom of the screen but **over** the window (I got the idea from the behavior of the status bar in chromium). Advantage: nothing moves in the window when the bar shows up, and it doesn't waste space when there is no message. In the editor, it appears over the bar at the bottom, so it doesn't hide the text.

![image](https://user-images.githubusercontent.com/1192933/33758773-0949c77a-dc00-11e7-835e-b0aa45417ac6.png)

Also, I added the ability to change the importance of the message: so "project saved" are very light, but some message will call for more attention:

![image](https://user-images.githubusercontent.com/1192933/33759029-0e87b9c6-dc01-11e7-8d82-dbace29cf669.png)

![image](https://user-images.githubusercontent.com/1192933/33759062-36fe1440-dc01-11e7-8dae-03bf5ef20e13.png)

Thoughts?

**Comment by anicede** [comment]
Yeah, that's good, at least for saving. Very not distracting, but definitely there if you're looking for confirmation of save.

**Comment by gedakc** [comment]
@olivierkes this is much improved.  I can still see that the project is being saved, but it is no longer distracting.

**Comment by olivierkes** [comment]
Thank you both for feedbacks.
