### ISSUE TITLE
Add print option

### ISSUE THREAD

**Issue by Reaper10** [olivierkes/manuskript#266]
Add a print option to manuskript

**Comment by olivierkes** [comment]
Hi @Reaper10,
I probably won't do that. Manuskript is about content, not form.
The idea is that we write in manuskript, but then we export to a software that can manage proper formatting (like latex, open document, html+css, etc.).
Sorry :)

**Comment by Reaper10** [comment]
ok i thinking of scripts being that Trelby program is dead and there's not any open scarce  software. sorry for bothering you.

**Comment by olivierkes** [comment]
You don't bother. I'd love to support scripts, but right now it's not a priority, there are many more things to make manuskript more mature. Scripts would require a largely different approach. Maybe in the future, but I can't promise anything.
