### ISSUE TITLE
Manuskript packaging  questions

### ISSUE THREAD

**Issue by Reaper10** [olivierkes/manuskript#267]
1. Is manuskript  going to build in pandoc just to make it easier?
2. Is manuskript  going to build into an android app, ios app and an windows app for the  windows app store? fyi  windows makes easy
https://developer.microsoft.com/en-us/windows/bridges/desktop

**Comment by olivierkes** [comment]
>1. Is manuskript going to build in pandoc just to make it easier?

Pandoc is included as dependency in linux packages. In windows and os x, with pyInstaller it is not included.Though we said that we should try to (cf. #190). 

So if somebody wants to test that, we could do it. (Something to start with [here](https://stackoverflow.com/questions/38874563/pypandoc-in-combination-with-pyinstaller))

>2. Is manuskript going to build into an android app, ios app and an windows app for the windows app store? fyi windows makes easy

**Android** and **ios** app would need a large ui rewrite, wouldn't it?
But if PyQt is portable to those plateform, why not. It's a priority for me, but if someone wants to try it could be interresting.

But anyway, with the open-folder file format, it's easy to work on the desktop, sync the project folder, and use any markdown / text editor on mobile to keep working.

As for the windows store, I don't have a computer with windows 10 (nor will I ever have one), so I can't. But again, if somebody (you?) wants to read about and try, that could be useful.

**Comment by Reaper10** [comment]
what about the old school msi installer aka window installer?

**Comment by olivierkes** [comment]
Same answer: don't have windows, don't know how it works, if somebody wants to do it great!
;)

**Comment by gedakc** [comment]
I think that Windows installation is more complicated than GNU/Liux because not only do files need to be installed, but also the registry needs to edited to add/change settings.  It might be best to leave pandoc installation packages to the pandoc team.

**Comment by gedakc** [comment]
Closing this question as answered either in this issue, or in the links included in this issue.
