### ISSUE TITLE
Bug: Writing a .msk file in linux and opening it in windows clean the outline files

### ISSUE THREAD

**Issue by vmpajares** [olivierkes/manuskript#27]
Steps to reproduce:

Create a new .msk file in linux or windows
Save it
Open it in Windows
The characters and Summary content are right, but the Outline is empty. When you close the file or wait the selected time in settings, Manuskript save your current file, erasing the outline files inside the .msk zip and losing your work.

Log/terminal doesn't say anything. The file opening the file multiple times in linux doesn't fail. Writing it in Windows works ok and you can open the .msk as .zip file and see the outline files.

**Comment by olivierkes** [comment]
How does it work on the other way: creating the file in windows and opening it in Linux ?

Can you create an .msk file in windows with an outline, and post it here please?

Also, if you feel like it, you can edit the content of manuskript/load_save/version_1.py: on line 52, replace

     LOG = False

With

    LOG = True

Now manuskript will give you a lot of info when loading and saving files. You can see if something is relevant.

Thanks !

**Comment by vmpajares** [comment]
I changed LOG = True
Writing a new Windows file and opening in Linux works ok.

But I notice something different opening a Linux created file and a Windows one:
This is opening the Linux created file in my windows:
```
C:\Users\Victor\VBoxCompartida\manuskript\manuskript-master\bin>\Python34\python
.exe manuskript
Loaded translation: C:\Users\Victor\VBoxCompartida\manuskript\manuskript-master\
i18n\manuskript_es_ES.qm.
Loading: C:/Users/Victor/VBoxCompartida/manuskript/Henry Smith and the Looters o
f Peru 8 Abril - copia.msk
Detected file format version: 1. Zip: True.

Loading C:/Users/Victor/VBoxCompartida/manuskript/Henry Smith and the Looters of
 Peru 8 Abril - copia.msk (ZIP)

Reading labels:
* Add status: Idea (#ffff00)
* Add status: Nota (#00ff00)
* Add status: Capítulo (#0000ff)
* Add status: Escena (#ff0000)
* Add status: Investigación (#00ffff)

Reading Status:
* Add status: POR HACER
* Add status: Primer borrador
* Add status: Segundo borrador
* Add status: Final

Reading plots:

Reading World:

Reading Characters:
* Adds Henry Smith (0)
* Adds Guardia de la Jungla (1)

Reading outline:
* Error: no item whose ID is 19
* Error: no item whose ID is 19
* Error: no item whose ID is 10
* Error: no item whose ID is 10
* Error: no item whose ID is 10
* Error: no item whose ID is 10
* Error: no item whose ID is 1
* Error: no item whose ID is 1
* Error: no item whose ID is 1
* Error: no item whose ID is 20
* Error: no item whose ID is 20
* Error: no item whose ID is 20
* Error: no item whose ID is 20
* Error: no item whose ID is 2
* Error: no item whose ID is 2
* Error: no item whose ID is 3
* Error: no item whose ID is 3
* Error: no item whose ID is 14
* Error: no item whose ID is 14
* Error: no item whose ID is 14
* Error: no item whose ID is 15
* Error: no item whose ID is 15
* Error: no item whose ID is 15
* Error: no item whose ID is 16
* Error: no item whose ID is 16
* Error: no item whose ID is 16
* Error: no item whose ID is 16
* Error: no item whose ID is 18
Proyecto C:/Users/Victor/VBoxCompartida/manuskript/Henry Smith and the Looters o
f Peru 8 Abril - copia.msk cargado.

```

And this is creating a new Windows file and opening it:
```
C:\Users\Victor\VBoxCompartida\manuskript\manuskript-master\bin>\Python34\pytho
.exe manuskript
Loaded translation: C:\Users\Victor\VBoxCompartida\manuskript\manuskript-master
i18n\manuskript_es_ES.qm.
Loading: C:/Users/Victor/VBoxCompartida/manuskript/outline_bug_test - copia.msk
Detected file format version: 1. Zip: True.

Loading C:/Users/Victor/VBoxCompartida/manuskript/outline_bug_test - copia.msk
ZIP)

Reading labels:
* Add status: Idea (#ffff00)
* Add status: Nota (#00ff00)
* Add status: Capítulo (#0000ff)
* Add status: Escena (#ff0000)
* Add status: Investigación (#00ffff)

Reading Status:
* Add status: POR HACER
* Add status: Primer borrador
* Add status: Segundo borrador
* Add status: Final

Reading plots:

Reading World:

Reading Characters:
* Adds Main Test (0)
* Adds Sidekick Test (1)

Reading outline:
Proyecto C:/Users/Victor/VBoxCompartida/manuskript/outline_bug_test - copia.msk
cargado.


Saving to: zip
Proyecto C:/Users/Victor/VBoxCompartida/manuskript/outline_bug_test - copia.msk
guardado.


```

I can't attach a .msk file, send me an email to my nick at gmail.com or send me an email as PM at twitter and I would send the file.
`Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. `

**Comment by olivierkes** [comment]
Or just change the extension from .msk to .zip, it will be easier

**Comment by vmpajares** [comment]
I had more data. 
Creating Outline content works ok, and Windows autosave it, but editing doesn't work it raises:
```
C:\Users\Victor\VBoxCompartida\manuskript\manuskript-master\bin>\Python34\python
.exe manuskript
Loaded translation: C:\Users\Victor\VBoxCompartida\manuskript\manuskript-master\
i18n\manuskript_es_ES.qm.


Saving to: zip
Proyecto C:/Users/Victor/VBoxCompartida/manuskript/outline_bug_test.msk guardado
.


Saving to: zip
Proyecto C:/Users/Victor/VBoxCompartida/manuskript/outline_bug_test.msk guardado
.


Saving to: zip
Unhandled Python exception
[outline_bug_test.msk.zip](https://github.com/olivierkes/manuskript/files/211878/outline_bug_test.msk.zip)

```

**Comment by olivierkes** [comment]
OK I'll have to investigate that, thanks for reporting !

**Comment by vmpajares** [comment]
I fix it. It seems like "files" stored all the files with the standard unix separator (/) and in the line 825 you split the paths with the os.path.separator. Obviously it works in Linux and MAC, but it fail in Windows.

Changing the line for:
split = f.split("/")[1:]

Fix the problem.
Perhaps you must change the way you stored the paths in "files" or fix it as (/)

**Comment by olivierkes** [comment]
Thanks for debugging that. It seems that zipfile, the python module used to handle zip, uses "/" as path separator even in windows. So your solution would work for project saved as single files, but not project saved as multiple files in a folder.

Can you please try the following: in `load_save/version_0.py`, line 181, replace

`files[f] = zf.read(f)`

with:

`files[os.path.normpath(f)] = zf.read(f)`

(You'll have to `import os` somewhere.)

This should use "\" in windows instead of "/". Can you confirm it works both in linux and windows?

Thanks,

**Comment by vmpajares** [comment]
It works. I created a new msk in Windows and add a folder and two page in the outline. Saved, closed Manuskript and open in Windows and Linux. (The same code in a shared folder)

I activated LOG=True and get a Warning in Windows, but not in Linux:
`There are some doublons: ['0', '0']`

This is the log. It's the same in Win and Linux except for the doublons line.

```
C:\Users\vi\Desktop\tmp\manuskript-master\bin>\Python34\python.exe manuskript
Found translation in settings: C:\Users\vi\Desktop\tmp\manuskript-master\i18n\ma
nuskript_es.qm
Loaded translation: C:\Users\vi\Desktop\tmp\manuskript-master\i18n\manuskript_es
.qm.
Loading: C:/Users/vi/Desktop/tmp/outline-test.msk
Detected file format version: 1. Zip: True.

Loading C:/Users/vi/Desktop/tmp/outline-test.msk (ZIP)

Reading labels:
* Add status: Idea (#ffff00)
* Add status: Nota (#00ff00)
* Add status: Capítulo (#0000ff)
* Add status: Escena (#ff0000)
* Add status: Investigación (#00ffff)

Reading Status:
* Add status: POR HACER
* Add status: Primer borrador
* Add status: Segundo borrador
* Add status: Final

Reading plots:

Reading World:

Reading Characters:

Reading outline:
* Adds 0-Nuevo to root (folder)
* Adds 1-Nuevo.md to root (file)
* Adds 2-Nuevo.md to root (file)
There are some doublons: ['0', '0']
Proyecto C:/Users/vi/Desktop/tmp/outline-test.msk cargado.
Could not parse stylesheet of object 0x4b841c8
Could not parse stylesheet of object 0x4b841c8
Could not parse stylesheet of object 0x4b841c8


Saving to: zip
Proyecto C:/Users/vi/Desktop/tmp/outline-test.msk guardado.

```

**Comment by olivierkes** [comment]
Thanks, that's good news :)
I committed the change to develop.

Are you using `develop` btw? Because I thought I fixed the duplicates ID thing ("doublons" in french....).

**Comment by vmpajares** [comment]
My mistake. 
I test this bug with master. I'll try to test the doublons with the develop.

**Comment by olivierkes** [comment]
This is not imprtant: I changed the way manuskript remembers which items were opened, since now in develop we can split views (and have multiple items open in parallel). So this means that manuskript simply failed to load what items in outline were opened. I changed that to make it less confusing.

And the qtwebkit dependency is in README.md.
