### ISSUE TITLE
Display images as tooltip

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#270]
If you have markdown references to images in your project, manuskript can now show them as tooltips:

![image](https://user-images.githubusercontent.com/1192933/33996399-6123f890-e0e1-11e7-9392-f9cc866dffac.png)

This works for local images (with absolute path only, though), and external images.

If you CTRL+Click the reference, it will open with the default system application.

This is part of #22.

(for the changelog)

**Comment by DarkRedman** [comment]
There is a bug for the display of the image as a tooltip, the tooltip keep blinking as I hover the cursor on the link, I think maybe there is a collision detection system that only detects on the letters of the link, not its bounding box, also sometimes when I click on it, the picture opens, sometimes it doesn't.

I think it'd be simpler and have more consistent results displaying it with a QPixmap in the rich textbox.

**Comment by obw** [comment]
Could be a side effect of: #729
