### ISSUE TITLE
Programm killed by Hovereffekt?

### ISSUE THREAD

**Issue by ScullyBlue** [olivierkes/manuskript#275]
When I have a Cheat Sheet from a Character open and the mouse get over the Text-References in the bottom of the Cheat, the Programm crashes ...

**Comment by olivierkes** [comment]
Thanks for reporting. This looks like something fixed in develop. So I need the usual info:

- What version are you using, and on what plateform?
- What's the error message in console?

**Comment by ScullyBlue** [comment]
I used version 0.6.0 on Windows 10 (can also test with Debian stretch) and on console this error comes:

Debug: Web rendering engine used: QWebView
Running manuskript version 0.6.0.
[...]
Traceback (most recent call last):
  File "manuskript\ui\cheatSheet.py", line 159, in linkHovered
  File "manuskript\models\references.py", line 496, in tooltip
ValueError: expected '}' before end of string

**Comment by gedakc** [comment]
@ScullyBlue would you be able to re-test this issue with Manuskript 0.7.0 released on Aug 15, 2018?

**Comment by gedakc** [comment]
Thanks @ScullyBlue for re-testing and reporting back that it now works.

Closing this issue as resolved.
