### ISSUE TITLE
List of characers per scene

### ISSUE THREAD

**Issue by aizenimr** [olivierkes/manuskript#277]
Is there any way to assign a scene the list of **_all characters_** participating in the scene?
Today you can only assign a POV and also labels (scene, TODO, idea, etc..).

**Comment by olivierkes** [comment]
Yes: use the **Notes / References** text area, in the metadata pane.

See [here](https://github.com/olivierkes/manuskript/wiki/How-to-keep-track-of-important-items#references-your-items-in-your-scenes) for an example (to track items, but the principle is the same).

Tell me if that answer your question.

**Comment by aizenimr** [comment]
Thank you, now I got it.
I like that you can use any any object of your choice this way - plot details, character, location, etc.
