### ISSUE TITLE
[Feature request] Accept first command line argument as project file name to open

### ISSUE THREAD

**Issue by taophp** [olivierkes/manuskript#278]
I used to start my working session with a script that launch some tools for me (version management, backup, editor... manukript in some case). As I may use manuskript on many project, it should be great that it opened using the first argument on the command line as the file name of the project to open. Seems classical to me.

**Comment by olivierkes** [comment]
Thanks for posting!
It's already been added to `develop` (#223), and will be release with 0.7.0. You can use it if you run `develop` from source, or use a develop package.
