### ISSUE TITLE
Adding Dictionary to Spell Checker

### ISSUE THREAD

**Issue by aizenimr** [olivierkes/manuskript#279]
What should be the proper way to add spell checking dictionary?
I use Manuskript on a Linux LXLE laptop, and on Windows 8 desktop. On the Linux I managed to add a Hebrew dictionary, but frankly speaking I'm not sure how I got it to work. On the Windows it does not work at all.
From where should I download dictionary? Does it different when doing it on Linux and Windows?

The instructions in the Enchant site are not so clear and point to download page of  a very old OpenOffice version...

**Comment by gedakc** [comment]
Thank you @aizenimr for this question and your interest in manuskript.

Based on your question I created the following wiki entry:  [Adding a Spellcheck Language Dictionary to Manuskript](https://github.com/olivierkes/manuskript/wiki/Adding-a-Spellcheck-Language-Dictionary-to-Manuskript).

Please try the steps in the wiki tutorial and let us know if solves the problem for you.

**Comment by aizenimr** [comment]
Hi, thank you for the wiki but now I encountered 2 problems. (Tested on Windows 8.1 machine).

Problem 1:
I download the files from the Libre Office site, as the wiki suggested, but the spell checker does not work properly. However, I used files in my current Libre Office [spell checker extension](https://extensions.libreoffice.org/extensions/hebrew-he-spell-check-dictionary) and checked it on a brand new project, and it works. I don't understand why the Manuskript built-in enchant does not recognize the files you suggested in your wiki. I want to clarify again that I saw it only in Windows platform - normally I work on my Linux laptop.

Problem 2: When I try to open my current project in Windows, the program shuts down and the console says the following:

> Debug: Web rendering engine used: QWebView
> Running manuskript version 0.6.0.
> Note: No translator found or loaded for locale en_US.
> Traceback (most recent call last):
>   File "manuskript\ui\welcome.py", line 141, in openFile
>   File "manuskript\mainWindow.py", line 517, in loadProject
>   File "manuskript\mainWindow.py", line 742, in loadDatas
>   File "manuskript\loadSave.py", line 60, in loadProject
>   File "c:\python34\lib\encodings\cp437.py", line 19, in encode
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 31-35: character maps to \<undefined\>

At first I thought it is because some problem with the spell checker and that is why I opened this issue in the first place. But now I see that it is unrelated... any suggestions?

**Comment by gedakc** [comment]
Response to Problem 1:  Did you download the *plain* or *raw* content of the file?  If not then that would explain why the downloaded file did not work.

![spellcheck-language-download](https://user-images.githubusercontent.com/10405019/34892199-99428b90-f795-11e7-9899-971fa9557cec.png)


Response to Problem 2: From the error messages it appears that there is at least one invalid character in the file.  If you are using [Open and plain-text file format](http://www.theologeek.ch/manuskript/2016/03/31/open-plain-text-file-format/) (i.e., you disabled *save to one single file*) then you might try accessing the file(s) with a different editor to remove the problem text character(s).

**Comment by gedakc** [comment]
Response to Problem 2:

@aizenimr do you the setting to **Save to one single file** disabled?

If so then the problem opening the manuskript project might be due to hidden files (those starting with a period) being in the same manuskript project folder.  This issue has been reported as is being tracked in issue #281.

**Comment by aizenimr** [comment]
Hi Curtis,
Concerning Problem 2:
I do not have hidden files in any of the project's folder. This problem does not occur on my Linux laptop, and it also does not occur on my Windows desktop computer at the office. It only happens at my desktop computer (also Windows).
Regarding the invalid character: which invalid character? how can I know where it appears? But more importantly - why does it not happen when I open same project in the 2 other machines?

**Comment by gedakc** [comment]
If the same project works on two other computers then the problem might be due to a corrupt install of either manuskript or the project.

Please try uninstalling/removing both manuskript and the project, and then re-install and test.

If the problem persists, then please create a new issue.

Because this issue is entitled **Adding Dictionary to Spell Checker** which has been documented in the Wiki article [Adding a Spellcheck Language Dictionary to Manuskript](https://github.com/olivierkes/manuskript/wiki/Adding-a-Spellcheck-Language-Dictionary-to-Manuskript), I am closing this issue.
