### ISSUE TITLE
OS X app with Platypus

### ISSUE THREAD

**Issue by husnoo** [olivierkes/manuskript#28]
Hi,

I have created an OS X App for this using Platypus. I attach the profile I used - you'd need to sed it to change the path to the appropriate thing on your computer, then create the app. That app will then be independent of paths on your computer.

(Oh sorry, the icon I used is a google download of a different app using the same name - so you'd need to change that for distribution).

Thanks,

Nawal.
[Manuskript.platypus.txt](https://github.com/olivierkes/manuskript/files/217661/Manuskript.platypus.txt)

**Comment by olivierkes** [comment]
Whaouw, thanks a lot !
I created an [entry in the wiki](https://github.com/olivierkes/manuskript/wiki/Bundle-manuskript-for-OS-X-with-Platypus) with your instructions.
Thanks again !
