### ISSUE TITLE
.DS_Store files let crash Manuskript when opening project

### ISSUE THREAD

**Issue by Dave-Ban** [olivierkes/manuskript#281]
Hey, I just started to use Manuskript on my Mac and I love it!

**The problem**
I created a project and everything was fine. But then I created a git-repository of my project and when I tried to open the project again Manuskript always crashed. This is the last part of what I get in the Terminal:

```
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 563: invalid start byte
Fatal Python error: Aborted

Current thread 0x00007fff7e01a000 (most recent call first):
  File "/Applications/Writing/manuskript/bin/../manuskript/main.py", line 76 in launch
  File "/Applications/Writing/manuskript/bin/../manuskript/main.py", line 64 in run
  File "/Applications/Writing/manuskript/bin/manuskript", line 13 in <module>
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

I've tried various things and then I noticed, that when I remove the .DS_Store-File in the project-folder right before I open the project it opens again without problems.
But because Mac automatically creates a new .DS_Store-file shortly afterwards the problem isn't really solved that way.

This problem also only exists when I use the save option with open-format files.

**Comment by gedakc** [comment]
Thanks @Dave-Ban for your interest in Manuskript.

Would you be able to post the complete console output for when this error occurs?

Neither @olivierkes nor myself have access to Mac OS computers to reproduce the issue so the more information you can provide, the better.

**Comment by olivierkes** [comment]
Also, can you tell us the content of the ds_store file? Or even post it here if it doesn't contain sensitive information?

**Comment by Dave-Ban** [comment]
Yes, sure. This is the complete console output:

```
Debug: Web rendering engine used: QWebEngineView
Running manuskript version 0.6.0.
Found translation in settings: /Applications/Writing/manuskript/i18n/manuskript_de.qm
Loaded translation: /Applications/Writing/manuskript/i18n/manuskript_de.qm.
Loading: /Users/andresbucher/Documents/Privat/Stories/Altweltdinge/Reworking/Manuskript/Altweltlasten.msk
Detected file format version: 1. Zip: False.
Traceback (most recent call last):
  File "/Applications/Writing/manuskript/bin/../manuskript/ui/welcome.py", line 127, in loadRecentFile
    self.mw.loadProject(act.data())
  File "/Applications/Writing/manuskript/bin/../manuskript/mainWindow.py", line 517, in loadProject
    self.loadDatas(project)
  File "/Applications/Writing/manuskript/bin/../manuskript/mainWindow.py", line 742, in loadDatas
    errors = loadSave.loadProject(project)
  File "/Applications/Writing/manuskript/bin/../manuskript/loadSave.py", line 66, in loadProject
    v1.loadProject(project, zip=isZip)
  File "/Applications/Writing/manuskript/bin/../manuskript/load_save/version_1.py", line 657, in loadProject
    files[os.path.join(p, f)] = fo.read()
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 1071: invalid start byte
Fatal Python error: Aborted

Current thread 0x00007fff7732d000 (most recent call first):
  File "/Applications/Writing/manuskript/bin/../manuskript/main.py", line 76 in launch
  File "/Applications/Writing/manuskript/bin/../manuskript/main.py", line 64 in run
  File "/Applications/Writing/manuskript/bin/manuskript", line 13 in <module>
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

And I attached the .DS_Store file too. It is a hidden file, which I couldn't upload so I changed its name from _.DS_Store_ to _DS_Store.txt_, but its (cryptic) content should be the same. Just let me know, if you need it another way.

As I understand, these files get automatically created from the mac system to provide some metadata about the folders (source [wikipedia](https://en.wikipedia.org/wiki/.DS_Store)). I can't comprehend under which conditions the file gets created because when I look up other folders, some of them have it and others not. In my case with the manuskript-document, it seemed to be created when I created the repository.

I also found a way to delete the file from the folder without it being created again (up to now).
I just need to delete it using the terminal and type:
`sudo find /path -name ".DS_Store" -depth -exec rm {} \;`

I hope my provided informations are enough to help you. ^^

[DS_Store.txt](https://github.com/olivierkes/manuskript/files/1597119/DS_Store.txt)

**Comment by gedakc** [comment]
Thanks @Dave-Ban for providing the additional details and the contents of the DS_Store.txt file.

I am able to reproduce the issue by copying the `DS_Store.txt` file to the name `.DS_Store` under a Manuskript project folder.  When the file is present I encounter similar messages when opening the manuskript project.  If I remove the file then manuskript opens the project correctly.

My initial guess is that we will need to enhance Manuskript to ignore files starting with a period, or at least ignore a known set of file names that start with a period such as `.DS_Store`.

**Comment by olivierkes** [comment]
Yes I think we can safely avoid reading names that start with a period. 

But we also need to catch that error: 

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 1071: invalid start byte
Fatal Python error: Aborted
```

If I remember correctly, it also happened when people copy / pasted some stuff with invalid characters (though I don't know which, since I understand very little about codecs.) and then closed / reopened the project or something like that. 

I guess if a file is read and such an error is raised, there should be a warning to the user that the content could not be loaded, and that it could be lost...

**Comment by gedakc** [comment]
@Dave-Ban, can you test the latest manuskript **develop** version?

You can either:

- download an auto-build from http://www.theologeek.ch/manuskript/releases/manuskript-develop.deb 

or, 

-  use the instructions to [Run Manuskript from Source Code on Mac OS X](https://github.com/olivierkes/manuskript/wiki/Run-manuskript-on-OS-X) and choose the **develop** branch.

**Comment by gedakc** [comment]
@olivierkes regarding the UnicodeDecodeError, can you reproduce it by cutting and pasting text?

It might make sense to try to catch the problem at the source, specifically cutting and pasting if that is where the problem arises.

**Comment by Dave-Ban** [comment]
I tested the latest version and it works now. I even created several ds_store files in different folders inside the project and it still opened the project without a problem. That's awesome!

**Comment by gedakc** [comment]
Thank you @Dave-Ban for confirming that the patch fixes the issue.

**Comment by geekbrit** [comment]
I don't know if this is still a live issue, but I just started seeing the error. I put an exception trap in load_save/version_1.py at line 668:
    try:
         files[os.path.join(p, f)] = fo.read()
    except UnicodeDecodeError:
         print(p, f)

and manuskript starts up correctly. The console shows that the codec in my case was barfing on two image files that had mistakenly been saved into the project folder. I *think* that this exception handler will kick out anything that was never intended to be parsed, but of course it will fail to load any story file that has been corrupted through editing in a non-UTF8 compliant editor.
