### ISSUE TITLE
Add polish translation 

### ISSUE THREAD

**Issue by TheRockyDoo** [olivierkes/manuskript#289]
I would like to start translating interface to Polish language here: https://hosted.weblate.org/projects/manuskript/translations/.

**Comment by olivierkes** [comment]
Hi @TheRockyDoo ,
Thanks for you interest in translating manuskript!
I created the empty polish translation, you can work on it. Tell me how things go, you're the first to use weblate :)
Cheers,

**Comment by gedakc** [comment]
@TheRockyDoo would you be able to test the Polish translation to see if I correctly added this translation work from Weblate?

**Comment by TheRockyDoo** [comment]
Yes, of course! But I don't know how to build Manuskript with my
translations. If there is my localization in newest test build just link it
to me and I'll test it asap.

Kind regards,

Norbert Kowalczyk

**Comment by gedakc** [comment]
Due to the amount of work involved to create packages we generally only do this for official releases.

Testing in the meantime requires running Manusript from the Source Code (See [Wiki](https://github.com/olivierkes/manuskript/wiki)) and choosing the **develop** branch of the git repository.

**Comment by gedakc** [comment]
Closing this issue so that the work to-date is included in the CHANGELOG.md file for when I create the next official release (soon).
