### ISSUE TITLE
Problem with minimum size of program window?

### ISSUE THREAD

**Issue by tildagail** [olivierkes/manuskript#29]
As you can see in the image, on my computer the program window extends off the bottom of the screen. This happens in 'GTK+' and 'Fusion' application styles. Bug, compatibility issue, QT version issue, something else..?

My computer runs Xubuntu 14.04, which has PyQT version 5.2.1. In the image it's using the default 'Greybird' theme. Screen resolution is 1280x800.

![screenshot](https://cloud.githubusercontent.com/assets/14209557/14552867/5669d5f0-0325-11e6-8943-cffda242c90e.png)

**Comment by olivierkes** [comment]
Thanks for reporting.
I'll look into it.

**Comment by tildagail** [comment]
Just an extra note: tried out the 'develop' branch just after posting my question and it doesn't appear to have the same problem.

**Comment by olivierkes** [comment]
Great, I'll close it then.
