### ISSUE TITLE
Doesn't Open When Clicked

### ISSUE THREAD

**Issue by RiverDawn** [olivierkes/manuskript#292]
I thought it might have been me, but I can't [get Manuskript to run. ](https://i.imgur.com/ioUWJ2B.gifv) I've got the most recent version, and I've tried uninstalling it and reinstalling. 

When I click it, it opens the command window for a split second, but then immediately shuts down. 
 
I'm running Windows 10.

**Comment by gedakc** [comment]
To capture more information about why manuskript is failing to run would you please perform the following steps?

1. Open a terminal window
2. Change into the directory that contains `manuskript.exe`
3. Enter `manuskript`
4. Copy the console output and paste it into this issue report

**Comment by RiverDawn** [comment]
Thanks for getting back to me :)

[Here's what it says](https://puu.sh/yVhNE/a0a654902d.png).

**Comment by gedakc** [comment]
I'll won't have a chance to investigate that error until later next week.  If anyone else has some tips then please feel free to add to this conversation.

In the meantime if you wish to try a different method then you might try to [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows).

**Comment by RiverDawn** [comment]
[I got it fixed](https://puu.sh/yWB9Q/9e26c0fe7c.png). My computer was deleting the needed .dll during extraction for some reason. The files I had open when it deleted the libraries are 0 bites now, but I think they just corrupted when my computer decided to be stupid. 

But yeah, problem solved and it was on my end.

**Comment by gedakc** [comment]
Thank you @RiverDawn for reporting back with how you fixed the problem.

I placed a tag of *Invalid* on this issue to try to keep it out of the release notes.
