### ISSUE TITLE
Request: update the download page

### ISSUE THREAD

**Issue by taophp** [olivierkes/manuskript#293]
This request does not concern the software but its [download page](http://www.theologeek.ch/manuskript/download/)
[It seems that the latest stable version is the 0.7.0](https://github.com/olivierkes/manuskript/issues/278#issuecomment-353790665), but the one presented on the download page is the 0.6.0.
Updating the Ubuntu package will greatly help me and others to update their instance.

**Comment by gedakc** [comment]
Currently the latest *published* stable version is 0.6.0.

The git **develop** branch contains the updates that will eventually become the next stable release which is planned to be labeled as 0.7.0.

The comment you linked to indicates that the code enhancement has been committed to the git **develop** branch in case you wished to run the **develop** branch to test the latest code.  The code in the **develop** will eventually be bundled up into 0.7.0 when it is published.

Does that explain the intention of the comment?

**Comment by gedakc** [comment]
Closing issue as *invalid* because 0.6.0 is currently the latest stable release of manuskript.
