### ISSUE TITLE
spell check issue

### ISSUE THREAD

**Issue by caseyjp11** [olivierkes/manuskript#296]
If this has been fixed in dev go ahead and delete this. 

With version .6 (linux), the spell check, using en_us, is reporting contractions as misspellings.
![screenshot from 2018-01-09 01-55-34](https://user-images.githubusercontent.com/11329574/34712588-881535b4-f4e0-11e7-9f42-0d799f662321.png)

**Comment by gedakc** [comment]
Thanks @caseyjp11 for posting the screen shot along with the issue.

From the screen shot I can see that you are running an older version of manuskript.  The lastest 0.6.0 version has different icons (see the screen shot on the [manuskript github page]()https://github.com/olivierkes/manuskript -- scroll down for picture).

In my tests with 0.6.0, words with contractions are not reported as errors.

![screenshot_20180111_132526](https://user-images.githubusercontent.com/10405019/34845685-0010ec86-f6d3-11e7-9aa5-1fa5281fd214.png)

Please install the latest version (0.6.0) and re-test.  If you still encounter the issue then please feel free to re-open this issue and add additional information.
