### ISSUE TITLE
version request

### ISSUE THREAD

**Issue by caseyjp11** [olivierkes/manuskript#297]
On the main menu having an "about" field to indicate what version of the application is being run would be nice.  (Request).
Using Archlinux, and the only AUR package is the git version. (v6), but there are no details to indicate specifics for bug reporting. --as far as I can find anyway.

**Comment by gedakc** [comment]
If you are running version 0.5.0 (or higher) then you can view the version of manuskript using the **Help -> About** menu option.

![screenshot_20180110_114846](https://user-images.githubusercontent.com/10405019/34789757-bec24738-f5fc-11e7-9360-7becd60cd901.png)

This was added to manuskript 0.5.0 with [Pull Request #153 - Add about manuskript dialog](https://github.com/olivierkes/manuskript/pull/153)

Does that answer your question?

**Comment by caseyjp11** [comment]
Using manuskript-git from Arch AUR. It indicates version 6.  On the main menu, clicking "help" reveals 
"show help texts"  CTRL+SHIFT+B.  When I do that it brings up a yellowed dialog with the word "write". (see attached picture.)
![manuskript issue](https://user-images.githubusercontent.com/11329574/34795629-2ef57c7e-f610-11e7-8c1a-5ad9aa685322.jpg)

**Comment by gedakc** [comment]
Thank you for providing more information.  Currently the highest stable release version of manuskript is 0.6.0 (not 6).

From the screen shot I can see that you are running an older version of manuskript because the word **Redaction** was changed to **Editor** (see recent screen shots for manuskript such as on the [manuskript github page](https://github.com/olivierkes/manuskript) -- scroll down to view).

You might try contacting the person who created the Arch AUR to see if they can update it to latest version of manuskript.

Alternatively, you might try to [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux).

Please let us know what you choose to do so that we can close this issue appropriately.

**Comment by caseyjp11** [comment]
Thought something was "off".  Anyway, just rechecked the AUR section, and this is where the build is pulling from:
source=("${pkgname}::git+https://github.com/olivierkes/manuskript#branch=master")
sha256sums=('SKIP')

If this is an old location, or incorrect, PLEASE let me know so that I can report this to the maintainer.

I'll attach the PKGBUILD file here as well.

[PKGBUILD.txt](https://github.com/olivierkes/manuskript/files/1625908/PKGBUILD.txt)

**Comment by gedakc** [comment]
The location of the source code is correct.  The tag associated with the **master** branch is **0.6.0**.

Currently the last commit for Manuskript in the **master** branch is as follows:
```
commit d32ee37e84b4e7e3732f75eb36fbe52c77e8171a
Author: Olivier Keshavjee <olivier.keshavjee@gmail.com>
Date:   Wed Nov 29 23:16:01 2017 +0100

    Hopefully last tweaks in context menu (#229) and optimization
```

My guess is that the AUR package is not using the latest code in the **master** branch.

I do not know how AUR packages work.  Perhaps you can find the location where the git source code is stored and do a `git pull` and then a `git log` in the git source code directory to check if the latest source code is on your computer.

**Comment by olivierkes** [comment]
I install the AUR package (I exchanged my chromebook for a ThinkPad X220, wanted a real keyboard :) and I installed Manjaro to change a bit.), and it is a 0.6.0:

![image](https://user-images.githubusercontent.com/1192933/34893581-25a073ac-f7de-11e7-91de-7fa3b2dfe088.png)

@caseyjp11, maybe you installed it before the 0.6.0 release, and you need to upgrade?

**Comment by caseyjp11** [comment]
I am baffled, but...I uninstalled, verified the application was gone, and then reinstalled from AUR. New version installed just fine. I'm going to chalk this one up to "wtf" and move on.  Go ahead and close this.  :-)

**Comment by olivierkes** [comment]
Great :)
