### ISSUE TITLE
Fullscreen editor error when text is empty (wordcount = 0)

### ISSUE THREAD

**Issue by andreashsagen** [olivierkes/manuskript#3]
Hi,

the fullscreen button didn't work for me. 

I commented out the three lines in question to make the fullscreen button work.

Error:
File "manuskript-0.1.1/bin/../manuskript/ui/editors/fullScreenEditor.py", line 284, in updateStatusBar
if goal - wc > 0:
TypeError: unsupported operand type(s) for -: 'str' and 'int'

**Comment by olivierkes** [comment]
Hi,
Thanks for the report.
Corrected in the last commit.
