### ISSUE TITLE
Overlay status bar prevents access to add/delete world item icons when displaying a message

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#307]
The issue exists in the current **develop** branch as a result of the changes made in issue #262.

# Problem

When working in the **World** pane, controls such as Add, Delete, Filter, and Favourites can be obscured when a status message is displayed such as "Project myproject.msk saved."  This is disruptive to work because the user must wait for the status message to disappear before proceeding to use the controls.  The problem would be similar for working in the **Characters**, **Plots**, and **Outline** panes.

Example of normally accessible **World** controls:

![world-1](https://user-images.githubusercontent.com/10405019/35054862-ec0e0772-fb6a-11e7-84c9-b13a43632908.png)

Example of status message obscuring **World** controls:

![world-2](https://user-images.githubusercontent.com/10405019/35054875-f2f1a224-fb6a-11e7-8e7d-f99f3a0c4867.png)

# Suggested Solution

Return to a static status bar (space is always available for the status bar as it was in 0.6.0).

**Comment by olivierkes** [comment]
I encountered the same issue recently but forgot to report. Thanks. 

Another option would be that the message disappears when mouse is over. 

Would that be enough?

**Comment by gedakc** [comment]
Thanks for providing an alternate suggestion.  I imagine that making the message disappear when the user mouses over the message would work.  Ideally I think that obscuring controls is not good UI design.  Of course UI design is subjective so I'll go along with whatever you decide.

**Comment by olivierkes** [comment]
Now the label should disappear on mouse over.

**Comment by gedakc** [comment]
Thanks @olivierkes for this fix.  I confirmed the overlay message disappears on mouse over.
