### ISSUE TITLE
Search highlighting?

### ISSUE THREAD

**Issue by Glotto** [olivierkes/manuskript#309]
Hi,

The search function doesn’t seem all that complete to me. I like how it will search through the whole document and not just the chapter open in the editor, but I think it’d be a lot better if you could then cycle through the searched word. Right now it’ll tell me that I have that word somewhere in a chapter but still requires that I then read through manually until I find it. Even a simple highlighting function would do wonders for usability.

Overall I can see myself falling hard for this software. It seems simple and clean with a few functions that already put it ahead of the alternatives.

**Comment by gedakc** [comment]
Thank you for the suggestion.  It would be nice to have the search word(s) highlighted so that they can be easily located.  Being able to cycle through the searched word would be great too.

**Comment by gedakc** [comment]
The ability to highlight search text terms has previously been requested in:

- [Issue 145 - global and local search and replace](https://github.com/olivierkes/manuskript/issues/145)

If there is something that missing in the above then please feel free to add to Issue #145.

In an effort to clean up requests for search functionality I am marking this issue as **duplicate**.
