### ISSUE TITLE
[MacOS 10.13.3] Crashes after changing smart revision settings. 

### ISSUE THREAD

**Issue by ethanbreck** [olivierkes/manuskript#314]
I changed the first revision history thing, 1 per minute for the last 10 minutes to 2 revisions per for the last 10 minutes. I can open the app to the new novel screen, but crashes when i go into settings. Pastebin has both the terminal output, and the crash report:

https://pastebin.com/MGCufVAs

**Comment by gedakc** [comment]
Which version of Manuskript are you running (e.g. 0.6.0)?
Are you running from the PyInstaller .zip package, or from source code (e.g., **master** or **develop** git branch)?

Following is a snippet of the output from the pastebin.com log:
```
ekbmacbook:~ ekb$ /Applications/manuskript/manuskript ; exit;
Warning: failed to load translator for locale en_US...
objc[74020]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff910b1b68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10f5efcd8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "manuskript/ui/welcome.py", line 159, in createFile
  File "manuskript/ui/welcome.py", line 344, in loadDefaultDatas
  File "manuskript/ui/welcome.py", line 344, in <listcomp>
IndexError: list index out of range
Fatal Python error: Aborted
```
From the output it appears that there are two classes with the exact same name.  Further the crash appears to have occurred in the welcome portion where a user is prompted with the create project screen and the **Recent** button drop-down is populated with the names of prior ".msk" project names.

Based on what I can see so far, the problem doesn't appear to be related to revisions....

**Comment by ethanbreck** [comment]
Yeah, im using 0.6.0, and i got the zip package from [here](http://www.theologeek.ch/manuskript/download/). It seems like you have a basic diagnostic, what do you need me to do to find the issue?

**Comment by gedakc** [comment]
From a quick google search other people seem to indicate that the [two classes with the same name is generally not an issue](https://stackoverflow.com/questions/46999695/class-fifindersyncextensionhost-is-implemented-in-both-warning-in-xcode-si).

The initial line 159 indicated in the crash log seems relatively benign.

In [line 159 of `manuskript/ui/welcome.py`](https://github.com/olivierkes/manuskript/blob/d32ee37e84b4e7e3732f75eb36fbe52c77e8171a/manuskript/ui/welcome.py#L159) the code is checking to see if the file path ends in `.msk`, and if so it removes the `.msk` from the name so that it can be displayed in the manuskript window title.

Do you have manuskript set to automatically load the last open project?

If so, can you try removing the custom manuskript configuration files and then start manuskript again?

I don't have access to Mac OS X, but since it is similar to GNU/Linux I believe the files will be under your userid home directory with the names `manuskript.conf` and `manuskriptrc`.  On my GNU/Linux computer these are located in the following directories.

```
~/.config/manuskriptrc
~/.config/manuskript/manuskript.conf
```

You might also try searching on your computer to locate these two file names.

**Comment by ethanbreck** [comment]
Im having issues finding them in the application support folder (which is probably akin to the config folder), and the folder with the files in it.

**Comment by ethanbreck** [comment]
I could try a reinstall?

**Comment by gedakc** [comment]
I don't think this would resolve the issue because reinstalling the package does not remove the configuration files.

From a quick google search for "mac os x configuration files" I came across the following link:
[Default location for configuration files - MacOS?](https://stackoverflow.com/questions/15677388/default-location-for-configuration-files-macos)

Can you check for manuskript configuration files in `~/Library/Application Support/manuskript/manuskript.cfg`?

It is also possible that hidden files (usually file names beginning with a period) are not shown.
See [Quickly Show/Hide Hidden Files on macOS Sierra, OS X El Capitan & Yosemite](https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/).

**Comment by ethanbreck** [comment]
![screen shot 2018-02-11 at 10 21 34 am](https://user-images.githubusercontent.com/6488051/36076751-5fb42e00-0f15-11e8-9faa-068d8e31b246.png)
I tried going to that folder, and that was what was there. There was no Manuskript.cfg file there.

**Comment by gedakc** [comment]
Can you try deleting the `~/Library/Application Support/manuskript` folder?

Please also try enabling the ability to see hidden files and then check for a `~/.config/manuskript` directory / file.

**Comment by ethanbreck** [comment]
I tried the hidden files, and still couldnt find it, so i deleted the folder. 

Here's the terminal output now, and the app just quits.

Last login: Sun Feb 11 10:29:14 on ttys001
ekbmacbook:~ ekb$ /Applications/manuskript/manuskript ; exit;
Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "manuskript/main.py", line 63, in run
  File "manuskript/main.py", line 69, in launch
  File "manuskript/mainWindow.py", line 57, in __init__
  File "manuskript/mainWindow.py", line 766, in setupMoreUi
  File "manuskript/ui/collapsibleDockWidgets.py", line 108, in restoreState
ValueError: too many values to unpack (expected 3)
manuskript returned -1
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by gedakc** [comment]
Okay, I think we are making progress.  Since manuskript is trying to "restoreState" that indicates that there must be some other configuration file left that we haven't yet deleted.

Can you try doing a search across the entire file system for the name "*manuskipt*"?

In GNU/Linux the terminal command would be:

`find / -name "*manuskript*" -print 2>/dev/null`

The redirect of stderr "2" is to avoid printing all the files and folders for which the userid does not have access.

**Comment by ethanbreck** [comment]
So i should search in my user files then? because my search function is grep -r 'text goes here' path_goes_here

the -r only searches subdirectory listed.

**Comment by gedakc** [comment]
The grep command will search within files for a string.

What we are trying to do is search for file and folder names that contain "manuskript" in the name.  I believe that Mac OS X should have the `find` command.

**Comment by ethanbreck** [comment]
Yeah, it has an mdfind command. If you want me to do the grep command as well, ill post the output later Here is the output:

/Users/ekb/Library/Application Support/Google/Chrome/Default/IndexedDB/https_titan.service.amazonbrowserapp.com_0.indexeddb.leveldb/000760.log
/Applications/manuskript/manuskript
/Applications/manuskript2.0/manuskript
/Applications/manuskript2.0
/Applications/manuskript2.0/sample-projects/book-of-acts/MANUSKRIPT
/Applications/manuskript2.0/i18n/print_project.sh
/Applications/manuskript2.0/i18n/manuskript_de.qm
/Applications/manuskript2.0/i18n/search_files.sh
/Applications/manuskript2.0/i18n/manuskript_de.ts
/Applications/manuskript2.0/i18n/manuskript_es.ts
/Applications/manuskript2.0/i18n/manuskript_es.qm
/Applications/manuskript2.0/i18n/manuskript_fr.ts
/Applications/manuskript2.0/i18n/manuskript_sv.ts
/Applications/manuskript2.0/i18n/manuskript_fr.qm
/Applications/manuskript2.0/i18n/manuskript.pro
/Applications/manuskript2.0/i18n/manuskript_sv.qm
/Applications/manuskript2.0/i18n/languages.txt
/Applications/manuskript2.0/icons/Manuskript
/Applications/manuskript2.0/icons/Manuskript/manuskript.svg
/Applications/manuskript2.0/icons/NumixMsk/index.theme
/Applications/manuskript
/Users/ekb/Downloads/manuskript-0.6.0-osx.zip
/Users/ekb/Library/Application Support/CrashReporter/manuskript_D81EB9AE-D6A0-56A0-B5F0-9C176829C6A5.plist
/Applications/manuskript/sample-projects/book-of-acts/MANUSKRIPT
/Applications/manuskript/i18n/manuskript_es.ts
/Applications/manuskript/i18n/manuskript_es.qm
/Applications/manuskript/i18n/manuskript_fr.ts
/Applications/manuskript/i18n/manuskript_fr.qm
/Applications/manuskript/i18n/manuskript.pro
/Applications/manuskript/i18n/tool.txt
/Applications/manuskript/icons/Manuskript
/Applications/manuskript/icons/NumixMsk/index.theme
/Users/ekb/Dropbox (Personal)/Apps/Manuskript
/Users/ekb/Downloads/manuskript-0.6.0-1.deb
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/manuskript.rb

**Comment by gedakc** [comment]
From looking at the output I did not observe any entries that started with a period or character string other than starting with "manuskript".  I wonder if the mdfind command is not doing the search we desire.

Can you try:

`find / -name "*manuskript*" -print 2>/dev/null`

**Comment by ethanbreck** [comment]
Here is the output of that.

ekbmacbook:~ ekb$ find / -name "*manuskript*" -print 2>/dev/null
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/manuskript.rb
/private/var/folders/ln/n_kbs5054px3m5hpwcmy52jw0000gn/T/AppTranslocation/93B3E39F-30B1-41F1-8A5C-F265F444172C/d/manuskript
/Users/ekb/Library/Application Support/CrashReporter/manuskript_D81EB9AE-D6A0-56A0-B5F0-9C176829C6A5.plist
/Users/ekb/Library/Preferences/com.manuskript.manuskript.plist
/Users/ekb/Library/Preferences/ch.theologeek.www.manuskript.plist
/Users/ekb/Library/Preferences/manuskript.plist
/Users/ekb/Library/Logs/DiagnosticReports/manuskript_2018-02-11-081327_ekbmacbook.crash
/Users/ekb/Library/Logs/DiagnosticReports/manuskript_2018-02-11-081141_ekbmacbook.crash
/Users/ekb/Library/Logs/DiagnosticReports/manuskript_2018-02-11-081735_ekbmacbook.crash
/Users/ekb/Library/Logs/DiagnosticReports/manuskript_2018-02-11-081144_ekbmacbook.crash
/Users/ekb/Library/Logs/DiagnosticReports/manuskript_2018-02-11-081326_ekbmacbook.crash
/Users/ekb/Library/Logs/DiagnosticReports/manuskript_2018-02-11-081313_ekbmacbook.crash
/Users/ekb/Library/Logs/DiagnosticReports/manuskript_2018-02-11-081737_ekbmacbook.crash
/Users/ekb/Library/Logs/DiagnosticReports/manuskript_2018-02-11-081311_ekbmacbook.crash
/Users/ekb/Downloads/manuskript-0.6.0-1.deb
/Users/ekb/Downloads/manuskript-0.6.0-osx.zip
/Applications/manuskript
/Applications/manuskript/manuskript
/Applications/manuskript/i18n/manuskript.pro
/Applications/manuskript/i18n/manuskript_fr.qm
/Applications/manuskript/i18n/manuskript_fr.ts
/Applications/manuskript/i18n/manuskript_es.qm
/Applications/manuskript/i18n/manuskript_es.ts

**Comment by gedakc** [comment]
Interesting.  We get different output that way.  The folder with "Preferences" sounds promising.

Can you try deleting the following preferences?
```
/Users/ekb/Library/Preferences/com.manuskript.manuskript.plist
/Users/ekb/Library/Preferences/ch.theologeek.www.manuskript.plist
/Users/ekb/Library/Preferences/manuskript.plist
```

Each of these files should be specific to the manuskript program.

**Comment by ethanbreck** [comment]
Deleted and trash emptied. what next? try again?

**Comment by ethanbreck** [comment]
This happens again: Last login: Sun Feb 11 10:49:54 on ttys000
ekbmacbook:~ ekb$ /Applications/manuskript/manuskript ; exit;
Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "manuskript/main.py", line 63, in run
  File "manuskript/main.py", line 69, in launch
  File "manuskript/mainWindow.py", line 57, in __init__
  File "manuskript/mainWindow.py", line 766, in setupMoreUi
  File "manuskript/ui/collapsibleDockWidgets.py", line 108, in restoreState
ValueError: too many values to unpack (expected 3)
manuskript returned -1
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by gedakc** [comment]
Hmmm.. I would have thought the startup messages would have changed.

I noticed two entries for manuskript:
```
/Applications/manuskript/manuskript
/Applications/manuskript2.0/manuskript
```

Did you install manuskript twice?
Or is this some other manuskript?

It might be worth trying to remove all copies of manuskript and then install again.

I'm off to have lunch and will check back after.

**Comment by ethanbreck** [comment]
manuskript was another install i had, trying to replicate the problem so i could try and see if i could diagnose it. Ill reinstall manuskript as a whole, and make sure i delete all the manuskript files except my novel files.

**Comment by gedakc** [comment]
Good to ensure your novel work is not deleted.  :-)

We might also be encountering an issue with upper and lower case "M".  It might also be worth trying the following command to look for manuskript preference settings:

`find / -name "*anuskript*" -print 2>/dev/null`

**Comment by ethanbreck** [comment]
so i reinstalled it, and here's the output. I think its working:

/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/manuskript.rb
/Users/ekb/Dropbox (Personal)/Apps/Manuskript
/Users/ekb/Library/Application Support/CrashReporter/manuskript_D81EB9AE-D6A0-56A0-B5F0-9C176829C6A5.plist
/Users/ekb/Downloads/manuskript-0.6.0-1.deb
/Users/ekb/Downloads/manuskript-0.6.0-osx.zip
/Applications/manuskript
/Applications/manuskript/icons/Manuskript
/Applications/manuskript/icons/Manuskript/manuskript.svg
/Applications/manuskript/manuskript
/Applications/manuskript/i18n/manuskript_sv.qm
/Applications/manuskript/i18n/manuskript.pro
/Applications/manuskript/i18n/manuskript_fr.qm
/Applications/manuskript/i18n/manuskript_sv.ts
/Applications/manuskript/i18n/manuskript_fr.ts
/Applications/manuskript/i18n/manuskript_es.qm
/Applications/manuskript/i18n/manuskript_es.ts
/Applications/manuskript/i18n/manuskript_de.ts
/Applications/manuskript/i18n/manuskript_de.qm

**Comment by gedakc** [comment]
Are you able to start manuskript so that it displays the welcome screen?

**Comment by ethanbreck** [comment]
No, it opens into the novel, but let me change the preference there, and try again.

**Comment by gedakc** [comment]
Can you try disabling automatic load first?

**Comment by ethanbreck** [comment]
I disabled it, and it loads to the welcome scene. Here's what i see:
<img width="1118" alt="screen shot 2018-02-11 at 11 24 23 am" src="https://user-images.githubusercontent.com/6488051/36077309-2320be32-0f1e-11e8-8d89-e98531967063.png">

**Comment by gedakc** [comment]
Good.  That's how it should work.  At least when automatic load is disabled.

Now try clicking on **Recent** and if it lists your novel then select it so that it loads.

**Comment by ethanbreck** [comment]
Yeah, it works. Loads back in to my project well. I think that solves it.

**Comment by gedakc** [comment]
Can you try changing the revision setting to see if Manuskript starts crashing again?

**Comment by ethanbreck** [comment]
sure.

**Comment by ethanbreck** [comment]
It changed the revision settings like last time, and it didnt crash.

**Comment by gedakc** [comment]
Interesting.  My guess it that the problem might have been a corrupt preference setting.

I guess we can close this issue as solved.  If it occurs again the please do re-open and provide additional details.

**Comment by ethanbreck** [comment]
okay. Thanks for the help @gedakc, if it happens again, ill reopen this, and provide all the stuff you asked for here.
