### ISSUE TITLE
Problem testing Portugal (pt_PT) translation

### ISSUE THREAD

**Issue by ghost** [olivierkes/manuskript#326]
Hi,
I have a complete translation for [Portugal (pt_PT)](https://www.dropbox.com/s/v4ud8hl7p74aamu/manuskript_pt_PT.ts.tar.gz?dl=0).

After git cloning Manuskript and checkout develop, I followed the procedure to test it, changing languages.txt, manuskript.pro and settingsWindow.py.
I did pyupdate, lrelease, even edited the makefile. Nothing. The translation is loaded but the UI is still in English.
I use Linux Debian based Mx-16 fully updated and ran Manuskript from /bin/manuskript
Thank you for any help.
[manuskript_pt_PT.ts.tar.gz](https://github.com/olivierkes/manuskript/files/1814765/manuskript_pt_PT.ts.tar.gz)

PS: maybe you can include the translation on the general release?

**Comment by pindarogb** [comment]
Hey, Im Brasilian user, and now, I have translate to ptBr too.

I see in your case missing ou generate *.qm file, to Manuskript load language.

on dir manuskript\i18n are two files to each language one *.ts and other *.qm

On select other language manuskript search for these *.qm file. Like printscreen below show.
![qm_files](https://user-images.githubusercontent.com/41213070/43214732-81636454-9010-11e8-8e30-bb9fa707122a.png)


sorry for my english

Att

**Comment by gedakc** [comment]
The pt_PT translation included on Weblate has been incorporated into the current **develop** branch.  

I am closing this issue because the user that created this original request has been deleted and has become a ghost account.
