### ISSUE TITLE
Crash in Redaction tab

### ISSUE THREAD

**Issue by magicvince** [olivierkes/manuskript#328]
When there's no chapter displaying in the redaction part, clicking on "go to parent …" crash manuskript.

Quand je suis dans la partie «rédaction» et qu'aucun chapître n'est affiché, si je clique sur l'icône «Aller à l'élément parent», Manuskript crashe instantanément

I'm using 0.6.1 on Debian Stretch

**Comment by gedakc** [comment]
Thank you @magicvince for you interest in Manuskript.

This problem was reported earlier in issue #318 - stop crash when click btnGoUp and current editor is None.

This problem has been fixed in the **develop** branch and will be included when 0.7.0 is released.

Marking this report as a duplicate.
