### ISSUE TITLE
Ctrl + f to search in editor

### ISSUE THREAD

**Issue by lechbaczynski** [olivierkes/manuskript#332]
I propose to allow searching edited text (in editor) with ctrl + f

Also, maybe, entering search tab (that one on the right) by using shift + ctrl + f

Also in fullscreen editor

**Comment by gedakc** [comment]
The ability to search in editor has previously been requested in:

- [Issue 145 - global and local search and replace](https://github.com/olivierkes/manuskript/issues/145)
- [Issue 309 - Search highlighting](https://github.com/olivierkes/manuskript/issues/309)

If there is something that missing in the above then please feel free to add to Issue #145.

Please note that a global search tab is accessible on the right-hand-side of the Manuskript window.

Marking this issue as **duplicate**.
