### ISSUE TITLE
Undo/redo works in some text areas but not others

### ISSUE THREAD

**Issue by tildagail** [olivierkes/manuskript#34]
The undo/redo commands don't work in main editor, notes/references, and World item description box. All other text areas seem to have undo/redo working.

**Comment by tildagail** [comment]
I've been looking through the code and I've figured out that the undo/redo is being broken whenever the 'highlightBlockBefore' function in basicHighlighter.py is called. Specifically, if I comment out this line...

QTextCursor(self.currentBlock()).setBlockFormat(bf)

...then undo/redo works in the affected text areas. Unfortunately, commenting out that line breaks the first line indent and line spacing in the main editor box.

System: Xubuntu 14.04, PyQT version 5.2.

**Comment by olivierkes** [comment]
Hi,
Thanks for reporting.
I think I need to use CSS for line spacing and indent and that sort of things. Now that I think about it, it seems much more natural.
I'll do that when I have the time :)

**Comment by Renkineko** [comment]
I confirm I had the problem with the 0.3.0 release, which made me have a big fear (I wrote a big text in "no distract mode" then my hand touched the touchpad so it selected a lot of text and i was writing, so a lot of text disappeared... And no CTRLZ. Thanks to the revision system I just had a paragraph who disappeared but I think it's pretty important to have the CTRL Z working, it's a must have when it comes to text editing. Just my opinion btw :)

**Comment by eshac** [comment]
Hi, I also have CTRL Z not working in Ubuntu 16.04. In the general writing tab (redaction) and in description in World tab. The other seem to be working.
I'm using the software almost for a month and I like it very much, thanks!

**Comment by gedakc** [comment]
While investigating this issue I came across and added to a related QT bug report.
See [QTextEdit undo fails after using QTextCursor (even with begin/end-EditBlock()](https://bugreports.qt.io/browse/QTBUG-55618).

**Comment by gedakc** [comment]
Using the tip from @tildagail, I tried commenting out the QTextCursor line.
This does enable _Undo_ (**Ctrl+Z**) and _Redo_ (**Ctrl+Shift+Z**) to work.  :-)

Using the tip from @olivierkes to use CSS instead of Qt rich-text-formatting, I discovered that [QT supports a limited set of CSS properties](https://doc.qt.io/qt-5/richtext-html-subset.html#css-properties).

Further when I tried to hard-code a **text-indent** CSS property, which is listed as being supported, I was unable to get it to work.

Following is a git diff of the two line changes to recreate the test I did:

```
$ git diff
diff --git a/manuskript/ui/editors/basicHighlighter.py b/manuskript/ui/editors/basicHighlighter.py
index 83e0630..75c2bfd 100644
--- a/manuskript/ui/editors/basicHighlighter.py
+++ b/manuskript/ui/editors/basicHighlighter.py
@@ -43,7 +43,7 @@ class basicHighlighter(QSyntaxHighlighter):
         """
         bf = QTextBlockFormat(self._defaultBlockFormat)
         bf.setAlignment(QTextCursor(self.currentBlock()).blockFormat().alignment())
-        QTextCursor(self.currentBlock()).setBlockFormat(bf)
+        # QTextCursor(self.currentBlock()).setBlockFormat(bf)
 
         # self.setFormat(0, len(text), self._defaultCharFormat)
 
diff --git a/manuskript/ui/views/textEditView.py b/manuskript/ui/views/textEditView.py
index c81349a..f50824c 100644
--- a/manuskript/ui/views/textEditView.py
+++ b/manuskript/ui/views/textEditView.py
@@ -187,6 +187,7 @@ class textEditView(QTextEdit):
             color: {foreground};
             font-family: {ff};
             font-size: {fs};
+            text-indent: 20px;
             }}
             """.format(
                 bg=opt["background"],
$
```

My thoughts are long term we should strive to remove QT rich-text-formatting from the Text Editor, and only support CSS, so that Undo/Redo works.

**Comment by olivierkes** [comment]
## CSS formatting

I tried to go all CSS for paragraph formatting, but I couln't find a way to do it.

As @gedakc pointed out, Qt supports a [subset of CSS properties for rich text](http://doc.qt.io/qt-5/richtext-html-subset.html) formatting, including `text-indent`, `margin-top` and `margin-bottom` for paragraph. Yet I wasn't able to apply them to `QTextEdit`'s *paragraph* (for exemple using CSS Selector `QTextEdit p {…}`).

> My thoughts are long term we should strive to remove QT rich-text-formatting from the Text Editor, and only support CSS, so that Undo/Redo works.

SyntaxHighlighting uses rich-text formating through QTextCharFormat, which works with the Undo/Redo stacks. So I guess there should be a way to get QTextBlockFormat to work too.

## Using QTextBlockFormat

When using QTextBlockFormat (as is the case in `basicHighlighter.py`), the Undo stack of the underlying QTextDocument gets a new item. I don't know why, or how to cancel that. So when the paragraph is formatted, the undo stack gets filled with undo items (also don't know where it gets filled), so we cannot undo.

I tried using `QTextCursor`'s [joinPreviousEditBlock](http://doc.qt.io/qt-5/qtextcursor.html#joinPreviousEditBlock), but no luck there.

Finally I found an ugly hack that works: after apply block format, I call the document's Undo function. And now the stack is not filled, and `undo` is usable (though not `redo`…)

**Please test and tell me if it works for you, and if you think this is an acceptable fix for the time being**.

The alternatives are:

- Finding a proper fix
- Removing paragraph formating until we find a proper fix
- Keeping things as they were (no undo function) until we find a proper fix

**Comment by olivierkes** [comment]
ok I found a fix: i apply the QTextBlockFormat only if it has changed. Now everything seems to work.

**Somebody please test and confirm** so that we can close this issue.

**Comment by gedakc** [comment]
Great work @olivierkes !

I tested this on the git _develop_ branch and it works like charm.

**Ctrl+Z** will undo recently typed text, and **Ctrl+Shift+Z** will  redo the text.
