### ISSUE TITLE
develop the same as release?

### ISSUE THREAD

**Issue by caseyjp11** [olivierkes/manuskript#343]
I wanted to try a few things changed/fixed that I'd read were in the develop version (mostly for find/replace). I did the normal git commands and 'checkout develop'...but a pull shows "up to date", and there is zero difference in the application when run.

If there is something I'm  missing something, I'd appreciate knowing any little tips/n/tricks.  

ty in advance.

**Comment by caseyjp11** [comment]
Curtis,

[casey@Kandalf manuskript]$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
[casey@Kandalf manuskript]$ git log
commit 4b50024a3276e9bef3e490ac9c4fe0318d196039 (HEAD -> develop,
origin/develop)
Author: Curtis Gedak <gedakc@gmail.com>
Date:   Fri Apr 6 11:15:45 2018 -0600

    Enhance Travis CI build on OSX to remove sudo ownership warning

    The Travis CI build reports the following in the messages from
    executing package/prepare_osx.sh:

        sudo pip3 install --upgrade pip setuptools wheel
        The directory '/Users/travis/Library/Caches/pip/http' or its       \
         parent directory is not owned by the current user and the cache   \
         has been disabled. Please check the permissions and owner of that \
         directory. If executing pip with sudo, you may want sudo's -H     \
         flag.
        The directory '/Users/travis/Library/Caches/pip' or its parent     \
         directory is not owned by the current user and caching wheels has \
         been disabled. check the permissions and owner of that            \
         directory. If executing pip with sudo, you may want sudo's -H     \
         flag.

:

Perhaps I have just misread the git bugs message section. I was under the
impression things like "ctrl+f" would do a find/replace and a few other
things that "seemed" to indicate they were in the dev version.
The "about" doesn't show anything other than this:

​

Casey

**Comment by caseyjp11** [comment]
the attached pic didn't go through here.  the "about" dialog only shows this:
Version 0.6.0
Software Versions in Use:
     Python 3.6.5
     PyQt 5.10.1
     Qt 5.10.1

**Comment by gedakc** [comment]
@caseyjp11, the information you provided is consistent with running the **develop** branch.

As you mentioned I suspect you may have misread an issue report.

**Comment by gedakc** [comment]
Closing this question as answered -- the **master** branch is the same as the last official release version.
