### ISSUE TITLE
Manuskript not opening 

### ISSUE THREAD

**Issue by hbt410** [olivierkes/manuskript#346]
Hello, 
I am somewhat new to ubuntu and I don't use windows because I have a low end machine.
I installed manuskript and when i try to run it through the terminal it shows the following error:
` 
hbt@hbt-jr:~$ manuskript
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 28, in <module>
    from manuskript import mai
  File "/usr/share/manuskript/manuskript/main.py", line 7, in <module>
    import manuskript.ui.views.webView
  File "/usr/share/manuskript/manuskript/ui/views/webView.py", line 3, in <module>
    import PyQt5
ModuleNotFoundError: No module named 'PyQt5'

`

I have tried installing PyQt5 through the following command but it says my system already has pyqt5:

`
hbt@hbt-jr:~$ sudo apt install python-pyqt5
[sudo] password for hbt: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pyqt5 is already the newest version (5.5.1+dfsg-3ubuntu4).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-21 linux-headers-4.4.0-21-generic linux-headers-4.4.0-79
  linux-headers-4.4.0-79-generic linux-image-4.4.0-21-generic
  linux-image-4.4.0-79-generic linux-image-extra-4.4.0-21-generic
  linux-image-extra-4.4.0-79-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 564 not upgraded.

`
I have looked up on the internet but couldn't find a solution. Please help!!

Edit : I removed it after upgrading  and updating as suggested by @nitinvinayak , and reinstalled it shortly after using Gdebi ...but the problem persists. **I'm on Ubuntu 16.04**.Here's the terminal code while reinstalling:

`
(Reading database ... 370700 files and directories currently installed.)
Preparing to unpack .../manuskript-0.6.0-1(1).deb ...
Unpacking manuskript (0.6.0-1) over (0.6.0-1) ...
Setting up manuskript (0.6.0-1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
 
#`

**Comment by nitinvinayak** [comment]
Run :
sudo apt-get update
sudo apt-get upgrade
and then try running the manuskript

**Comment by hbt410** [comment]
@nitinvinayak No it's still not opening

**Comment by gedakc** [comment]
Closing this issue as **invalid** because there has been no further information provided.
