### ISSUE TITLE
Crash if Cheatsheet filter term not found and Enter key pressed

### ISSUE THREAD

**Issue by schifreen** [olivierkes/manuskript#354]
Title says it all really.  Enter something into the cheat sheet search box.  If not found, Windows version exits immediately.

**Comment by bartart3d** [comment]
Happens here too.

**Comment by gedakc** [comment]
@schifreen and @bartart3d, what version of Manuskript are you running?

I've tried the Windows Manuskript 0.6.0 package, and also running the git **master** and **develop** branches on Windows XP and none of these crash when I enter text (that doesn't exist in the document) into the **Cheatsheet** search field.

It is possible that this is related to crash issues previously identified with spell check when the dictionary doesn't exist.  See issue #273.

Do you have spell check enabled with a valid dictionary?

Can you try invoking manuskript from a command prompt and then recreate the issue and post the output here?

**Comment by schifreen** [comment]
Sorry, I don't currently have Manuskript installed here so I can't easily
try it.

But yes, it could be because I didn't have spell check and a dictionary
installed/enabled.  I don't think I enabled either of those.


Regards,


Robert Schifreen

https://www.securitysmart.co.uk
https://www.linkedin.com/in/robertschifreen

**Comment by gedakc** [comment]
Thank you @schifreen for the prompt response.  Hopefully @bartart3d will be able to provide the console output for the issue you encountered.

**Comment by bartart3d** [comment]
Hello,

The masterbranch gives me this:

(no spellcheck language selected and spellcheck not active)
```
Traceback (most recent call last):
  File "manuskript\ui\cheatSheet.py", line 150, in showInfos
AttributeError: 'NoneType' object has no attribute 'data'
```

The development version, with the same conditions gives me a similar result

  ```
File "C:\Users\bartd\Documents\manuskript-devel\manuskript-develop\bin\..\manuskript\ui\cheatSheet.py", line 150, in showInfos
    ref = i.data(Qt.UserRole)
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by gedakc** [comment]
Thank you @bartart3d for providing additional details on both the **master** and **develop** branch.

To simulate starting Manuskript for the first time on Windows 10 I used `regedit` to remove the **HKEY_Current_User/Software/manuskript** entry.  Then I started manuskript, loaded a document, and then typed in a non-existent word into the **Cheatsheet** filter.  For me manuskript continued to run properly.  This leads me to believe that something else is needed to reproduce the issue.

Would you be able to provide the output from the following command to help investigate this issue?

In a command prompt enter the `systeminfo` command.

On my Windows XP VM the output is as follows:

```

Host Name:                 WINXPPRO
OS Name:                   Microsoft Windows XP Professional
OS Version:                5.1.2600 Service Pack 3 Build 2600
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Uniprocessor Free
Registered Owner:          client
Registered Organization:   company
Product ID:                55274-OEM-0014324-00153
Original Install Date:     05/04/2016, 10:08:15 AM
System Up Time:            0 Days, 0 Hours, 10 Minutes, 15 Seconds
System Manufacturer:       VMware, Inc.
System Model:              VMware Virtual Platform
System type:               X86-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: x86 Family 6 Model 158 Stepping 9 GenuineIntel ~4198 Mhz
BIOS Version:              INTEL  - 6040000
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (GMT-08:00) Pacific Time (US & Canada); Tijuana
Total Physical Memory:     2,047 MB
Available Physical Memory: 1,797 MB
Virtual Memory: Max Size:  2,048 MB
Virtual Memory: Available: 2,008 MB
Virtual Memory: In Use:    40 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\WINXPPRO
Hotfix(s):                 2 Hotfix(s) Installed.
                           [01]: Q147222
                           [02]: KB936929 - Service Pack
NetWork Card(s):           1 NIC(s) Installed.
                           [01]: AMD PCNET Family PCI Ethernet Adapter
                                 Connection Name: Local Area Connection
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.218.254
                                 IP address(es)
                                 [01]: 192.168.218.129
```

I am mostly curious as to whether a different language locale is involved.

If you have a sample document and a list of steps that recreate the issue then posting those would be a great help too.

**Comment by schifreen** [comment]
Have a look at https://www.youtube.com/watch?v=5V0WpmvobD8&feature=youtu.be
to see what happens on my PC.


Regards,


Robert Schifreen

**Comment by schifreen** [comment]
Thanks.  No problem.  I'm not really using Manuskript much right now, but
just wanted to try to help you out.


Regards,


Robert Schifreen

https://www.securitysmart.co.uk
https://www.linkedin.com/in/robertschifreen

**Comment by gedakc** [comment]
I have confirmed the crash on both the **master** (0.6.0) and **develop** branch.  The key piece of information I was missing is that the crash occurs when the **Enter** key is pressed after typing in a non-existent word in the **Cheatsheet** filter.

The crash also occurs in the GNU/Linux version of manuskript so is common to all OSes.

**Comment by gedakc** [comment]
I've committed a fix for this crash to the **develop** branch.  As such I'm closing this report so that it will be properly included in the CHANGELOG.md file when I create the next official release (soon).

**Comment by schifreen** [comment]
Thanks!



Regards,


Robert Schifreen

https://www.securitysmart.co.uk
https://www.linkedin.com/in/robertschifreen

**Comment by gedakc** [comment]
Thank you @bartart3d for reporting that issue no longer appears and Manuskript works.
