### ISSUE TITLE
world elements' text in list does not fit

### ISSUE THREAD

**Issue by Leblake** [olivierkes/manuskript#369]
First things first: Manuskript is AWESOME. It really makes it easier to write a story!

Now...

Might be something with my installation? The thing is I really can't use the World section as any element I create there does not show its full name and I don't have column titles that I can resize. I tried everything I could think of...

![selection_142](https://user-images.githubusercontent.com/22378679/43418529-776c8430-943e-11e8-8fde-f0d67f0749ca.png)

**Comment by gedakc** [comment]
What version of manuskript are you running (for example:  0.6.0, or git **develop** branch source code)?

I'm running the git **develop** branch source code on Linux and see the following:

![manuskript-world-version_0 6 0-develop-](https://user-images.githubusercontent.com/10405019/43419249-abe3f446-93fd-11e8-88ad-2990bd5e1ba5.png)

**Comment by Leblake** [comment]
0.6.0, downloaded from the web.

What a quick response! :O Should I install the develop version?

**Comment by gedakc** [comment]
What operating system are you running on?

I just checked Manuskript 0.6.0 running on Windows XP and it looks the same as the picture I included above.

**Comment by Leblake** [comment]
Linux Mint 19 MATE Edition.

Just installed the dev version and it works as you posted now. I'll see what happens if I install the web version again.

**Comment by gedakc** [comment]
Which "web" version are you referring to?

Is it from [http://www.theologeek.ch/manuskript/download/](http://www.theologeek.ch/manuskript/download/) or [https://sourceforge.net/projects/manuskript/files/manuskript/](https://sourceforge.net/projects/manuskript/files/manuskript/)?

**Comment by Leblake** [comment]
Strange, I did as I said and it works well now... but yesterday, I checked my version number and said 0.6.0.

Well, that's it. Thanks for the help and keep it up, this software is sooooo nice. ;)
