### ISSUE TITLE
[Windows] Cancel Button on Compile Dialog does not work

### ISSUE THREAD

**Issue by JoaoGFarias** [olivierkes/manuskript#38]
The Cancel Button in the Compile dialog has no action. The user needs to use the close button, in the top-right area of the dialog.

![cancel button](https://cloud.githubusercontent.com/assets/1585655/17081645/bc17aa6c-5136-11e6-808f-e18511684b1f.png)

**Comment by olivierkes** [comment]
Thanks a lot for your reports, but if you wanna test the export dialog you must test the develop branch. Lots of work has been done there, the exporter is much more powerful.

Can you run from develop?
