### ISSUE TITLE
[Windows] Compile Dialog does not have a title

### ISSUE THREAD

**Issue by JoaoGFarias** [olivierkes/manuskript#39]
The compile dialog title is not defined.

Expected to have "Compile" in the title, not "Dialog"

![dialog](https://cloud.githubusercontent.com/assets/1585655/17081649/e78f3c78-5136-11e6-8e37-6e4c158f6ee6.png)

**Comment by olivierkes** [comment]
Thanks
The compile dialog has been completely redisigned in 0.4.0, you can try it in the develop branch.
