### ISSUE TITLE
Grammar bug introduced by #383

### ISSUE THREAD

**Issue by RiderExMachina** [olivierkes/manuskript#390]
Manuskript version: 0.7.0 develop

When creating a new project the created Books, Sections, Chapters, and Scenes are now labelled as "Chapters 1, Chapters 2," etc. in the Outline view. See screenshot.

![python_2018-09-20_12-23-31](https://user-images.githubusercontent.com/8017578/45841923-1832c500-bcd0-11e8-88ea-0a6eb7575bd8.png)

**Comment by gedakc** [comment]
Thank you @RiderExMachina for discovering this issue.

Are you in agreement that I should revert commit 2fdf8c64bf00?

**Comment by RiderExMachina** [comment]
@gedakc 

Yes, that seems to be the best approach at this current moment.

**Comment by gedakc** [comment]
Hmm... I'm seeing some strange behaviour on my Kubuntu 16.04 development computer.

On my local git repository I have reverted commit 2fdf8c6 and have been doing some testing.

If I create a new project with manuskript, both the **Chapter** and **Scene** words are missing from the **Outline** pane as shown in the attached screen shot.

![screenshot_20180920_144524](https://user-images.githubusercontent.com/10405019/45846083-0d822b00-bce4-11e8-81b0-0109d4aa96a7.png)


Does the same problem happen when you create a new project?

**Comment by gedakc** [comment]
Closing this issue and marking it as **invalid** so that it does not get picked up the the automatic generation of CHANGELOG.md.
