### ISSUE TITLE
On small screens/windows, Chapter/Scene do not appear in Outline pane

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#391]
Steps to Reproduce Issue:

1. Create a new project with manuskript 0.7.0 using the **Novel** template.
2. Select the **Outline** pane.
3. Notice that both the **Chapter** and **Scene** words are missing from the **Outline** pane as shown in the attached screen shot.

![screenshot_20180920_144524](https://user-images.githubusercontent.com/10405019/45846083-0d822b00-bce4-11e8-81b0-0109d4aa96a7.png)

Using these same steps with Manuskript 0.6.0 works correctly as shown below.

![screenshot_20180920_151249](https://user-images.githubusercontent.com/10405019/45847246-a6ff0c00-bce7-11e8-9a54-c77d6a626a93.png)

**Comment by gedakc** [comment]
Assuming I performed the `git bisect` steps correctly, the result is several commits to check:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
8ff046b23b0c0132f183e430a14dcfe4bf2dc952
ba4fe6b57ad4f272a0685cf0e266ba83e2ac391c
a7f668c2bfb6e1ddd2059ed54337d3fd1457d032
f945387066e73027963b23390ef2c166c0384ecd
43c82cb3c9eb10a943cbd50895f8b40214afafd0
b9e35c87097c7f20f8b8c22bcee424e96ceac5b0
64994cde3a9a9d72d3f2f004182e384b4f2ab9af
9e91fe3f2cbefb117400458ab999ecc2af88c86d
4525f23d5dab207a58f8beea44c5875a03dc3c69
9d3b64de8ff326b6756826240e73a2a575f81ca2
7db2848474546910ed6b5fcf543e5744fc2fa9b8
c2dcbf56a0111c1035583cb6acd3f28cb9db92c6
cb79e504e7c777850c570e4a9c8825c8d3c38972
f098e74f45b57fcefc94199b58a020f1afea0bc8
584b0b04a60d782fd2f1c14c90cffe6594260d57
5f68ca7efa20595761ef690c909f2b95d6f43fc4
f999d6b33da1e52b9ff2b73d70df18c90f75b275
We cannot bisect more!
```

**Comment by RiderExMachina** [comment]
I have no issues on Windows 7 with either branch.

**Comment by gedakc** [comment]
Thanks @RiderExMachina for testing on Windows 7.

Based on you feedback I tested using 0.7.0 on Windows XP.  Initially it shows a partial title for "**Chap...*" as shown below:

![screenshot_20180920_160436](https://user-images.githubusercontent.com/10405019/45849437-1fb59680-bcef-11e8-824e-48ec480b84e3.png)

However when I tried maximizing the manuskript window, the "**Chap..**" text disappeared as shown below:

![screenshot_20180920_160509](https://user-images.githubusercontent.com/10405019/45849450-3825b100-bcef-11e8-88f0-e12635e6956e.png)

I am unable to click and drag the column heading resize bars.

This leads me to believe there is an issue with column sizing on the **Outline** pane.

**Comment by RiderExMachina** [comment]
Does it happen with a brand new clone of the repository? Everything is fine on my end I downloaded straight from the repo.

**Comment by gedakc** [comment]
I tried it from both the @olivierkes repo and my own @gedakc repo and the problem persists.

Note that the issue only occurs for newly created projects.  Old projects created with a prior version of Manuskript do not exhibit this issue.  In fact the prior created project do not display the **POV** column heading so something is different.

**Comment by gedakc** [comment]
The change in behaviour I observed was introduced with the following commit.

9e91fe3f2cbef - Fixes: POV column visibility in outline is always hidden at start

**Comment by gedakc** [comment]
At first I thought this was a regression in the display graphics.  However upon further investigation it turned out that the issue was simply more prominent because now, by default, the POV column is also displayed in the **Outline** pane.  Because this was the intention of the original developer I do not plan to reverse this change.

Moreover, this issue is something that will always arise at some point when the screen space, or window size is reduced.

There are several ways that a user can work around this issue:

- Hide some of the panes (e.g., Cheatsheet, Search, Navigation) to permit more screen real estate for the **Outline** pane.
- Make the Manuskript window larger, or use a bigger monitor when using the **Outline** pane.
- Hide some of the columns in the **Outline** pane using the **Edit -> Settings -> Views -> Outline** under **Visible columns**.

![screenshot_20180921_092754](https://user-images.githubusercontent.com/10405019/45890672-c5fdac80-bd80-11e8-8a07-b03edb2cec3a.png)

Because this issue can be worked around, I will close this issue and label it as **invalid** so that it does not get included in the automatic generation of CHANGELOG.md.
