### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Kallife71** [olivierkes/manuskript#395]
I want to contribute writing Italian translation file. Send me the instructions, please! Thank you.

**Comment by gedakc** [comment]
Take a look at the [Manuskript Wiki](https://github.com/olivierkes/manuskript/wiki) for instructions on how to [Translate Manuskript](https://github.com/olivierkes/manuskript/wiki/Translate-Manuskript).

**Comment by gedakc** [comment]
Following is a screen shot of the progress of [Manuskript translations](https://hosted.weblate.org/projects/manuskript/translations/) as of Nov 21, 2018.

![manuskript-translations-20181121](https://user-images.githubusercontent.com/10405019/48856394-800a9800-ed73-11e8-86f5-77c2c45912f0.png)

It appears that 100% of the Italian translation has been completed, although there are 71.6% of checks remaining.  As such I am closing this ticket as these translation updates are planned for inclusion in the next release of Manuskript.
