### ISSUE TITLE
Information Text Hard to read

### ISSUE THREAD

**Issue by ditokp** [olivierkes/manuskript#398]
Hello, yesterday I download your app. And today I test it. I like it, but the information text in the bottom left corner is hard to read and see. This is the screenshot:
![screenshot from 2018-10-13 14-36-02_manuskript_app](https://user-images.githubusercontent.com/27815899/46904085-193ec700-cf09-11e8-90f0-b17b34cc91a7.png)

I'm using Manuskript 0.7.0 in Ubuntu 18.04.1 64-Bit

Thank you for reading my issue, and I'm sorry if my English is bad.

**Comment by ditokp** [comment]
Umm... My request for next release is, can you make that information text have black font color, so it can easy to read?

**Comment by gedakc** [comment]
The color of the text in the pop-up status bar is variable.  The color depends on the importance of the information notice.  An event such as "_saving filename.msk file_" is considered low importance and hence has a light text color.

For background information (and screen shots) on when this feature was implemented see issue #262.

**Comment by ditokp** [comment]
Thank you very much for replying my issue. Now I understand. I will close this issue.

**Comment by gedakc** [comment]
Thanks @ditokp for closing this issue.  I am marking it as **invalid** so that it does not get included in the automatic generation of the CHANGELOG.md file.
