### ISSUE TITLE
[Feature Request] Add Ability to Add Image When Creating Fullscreen Theme

### ISSUE THREAD

**Issue by ditokp** [olivierkes/manuskript#399]
When creating fullscreen theme, ada ability to add user's image as background. For now, it only can add space and table image and color.
![screenshot from 2018-10-13 17-20-41](https://user-images.githubusercontent.com/27815899/46904383-6fae0480-cf0d-11e8-8ae0-b002a122277a.png)

**Comment by tildagail** [comment]
Just a note: if you place your images in the folder .local/share/manuskript/manuskript/resources/backgrounds/ (on linux) they can be selected when creating a new fullscreen theme. I presume there would be a similar path on any other OS as well?
