### ISSUE TITLE
[Windows] Compile dialog comes with development machine default location

### ISSUE THREAD

**Issue by JoaoGFarias** [olivierkes/manuskript#40]
![default_location](https://cloud.githubusercontent.com/assets/1585655/17081651/fc37efbc-5136-11e6-8348-58da26324faa.png)

Expected to use a location relative to the project's location, since the user expects to have the files related to this project in this folder.

**Comment by olivierkes** [comment]
Fixed in 0.4.0 with new compile dialog.
