### ISSUE TITLE
pt_PT translation and Weblate

### ISSUE THREAD

**Issue by pmraps** [olivierkes/manuskript#408]
Hi,
I just made a fresh clone and some of the strings were not translated. However, my [Portuguese (Portugal)](https://hosted.weblate.org/projects/manuskript/translations/pt_PT/) translation at Weblate is at 100%.
Should I send the new file somewhere? Just in case, I'll attach it here:
[manuskript_pt_PT.ts.tar.gz](https://github.com/olivierkes/manuskript/files/2573040/manuskript_pt_PT.ts.tar.gz)

Thanks.

**Comment by gedakc** [comment]
The file from this issue has been manually downloaded and committed to the **develop** branch for inclusion in the upcoming **0.8.0** release.
