### ISSUE TITLE
[Windows] Compile operation does not adds the file extension when the file type option is changed

### ISSUE THREAD

**Issue by JoaoGFarias** [olivierkes/manuskript#41]
Steps to reproduce:
1. Save a project as HTML in a file named test.html;
2. Change the compilation type to ODT;
3. Try to compile the file as test.odt;
4. Observe the alert indicating you already have a file named test**.html** in this location.

![save_odt](https://cloud.githubusercontent.com/assets/1585655/17081654/1f842918-5137-11e6-844b-7584709c84d6.png)

**Comment by olivierkes** [comment]
The compile dialog as been completely rewritten for 0.4.0. You can try it in the develop branch.

![export-preview](https://cloud.githubusercontent.com/assets/1192933/19013182/b52489ae-87c9-11e6-9449-6a9640da5949.jpg)
