### ISSUE TITLE
manuscript closed when I try html export with Pandoc

### ISSUE THREAD

**Issue by BienveSR** [olivierkes/manuskript#415]
I have installed manuscript 0.7.0 and Pandoc 2.4 in macOS 10.13.6.
When I try html export in manuscript with pandoc, the manuscrip closed.

Regards

**Comment by gedakc** [comment]
This is a known problem and was reported previously as [Issue #304 - pandoc v2 has deprecated some options and extensions so manuskript is giving error](https://github.com/olivierkes/manuskript/issues/304#issuecomment-402535561).

The current lack of support for pandoc 2.x is mentioned on the [Manuskript Download](http://www.theologeek.ch/manuskript/download/) page under the section **Extra Export Formats**.

To work around the issue install pandox 1.x.

Closing this issue and marking it a duplicate of issue #304.

**Comment by BienveSR** [comment]
Thanks for your answer
