### ISSUE TITLE
Now, manuscrip have Spanish language dictionary

### ISSUE THREAD

**Issue by BienveSR** [olivierkes/manuskript#416]
In manuscript 0.7.0 we have dictionaries languages for de_DE; en_AU; en_GB; en_US and fr_FR.
**Now, we have also spanish language in manuscript**, for this we need myspell .aff and .dic for Spanish language.

We have two fonts that I tried and run correctly.

**First font:**

Download index.aff and index.dic (Raw) with Right-Click Select/Save how ...
[https://github.com/wooorm/dictionaries/tree/master/dictionaries/es](url)

Change "index" name to es-ES in .aff and .dic.

Put es-ES.aff and es-ES.dic in this directory:
manuscript/enchant/share/enchant/myspell/

Now, manuscript have spanish language dictionary.

**Second font:**
Download myspell-es .deb for Ubuntu trusty; xenial; bionic or cosmic here:
[https://packages.ubuntu.com/cosmic/myspell-es](url)

Change .deb extension for .zip and unzip.

Now, unzip dat.tar.

In data folder search es.aff and es.dic in this directory:
usr/share/hunspell/

Put es-ES.aff and es-ES.dic in this directory:
manuscript/enchant/share/enchant/myspell/

Now, manuscript have spanish language dictionary.

Regards

**Comment by gedakc** [comment]
Marking this as an answered **question** so that it will show up on the list of answered questions in the Manuskript Wiki.

**Comment by BienveSR** [comment]
I didn't read the wiki, is my first post in GitHub.
Thanks for your answer
