### ISSUE TITLE
Can't Open Manuskript in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ditokp** [olivierkes/manuskript#417]
I don't know why, but I can't open manuskript. I'm using Ubuntu 18.04 LTS and before I upgrade to 18.04 LTS, I can run manuskript in Ubuntu 16.04 LTS.

This is the error message:
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 28, in <module>
    from manuskript import main
  File "/usr/share/manuskript/manuskript/main.py", line 7, in <module>
    import manuskript.ui.views.webView
  File "/usr/share/manuskript/manuskript/ui/views/webView.py", line 3, in <module>
    import PyQt5
ModuleNotFoundError: No module named 'PyQt5'

Thank You very much for reading my issue.

**Comment by gedakc** [comment]
The message indicates that the PyQt5 package(s) are missing.

If you installed the [.deb package file from the download page](http://www.theologeek.ch/manuskript/download/) then be sure to follow all the steps, such as:

    sudo apt update
    sudo dpkg -i manuskript-0.7.0-1.deb
    sudo apt install -f

If you [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux) then be sure to follow all the instructions to [install required software packages](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux#install-required-software-packages).

**Comment by gedakc** [comment]
Let us know how you make out.

**Comment by ditokp** [comment]
same result. When I want to install it again. It need some dependencies, than I try install it. But, I can't install it. But in the terminal there is this command "apt --fix-broken install". I run that command. After that I try installing Manuskript again. And I can install Manuskript. But I can't open Manuskript. The error message is same.

**Comment by gedakc** [comment]
It appears that something might be amiss with the package manager.

Can you try the following command?

`sudo apt install python3 python3-pyqt5 python3-pyqt5.qtwebkit libqt5svg5 python3-lxml zlib1g python3-enchant python3-markdown pandoc`

These are the dependencies for either the binary or source package install.

**Comment by ditokp** [comment]
same result. This is the message from terminal.

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5svg5 is already the newest version (5.9.5-0ubuntu1).
python3-lxml is already the newest version (4.2.1-1).
zlib1g is already the newest version (1:1.2.11.dfsg-0ubuntu2).
pandoc is already the newest version (1.19.2.4~dfsg-1build4).
python3-enchant is already the newest version (2.0.0-1).
python3-markdown is already the newest version (2.6.9-1).
python3-pyqt5 is already the newest version (5.10.1+dfsg-1ubuntu2).
python3-pyqt5.qtwebkit is already the newest version (5.10.1+dfsg-1ubuntu2).
python3 is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by gedakc** [comment]
Can you check the md5sum checksum to see if it matches the official working file?  If it doesn't match then the downloaded file is corrupt and will need to be re-downloaded.

`md5sum manuskript-0.7.0-1.deb`

The checksum should match the following:

```
$ md5sum manuskript-0.7.0-1.deb 
92c006c86e31f28d721483f9ed79bc7b  manuskript-0.7.0-1.deb
```

**Comment by ditokp** [comment]
I'm sorry, now I moved to Lubuntu 18.04.1 LTS because Ubuntu 18.04.1 LTS slow down my laptop. I success install Manuskript in Lubuntu 18.04.1 LTS.

When I follow the install instruction in the website, I have error message about dependencies. so, I run command like this, not like the instruction in the website:
`sudo apt update`
then
`sudo apt install -f`
and then
`sudo dpkg -i manuskript-0.7.0-1.deb`

I'm really sorry, I will close this issue. Thank you very much for your hard work, and have a nice day

**Comment by gedakc** [comment]
Thank you for reporting back with how you resolved the problem and for closing the issue.  I will tag the issue as **invalid** so that it does not get picked up by our automatic CHANGLELOG.md file generation.
