### ISSUE TITLE
Snowflake Method option is greyed out.

### ISSUE THREAD

**Issue by AuroraMartell** [olivierkes/manuskript#419]
I'm running Ubuntu 18.10 and the latest version of Manuskript, and I can't access the Snowflake method option in the menu.

**Comment by gedakc** [comment]
The menu option **View ->Mode -> Snowflake** is greyed out / disabled on all Manuskript versions because it has not been implemented.

Most likely we should remove this menu option because it has caused confusion in the past as seen in issue #45.

**Comment by gedakc** [comment]
Manuskript can be used to write a novel and you can follow the Snowflake method.  It has help prompts to guide you, but does not enforce the Snowflake method.

Manuskript permits any writing method to be used.

**Comment by AuroraMartell** [comment]
Got it.

**Comment by gedakc** [comment]
The menu entry "**View -> Mode -> Snowflake**" has been removed.  This change will be included in the next release of Manuskript.
