### ISSUE TITLE
[Feature request] Spreadsheet like J.K.Rowling

### ISSUE THREAD

**Issue by nicxxx** [olivierkes/manuskript#427]
It would be great to add a scene-detailed overview like this image:

[http://harrypotter.wikia.com/wiki/File:Revision_of_the_plan_of_'Order_of_the_Phoenix.jpg](http://harrypotter.wikia.com/wiki/File:Revision_of_the_plan_of_'Order_of_the_Phoenix.jpg)

Many authors use this technique to plan every scene in detail.
For the beginning a spreadsheet with blank fields would be great.

At the moment I am switching between a Calc document and Manuskript. It would be great if it could be implemented.

**Comment by AuroraMartell** [comment]
> It would be great to add a scene-detailed overview like this image:
> 
> http://harrypotter.wikia.com/wiki/File:Revision_of_the_plan_of_'Order_of_the_Phoenix.jpg
> 
> Many authors use this technique to plan every scene in detail.
> For the beginning a spreadsheet with blank fields would be great.
> 
> At the moment I am switching between a Calc document and Manuskript. It would be great if it could be implemented.

I second this, it would be so cool.

**Comment by siliconserf** [comment]
I can see the function of the first three columns in the image linked to, but the next three are hard to make out. None the less, I can see where setting up the text files as "scene cards" to display in a spreadsheet (a text file per line display/data entry) might be useful. The downside is it is likely to require a bit of effort to code.

**Comment by nicxxx** [comment]
Thank you very much for your reply. It ist great to hear you would like the feauture, too.
In the plot section, there are "resuolution steps". This format is in the same style as a spreadsheet.
Would it be possible to just add a section with a blank spreadsheet?

Thank you very much!

![bildschirmfoto_2018-12-19_10-15-48](https://user-images.githubusercontent.com/30736145/50210689-159b4680-0377-11e9-9324-97a0cbca18ba.png)

**Comment by Eusorph** [comment]
I believe this will be achieved once we have a Timeline in the Storyline and once the world items will show up in the Storyline. Then perhaps, we could have a couple of different ways to visualize the Storyline, one of which could be spreadsheet like.

**Comment by TheJackiMonster** [comment]
This issue seems to be contained in the with the features requested in #118. So I'm closing this as duplicate.
