### ISSUE TITLE
Chinese translation filename suffix

### ISSUE THREAD

**Issue by lingsamuel** [olivierkes/manuskript#428]
![image](https://user-images.githubusercontent.com/14567045/49506952-5ea0c480-f8ba-11e8-8e07-082594ce496c.png)
I noticed that manukript loads the translation `manuskript_zh_CN`, but the current translation filename is `manuskript _zh`.
Maybe that's because there are two type of Chinese, Chinese(Simplified) which is translated in Weblate called `zh_CN` and Chinese(Traditional) called `zh_TW` (or `zh_HK`). In operating system, they will use code like `zh_CN` or `zh_TW` instead of just `zh`.

**Comment by gedakc** [comment]
I'm not overly familiar with how Weblate works, but perhaps the base translation file was created with only the `_zh` suffix?

From a quick look at the Manuskript source code it appears that there are two Portuguese translations: [`_pt_BR`](https://hosted.weblate.org/projects/manuskript/translations/pt_BR/), and [`pt_PT`](https://hosted.weblate.org/projects/manuskript/translations/pt_PT/) so it seems it should be possible to have both `_zh_CN` and `_zh_TW`.

Can you create a new translation using the proper suffixes raised in this issue?

**Comment by lingsamuel** [comment]
Created: #430
