### ISSUE TITLE
[Enhancement] Export UTF-8

### ISSUE THREAD

**Issue by lingsamuel** [olivierkes/manuskript#432]
I found that exported files with Chinese characters will be encoded by GBK, that's bad.

**Comment by gedakc** [comment]
Manuskript version 0.8.0 released yesterday included an enhancement to use UTF-8 with compile / export.  See issue #331 and pull request #340.

Does the previous issue and PR address the problem, or is this issue about something else?

**Comment by lingsamuel** [comment]
Yes I am 0.8, I don't know why it happens, I will try to found the reason.

**Comment by gedakc** [comment]
Thank you @lingsamuel for closing this issue.  I will label it as **invalid** so that it does not get included in the generated CHANGELOG.md file when we create the next release.
