### ISSUE TITLE
crash on create new project

### ISSUE THREAD

**Issue by fake-fur** [olivierkes/manuskript#44]
hi

i git cloned and installed the dependencies on debian stretch running gnome 3.20

every time i try to create a new project the software crashes out with some kind of template error

`Traceback (most recent call last):
  File "/home/lauren/manuskript/bin/../manuskript/ui/welcome.py", line 159, in createFile
    self.loadDefaultDatas()
  File "/home/lauren/manuskript/bin/../manuskript/ui/welcome.py", line 344, in loadDefaultDatas
    t = [i for i in self.templates() if i[0] == self.template[0]]
  File "/home/lauren/manuskript/bin/../manuskript/ui/welcome.py", line 344, in <listcomp>
    t = [i for i in self.templates() if i[0] == self.template[0]]
IndexError: list index out of range
Fatal Python error: Aborted

Current thread 0x00007ffad5fb3700 (most recent call first):
  File "/home/lauren/manuskript/bin/../manuskript/main.py", line 72 in launch
  File "/home/lauren/manuskript/bin/../manuskript/main.py", line 63 in run
  File "./manuskript", line 13 in <module>
Aborted
`

**Comment by william01110111** [comment]
I'm having the same issue.

**Comment by william01110111** [comment]
I've figured something out. If you just hit create, or you select a template and then click create it crashes when you save. However, if you double click on a template the UI slightly changes and then it successfully saves without crashing.

before properly selecting template (it will now crash if you try to create and save):

![bad](https://cloud.githubusercontent.com/assets/9331264/18403682/0d84f420-769b-11e6-9b6b-528bc766a98d.png)

after double clicking on 'Empty fiction' (it will now work):

![good](https://cloud.githubusercontent.com/assets/9331264/18403703/3a927c94-769b-11e6-8e74-5245f69a3973.png)

**Comment by olivierkes** [comment]
Thanks for pointing that. I guess Qt's signals for "activate" work differently on gnome or kde. I need to investigate that.

**Comment by olivierkes** [comment]
Can you try the develop version now?

**Comment by william01110111** [comment]
@olivierkes I just tested from develop branch. It now works as it should. Single click selects template and it doesn't crash even if you don't select anything. Thanks.

**Comment by olivierkes** [comment]
Thanks!
