### ISSUE TITLE
[Feature request] Standard character fields

### ISSUE THREAD

**Issue by scribas** [olivierkes/manuskript#442]
Hiveword.com has a pretty extensive set of character fields:

- Basics (First Name, Middle Name, Last Name, Alias, Type, Importance, Gender, Occupation, Sexual Orientation)
- Physical (Age, Height, Weight, Eye Colour, Hair, Race, Appearance)
- Psychological (Religion, Wants, Likes, Dislikes, Fears, Personality, Habits)
- Miscellaneous (Birthday, Place of Birth, Home Town, Date of Death, Place of Death, Cause of Death, Financial, Family, Unusual Aspects, Education, Back Story, Hobbies, Miscellaneous Notes).

Now, I realise that I could add all of these under the Detailed Info tab, but that is quite a lot of work for every character. Any chance of including such a standard template? Additionally, it would be quite helpful, if we could upload an image for every character (like an avatar). 

This also applies for the Plots, World (or rather items?) and Editor environments - being able to add images and maybe hyperlinks to some articles, especially if one wants to mark a page as research. Unless this already exists with some Markup capability?

**Comment by scribas** [comment]
Oops, I just tried Markdown and was able to add a variety of formatting, including images and hyperlinks into my text. Very cool. Pity that the extended markup for tables and to-do lists doesn't work, but this is already great. One thing that is a bit weird, is that numbered lists still only appear as bullet items? Not really a train smash though.

**Comment by gedakc** [comment]
An editable character template or free form space makes sense to permit flexibility when describing characters.  There is a discussion about this in issue #252 that ranges from fixed fields all the way to a free form page that uses markdown highlighting for the fields.  Unfortunately there is no consensus on how this should be implemented.

Regarding numbered lists and extended markdown tables what isn't working?

Following is an example of markdown highlighting in Manuskript:

![manuskript-markdown-example](https://user-images.githubusercontent.com/10405019/50237423-1bdef200-037a-11e9-8f11-f8e32f42451d.png)

**Comment by scribas** [comment]
Ah, yes, I had not yet installed Pandoc. Only previewed with html. Will play a little more. 

I saw the discussion on 252. I like the idea of having a config file, where one can configure the fields in the template. Maybe it can come pre-populated with something along the line of the above I mentioned as the default behaviour, with the option of users customizing it according to their own needs. Then reuse this functionality for some of the other tabs as well. That would be pretty powerful.

**Comment by gedakc** [comment]
I use GNU/Linux and documented the packages for PDF export at [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux#install-pandoc-for-more-compileexport-formats).

If you figure out what packages are required for PDF export on Windows, then please update [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows).

**Comment by jyhelle** [comment]
Hi to all,
Newcomer to Manuskript, I previously used OpenOffice Calc then oStoryBook to write several shorties and a longer (230 pages) piece.
I too would like to have sets of custom fields for characters, I don't know if I should rather put this one under the #252 item ?
I tried entering several fields for a given character then copy-paste them to another, but naught
I presently use 4 different models of cardboard cards that contain from 60 to 130 custom fields to describe my chars and I was thinking about some user-defined "templates" that we could choose to apply when creating a new character.
The way I imagined it was using some Comma Separated Format, so one can use the same templates to-from a spreadsheet (my current method for producing the cards) without restricting the user to a single spreadsheet program ...

**Comment by scribas** [comment]
Hi @jyhelle, I ended up using the free textbox area inside the Notes tab. Easy enough to quickly copy and paste to each character:
##Basics
- First Name:
- Middle Name:
- Last Name:
- Aliases:
- Type: Protagonist / Antagonist
- Importance: Major / Minor
- Gender: Male / Female
- Sexual Orientation:

##Physical
- Age:
- Height:
- Weight:
- Eye Colour:
- Hair:
- Race:
-Appearance:

##Psychological
- Religion:
- Wants:
- Likes:
- Dislikes:
- Fears:
- Personality:
- Habits:

##Miscellaneous:
- Birthday:
- Place of Birth:
- Home Town:
- Date of Death:
- Place of Death:
- Cause of Death:
- Financial:
- Family:
- Unusual Aspects:
- Education:
- Back Story:
- Hobbies:
- Miscellaneous Notes:

**Comment by jyhelle** [comment]
thanks @scribas , it's true that solution is easy and k.is.s. 
I probably was too much attached to my spreadsheet solution and missed the obvious !

**Comment by TheJackiMonster** [comment]
So because there seems to be a solution to the problem, I would close this issue.
