### ISSUE TITLE
[Feature Request] Keyboard shortcuts in Full-Screen mode

### ISSUE THREAD

**Issue by scribas** [olivierkes/manuskript#444]
When in full-screen mode, it would be helpful if there was a way to flip between pages already created, without having to leave full-screen mode. Something like PAGE-UP and PAGE-DOWN? Or CTRL-SHIFT-LEFT and CTRL_SHIFT-RIGHT?

Additionally, maybe a button in the top or bottom hidden menus, that let's you flip into a mode, where the markdown is already executed (like a Read-Only Preview Mode).

**Comment by gedakc** [comment]
With the merge of Pull Request #509, navigation between scenes can be performed by a visual drop down menu, and can also be done using Alt+Page-Up, Alt+Page-Down or Alt+Left and Alt+right
shortcuts.
