### ISSUE TITLE
Where are the configuration settings stored?

### ISSUE THREAD

**Issue by scribas** [olivierkes/manuskript#446]
Hi, I switched to dark theme inside my linux installation. Now only the File Menu still works and is completely black.

Where is the config file located for the them and what should I change to put it back on the default theme?

**Comment by gedakc** [comment]
The location for changing the theme is dependent upon the GNU/Linux distribution and window manager in use.

For example on my Kubuntu 16.04 the theme can be changed at:
**K -> Settings -> System Settings -> Workspace Theme**.

**Comment by scribas** [comment]
Apologies, I was not very clear - I changed to one of the dark themes within Manuskript on a Linux Mint installation. I am unable to change it back, as the menus become unresponsive. I tried uninstalling Manuskript and reinstalling it, however, it stays set to the broken theme. Is there a config file, where I can change it back and what is the default value.

**Comment by gedakc** [comment]
Thank you @scribas for clarifying your question.  I have updated the title accordingly.

To the best of my knowledge the configuration settings for Manuskript are stored in the following locations.

# Configuration Settings Storage Locations

## GNU/Linux

Files:
- ~/.config/manuskript/manuskript.conf
- ~/.config/manuskriptrc

Directory:
- ~/.local/share/manuskript

## Mac OS X:

Files:
- ~/Library/Preferences/com.manuskript.manuskript.plist
- ~/Library/Preferences/ch.theologeek.www.manuskript.plist
- ~/Library/Preferences/manuskript.plist

See also issue #314.

## Windows

Registry Hive:
- HKEY_CURRENT_USER/Software/manuskript/manukskript

On GNU/Linux and Windows I have tried deleting these files / registry hive locations and by doing so I was able to reset Manuskript back to the default settings on the next startup of Manuskript.

Does that answer your question?

**Comment by scribas** [comment]
Yes, it does, thank you! I actually found the config file earlier today.
Turns out that there are a couple of the style options that, at least on
Linux Mint, crash Manuskript, or make it unusable (bb10dark, bb10bright,
motif, plastique, etc). I found that removing the style line in the config
file resets the style to default Fusion. Gtk2 seems to align the style
closest to the Linux theme, as far as I can see.

Also, interestingly, if I start Manuskript from command line, either as
root or normal user, only Fusion and Windows styles remain as options.

**Comment by gedakc** [comment]
Thanks for reporting back that you were able to reset the configuration.  As such I will close this issue.

If you are able to gather a console log and/or GNU debug output for the crash you mentioned then please feel free to create a new issue and include that information along with the steps to reproduce the problem.
