### ISSUE TITLE
missing packages? upquote ...

### ISSUE THREAD

**Issue by j2l** [olivierkes/manuskript#447]
Tout d'abord, bravo et merci pour ce fantastique outil. Que Dieu vous bénisse !

I'm not sure if it's manuskript or PanDoc since I wanted to test output formats directly I installed PanDoc and got multiple messages like this one:
![image](https://user-images.githubusercontent.com/65325/50446908-d3927780-0917-11e9-9fb6-489a5fa6628e.png)
After clicking Install button it worked fine though.

**Comment by gedakc** [comment]
Thanks for posting a screen shot along with your report.

It appears to reference "*tex*" which is a requirement for exporting to PDF using pandoc.  This is not a requirement for Manuskript which can be used without pandoc.

Does that answer your question?

**Comment by j2l** [comment]
Happy new year!
Yeah, it's ok, thx

**Comment by gedakc** [comment]
Labeling this as **invalid** so that this issue does not get included in the automatic generation of the CHANGELOG.md file.
