### ISSUE TITLE
Snowflage view mode always disable

### ISSUE THREAD

**Issue by taophp** [olivierkes/manuskript#45]
There is a entry in the menu View/Mode name "Snowflag" that is disabled. I expect this to be related with the Snowflake method and the novel assistant (if not, where is it?). I was curious to test it, but I can figure how to activate it.

**Comment by olivierkes** [comment]
The Snowflake mode is not implemented yet from a user point of view. You can use it if you know the snowflake method (the software was designed with that idea in mind), but manuskript is not yet able to guide you through it. Because there are more important issues at hand first :)

**Comment by taophp** [comment]
OK. Fine for me.
