### ISSUE TITLE
Font size change doesn't work in full screen mode

### ISSUE THREAD

**Issue by gbelbe** [olivierkes/manuskript#452]
I can change font size on EDIT / SETTINGS / VIEWS / Text Editor, but it doesn't  change anything on full screen mode. On Settings / FullScreen there is no option for font size change.
If you know where i could modify it in a template file, that would be helpful, as i write with a notebook with a high resolution and text appears very small...

Thanks for your help

**Comment by gedakc** [comment]
The font-size is stored in the respective fullscreen theme files.  Hence to change the font-size, edit the theme file.

For example if you [Run Manuskript from Source Code](https://github.com/olivierkes/manuskript/wiki#install-source-code-more-work-runs-on-more-os-platforms) then to change the font size in the **Gentle Blues** fullscreen theme, edit [`resources/themes/gentleblues.theme#L39`](https://github.com/olivierkes/manuskript/blob/4ff84d328d9bde98fc16de0e39c1786e3b44a436/resources/themes/gentleblues.theme#L39) to include a different font-size.

Change From:
`Font="Times New Roman,12,-1,5,50,0,0,0,0,0"`

To:
`Font="Times New Roman,20,-1,5,50,0,0,0,0,0"`

Does that help?

**Comment by gedakc** [comment]
Recently I discovered that Manuskript already has native support for changing the font size in **Fullscreen** mode for user created **Fullscreen** themes..

1. Select **Edit -> Settings -> Fullscreen**.

2. Choose a theme that you created.  For example "**New theme**".

3. Click **Edit** button.

4. Click on **Window Background** drop-down menu and select **Text Options**.
![manuskript-settings-fullscreen-text-options-font-size](https://user-images.githubusercontent.com/10405019/53759034-9fd64f80-3e7c-11e9-89b0-d787416d7a87.png)

5. Change **Size** value.  For example "20".

6. Click **Apply** button.

The change in font size should be apparent the next time **Fullscreen** mode is activated.
