### ISSUE TITLE
select which monitor in full screen mode

### ISSUE THREAD

**Issue by bartart3d** [olivierkes/manuskript#456]
I use two monitors and currently by default the second monitor is selected for full screen distraction free editing.
But I'd like to change that, use the first monitor for full screen. I haven't found any setting to configure this. 
Maybe I've overlooked it, if not, it would be good to see such an option.

thanks,
Bart

**Comment by skle46** [comment]
I do not use dual screens, so I haven't tested this myself. 

Is your second monitor marked as the primary monitor?

A few tests I would like to have happen:

1. Open ManuSkript in your primary screen.
2. Open full screen.
3. What screen does full screen appear?

1. Open ManuSkript in your primary screen.
2. Move the window to your secondary screen.
3. Open full screen.
4. What screen does full screen appear?

**Comment by obw** [comment]
I have also dual Monitor, I use following Trick, make the main window of Manuskrit smaller(Not full screen), move it too the screen where I want the 'full screen distraction free editing', then move the Main window to the othe Screen, I use this trick to lookup Person or World Infos while writing.

Would be nice to have a Option too say, 'full screen distraction free editing' goes to Screen 'X'. Better Support for multi display would be a nice Goody.

I know we have possibilities for lockup of some of the Data, but I use a lot of Details, Notes and so on. Which are not visible in the 'Cheat Sheet'

**Comment by bartart3d** [comment]
Hi all, 
thanks for the replies, sorry for for the mega long delay.. 

The terminology about multi-monitor use is confusing. There is a difference between the primary/secondary **monitor** in terms of hardware and primary/secondary **display**, which is the software side describing which is the primary to use, e.g. where Gnome Shell placing the desktop elements (top bar, side bar) . A _primary display_ can be placed on the _secondary monitor_ (which is the case here).

With all the tests I've done, no matter which monitor I use as primary display and no matter on which display I launch Manuskript, the full-screen editor always launches on the **secondary monitor**.

I think other behavior might be caused by the OS or display manager in use. Here it's Gnome on ubuntu 19.10 by now.

I hope this helps to find a solution :-)

**Comment by TheJackiMonster** [comment]
Would be interesting to know whether it's still a problem with other DEs? Have you tried KDE Xorg or GNOME? Because maybe that's an issue of the DE.

**Comment by ShaddyDC** [comment]
I'll try that next time I log out and can probably get back to you on that tomorrow

**Comment by ShaddyDC** [comment]
I tested it on another machine with KDE Manjaro. With X11, it correctly opened on the screen that the window had already been open on. On Wayland, it always opened on the same screen, no matter where the original window had been.  
I suspect it may be related to the increased focus on privacy and security in Wayland that doesn't allow you to get window positions as easily, but I have looked into neither that nor how exactly it's implemented here.

**Comment by TheJackiMonster** [comment]
> I tested it on another machine with KDE Manjaro. With X11, it correctly opened on the screen that the window had already been open on. On Wayland, it always opened on the same screen, no matter where the original window had been. I suspect it may be related to the increased focus on privacy and security in Wayland that doesn't allow you to get window positions as easily, but I have looked into neither that nor how exactly it's implemented here.

Thanks for testing. I'm using GNOME with Wayland and it worked back then when I applied the fix. So I would assume this is specific to KDE Wayland but it could still depend on something else. To be sure you would probably need to test with another DE.
