### ISSUE TITLE
Unable to type the "ê" character

### ISSUE THREAD

**Issue by taophp** [olivierkes/manuskript#46]
I am unable to type the "ê" character, which required to type the "^" character first and then the "e" on the French azerty keyboard: nothing happens then. I suppose the same problem occurs with "î,û,n,â,ï,ë,ä,ö", but I have not tested. I never meet this problem with any software.
I use the last dev branch of manykript on Ubuntu 16.

**Comment by olivierkes** [comment]
That's strange, it works on my side (last dev branch, on Ubuntu 14.04).
Is it in all text fields or only some?

**Comment by taophp** [comment]
Sorry, it seems to have been a temporary bug during my working session. Strangely, it did not occur with other apps. But I cannot reproduce today.
