### ISSUE TITLE
New level 'unit' is reset

### ISSUE THREAD

**Issue by worstje** [olivierkes/manuskript#468]
While trying to create a project for an existing work-in-progress of mine, I tried to configure it to use 100 Chapters of 1,000 words to simplify importing all of it.

But no matter what I do, when the file is created, I end up with 'Something 1' thru 'Something 100'.

It isn't the end of the world, but it did have me recreate a couple of times trying to figure out if I was the stupid one for not properly adjusting the default 'Something' text. I did note that specifying a word count would reset the unit back to 'Something', but even after putting in 'Chapter' as the last thing before hitting the Create button would not let the text stick around.

I am trying out Manuskript for the very first time on Windows, so I am just using the official 0.8.0 release.

Manuskript looks quite promising so far, so thank you for creating it!

**Comment by gedakc** [comment]
Thanks @worstje for your interest in Manuskript.

I was able to confirm the issue with the name being reset to "Something" upon creation.

For example I tried creating an **Empty fiction**:

![manuskript-before-create-empty-fiction](https://user-images.githubusercontent.com/10405019/52225919-c8acfa00-2868-11e9-8f9c-45ebd91a62e0.png)

And in the project created, "Something Chapters" was reset to "Something":

![manuskript-after-create-empty-fiction](https://user-images.githubusercontent.com/10405019/52225935-debaba80-2868-11e9-9c04-c3185fbf61fa.png)

In Manuskript note that the base level is a "text" or scene in fiction terminology.  If you wish Chapters "folders" containing Scenes "texts", then you would need to create at least two levels.

For more tips, see the [Manuskript Wiki](https://github.com/olivierkes/manuskript/wiki) and a tutorial I wrote called [Using Manuskript to Write a Fiction Novel](http://gedakc.users.sourceforge.net/display-doc.php?name=manuskript-novel-writing).

**Comment by worstje** [comment]
Thank you. I am sure I'll learn the proper terminology in time; I just wanted to make sure to report the bug now before I'd forget about it.

As for the tips and tutorial, thank you for writing them and I will surely look at them at some point. For now I feel a lot more productive trying to input the notes of 100k words of written story just to see what I'll end up with. I have no proper foundation and have approached plotting my own unique way while writing until this point, so doing things for myself and bumping my head seems to be the easier route for me right now. Monkey see, Monkey do, Monkey stumbles, Monkey tries again. That's me. ;-)

**Comment by gedakc** [comment]
You might be interested in Manuskript's import capability for splitting up an existing written work into chapters and scenes. See [Issue 200 - Adds: Importer (docx, html, opml, …)](https://github.com/olivierkes/manuskript/issues/200).

The import feature is relatively new and has not been extensively tested.

**Comment by worstje** [comment]
Ooh, that sounds useful. I'll have to see if I can abuse it to auto-generate the really rough structure I've been following. (Which is unfortunately also hamstrung with exceptions.)

If I run into bugs or problems with it, I'll open an issue or comment wherever relevant. :-)

**Comment by gedakc** [comment]
@worstje would you like to test PR #587 before I merge it with the **develop** branch?

**Comment by gedakc** [comment]
This issue is resolved with PR #587 which has been merged with the **develop** branch.

**Comment by worstje** [comment]
@gedakc Whoops, sorry! I had totally forgotten you asked this. I really should not be browsing about while trying to fall asleep on my phone. 😊
