### ISSUE TITLE
Missing GUI objects in AUR package

### ISSUE THREAD

**Issue by gmish27** [olivierkes/manuskript#471]
I installed from AUR and found the GUI has missing objects such as:

1. Missing widgets in 'fiction' view on LHS of the layout
2. Missing buttons across layout - like +/- missing for adding characters

Also, changing the windows style simply crashes the tool. Below is a console log I obtained after chainging the layout to QT-style:

Debug: Web rendering engine used: QWebView
qt5ct: using qt5ct plugin
Running manuskript version 0.8.0.
Note: No translator found or loaded for locale en_US.
qt5ct: D-Bus global menu: no
Loading: /opt/manuskript/sample-projects/book-of-acts.msk
Detected file format version: 1. Zip: False.
Project /opt/manuskript/sample-projects/book-of-acts.msk loaded.
Traceback (most recent call last):
  File "/opt/manuskript/bin/../manuskript/ui/views/outlineDelegates.py", line 316, in sizeHint
    s = qApp.style().sizeFromContents(QStyle.CT_ItemViewItem, opt, QSize())
TypeError: sizeFromContents(self, QStyle.ContentsType, QStyleOption, QSize, QWidget): not enough arguments
Fatal Python error: Aborted

Current thread 0x00007f5db110f600 (most recent call first):
  File "/opt/manuskript/bin/../manuskript/settingsWindow.py", line 315 in setStyle
  File "/opt/manuskript/bin/../manuskript/main.py", line 89 in launch
  File "/opt/manuskript/bin/../manuskript/main.py", line 102 in run
  File "/usr/sbin/manuskript", line 13 in <module>
zsh: abort (core dumped)  manuskript

**Comment by gmish27** [comment]
Apparently, running the application as ROOT fixes the problem.

**Comment by gedakc** [comment]
Problems with the [Manuskript AUR package](https://aur.archlinux.org/packages/manuskript-git/) should be directed to the persons responsible for the ArchLinux User Repository.
