### ISSUE TITLE
Spellcheck On/Off setting ignored / Manuskript unresponsive

### ISSUE THREAD

**Issue by madeonearth** [olivierkes/manuskript#474]
Manuskript 0.8.0 Win 10 64 4GB / OS X El Capitan 4GB

When the spellcheck is turned Off in the main menu Manuskript ignores that setting depending on from where you open a new tab. When you open tabs from the search results or the cheatsheet the spellcheck is On no matter what the setting is. Same when you reopen tabs or hold cmd key down.

Text view in the Root tab with the whole text from the sample project selected (13.088 words) it takes over a minute to open with the spellcheck turned On. Manuskript is unresponsive till the text is fully loaded. Again spellcheck is On even though turned Off in the main menu.
Editing is near impossible with a long text and spellcheck turned On. As soon as you scroll the text Manuskript is unresponsive again.

With the spellcheck turned Off evreything works fast and relieable. 
Spellcheck is just always coming back On.

Please also read my post regarding the searchbox where I have mentioned this behaviour:
(https://github.com/olivierkes/manuskript/issues/376#issuecomment-460396349)

**Comment by gedakc** [comment]
Problem confirmed.

Steps to reproduce (I used an existing project with at least two scenes):

1. Disable **Tools -> Spellcheck** (verify that spellcheck is not enabled).
2. Select the **Editor** pane and a scene.
3. In the **Search** pane type in a word that exists in a different scene and press **Enter**.
4. In the **Search** pane click on a search entry that is not the currently displayed scene.

Notice that spellcheck **is** enabled in the newly displayed scene.
