### ISSUE TITLE
trying to get pandoc to work manuskript 0.8.0 Win10 64

### ISSUE THREAD

**Issue by madeonearth** [olivierkes/manuskript#475]
I am trying to get pandoc to work with manuskript 0.8.0 on Win10 64
So far I tried pandoc-1.19.2.1 and above with no success. 
Manuskript and the Dos window crash as soon as preview or export is clicked. I tried several settings. 
I have tried windows-i386 and windows-x86_64 versions.
Manuskripts own export works fine!
Also the Manage Exporters window is off the desktop to the left and top so the user can not get a grip on the window to move it. The exporters options are hidden this way.

**Comment by gedakc** [comment]
Can you try creating a sample project with only a simple scene or two and try to compile / export it using pandoc?

That will help to identify if the problem originates with the content of your project or not.

Also you might try using Manuskript's built-in in compile / export to Markdown.  Then using that file try running pandoc from the command line.

That will help to identify if pandoc is able reformat your project content.

**Comment by madeonearth** [comment]
\Manuskript\pandoc-1.19.2.1>pandoc -s -o output.html test.md

successfully created my one sentence test file that I generated with Manuskript build in markdown export from a new project!!
I tried granting exclusive administrative rights for manuskript and pandoc but it did not make any difference. I am quite clueless what to do next!?

**Comment by gedakc** [comment]
Using the one sentence project, can you try the export in Manuskript and select the pandoc HTML option?

If this crashes, then open a command prompt, run manuskript from the command line and perform the steps that cause the crash.  Then copy the log output from the command prompt into this report.

**Comment by madeonearth** [comment]
Thanks for walking me through this ...

C:\Manuskript\080>manuskript.exe
Debug: Web rendering engine used: QWebView
Running manuskript version 0.8.0.
Found translation in settings: C:\Manuskript\080\i18n\manuskript_de.qm
Loaded translation: C:\Manuskript\080\i18n\manuskript_de.qm.
Loading: C:/Manuskript/080/test.msk
Detected file format version: 1. Zip: False.
Project C:/Manuskript/080/test.msk loaded.
Traceback (most recent call last):
  File "manuskript\ui\exporters\exporter.py", line 107, in export
  File "manuskript\exporter\manuskript\plainText.py", line 94, in export
  File "manuskript\exporter\pandoc\abstractPlainText.py", line 41, in output
  File "manuskript\exporter\pandoc\__init__.py", line 79, in convert
  File "subprocess.py", line 859, in __init__
  File "subprocess.py", line 1114, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

C:\Manuskript\080>

**Comment by gedakc** [comment]
The console log helps a lot.

The following line seems to indicate that the **pandoc** executable can not be found in the system path.

```
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

Did you follow the installation instructions for Windows on the following [Pandoc - Installing](https://pandoc.org/installing.html) page?

> Windows
>
> - There is a package installer at [pandoc’s download](https://github.com/jgm/pandoc/releases/latest) page. This will install pandoc, replacing older versions, and update your path to include the directory where pandoc’s binaries are installed.


If so then it should have updated the **PATH** environment variable on your computer to include the directory where pandoc's binaries are installed.

Otherwise you could manually add the location to the **PATH**.

**Comment by madeonearth** [comment]
In the Manage Exporters window the path to pandoc is set, the version is identified, status is custom!
How else would I set the PATH manually?

**Comment by gedakc** [comment]
What is the custom pandoc path set to in the Manage Exporters window?

For example on my Windows XP Virtual Machine is was automatically set to:

```
C:\Program Files\Pandoc\pandoc.EXE
```

To manually set the path before executing manuskript you could open a command prompt and add to the path with a command similar to:

```
set PATH=C:\My New Path to Binaries;%PATH%
```

**Comment by madeonearth** [comment]
Setting the path variable finally did the trick. 
Pandoc did not take care of the propper character encoding though. The German Umlaute ä ö ü all show messed up!!
About the custom pandoc path where I installed pandoc to, I was referring to this window:

![exporters](https://user-images.githubusercontent.com/47332487/52375406-e0020800-2a5f-11e9-9ccb-dae9e8239ed6.jpg)

Well I guess Manuskript is not too happy with that. I will install to the default location so I don't have to set the path manually.

Thank You very much though ...
I wouldn't have figured out this one on my own.

Did You see my question abou the Manuskript search?

https://github.com/olivierkes/manuskript/issues/474#issue-407005988

I am just curious if it there really is not meant to be any visual indication within the text regarding the occurance of the search phrase!?

**Comment by gedakc** [comment]
'Glad to hear that Manusrkipt on your computer can now find pandoc.

If you are experiencing a problem with German Umlaute ä ö ü being messed up then it would help if you can create a new issue with sample text and steps to reproduce the issue.

> Did You see my question about the Manuskript search?

Yes, but I can only work on a limited number of issues at a time. :-)

Shall we close this issue as resolved?

**Comment by madeonearth** [comment]
Umlaute are fine after second attempt!!
Don't know why it works now ...
Glad it does though ;-)

YES .. we can close it

Thanks again
