### ISSUE TITLE
Crash when deleting folder with files in tree view

### ISSUE THREAD

**Issue by madeonearth** [olivierkes/manuskript#479]
**Manuskript 0.8.0 Win 10 64 4GB**

Manuskript crashes when you try to delete a folder in treeview that contains files.

> C:\Manuskript\080>manuskript.exe
> Debug: Web rendering engine used: QWebView
> Running manuskript version 0.8.0.
> Found translation in settings: C:\Manuskript\080\i18n\manuskript_de.qm
> Loaded translation: C:\Manuskript\080\i18n\manuskript_de.qm.
> Loading: C:/Manuskript/080/test.msk
> Detected file format version: 1. Zip: False.
> Project C:/Manuskript/080/test.msk loaded.
> Project test.msk saved.
> Project test.msk saved.
> Project test.msk saved.
> Traceback (most recent call last):
>   File "manuskript\models\abstractModel.py", line 125, in parent
>   File "manuskript\models\abstractItem.py", line 124, in row
> ValueError: <manuskript.models.outlineItem.outlineItem object at 0x05D7B870> is not in list

**Comment by gedakc** [comment]
Would you be able to provide a list of steps to recreate the problem?

So far I have been unable to recreate the crash.

I have tried the following:

1. Create a new Manuskript project using the **Novel** template
2. Select the **Outline** pane
3. Select **Chapter 2**
4. Click the red minus sign icon near the bottom of the pane
5. Click **Yes** when asked to confirm "You're about to delete 1 item(s)"

In my case I noted that **Chapter 2** and the scenes within were all deleted.  There was no crash.

**Comment by madeonearth** [comment]
Following your steps at first I wasn't able to recreate myself.
I was allready starting to get nervous but finally after I changed the view from 'index cards' to 'text' with the bottom cmdButtons I was able to reproduce the crashes.
I noticed different values for the Error:


ValueError: <manuskript.models.outlineItem.outlineItem object at 0x05D50C30> is not in list
ValueError: <manuskript.models.outlineItem.outlineItem object at 0x05D42C90> is not in list
ValueError: <manuskript.models.outlineItem.outlineItem object at 0x05D81AD0> is not in list
ValueError: <manuskript.models.outlineItem.outlineItem object at 0x05D43B90> is not in list
ValueError: <manuskript.models.outlineItem.outlineItem object at 0x05C8B610> is not in list

While I am at it what is the tab button 'open selected items in that view' next to the 'split' button for? In whatever state of Manuskript I use it I can not note any difference!?

**Comment by madeonearth** [comment]
Reopening the same project after the crash the folder and scenes are not deleted!

**Comment by gedakc** [comment]
Following are the set of steps which reproduce the crash using Manuskript 0.9.0.

1. Create a new Manuskript project using the **Novel** template
2. Select the **Editor** pane
3. Select **Chapter 2**
3. Change view from _Index cards_ to _Text_ using bottom cmdButtons.
4. Click the red minus sign icon near the bottom of the pane
5. Click **Yes** when asked to confirm "_You're about to delete 1 item(s)_"

Crash confirmed on Kubuntu 16.04 with Manuskript 0.9.0.

**Comment by gedakc** [comment]
This issue has been resolved in the **develop** branch and will be included in the next release of Manusrkript.
