### ISSUE TITLE
Inconsistent and/or undesirable window placements

### ISSUE THREAD

**Issue by worstje** [olivierkes/manuskript#481]
_A small thing turned kinda big in issue 470, so as requested a separate issue for the observed behaviour ( https://github.com/olivierkes/manuskript/issues/470#issuecomment-460823331 )_

As it turns out, there are a lot of ways to do window placement. The way the QT5 library appears to behave differs considerably across Linux/Windows, and my particular observations were made on Windows 10.

Based on observations using Windows 10, the various windows can be put into a few different groups:

**F6 - Compile:** No respect for screen edges.
**F7 - Import:** No respect for screen edges.
**F8 - Settings:** Centered on top of main window.
**Help -> About:** No respect for screen edges.
**Organize -> Split**: Centered on top of main window.
**Tools -> Frequency Analyser:** Centered on the primary monitor(?)

_These classifications may not necessarily be correct; I basically drew the screen and window diagonals on my screenshots to reach these conclusions._

According to @gedakc, window placement is considerably different on Kubuntu 16.04.

**_This behaviour is not desirable; ideally all the modal / dialog windows act identically in a manner that agrees with the standard behaviours of the operating system in question._**

> 
> 
> **Appendix: Screenshots** _(Windows 10)_
> 
> Of particular note on the Windows 10 screenshots supplied by me in this issue is that I have two monitors: my primary monitor (1) is the larger 2560x1440 one situated on the **right** side, whereas my secondary monitor (2) is the 1920x1080 on the **left** side.
> 
> Also note that the following screenshots were based off the -test2 build at https://github.com/olivierkes/manuskript/issues/470#issuecomment-461125961 ; the fix in it was not appropriate but because the screenshots themselves still demonstrate the various 'approaches' of window placement on Windows 10, I haven't repeated the effort.
> 
> **F6 - Compile:** Cut off at the top.
> ![manuskript-test2-f6](https://user-images.githubusercontent.com/399950/52414811-98be5a80-2ae5-11e9-9b7f-efed36855e4a.png)
> 
> **F7 - Import:** Cut off at the top.
> ![manuskript-test2-f7](https://user-images.githubusercontent.com/399950/52414916-e1761380-2ae5-11e9-9620-fa608b24da82.png)
> 
> **F8 - Settings:** Appears to be centered on top of main window.
> ![manuskript-test2-f8](https://user-images.githubusercontent.com/399950/52414927-ed61d580-2ae5-11e9-8133-92a18695c841.png)
> 
> **Help -> About:** Cut off at the top.
> ![manuskript-test2-help-about](https://user-images.githubusercontent.com/399950/52414984-18e4c000-2ae6-11e9-829b-42bb0754cbd0.png)
> 
> **Organize -> Split**: Appears to be centered on top of main window.
> ![manuskript-test2-organize-split](https://user-images.githubusercontent.com/399950/52415460-4aaa5680-2ae7-11e9-95d8-25a0b84ddda6.png)
> 
> **Tools -> Frequency Analyser:** Appears to be centered on the primary monitor (right screen).
> ![manuskript-test2-tools-frequency-analyser](https://user-images.githubusercontent.com/399950/52415000-2732dc00-2ae6-11e9-975c-08f070f2cc12.png)
> 
> **Appendix: Screenshots** _(Kubuntu 16.04)_
> 
> @gedakc shared a screenshot of the Frequency Analyser window on Kubuntu 16.04 in the original issue for comparison purposes.
> 
> ![manuskript-tools-frequence-analyser-desktop](https://user-images.githubusercontent.com/10405019/52430411-3ce2da00-2ac3-11e9-8460-2f48c271da6b.png)
>

**Comment by gedakc** [comment]
@worstje is this fixed with [PR 576 - Fix dialog windows being created outside the desktop area](https://github.com/olivierkes/manuskript/pull/576) being merged with the **develop** branch?

**Comment by worstje** [comment]
@gedakc Like I mentioned [here](https://github.com/olivierkes/manuskript/pull/576#issuecomment-491505856), the patch addresses the problem. My only sidenotes on that were about the best time to do the position adjustment, but tests showed that PR did it in the way that works best.

All good. 👍

**Comment by gedakc** [comment]
Thanks for the confirmation.  I will mark this so it gets automatically picked up for the CHANGELOG.md file.
