### ISSUE TITLE
Crash when previewing malformed regular expression when compiling

### ISSUE THREAD

**Issue by worstje** [olivierkes/manuskript#488]
Using a malformed regular expression in the transformation screen and clicking 'preview' causes the program to crash.

In case it is specific to the exporter chosen: I was messing around with the Pandoc 'HTML' export.

**Traceback**:

> C:\Portable\Manuskript>manuskript.exe
> Debug: Web rendering engine used: QWebView
> Running manuskript version 0.8.0.
> Note: No translator found or loaded for locale en_US.
> Loading: <snip>.msk
> Detected file format version: 1. Zip: True.
> Project <snip> loaded.
> Traceback (most recent call last):
>   File "manuskript\ui\exporters\exporter.py", line 101, in preview
>   File "manuskript\exporter\pandoc\HTML.py", line 33, in preview
>   File "manuskript\exporter\pandoc\abstractPlainText.py", line 36, in src
>   File "manuskript\exporter\manuskript\plainText.py", line 44, in output
>   File "manuskript\exporter\manuskript\plainText.py", line 174, in concatenate
>   File "manuskript\exporter\manuskript\plainText.py", line 151, in concatenate
>   File "manuskript\exporter\manuskript\plainText.py", line 217, in processText
>   File "c:\python34\lib\re.py", line 179, in sub
>   File "c:\python34\lib\re.py", line 294, in _compile
>   File "c:\python34\lib\sre_compile.py", line 568, in compile
>   File "c:\python34\lib\sre_parse.py", line 780, in parse
>   File "c:\python34\lib\sre_parse.py", line 377, in _parse_sub
>   File "c:\python34\lib\sre_parse.py", line 728, in _parse
>   File "c:\python34\lib\sre_parse.py", line 377, in _parse_sub
>   File "c:\python34\lib\sre_parse.py", line 730, in _parse
> sre_constants.error: unbalanced parenthesis

**Expected behavior**:

A popup that tells me what is wrong and ideally also how to fix it. For example, disabling the regular expression option will not cause the crash and cause pandoc to complain about me failing to properly specify a title.

**Comment by gedakc** [comment]
This sounds similar to recently created [Pull Request #486 - Don't crash if a typo is made in the exporter's regular expression](https://github.com/olivierkes/manuskript/pull/486/commits/823e5410ee6e291ba6d71446a74517e656ff2a8f).

Are you able to test using the code change in the above listed PR?

**Comment by kakaroto** [comment]
I checked an unbalanced parenthesis and confirm it's caught (the sre_constants exception is caught by re.error). I've also added the error message to the dialog and it's much more helpful now.

**Comment by gedakc** [comment]
I confirmed the crash on compile / export preview with an invalid regexp transformation.

I also confirmed that PR #486 prevents the crash and pops up a dialog box with an error message.
