### ISSUE TITLE
Multiple multiple blank lines in editor get deleted after exporting to PDF

### ISSUE THREAD

**Issue by vice236** [olivierkes/manuskript#496]
Hello
I'm trying to have 2 line breaks between some paragraphs but after exporting to PDF, there are no empty lines. For example:
In the editor:
Par1
&nbsp;
&nbsp;
Par2

In the PDF:
Par1
Par2

Any way to keep the lines?

**Comment by gedakc** [comment]
The line collapse behaviour described is the way that Markdown works.

If you wish to have a carriage return after a line, then the practice in Markdown is to use _Manual Line Breaks_.  These are specified by having a line end with two or more spaces.  See _Manual Line Breaks_ in [Daring Fireball - Markdown Web Dingus](https://daringfireball.net/projects/markdown/dingus).

For example (note trailing spaces after _Hello_ and on lines up to _There_:

```
Hello  
  
  
There
```

will display as:

Hello  
  
  
There

**Comment by vice236** [comment]
Thanks! Spaces only method didn't work but `&nbsp;` one did, Thank you!
