### ISSUE TITLE
Total word count is missing or hard to find

### ISSUE THREAD

**Issue by tkoop** [olivierkes/manuskript#497]
I've looked everywhere I can think of, and I can't find a total word count.  The Outline page shows word count for each folder/chapter, but I would really like to see a grand total.  And while we're at it, a grand total goal with percent completed.  Thanks.

**Comment by tkoop** [comment]
I just found a work-around.  Simply put all your folders into one parent folder.  Problem solved.

**Comment by gedakc** [comment]
To view the entire project word count / goal, select the **Editor** pane and then navigate to the top of the project using the **Up Arrow** icon located at the bottom left of the **Editor** Pane.

![manuskript-total-word-count](https://user-images.githubusercontent.com/10405019/52805189-492ae200-3043-11e9-84f7-2056eebd2feb.png)

Does that answer your question?
