### ISSUE TITLE
Likes to freeze and crash

### ISSUE THREAD

**Issue by abizrihays** [olivierkes/manuskript#50]
I would really like to be able to type more than three characters without the program stalling, freezing, or crashing.  Takes forever to type anything and only some of the characters register so there are a ton of misspellings.  Doesn't matter if I'm in distraction-free mode or whatever mode I'm in.  Usually the problem is tied to the Revisions, but whenever I try to alter those (most notably the frequency), the program crashes.

Only happens in Redaction; Characters, Plots, World, etc. all work more or less seamlessly.

OS: Windows 10
Current V.: Manuskript 0.3.0
Used Previous V.?: No
Imported file?: No

**Comment by olivierkes** [comment]
Thanks for reporting.
When it crashes, any error message in console? That would be helpful.

**Comment by abizrihays** [comment]
Nothing.  The whole thing shuts down, all windows, and all manuskript folders.  When I start it up again, it's basically a clean slate like nothing happened.

**Comment by olivierkes** [comment]
In what language / locale are you using manuskript?
Maybe it's an encoding issue, i had sometimes similar problems.

**Comment by abizrihays** [comment]
J'ai changé la langue française.  Il n'a pas écrasé, mais il gèle encore et il est très lent à rattraper.

**Comment by abizrihays** [comment]
Kind of late since I figured this out months ago.  It was tied to the automatic save feature, after X number of seconds.  It was set to 1 second so every time I paused, it was trying to save and it just got in the way.  I ended up having to just disable it an it seems to work fine now.

**Comment by olivierkes** [comment]
thanks for that.
do you have a huge projet? Or a very slow computer? or do i need to check in that auto-save feature?

**Comment by abizrihays** [comment]
That's debatable.  The computer (laptop to be specific, not sure on exact
specs) is only three years old, but it's been a little on the fritz for the
last year.  It does computer games and heavy downloading with minimal
issue.  As for my project, it has been doing this since the beginning.  I
disabled the autosave before I even completed book one.  I am just starting
book four (all ave. 30 ch, 200k words, so pretty hefty projects) and have
only had one incident of the program crashing completely and without
warning, but everything that had been saved was saved.

On Apr 5, 2017 8:46 AM, "Olivier" <notifications@github.com> wrote:

thanks for that.
do you have a huge projet? Or a very slow computer? or do i need to check
in that auto-save feature?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/olivierkes/manuskript/issues/50#issuecomment-291850243>,
or mute the thread
