### ISSUE TITLE
In revision mode text, selecting group doesn't load text-preferences right.

### ISSUE THREAD

**Issue by therahedwig** [olivierkes/manuskript#51]
Ubuntu 16.04, using the download from the official website.

When selecting a group of texts in revision mode, the child texts get pasted underneath each other and you can edit the text in the preferences.

However, the main text doesn't load these preferences unless you just edited them. The header does load right. This is a bit annoying as I have dyslexia and need the text to be way bigger than it is by default :)

**Comment by olivierkes** [comment]
I'm sorry I don't understand :)

**Comment by therahedwig** [comment]
Lemme give you some images.

![problem_1](https://cloud.githubusercontent.com/assets/1759191/19570106/cd80869a-96f8-11e6-894c-e88858fd0986.png)
I set my font size to 14. It shows as 14.

Going to the chapter overview:
![problem_2](https://cloud.githubusercontent.com/assets/1759191/19570124/e6274012-96f8-11e6-9ccc-89652b04e9ac.png)
Font size is tiny again. Despite being 14.

![problem_3](https://cloud.githubusercontent.com/assets/1759191/19570145/028d6948-96f9-11e6-9843-ce8008024203.png)
Setting the font a bit higher, it does load the preferences.

Then, when switching to another chapter view, the problem is back again:
![problem_4](https://cloud.githubusercontent.com/assets/1759191/19570169/17ea7e34-96f9-11e6-9535-e8f43570daca.png)

Does this clarify?

**Comment by olivierkes** [comment]
Yes thanks a lot !

**Comment by olivierkes** [comment]
Fixed, thanks for reporting.
