### ISSUE TITLE
Index cards seem to keep a background image by default.

### ISSUE THREAD

**Issue by therahedwig** [olivierkes/manuskript#52]
Ubuntu 16.04, Unity, Using download from the website.

The index cards keep the space background despite setting the background to none in the preferences. Setting a different image works, but not setting to "none".

**Comment by gedakc** [comment]
@therahedwig, a fix for this issue has been committed to the **develop** branch.

If you would like to test the fix, use the steps to [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux) and be sure to `git checkout develop` to be on the **develop** branch.
