### ISSUE TITLE
Corrupted Project File Crashes When Opening. 

### ISSUE THREAD

**Issue by Selzier** [olivierkes/manuskript#522]
I am using Windows 7 64 bit with Manuskript 0.8.0.

I had a power outage and my computer shut down. After turning my computer on, my .msk project file is corrupted and will not open. Other .msk files open without a problem. Here is the error when I try to open my project:
https://i.postimg.cc/SsnBvgFr/error.jpg

I've tried to unzip the .msk file to no avail. I even downloaded the linux unzip program for Windows, and it still won't open the msk file as a zip. The error is:
_End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive._ 

Please let me know if there's any way to recover my project.

**Comment by gedakc** [comment]
To gain access to the contents of the zip file you might try searching for software to recover as much content as possible.

I use GNU/Linux and the zip command to recover contents of a corrupted file such as you describe is:

`zip -FF Corrupted.zip --out Recovered.zip`

After recovering as much content as possible you will need to recreate the Manuskript project and copy and paste the recovered contents where applicable.

It sucks to lose data whether through power outages, software bugs, or hardware failure.  We highly recommend making frequent backups to minimize such losses.

**Comment by Selzier** [comment]
Using Ubuntu 18.04.2 LTS, running _zip -FF corrupted.zip --out Recovered.zip_
Scanning for entries...
    zip warning: zip file empty

**Comment by gedakc** [comment]
How big is the file size?

For example the tutorial I wrote called [Using Manuskript to Write a Fiction Novel](http://gedakc.users.sourceforge.net/display-doc.php?name=manuskript-novel-writing) is ~ 19 kB in size (note that the `.msk` file does not contain images, only links).

```
$ ls -l manuskript-novel-writing.msk 
-rw-rw-r-- 1 gedakc gedakc 19461 Feb 14 10:29 manuskript-novel-writing.msk
```

If the `project.msk` is less than a few kilobytes then it probably does not contain much content.

**Comment by Selzier** [comment]
In this case, the solution was to move to a new software and start over from scratch. Thanks for the quick responses and keeping it open source.

**Comment by gedakc** [comment]
Thank you for trying out Manuskript and reporting the **critical** issue you encountered that resulted in loss of work.  We value your feedback and will use it to help guide future improvements to Manuskript.
