### ISSUE TITLE
Top menu not shown on Ubuntu with Unity desktop

### ISSUE THREAD

**Issue by Expipiplusone** [olivierkes/manuskript#534]
The top menu (File, Edit...) does not show up. Tried both the 0.8.0.deb package installation and source run, both on master and develop branches, same result. Tried to debug the code itself but, being myself a Java backend dev at most, I'm not sure where exactly to look for.
The environment is pretty old (Ubuntu 14.04.6 LTS).

![Schermata del 2019-03-09 18:37:35](https://user-images.githubusercontent.com/33549645/54075048-8bd68780-429a-11e9-98e3-4a9c424c1390.png)

**Comment by gedakc** [comment]
Often with Ubuntu the "file menu" is actually placed at the top of screen and only shows up when you hover the mouse cursor at the top bar of the screen.

You might try forcing the menu to display with the application's window title bar with:  
**System setting / Appearance / Behavior / Show the menus for a window / In the window's title bar**

See [StackOverflow - Missing menuBar in PyQt5](https://stackoverflow.com/questions/39574105/missing-menubar-in-pyqt5)

Does that fix the issue for you?

**Comment by Expipiplusone** [comment]
Thank you for your time, unfortunately changing that option doesn't solve the issue, it doesn't seem to have any effect on any application whatsoever. As far as I recall, when I first set up this system years ago, I had to fiddle around a lot in order to get the application menus in the right place, I guess something might still be broken. I haven't noticed until now, though, as you can see from the sceenshot other applications show the menus.

**Comment by gedakc** [comment]
It sounds as if there is something unique about the application menu configuration on your computer.

In an Ubunbu 14.04 Virtual Machine, the Unity desktop works as I described earlier.  Following is a screen shot demostrating the file menu that appears when the mouse if positioned over the window's title bar.

![Manuskript-Ubuntu1404-File-Menu](https://user-images.githubusercontent.com/10405019/54767459-c60d2680-4bc2-11e9-9bdf-9781493985a5.png)
