### ISSUE TITLE
Qt WebKit is deprecated

### ISSUE THREAD

**Issue by katafrakt** [olivierkes/manuskript#54]
This is more of a question than actual issue. Qt WebKit [has been deprecated](https://wiki.qt.io/New_Features_in_Qt_5.6) some time ago already. This makes it impossible to build Manuskript with new Qt versions (mine was 5.7).

My question is: 
What is Qt WebKit used for and if, perhaps, it would be easy to replace it wit QtWebEngine?

I know that there are some functional differences between Qt WebKit and QtWebEngine and some people are neglecting deprecation and removal of the former but maybe it is easier in case of this project?

**Comment by olivierkes** [comment]
Thanks for noting that. QtWebKit is used mainly to preview HTML rendering. It should not be to difficult to replace it, and it is the logical thing to do I guess. Thanks.

**Comment by annulen** [comment]
JFYI, QtWebKit is not deprecated anymore

http://qtwebkit.blogspot.com/2016/08/qtwebkit-im-back.html

**Comment by katafrakt** [comment]
@annulen This is great news. But do you know if it will be bundled with Qt releases again?

@olivierkes If it won't be bundled, it might still be good idea to rewrite to Web Engine and not have developers compile Qt by hand.

**Comment by annulen** [comment]
@katafrakt We are integrating it into Qt CI system, when it's done there will be releases

**Comment by annulen** [comment]
For now you can use binary builds for win and mac: https://github.com/annulen/webkit/releases/tag/qtwebkit-tp4

**Comment by katafrakt** [comment]
Cool. I guess we can close this issue in this case, @olivierkes.

**Comment by olivierkes** [comment]
Ok thanks !
