### ISSUE TITLE
Won't run (Arch Linux)

### ISSUE THREAD

**Issue by egazz** [olivierkes/manuskript#546]
I've installed the [AUR](https://aur.archlinux.org/packages/manuskript-git) version, which is a PKGBUILD based on the .git.  It compiles without issue, and as far as I can tell I have all dependencies.

When trying to run manuskript, however, all I get is this:

``Bus error (core dumped)``

I can't find any kind of error log or anything, although this of course doesn't mean it's not there.

As the subject says, I'm running Arch Linux and as far as I know everything is up to date.  I can provide whatever information you may need.  I don't know if this makes a difference, but Arch doesn't call things ``python3-`` in its package manager.  Instead, ``python-`` means python3 while ``python2`` means, well, python2.

**Comment by gedakc** [comment]
Thank  you @egazz for your interest in Manuskript.

For problems with the Arch Linux package please contact the maintainers of the Manuskript Arch Linux package.

If you wish to try to [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux) then we can try to assist you.  Note that the [`bin/manuskript`](https://github.com/olivierkes/manuskript/blob/develop/bin/manuskript) shell script invokes `python3`.  When you get Manuskript running on Arch Linux then you might consider updating the Wiki, or creating a new "_Run Manuskript from Source Code on Arch Linux_" Wiki entry for Arch Linux.

**Comment by gedakc** [comment]
Closing this issue because we do not maintain the Arch Linux package.
