### ISSUE TITLE
Image crash: When using tooltip on an incomplete image filename

### ISSUE THREAD

**Issue by cristtapia** [olivierkes/manuskript#549]
If i insert an image file as a markdown link, and the image is empty, program crashes, example:

`![image](file:)`

When using the mouse over the link, the program closes.

**Comment by gedakc** [comment]
Thank you @cristtapia for reporting this issue.  I confirmed the crash by hovering the mouse over an imcomplete image filename.

**Comment by gedakc** [comment]
PR #558 prevents the crash.
