### ISSUE TITLE
Doesn't save in redaction

### ISSUE THREAD

**Issue by christoffersch** [olivierkes/manuskript#55]
Wrote lots of good stuff yesterday, but when I open Manuskript today, everything under "Redaction" is gone. Positive I saved everything, it also saves automatically.

Is it gone forever or can I find it somehow? Tried opening the .msk in Notepad, but there wasn't really lots of information.

At least it's worth looking into.
On Windows 10, pulled the download from the website.

**Comment by olivierkes** [comment]
Hi,
Sorry manuksript is still unstable, so this can happen. But i really need to find why.
In order to recover your text, you can rename your file from *.msk to *.zip, and then open it as a zip file, and see if you can find your text. But depending where the bug was, it might be empty.
Thanks for the report.

**Comment by christoffersch** [comment]
Sure, shit happens :) Thankfully I only wrote a few pages, I can write it again.
I zipped it and it contained my everything inside my project, except everything from Redaction.

Is there anything specific you want me to send over?

**Comment by olivierkes** [comment]
It's too late now. If there were some error message in the console those would have been useful.

Oh, you can check on the file called revisions.xml, to see if it is empty too.

**Comment by gedakc** [comment]
@christoffersch would you be able to try Manuskript 0.4.0 to see if the redaction data lost issue is resolved for you?

Using Manuskript 0.3.0 and the steps from the video in issue #92 I was able to confirm loss of data from the Redaction tab.  Using these same steps with 0.4.0 did not result in lost data.
