### ISSUE TITLE
Is This An Active Project

### ISSUE THREAD

**Issue by Quasaur** [olivierkes/manuskript#56]
Your software shows great promise, but i noticed there hasn't been an update in 7 months...is this project still under active development???

**Comment by seffw** [comment]
Surprised at this question. The lead of this project has been updating here (a quick glance shows 13 and 26 days ago). Also 7 months is not that long. 

Actually your post initially put me off trying Manuskript. I'm very glad i finally did try it as in my opinion it not only shows promise, but is extremely well thought out and functional writing software.

**Comment by olivierkes** [comment]
Thanks @seffw . Yes Manuskript is still active, but it's true that the development is slow. Most of my free time is now taken by my latest project: my 6th month old son.

But I keep working on it, and plan on continuing !
