### ISSUE TITLE
Crash on insertion of new page character

### ISSUE THREAD

**Issue by kakaroto** [olivierkes/manuskript#562]
Not at home now so limited testing abilities, but I was showing a friend Manuskript and it kept crashing and I managed to find a way to reproduce the crash. There might be an easier way to reproduce it, but here's what I got : 

From a google document, press Ctrl-Enter to create a page break, then select the page break (select text including the new page 'character', the selection should appear longer than on an empty line)
Paste that into a scene in manuskript, once it saves, it will crash with the following error : 
```
Traceback (most recent call last):
  File "manuskript\mainWindow.py", line 765, in saveDatas
  File "manuskript\loadSave.py", line 21, in saveProject
  File "manuskript\load_save\version_1.py", line 260, in saveProject
  File "manuskript\models\abstractModel.py", line 525, in saveToXML
  File "manuskript\models\abstractItem.py", line 281, in toXML
  File "manuskript\models\abstractItem.py", line 281, in toXML
  File "manuskript\models\abstractItem.py", line 272, in toXML
  File "lxml.etree.pyx", line 744, in lxml.etree._Element.set (src\lxml\lxml.etree.c:44335)
  File "apihelpers.pxi", line 554, in lxml.etree._setAttributeValue (src\lxml\lxml.etree.c:19531)
  File "apihelpers.pxi", line 1393, in lxml.etree._utf8 (src\lxml\lxml.etree.c:27125)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

```

Hope you can fix, otherwise will look at it when I get back home next week.

**Comment by gedakc** [comment]
Is there another way to create the **Ctrl+Enter** character using just the applications installed by default in the operating system?

The reason I ask is because I do not wish to use proprietary software like Google Docs.

I've tested with Kubuntu 16.04 and using **Ctrl+Enter** in LibreOffice Writer, then copied and pasted into Manuskript but did not experience a crash on save.

**Comment by kakaroto** [comment]
No, it is the character with hex value 0x0C (12 decimal), but it seems that using the Alt key doesn't have the same effect. I checked with a hex editor and the Text file contains the unicode character equivalent it seems with hex value 0xE29980.

I checked the 0-Scene_1.md file and it just has the character with hex value 0x0C. I'd suggest maybe trying to use a hex editor and replace a character with value 0C and then opening manuskript, as soon as you change text in that scene, it should crash. Or maybe you can just copy/paste the character from there.
Anyways, here it is, pasted in here, though I doubt it will come through the github comment, you can try to copy/paste this like though :  ``

**Comment by gedakc** [comment]
Your suggestion worked perfectly.  By copying and pasting the character in the above post I was able to confirm the crash on save on Kubuntu 16.04.

Your proposed patch prevents the crash.  :-)
