### ISSUE TITLE
Crash when exporting with pandoc as custom path only

### ISSUE THREAD

**Issue by kakaroto** [olivierkes/manuskript#563]
If pandoc is not globally installed and only a custom path is specified, manuskript crashes when it tries to export.
I've looked at the code and I think I see the issue but I can't test/confirm for now.
The Exception is "File not found" on the subprocess.Popen : 
https://github.com/olivierkes/manuskript/blob/2b4943c36b20c2c4f889e2e21c1f7b54d8f53ace/manuskript/exporter/pandoc/__init__.py#L75

The issue I think is that the command is built using `self.cmd` : https://github.com/olivierkes/manuskript/blob/2b4943c36b20c2c4f889e2e21c1f7b54d8f53ace/manuskript/exporter/pandoc/__init__.py#L51

but the `self.cmd` is empty and instead `self.customPath` needs to be used.
The `version()` method uses `self.run([--version])` and the run method in basic.py does : https://github.com/olivierkes/manuskript/blob/2b4943c36b20c2c4f889e2e21c1f7b54d8f53ace/manuskript/exporter/basic.py#L55-L59

**Comment by gedakc** [comment]
Confirmed crash on Kubuntu 16.04 with the following steps:

1. Rename pandoc executable.  
   `sudo mv /usr/bin/pandoc /usr/bin/pandoc.orig`

2. Create new symbolic link to similate custom path.  
   `ln -s /usr/bin/pandoc.orig ~/pandoc`

3. Set pandoc custom path.  
   Select **Compile -> Manage exporters -> Pandoc**.  
   Set **Path** to _~/pandoc_ which in my case is `/home/gedakc/pandoc`  
  Close **Manage Exporters** window.

4. Perform export.  
   Beside **Export to** choose Pandoc - _HTML_.
   Click **Preview** button.

5. Pandoc crashes.
