### ISSUE TITLE
Package as App Bundle for macOS

### ISSUE THREAD

**Issue by dschanoeh** [olivierkes/manuskript#567]
It would be nice to package the app as an App Bundle so that it can live in the Applications folder and be added to the dock.
I did some research on how to achieve this with PyInstaller. The changes in [this](https://github.com/dschanoeh/manuskript/commit/2574772cfd06baca4fcb6a95a69102a4f371b057) commit seem to do the trick. A Manuskript.app is created and zipped ready for deployment.

I noticed that the icon doesn't display in Finder but before investigating further: Is that something that can be added and is the integration going in the right direction?

**Comment by gedakc** [comment]
> I did some research on how to achieve this with PyInstaller.

@dschanoeh can you add link(s) to the web document(s) that you read to learn how to do this for macOS X?

Such links may be useful in the commit message for the PR.
