### ISSUE TITLE
HTML Preview does not Recognize Strikethrough Text

### ISSUE THREAD

**Issue by mikeandjam** [olivierkes/manuskript#568]
I have found when using the Compile preview with HTML as the output, text that has been formatted with strikethrough is not recognized as such.

Typing: `~~this is strikethrough text~~`

Yields: `~~this is strikethrough text~~`

Rather than: ~~this is strikethrough text~~

I would assume this is because strikethrough is not included in original Markdown, though the formatting is recognized in Manuskript's editor.

**Comment by gedakc** [comment]
Were you aware that there is no **strikethrough** in the [official syntax for markdown](https://daringfireball.net/projects/markdown/syntax)?

Instead **strikethrough** was added on by other Markdown interpreters, such as [GitHub - Mastering Markdown](https://guides.github.com/features/mastering-markdown/).

The internal Manuskript HTML previewer tries to stay true to official markdown.

If you wish to use an extended version of Markdown which includes **strikethrough** then choose the **Pandoc** HTML previewer.

Does that answer your question?

**Comment by mikeandjam** [comment]
I was aware! I thought that might be the case, but as I mentioned, the editor does recognize strikethrough, and I did not want to assume.

If I may be so bold, might I ask what sort of plans there are in regards to Compile's preview at the moment? I ask because the preview does not currently work with all of Pandoc's options. I expect no one intends for Manuskript to become a full GUI for Pandoc, but should we consider Compile currently in a "mostly done" state with only small tweaks coming? I would assume OPML implementation is one thing. 

I apologize if I am out of line, but there is currently nothing on the Roadmap about Compile, and I would rather ask a foolish question then make a foolish mistake.

Thank you.

**Comment by gedakc** [comment]
My personal focus is on software stability, not items such as this which has a work-around.

**Comment by mikeandjam** [comment]
Okay then. @gedakc, thank you for your answers and your time.
