### ISSUE TITLE
Application Style setting GTK+ on Linux Mint Mate 

### ISSUE THREAD

**Issue by seffw** [olivierkes/manuskript#57]
This may be due to the Mate desktop (which is based on Gnome 2) on Linux, not sure.

With GTK+, the window does not maximise, and minimized the window height is to much (the bottom of the window is off screen).

It's not a functional issue as with Fusion setting it's fine (but GTK+ fits in better with the Linux Mint look).

**Comment by olivierkes** [comment]
Can you post a screenshot?

**Comment by olivierkes** [comment]
Similar to #108 .
