### ISSUE TITLE
Crash on showing storyline

### ISSUE THREAD

**Issue by krdau** [olivierkes/manuskript#572]
Manuskript 9.0 opens fine on start. But when trying to show/ the storyline (respective the characters) it crashes.

Terminal output:

Traceback (most recent call last):
  File "/home/krdau/manuskript-0.9.0/bin/../manuskript/ui/views/storylineView.py", line 224, in refresh
    listItems(root, outline)
  File "/home/krdau/manuskript-0.9.0/bin/../manuskript/ui/views/storylineView.py", line 184, in listItems
    parent.setToolTip(references.tooltip(references.textReference(child.ID())))
  File "/home/krdau/manuskript-0.9.0/bin/../manuskript/models/references.py", line 503, in tooltip
    tt = qApp.translate("references", "Folder: <b>{}</b>").format(infos["title"])
ValueError: expected '}' before end of string
Fatal Python error: Aborted

Current thread 0x00007f5e76090700 (most recent call first):
  File "/home/krdau/manuskript-0.9.0/bin/../manuskript/main.py", line 145 in launch
  File "/home/krdau/manuskript-0.9.0/bin/../manuskript/main.py", line 158 in run
  File "./bin/manuskript", line 13 in <module>
Aborted.

Linux Mint Mate 18.3 64-bit on ACER Aspire (12 GB RAM)

By the way: Manuskript 0.8.0 works fine so far

**Comment by worstje** [comment]
I haven't seen this one before. Some questions:

1) What language are you using? Maybe it is a malformed translation.

2) Does it happen for a fresh project? If not, can you create a fresh project that shows these symptoms? (Based on the traceback, it might involve one of your references being formed in such a way that it triggers this, so duplicating those would be a good spot to start in that case.)

**Comment by gedakc** [comment]
@krdau if you are using the German translation then an issue related to a bad translation file was fixed with [Pull Request 566 - Fix typos in translation format placeholders that lead to crash](https://github.com/olivierkes/manuskript/pull/566).

**Comment by krdau** [comment]
Yes, problem solved by compiling the updated de.ts file into a new de.qm file. Woeks in 0.9 as well as in develop.

**Comment by gedakc** [comment]
Thanks @krdau for testing and reporting back that PR #566 did indeed resolve the issue.

'Labeling this as a duplicate of PR #566.
