### ISSUE TITLE
[BUG] Shim error

### ISSUE THREAD

**Issue by b16r05** [olivierkes/manuskript#579]
Manuskcript: 0.9.0
Pandoc: 2.7.2

I am trying to export (compile) my work to a docx word file and the screen freezes with "not responding". The computer runs out of memory (16 GB) and there are a lot of duplicate `sim gen generated shim shim shim` files. I don't know if I am doing something wrong, but this sure look like a bug.

**Comment by gedakc** [comment]
Can you try compile/exporting to other formats, such as HTML to see if other formats work?

You might also try both the built-in Manuskript HTML export and the Pandoc HTML export.

It would help if you invoke Manuskript from a terminal window.  That way you can copy the console output and paste it into this issue to help with debugging.

It would also help to know what operating system you are using

**Comment by b16r05** [comment]
I tried another computer (both running Windows 10). It worked!

HTML regular worked. Pandoc HTML worked as well and so did output to docx. So, now I am not able to reproduce the issue on another computer. 

For the second computer, I was using recently updated 0.9 version with the sample file. The original computer has some msk files created in version 0.8. I wonder if that is creating some problems? 
Anyway, I will try uninstalling and reinstalling both Manuskript and Pandoc on the first computer to see if the problem goes away. 

I will leave the console work as the last resort... if re-installing fails to solve this issue.

**Comment by b16r05** [comment]
I reinstalled Pandoc and refreshed the Manuskript folder today; export is working fine.
