### ISSUE TITLE
Accent marks not working

### ISSUE THREAD

**Issue by AngelArnal** [olivierkes/manuskript#58]
Linux Mint 17.3, manuskript-0.3.0-linux-1, accent marks don't work in Spanish layout. Whenever I type an accented vowel the program ignores the accent mark and shows an unaccented vowel.

"Ñ" works fine.

If I modify the text file from another application the program loads the text without problems and I can copy and paste whatever with accent marks, it's not than it can't manage them, only fails when typing.

Fails in dialog fields and text editor window.

**Comment by jmgaguilera** [comment]
I'm working with manuskript in spanish in Ubuntu 16.04 and accents and 'Ñ' works fine in my computer. Could you add some information about the error? Has Linux mint 'ibus' packages installed? I remember that in Mint you can select "input method" from system settings in language app, I think Ubuntu uses iBus by default.

**Comment by AngelArnal** [comment]
Thanks for the tip, but it didn't work. :(
I installed ibus, configured it for Spanish, and same result. The keyboard works fine with any application but Manuskript.

**Comment by eshac** [comment]
Hi, the same happening here. Also Ubuntu 16.04 and no accents.
Thanks for the software, I started using it last week and I'm loving it.

**Comment by Renkineko** [comment]
I have the same problem on my Xubuntu (16.10) but I don't have the problem on my ubuntu (16.10). Both configured the same way. Don't really understand what triggers the issue.

**Comment by garazaber** [comment]
Hello! I'm experiencing the same issue in Ubuntu 16.04. Even though the configuration "english with dead keys" works fine in other applications, I'm not able to use the accents marks in Manuskript.

**Comment by olivierkes** [comment]
Thanks for the reports. This is strange.

Can you tell me whether it happens in **all** text fields, or only in some?

Also, does this happen only with multi-touch accentuated letters (like "~" + "N"), or also with single-touch (like on the french keyboard we have "é", "à", etc.)?

Thanks,

**Comment by AngelArnal** [comment]
In Spanish only with multi touch (' + a). Ñ works fine. I found the problem on my desktop with Mint 17.3, had the same issue on Mint 18 on my laptop, I installed Ubuntu 16.10 on my laptop and the behaviour is the same. Any field. If I copy-paste the fields, whichever, accept the accented letters. It's a keyboard thing. Keystrokes don't have the expected result.

Hope you find what it is soon. I love the program.

**Comment by Renkineko** [comment]
All the simple accents of the french keyboard (è, é, à) was ok, but i can't do ê or ë. I'm not sure if the copy/paste works, I'm pretty sure i tried and it failed, but I can't say my memories are reliable. Besides, it was on the 0.3.0 version, I can't say the problem still exists in the dev version because it fail to load when I try to launch it myself (probably missing something but don't understand what). I'll do more tests this week-end.

**Comment by olivierkes** [comment]
Just to be sure, this is also in single-line fields? Like in the "general" or "summary" tabs.

**Comment by AngelArnal** [comment]
In my case, yes. With all three distros I've tried. Single-line and multi-line fields. Copy-paste works fine, external edition and reload also works fine.

**Comment by garazaber** [comment]
Hello. I had it tested and, in my case, every field shows this issue. However, when I paste some text from another application, the accents marks are shown with no problem. This weekend I'll try and install Manuskript on a laptop running Ubuntu 14.04 and see if the issue repeats itself.

**Comment by eshac** [comment]
It is. For me accents ('+ a for example) do not work in any tab. But ñ works (in my Spanish keyboard this is a sinlge touch key)

**Comment by olivierkes** [comment]
I tried on a fresh Linux Mint install, and I cannot reproduce. All accents work well, on 0.3.0 and develop...
This is frustrating.

**Comment by Renkineko** [comment]
(Note: I know you're or some of your team are french, me too, so I'll refer to the french keyboard)

I tried again on my laptop with xubuntu:

develop branch works well
0.3 package doesn't. 

If I do altgr+d, the accent is good (Ê), same for altgr+$ (ê) but if I do the two touch ^(above the "ù") and "e", it doesn't work and i only get "e". altgr+9 gives immediately the ^, as expected.

My keyboard layout, don't know if it can help. What's strange is that develop works well, so maybe the bug is not there anymore.

![image](https://cloud.githubusercontent.com/assets/2254151/24295031/4ce512f6-1099-11e7-8168-34bed29a51fe.png)

**Comment by olivierkes** [comment]
Thanks, if it's only failing with the package version of 0.3.0 but develop branch works, then i'm relieved: it's a packaging issue. I'll have to find a better way to package manuskript anyway.

**Comment by bartart3d** [comment]
I can confirm the problem with 0.4.0 too. The issue is not present in the development branch, but it remains a problem in the stable branch, now 0.4. 
Also, the PyEnchant package is not detected by the stable branch, but it is detected by the development branch.

**Comment by gedakc** [comment]
@bartart3d, were you running manuskript 0.4.0 from the binary executable from the `manuskript-0.4.0-linux.zip` file, or from the **0.4.0** git branch with the `bin/manuskript` python script?

You can check the `manuskript` type of file with the following command `file manuskript`.
For example:

```
$ file manuskript/bin/manuskript
manuskript/bin/manuskript: Python script, ASCII text executable
$

$ file manuskript/manuskript
manuskript/manuskript: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=373ec5dee826653796e927ac3d65c9a8ec7db9da, stripped
$
```

**Comment by bartart3d** [comment]
@gedakc, The 0.4.0 on one PC was the binary file. On my laptop I have the python script, that works fine.

**Comment by gedakc** [comment]
Thanks @bartart3d for the prompt response.

>  The issue is not present in the development branch, but it remains a problem in the stable branch, now 0.4.

1. Does this mean that the accent problem exists if you checkout the **master** git branch?

2. Does the accent problem go away if you checkout the **develop** git branch?

**Comment by thoronaug** [comment]
Same problem here. Using Antergos Linux (Arch based) and Manuskript 0.4.0. If I install Manuskript via  AUR package, accents works perfectly, but program crashes few seconds after loading book-of-acts sample. If I download zip version from the web, program works well but no accents. Please, ask me more info if needed.
I like Manuskript very much. Thanks for sharing it. But I need accents working.

**Comment by gedakc** [comment]
@thoronaug, accents only appear to work if running from the source code, and not from a PyInstaller package.

Further there is a bug with manuskript that causes it to crash if accessing a project (e.g., book-of-acts sample) for which the user does not have write access.  See [Issue 138 - Crash when permissions don't allow saving](https://github.com/olivierkes/manuskript/issues/138).

If this is the issue you encountered then try copying the book-of-acts to a directory where you have write access, and ensure that all files and directories for the book-of-acts project have read/write access for your userid.

**Comment by gedakc** [comment]
For users of Debian based GNU/Linux distributions, such as Ubuntu and Linux Mint, please try the `manuskript-0.5.0-1.deb` package to see if accents now work for you.

The package along with the instructions for installation can be found at:   
[SF - manuskript-0.5.0](https://sourceforge.net/projects/manuskript/files/manuskript/manuskript-0.5.0/)

**Comment by AngelArnal** [comment]
YESSSS! Great, it works perfectly in Spanish.

Thanks a lot

**Comment by gedakc** [comment]
For users of Fedora based GNU/Linux distributions please try the `manuskript-0.5.0-1.noarch.rpm` package to see if accents now work for you.

The package along with the instructions for installation can be found at:   
[SF - manuskript-0.5.0](https://sourceforge.net/projects/manuskript/files/manuskript/manuskript-0.5.0/)
