### ISSUE TITLE
Adding Persian(Farsi) in Weblate

### ISSUE THREAD

**Issue by AliKhomami** [olivierkes/manuskript#596]
Hello✋,
I'd like to help translate _Manuskript_ into Persian but there is no section for Persian on _Weblate_ it would be really great if you add Persian so I can help!
By the way, Did you know Persian has about **110 million** speakers worldwide?
Peace and Goodbye!💐

**Comment by gedakc** [comment]
Have you tried creating an account on *Weblate*, scrolling down to the bottom of [https://hosted.weblate.org/projects/manuskript/translations/](https://hosted.weblate.org/projects/manuskript/translations/) and then clicking **Start new translation** button to add a new language?

**Comment by gedakc** [comment]
I just finished updating the **develop** branch with the current language translations from [Weblate](https://hosted.weblate.org/projects/manuskript/translations/) and noticed that an empty Persian (Farsi) translation has been added.  We will have to rely on the generosity of volunteers to fill out the Persian translation.
