### ISSUE TITLE
Feature request: Option to vertically center text input line on screen in fullscreen mode

### ISSUE THREAD

**Issue by mbuscemi** [olivierkes/manuskript#602]
When writing, it is preferable to have the line where I am entering text to remain at eye level (roughly the center of my monitor). This feature, if it were implemented, would adjust the text box in full screen mode so that extra space is added above the text, if the text is very short, or below the text, if the text is very long, so that the line where text is being input is always at the vertical center of the monitor.

**Comment by gedakc** [comment]
Have you tried enabling **Typewriter mode** in **Edit -> Settings -> Views ->Text editor** and then working with more than a fullscreen of text?

![Manuskript-Settings-Text-Editor-Typewriter-Mode](https://user-images.githubusercontent.com/10405019/60735211-ae5a7380-9f0f-11e9-8443-0a7f39bea5ab.png)

**Comment by mbuscemi** [comment]
Yup. This is the functionality I want, but I didn't recognize it from the name "typewriter mode."
