### ISSUE TITLE
Word count statistics incorrect when using Chinese characters

### ISSUE THREAD

**Issue by finitecow** [olivierkes/manuskript#607]
wold statistics incorrect when using Chinese character

**Comment by worstje** [comment]
I do not speak/read Chinese, so I am unable to verify the exact nature of how it is wrong or what needs to be done to fix it.

Can you supply examples of Chinese text, what the statistics report and what the statistics ought to read? If you can offer up a sample Manuskript project that exhibits the problem, that would be ideal.

**Comment by obw** [comment]
Chinese is a Language, where normally not Word- but Charcount ist used, like Japanese. A Char is often a complete Word!

Counting Chinese or Japanese Words is a art-form.

One Symbol can be a Word, but also it can be part of a Word. Also there are normally no white-spaces between Words. Simples and best Solution is a Switch to count all not white-space Chars. This is, be my knowledge what is used in these Countries!

**Comment by gedakc** [comment]
Thanks @obw for the explanation that some Chinese characters are a complete word, and that may make counting Chinese words challenging.  This is something that likely requires a person with Chinese knowledge to address correctly.

**Comment by obw** [comment]
Sorry English is not my first Language.

All Chinese Chars are one Word, but sometimes there are compound words... so two or more Words are combined to one.

Japanese is the real evil here:
4 Alphabets:
Hiragan, Katakana: Sybil chars, oh and the Sybils of both Alphabets are the same, but the Layout is different, one is used for loanwords and technical terms, the other for lyrical and if you don't know the Kanji. (Fun Fact the Term Lightnovel in Japan means, a book without seldom used Kanyis, so you don't need a dictionary too read it)
Kanji: see Chinese, they are literal Chinese Chars
Latin Alphabet, including Arabic Numbers... Why easy, when you can go too (insert the place you don't like here ;) )

I hope this is more correct an better for understanding...

I also repeat, I had look it up. All payments for Authors, Translators and so on are calculated over the char count (without white spaces).

**Comment by TheJackiMonster** [comment]
I added a PR (https://github.com/olivierkes/manuskript/pull/746) for a char-counter which can be enabled/disabled in settings. Should I add a setting to ignore white spaces or shouldn't it count them anyway? I could still add something like this before it gets merged, I guess. ^^

**Comment by taophp** [comment]
@TheJackiMonster I think a option for ignoring/including spaces is required as in France, for example, some publishers count in a way and some in the other.
Thanks for the job !

**Comment by TheJackiMonster** [comment]
@taophp I can look into it. So it should be possible to add an option in the settings right next to enabling/disabling the char-counter. Although it doesn't make much sense to me that people would count in characters but ignore the whitespace which will still require space on a page. ^^'

**Comment by TheJackiMonster** [comment]
@taophp I've uploaded a commit which was added to the pull request. So it is possible to ignore spaces now too.
