### ISSUE TITLE
does not compile to OpenOffice format

### ISSUE THREAD

**Issue by docaltmed** [olivierkes/manuskript#61]
Ubuntu 16.10/Gnome desktop. Fails to compile without notification to OpenOffice format.

**Comment by olivierkes** [comment]
What version are you using?
In develop (0.4.0), the export engine has been totally rewritten.

**Comment by docaltmed** [comment]
I was using 3.1. I'll update and try again, thanks!

(I really love this program, btw -- thank you. as soon as I can be sure it works for my needs, I will be making a donation).

**Comment by olivierkes** [comment]
Thanks :)
