### ISSUE TITLE
Manuskript me fastidio un documento de word

### ISSUE THREAD

**Issue by Dorian-Insausti** [olivierkes/manuskript#616]
este programa me daño un documento de word en el que tenia mucho tiempo trabajando, al parecer no podre recuperarlo ya lo he intentado de todas las formas que he encontrado en la red, deberían informar que puede causar daños irreparables para los ciertos documentos, me arrepiento haber bajado su programa , por desgracia no tenia respaldo del documento, si saben como recuperar mi información se los agradeceré mucho, y si deberían de hacer algo para que estas cosas no sucedan, imagino que debe ser muy cansado trabajar en un proyecto gratuito y que debe requerir de mucho amor para llevarle a cabo, por lo que les felicito, espero mejoren su proyecto, por que si hace mucha falta algo como lo que proponen, muchas gracias.

**Comment by gedakc** [comment]
@Dorian-Insausti, if order to receive support you will need to edit the post to use the English language.

**Comment by worstje** [comment]
@gedakc Based on what I could tell with Google translate, he lost his data and 'tried everything he could find on the network to fix it'. I am not sure if that is a reference to the internet, or whether he had backups on a network somewhere that was also lost. He also calls it a 'word document', but Manuskript can't open word documents, so I am quite confused.

@Dorian-Insausti As gedakc already wrote, we cannot help you unless you communicate in English. There is too much nuance involved in your words for us to properly answer any of your concerns if we try to rely on machine translation tools.

I empathize with you losing (some of your) work. That is most regrettable, and you are unfortunately not the first. However, your issue does not appear to contain any information we can actually act on. Ideally, you would offer us a sequence of events to serve as reproduction instructions, maybe a screenshot, or maybe the broken file... in addition to things like your operating system, version of Manuskript and so forth.

As such, for almost too many different reasons, we cannot do anything with your issue at this time. 😦
