### ISSUE TITLE
Locale Warning

### ISSUE THREAD

**Issue by liborty** [olivierkes/manuskript#62]
Comes up with a warning: Can not locate locale English_UK

**Comment by olivierkes** [comment]
Just a warning, you can ignore it.

**Comment by kevfrost** [comment]
This warning cannot be ignored.  Prevents loading.

**Comment by gedakc** [comment]
@kevfrost, please create a new issue if you continue to experience problems with Manuskript.  Please also provide the version of manuskript you are running and on which OS.
