### ISSUE TITLE
Spell Check Not working

### ISSUE THREAD

**Issue by steve3g** [olivierkes/manuskript#625]
I am struggling to get the spell checker to work.  I have confirmed that pyenchant is installed (I have also installed symspellpy and pyspellchecker), but when I look at Tools-Dictionaries, it says that the applications are not installed.

I do not know where to look for a cure.  Is there a log file somewhere.

**Comment by worstje** [comment]
Can you share with us the version of Manuskript and operating system that you are using?

**Comment by steve3g** [comment]
Xubuntu 18.04.3 LTS
Linux 5.0.0-27-generic x86_64
Manuskript Version 0.9.0
Python 3.6.8
PyQt 5.10.1
Qt 5.9.5
pyenchant 2.0.0

**Comment by gedakc** [comment]
How did you install Manuskript?  Did you use the binary or run-from-source-code method?
If binary, which filename did you download and install?

In addition to having PyEnchant installed along with some dictionaries, Manuskript also requires:
- Select a language from **Tools -> Dictionary**
- Enable spellcheck with the **Tools -> Spellcheck** toggle

Symspellpy and pyspellchecker are two optional spell checkers whose key use is for Windows 10 users running 64-bit Python.  These are not required on GNU/Linux (Xubuntu).

**Comment by steve3g** [comment]
Thanks for the hint.  I had installed Manusckript through the native Software Installer GUI in Xubuntu.  It obviously did not install all of the dependencies correctly.  I uninstalled, downloaded the debian package from the website, installed the package, and fixed the dependencies.  Everything works now.
