### ISSUE TITLE
Manuskript 9.0 crashes when creating new project or opening existing project 

### ISSUE THREAD

**Issue by RaykWashington** [olivierkes/manuskript#631]
I'm having an issue in which manuskript 9.0 crashes when i click on "create" or "open". there's no error message.
I'm able to load the demo project book of acts. From there, i can save, but trying to "save as" causes it to crash.

EDIT :
i noticed that deleting the registry keys for lastProject, recentFiles and lastAccessedDirectory solves the problem until i restart manuskript.

i'm on windows 10

**Comment by RaykWashington** [comment]
oh, and i'm on windows 10.

**Comment by worstje** [comment]
What OS are you using?

Have you tried starting manuskript from the command line? Most likely there is a crash which may not be visible to you when you start it normally.

**Comment by RaykWashington** [comment]
I'm on windows 10
i'm not sure how to start it from the command line, how can i do that?
thanks!

**Comment by RaykWashington** [comment]
wait, i think i found the problem:
the project was on a folder inside another folder with a name that started with"_". I deleted the registry keys and created the project on another folder and it worked just fine.

**Comment by worstje** [comment]
You can do so by opening the command line (type `cmd` in your start menu), and in the window that opens you type:

`cd \path\to\manuskript` (assuming it is on your c drive somewhere; if not you may have to use `d:` or `e:` or whatever to switch to the correct drive first.)

Alternatively, you can look up the folder where you installed manuskript, right click the *folder* while holding **shift** pressed, and then select 'open command window here' which takes care of the directory switch for you.

Once you are in the correct directory, you can start it using `manuskript`.

**Comment by RaykWashington** [comment]
for a moment i thought that it was caused by the directory being deeply nested too, but i managed to get it working by removing every special character in every folder on the path to the project. I'll try to replicate the error running it from command line to get the error message now
thanks again!

**Comment by worstje** [comment]
@RaykWashington Since you closed it, I guess you resolved it and weren't able to reproduce it. But if that changes, do feel free to reopen the issue so that we can investigate the cause. 👍
