### ISSUE TITLE
Italian dictionary

### ISSUE THREAD

**Issue by Eusorph** [olivierkes/manuskript#638]
There is no Italian spell check dictionary. If you can point me toward some guide I can try and put it together.

**Comment by gedakc** [comment]
There is lots of good information in the [Manuskript Wiki](https://github.com/olivierkes/manuskript/wiki).  The wiki is open for reading and adding/correcting.

The document [Adding a Spellcheck Language Dictionary to Manuskript](https://github.com/olivierkes/manuskript/wiki/Adding-a-Spellcheck-Language-Dictionary-to-Manuskript) is available on the Wiki.
