### ISSUE TITLE
Word count goal progress bar broken in develop.

### ISSUE THREAD

**Issue by vithiri** [olivierkes/manuskript#652]
The word count progress bar currently seems to be broken in develop while working fine in master.

**Steps to reproduce:**

Set a word goal for a text and start typing

**Expected outcome:**

Get a blue growing progress bar in the lower right hand corner of the editor

**Actual outcome:** 

The area where the bar is supposed to be is displaying next to the word count, but the bar itself never fills up

**Comment by worstje** [comment]
Thank you.

I have already traced this back to the fix for issue #561 which was fixed in PR #609, and am currently looking into a proper way to fix this.

**Comment by gedakc** [comment]
Good catch @vithiri.  We'll want to fix this before releasing 0.10.0.

Thanks @worstje for looking into this.  It might be an automatic type conversion thingy defaulting to either an integer or a real number.  For example: 100 / 500 = 0.2 real = 0 integer

**Comment by worstje** [comment]
@gedakc You were completely right. :)

I took the fix a little bit further in the interest of encouraging a more systematic approach to user input validation in the future. I hope that's not a problem. 😄

**Comment by gedakc** [comment]
Closing this issue as it is resolved with the merge of PR #654.
