### ISSUE TITLE
0.10.0 crash using Windows dark mode

### ISSUE THREAD

**Issue by mxamber** [olivierkes/manuskript#659]
Just downloaded the new 0.10.0 release to both my machines. While it seems to work on my main rig (Windows 7 64-bit), apparently fixing all issues I had experienced with 0.9.0, I can't get it to run on my laptop with the Windows colour scheme set to dark. Starting it results in the following error:

> Debug: Web rendering engine used: QWebView
> Running manuskript version 0.10.0.
> Preferred translation: ['de-DE', 'en-US'] (based on available ui languages)
> Loaded translation: manuskript_de_DE.qm
> Traceback (most recent call last):
>   File "manuskript", line 13, in <module>
>   File "manuskript\main.py", line 231, in run
>   File "manuskript\main.py", line 142, in prepare
>   File "manuskript\main.py", line 115, in respectSystemDarkThemeSetting
> AttributeError: type object 'GlobalColor' has no attribute 'white'
> Failed to execute script manuskript

The machine is running Windows 10 64-bit and a fresh install of Manuskript, having deleted the old instance and installed it anew from the 0.10.0 archive. Deleting it and installing it again didn't fix the issue. Manuskript 0.9.0 previously ran perfectly fine. Changing Windows' colour scheme to bright (which is the default) rather than dark fixed the issue.

**Comment by worstje** [comment]
Weird. That did not come up during testing. (I feel terrible since I wrote that patch...)

I guess it is due to the version of PyQt bundled with the PyInstaller build. I'll look into it.

**Comment by worstje** [comment]
@mxamber I am very sorry that you (and likely others) are affected by this bug. I should have caught that; I thought I was distrustful enough of the version differences as it was but apparently I need to be even more paranoid in the future.

I have submitted PR #660 along with the request that @gedakc creates a new Windows build.

(Unfortunately I can't provide a proper Windows build for you myself at this time; if I could I would have provided a download with the fix included.)

**Comment by gedakc** [comment]
A win32 PyInstaller package with PR 660 applied is ready for testing.

https://sourceforge.net/projects/manuskript/files/manuskript/testing-only/

**Comment by worstje** [comment]
I have tested that new package on my end and the problem has been fixed. 👍

**Comment by gedakc** [comment]
Closing this issue because PR #660 (which prevents the crash) has been merged with the **develop** branch.

Further the test package file has been renamed:  
`manuskript-0.10.0-2-win32.zip`  
and uploaded to the official release areas.
