### ISSUE TITLE
Program crashes randomly and then never opens again even after reinstall

### ISSUE THREAD

**Issue by johnnyjmcivorv** [olivierkes/manuskript#665]
I was using this program for a while -- I think under a previous version. But one day it crashed and would never open -- I tried reinstalling it but all that would happen is this and then it would close immediately.

[https://i.imgur.com/FBEokfk.png](url)

**Comment by worstje** [comment]
Your current screenshot was made while the program was still running but the terminal output was frozen, meaning that the actual cause of the crash is likely not showing. (As opposed to not existing whatsoever, which is possible but far more unlikely.)

If you run from the command line, what do you see? Steps to take:

1. Open command line. (`cmd`)
2. Switch to the directory containing manuskript: `cd /d P:\ath\Containing\manuskript`
    *You can get the path by Shift-right clicking on the manuskript folder and selecting `Copy as Path`), and then pasting it in the command line.*
3. `manuskript`

If all is well, you should be able to see the actual cause of the crash without the window closing.

**Comment by johnnyjmcivorv** [comment]
**Ok i think i found it**


Debug: Web rendering engine used: QWebView
Running manuskript version 0.10.0-with-PR660-dark-theme-fix.
Preferred translation: ['en-US'] (based on available ui languages)
Using the builtin translation.
Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 86, in showEvent
  File "manuskript\mainWindow.py", line 560, in loadProject
  File "c:\python34\lib\encodings\cp437.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 70-73: character maps to <undefined>

**Comment by gedakc** [comment]
What is the entire path / filename for the project?

Perhaps it has some non-ASCII characters in the project name?

The reason I ask is because line 560 in file "manuskript\mainWindow.py" is to print a message that the project does not exist with "print((...).format(project)".  This can happen if the project was moved to a different folder, or was renamed.

https://github.com/olivierkes/manuskript/blob/67f987d44b604344e0888256359a7e32512f98a0/manuskript/mainWindow.py#L554-L656

**Comment by johnnyjmcivorv** [comment]
C:\Users\Johnny\Downloads\manuskript-0.10.0-2-win32\manuskript\manuskript.exe

**Comment by johnnyjmcivorv** [comment]
ok i did what you said -- opening the project directly and then selecting the .exe -- and NOW it opens

**Comment by gedakc** [comment]
That's the path to where you have the manuskript.exe executable.

I'm looking for the complete path to where your project file is stored.
