### ISSUE TITLE
Cut and Paste - Comment Field - First shows, then disappiers

### ISSUE THREAD

**Issue by obw** [olivierkes/manuskript#670]
I'm trying to get a Overview for a little bigger project of mine. A Part of it, is to add Locations, Outfits, Plot and Persons to the comment of every Chapter. To get a quicker grasp of it. I have this information mostly in the Scenes, where something change and so on.
So I tried to copy the comment of the scene, to the comment of the Chapter and Manuscript loose it:(.

After that I tried to copy something in a Scene comment, there it also got lost.

If there was some text, this Text will go also away, not found again...:(

Forgot to mention:
Latest Dev-Branch, I think cloned yesterday,
Linux under KDE

Verwendete Software-Versionen:
     Python 3.6.8
     PyQt 5.13.1
     Qt 5.13.0

**Comment by obw** [comment]
ALso in the Content Overvier or so, I use German Locale, there the Name is '**Inhaltsangabe**'

**Comment by obw** [comment]
#706 - this Patch solve this Problem!

If merged with develop and master Branch, this Bug can be closed!

**Comment by gedakc** [comment]
Closing as fixed by PR #706.
