### ISSUE TITLE
After use of ctrl-z or ctrl-v Manuskript goes in inactive State

### ISSUE THREAD

**Issue by obw** [olivierkes/manuskript#672]
Goes back active, when Text is changed.

![manuskript_after_use_of_ctrl_v](https://user-images.githubusercontent.com/3050806/67582771-a5094700-f74a-11e9-8582-0b94f40ced80.png)

Forgot to mention:
Latest Dev-Branch, I think cloned yesterday,
Linux under KDE

Verwendete Software-Versionen:
     Python 3.6.8
     PyQt 5.13.1
     Qt 5.13.0

**Comment by worstje** [comment]
Can you clarify the nature of the problem more?

Perhaps it is obvious to a KDE user, but just by looking at the redacted screenshot I don't immediately see what might be wrong.

Does the text box lose focus? Or does the entire window lose focus? Or do you mean something else entirely when you talk about an 'inactive' state?

**Comment by obw** [comment]
The Problem, that you must change the Text in the Scene, to enable the Selectboxes again in '**Einstellungen**', sorry I actual don't know the English label, it should be '**Configuration**'

A Picture say more the thousand words:)

![manuskript_after_use_of_ctrl_v_what_it_should](https://user-images.githubusercontent.com/3050806/67620567-9ed9a000-f808-11e9-8f7a-05afd02a4723.png)

**Comment by obw** [comment]
#706 - this Patch solve this Problem!

If merged with develop and master Branch, this Bug can be closed!

**Comment by gedakc** [comment]
Closing as fixed by PR #706.
