### ISSUE TITLE
Spelling checker doesn't work with contractions

### ISSUE THREAD

**Issue by t0rb1t** [olivierkes/manuskript#674]
I tried all three available spelling checkers, and maybe this is an issue because of how I configured it, but after searching through similar issues I was unable to find a reason for it.

There was this related post
https://github.com/olivierkes/manuskript/issues/296

Otherwise, I'm unsure, AFAIK I'm completely up to date, I installed from the snap store.

I'm on manjaro, kernel 5.3, and have fully up-to-date python.

![image](https://user-images.githubusercontent.com/26368621/67630133-3b6f6280-f848-11e9-9b81-5c02025e3e66.png)

![image](https://user-images.githubusercontent.com/26368621/67630105-c734bf00-f847-11e9-9be7-87b6565e807a.png)

![image](https://user-images.githubusercontent.com/26368621/67630089-7f159c80-f847-11e9-81b4-1fffab6b951d.png)

**Comment by t0rb1t** [comment]
Update: After some messing around, I uninstalled all of the spelling checkers, and installed pyenchant from the AUR, and lo and behold, it's not doing it anymore!

![image](https://user-images.githubusercontent.com/26368621/67630191-50002a80-f849-11e9-8969-d1b41e84dc34.png)

![image](https://user-images.githubusercontent.com/26368621/67630193-58f0fc00-f849-11e9-8caf-1764ee028552.png)

**Comment by t0rb1t** [comment]
This issue happened to me again, and to be honest I have no idea why.

**Comment by gedakc** [comment]
The problem with the spell checker not working with contractions appears to be an issue with symspellpy.  As you discovered PyEnchant does not have this problem.

Closing this issue as **wontfix** because it is outside the control of Manuskript.
