### ISSUE TITLE
Can't get the program to open

### ISSUE THREAD

**Issue by emi-ann** [olivierkes/manuskript#686]
I was able to open this program yesterday after installing, but today I click to open the application and it just stays on this screen and never actually launches.  This is the windows version, .10.  Not sure what I'm doing wrong but hoping someone can point me in the right direction.

![image](https://user-images.githubusercontent.com/57581647/68539137-1ac10580-033c-11ea-83d7-a2dbe244cb99.png)

**Comment by worstje** [comment]
I have no clue where it is getting stuck based on that screen. (The one line you see is a side-effect from an import, so it doesn't tell me anything about where the program is getting stuck in its logic.) It just gets stuck looking like that? Really weird.

If you go to `C:\Users\YOUR_USERNAME\AppData\Local` and rename the `manuskript` folder there to something like `manuskript-test`, does that fix it?

If that does indeed fix it, can you send us that folder so we can maybe try to reproduce what is going on?

**Comment by emi-ann** [comment]
Thank you for the quick response.  Unfortunately, that did not fix the issue.

**Comment by worstje** [comment]
A very obvious and outwardly silly idea: have you tried rebooting?

I can't possibly think of something that could cause this behaviour where Manuskript's code is concerned. Really early in the start process, it should at least display the version and translation stuff, but you aren't seeing that.

At this point I can only think of something getting stuck in your system that somehow prevents Python (or Qt) from starting / resuming as intended. Maybe it is a driver issue, maybe something antivirus related, maybe UAC? I honestly have no clue right this moment.

I'll think it over some more while I eat my dinner; this is a really weird issue.

**Comment by emi-ann** [comment]
I did try rebooting.  

But it's okay, I think I finally figured out the problem.  

I had it set to open the last file I had open on start up.  For some reason, as soon as I disabled that, it opened no problem.  Still unsure of why that would cause it not to open, but it's working and that's all that matters to me.

Thanks for jumping in and helping me!

**Comment by worstje** [comment]
That is really weird. That setting should only start doing stuff later in the process...
