### ISSUE TITLE
References Mysteriously Delete in Summary and Reference/Notes Fields

### ISSUE THREAD

**Issue by opensourcefiction** [olivierkes/manuskript#688]
I've really been enjoying how Manuskript has matured over the last few years. I recently imported a project from ZimWiki and have really appreciated the fiction-specific  features Manuskript offers over Zim. It's also much easier to tag scenes with metadata than in Bibisco. 
Right now I am using Manuskript 0.10.0 on Linux Mint 18.2.

An issue I've been encountering is when I attempt to tag all my scenes with relevant metadata using references. I started making a list of characters in each scene, important objects, and plot threads in the references tab. Sometimes it went great, other times I would have completed the entire list, attempt to make a new reference, or click in the field, and everything would be deleted (including text that was not a reference, such as a note). As a work around I tried doing the same in the Summary field, with similar results. I have yet to be able to find the consistency in the bug (as in, which actions will definitely lead to the mysterious deletion).

Does anyone have any insight into this issue? Thanks in advance!

**Comment by worstje** [comment]
No insights other than that I noticed the same thing happening yesterday. I haven't used the notes / references field in a while, so I don't know if it is something new or if it goes back a little ways.

All I know is that sometimes things would stick around, and sometimes it would be in a hurry to poof again. Really annoying.

**Comment by obw** [comment]
Could it be the same Error as in my Issue? #670

**Comment by worstje** [comment]
@obw It could be, good point! I hadn't associated it with your report because I thought you were talking about the 'Summary' field as opposed to the 'Notes / References' field.

There's definitely some searching that needs to be done on this issue.

**Comment by Cuillerechan** [comment]
It seems to happen precisely when the "insert reference" is activated, which is how I find myself with something like 
![image](https://user-images.githubusercontent.com/4191253/68965061-33696980-07db-11ea-904d-dd7c19623b8c.png) : All previous text has just disappeared.

**From what I can tell**, it does seem to happen with all types of references, but only when using the ctrl+SPACE shortcut (versus the use of the context menu) and only when there is already text written (that it will use to look up the reference).

I also noticed that even though the ctrl+z shortcut usually works in there, when the bug happens, the shortcut is unable to go back and undo the accidental delete.

Hope this might help :)

**Comment by worstje** [comment]
I have had the deletion happen without relying on the popup or Ctrl+V. All I did was paste a few links which would mysteriously disappear. So I am not sure it is the Ctrl+Space or popup itself that is at fault.

**Comment by Cuillerechan** [comment]
mmm, I wonder what you call the popup? Is that the context menu? 
![image](https://user-images.githubusercontent.com/4191253/68974665-92d27400-07f1-11ea-97ac-99c361fd986d.png)
When you say you pasted a few links, is it that you copy pasted the "{W:0:World}"?

**Comment by worstje** [comment]
Nah, I literally mean that I Ctrl+V-pasted some http://... link to some clothing outfits for reference purposes while writing. No special Manuskript reference; just some ordinary text got pasted.

With the popup I meant the Ctrl+Space insert reference selection thingy that you can pop up. Sorry for my unclear verbiage.

My point was that it seems to be something deeper than entry into the field itself.

**Comment by Cuillerechan** [comment]
Ok, interesting! Thank you for the clarification! I may make a few additionnal tests tomorrow with this into consideration!
So when you use the ctrl+SPACE shortcut to insert reference, how do you look up the reference? Do you write inside the "popup" or do you write before you use the shortcut? Do you use both?

**Comment by worstje** [comment]
I haven't used the actual 'insert reference' feature in Manuskript in a while. My big story has been shelved for quite some time because I got distracted with bugfixes and short stories which don't need that kind of planning.

All I did to cause it to be removed was paste links and perhaps press enter once or twice. That's literally all.

**Comment by opensourcefiction** [comment]
I have primarily used ctrl + space, then typed the first few letters of the reference, then hit enter. I've experienced the mysterious deletion when inserting a reference in this manner, and when using copy/paste (for instance when I know a scene has most of the same characters/objects/plots as another, and only needs some minor editing).

Going to go experiment a bit...

###Data
Try 1: Copy/paste list of references immediately deletes without further action.
Try 2: Copy/paste list of references  immediately deletes without further action.
Try 3: Successful copy/paste functions.
Try 4: Insert references using ctrl + space, type first characters of reference, select with arrow keys. Functions normally for two references. Switch to Character tab to look up character name. Inserts three more references normally.
Try 5: Next scene. Copy/pastes list of references from last scene normally. 
Try 6: Attempt to insert reference via ctrl-space, everything disappears! Ctrl-z does nothing! Catastrophe!
Try 7: Successful copy/paste same list. 
Try 8: Successfully insert 2 references via ctrl-space.
Try 9: Attempt to insert 3rd reference via ctrl-space. Everything deletes! This is the really frustrating part. I have to go back and reconstruct what I've already done. At the time of the bug I made a typo and was typing fast and attempted to backspace, but might have gotten the backspace key mixed up in keystrokes for ctrl + space. Will test further.
Try 10: Successful copy/paste same list.
Try 11: Successfully insert two references.
Try 12: As an experiment, tried hitting ctrl + backspace. Everything deletes! But at least that sort of makes sense.
Try 13: Copy/paste success. 
Try 14: Delete reference. Insert reference via ctrl + space deletes everything.
Try 15: Repeat of Tries 13 & 14.
Try 16: Copy/paste success.
Try 17: Successful insert reference via ctrl + space. _Then_ delete other reference. No mysterious deletions.
Try 18: Insert reference via ctrl + space deletes everything.
Try 19: Copy/paste success. 
Try 20: Successful insert via ctrl + space.
Try 21: Delete reference. Successful insert via right-click menu.
Try 22: Successful insert via ctrl + space.
Try 23: Sucessful insert via ctrl + space.
Try 24: Delete reference. Successful insert via ctrl + space.
Try 25: Save project, close Manuskript, restart program. Next scene. Successful copy/paste.
Try 26: Successful insert reference via ctrl + space.
Try 27: Fiddle with formatting in refences field. Notice a comment in editor field is not properly formatted, fix, save. Insert via ctrl + space deletes everything.
Try 28: Successful copy/paste. Delete several references. Successful insert of 2 references with ctrl+space.
Try 29: Type three words on three lines in summary field. First time ctrl + backspace deletes previous word. 2nd time deletes entire field.
Try 30: Try three words on same line in summary field. Ctrl + backspace deletes one word at at ime.
Try 31: Repeat of try 29.
Try 32: Type words with markdown formatting (**bold** and - list), which is how I format list of references. Ctrl + backspace deletes entire field.

I hope that will give some helpful data for the code contributors. As a layperson the bug seems difficult to duplicate under the exact same circumstances, but there might be a pattern hidden there somewhere. I saw two patterns that cover some, but not all, of the spontaneous deletions.

###Patterns
Some of my experiences of everything being deleted could have been due to typing too fast and backspacing to delete a typo, and mixing up the keys with the ctrl-space keybinding. When I test the ctrl-backspace keybinding in Zim Wiki, Firefox, and LibreWriter, it deletes the previous word, but not the entire field. So apparently this is a standard keybinding I was not aware of. But it appears to be functioning atypically in Manuskript (unless that's normal behavior for markdown?). Any mix-up with keybindings, however, does not explain the other instances. 

The second pattern seemed to be that I could duplicate the spontaneous deletion more often if I first deleted an irrelevant reference (using backspace), _then_ tried to insert a new reference. I did this several times earlier in my trial/errors, but I hadn't noticed the correlation yet so I didn't record it until I noticed it. This doesn't seem to account for all spontaneous deletions, either, though.

###Misc

Overall ctrl + z does work in the references field, but for some reason it doens't work with these mass deletions, so the deleted references and notes cannot be recovered.

I was not able to duplicate the case where simply by clicking in the reference field everything deleted, but that did happen to me on several occasions before. I've also had the summary field delete simultaneously during past sessions.

For the record, I think needing to choose "insert reference" from the right-click menu would make the insert references feature too cumbersome to use for me.

Thanks for everyone's time and effort regarding this issue!

**Comment by obw** [comment]
#706 - this Patch solve this Problem!

If merged with develop and master Branch, this Bug can be closed!

**Comment by gedakc** [comment]
Closing as fixed by PR #706.
