### ISSUE TITLE
Main major and minor character are not functional

### ISSUE THREAD

**Issue by y2us** [olivierkes/manuskript#698]
Hi!

When creating a new character, the minor, main and secondary can't be selected.
All characters ends in minor section.

The slider to select he character importance level is inoperant.

Thanks,
Problem spoted on Arch Linux, Awesome Window manager, Manuskript 0.10.0

**Comment by avasilescu** [comment]
Hi,

I haven't tested it on Arch Linux, but i have tested Manuskript 0.10.0 on Windows 10 x64 and OSX Catalina with this issue. 

The Character Importance Slider effectively has 3 positions (minor, secondary, and main). Minor is all the way to the left. Secondary is in the middle. Main is all the way to the right. There are no in between positions other than those 3. It is not a gradual transition. Can you try the slider again and move it, by grabbing the actual slider, all the way to the right?

Thanks

**Comment by TheFeshy** [comment]
I'm another Arch user, and tested this on 0.11.0.  The slider appears to work fine for me.

**Comment by TheJackiMonster** [comment]
Works fine on my Arch too (tested version: 0.11.0) using Gnome 3.
