### ISSUE TITLE
text editor needs italic and bold

### ISSUE THREAD

**Issue by clintmbishop** [olivierkes/manuskript#705]
The text editor looks really good. I love the font and spacing and margin options. But the one thing I don't see, which is REALLY REALLY necessary for a writer, is the ability to put text in italic mode. Th software has so many amazing options, but I'm really amazed that something straightforward as basic italic and bold formatting is not allowed. You need italics for writing inner dialogue. It's essential.  Please put that in. Thanks.

**Comment by obw** [comment]
Well it use markdown.

**bold** and *italic*, the Editor also render this visually.

Have a look at:

- Menu -> Edit
  - Format

There are all standard markdown formats listed.

When you export this will be converted.

**Comment by gedakc** [comment]
Closing issue and labeling as **invalid** because Markdown already supports **bold** and _italic_ as mentioned by @obw.
