### ISSUE TITLE
All types of export with pandoc fail with error 97

### ISSUE THREAD

**Issue by wrtrtstr** [olivierkes/manuskript#709]
No matter what format I choose, the message from stderr says:
pandoc: Could not find data file /usr/share/pandoc/data/templates/default.*

The files, however, are there:
$ ls -l /usr/share/pandoc/data/templates/
total 144
-rw-r--r-- 1 root root  429 Jan 26  2018 default.asciidoc
-rw-r--r-- 1 root root 7483 Jan 26  2018 default.beamer
-rw-r--r-- 1 root root  218 Jan 26  2018 default.commonmark
-rw-r--r-- 1 root root 3708 Jan 26  2018 default.context
-rw-r--r-- 1 root root  719 Jan 26  2018 default.docbook
-rw-r--r-- 1 root root  569 Jan 26  2018 default.docbook5
-rw-r--r-- 1 root root  130 Jan 26  2018 default.dokuwiki
-rw-r--r-- 1 root root 4307 Jan 26  2018 default.dzslides
-rw-r--r-- 1 root root 1332 Jan 26  2018 default.epub
-rw-r--r-- 1 root root 1329 Jan 26  2018 default.epub3
-rw-r--r-- 1 root root    7 Jan 26  2018 default.haddock
-rw-r--r-- 1 root root 1581 Jan 26  2018 default.html
-rw-r--r-- 1 root root 1502 Jan 26  2018 default.html5
-rw-r--r-- 1 root root 1851 Jan 26  2018 default.icml
-rw-r--r-- 1 root root 7548 Jan 26  2018 default.latex
-rw-r--r-- 1 root root  512 Jan 26  2018 default.man
-rw-r--r-- 1 root root  218 Jan 26  2018 default.markdown
-rw-r--r-- 1 root root  130 Jan 26  2018 default.mediawiki
-rw-r--r-- 1 root root 2097 Jan 26  2018 default.opendocument
-rw-r--r-- 1 root root  244 Jan 26  2018 default.opml
-rw-r--r-- 1 root root  295 Jan 26  2018 default.org
-rw-r--r-- 1 root root  218 Jan 26  2018 default.plain
-rw-r--r-- 1 root root 7365 Jan 26  2018 default.revealjs
-rw-r--r-- 1 root root  501 Jan 26  2018 default.rst
-rw-r--r-- 1 root root  586 Jan 26  2018 default.rtf
-rw-r--r-- 1 root root 2541 Jan 26  2018 default.s5
-rw-r--r-- 1 root root 2782 Jan 26  2018 default.slideous
-rw-r--r-- 1 root root 1984 Jan 26  2018 default.slidy
-rw-r--r-- 1 root root  741 Jan 26  2018 default.tei
-rw-r--r-- 1 root root  763 Jan 26  2018 default.texinfo
-rw-r--r-- 1 root root  103 Jan 26  2018 default.textile
-rw-r--r-- 1 root root  182 Jan 26  2018 default.zimwiki

I installed Manuskript via the normal process using the standard "Ubuntu Software" tool. My setup is:

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

$ apt -qq list pandoc
pandoc/bionic,now 1.19.2.4~dfsg-1build4 amd64 [installed]

$ snap list manuskript
Name        Version  Rev  Tracking  Publisher  Notes
manuskript  0.10.0   187  edge      twom       -

**Comment by gedakc** [comment]
I am unfamiliar with whether a snap package can access locally installed programs like pandoc.  If not then perhaps this is a snap packaging issue.  @tomwardill might be able to answer this question more accurately.

You might try [downloading and installing manuskript-0.10.0.-1.deb](https://www.theologeek.ch/manuskript/download/) which is for debian based distros like Ubuntu.  I use this on Kubuntu 18.04.

**Comment by tomwardill** [comment]
This is probably due to the isolation of snap applications. I'll have a look at this when I get chance, I'm not sure immediately what the answer is.
