### ISSUE TITLE
[Request] Additional Package formats: AppImage (also note Flatpak, Snap)

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [olivierkes/manuskript#71]
Just cloning the repo and running from there via terminal works out-of-the box on my current (Ubuntu Gnome 16.04) system, but not on my test (Bodhi Linux 3.0) system. Both are debian-based, so I can follow the apt commands and make it work just fine.

However. Not every linux system is debian based and newbs may balk at trying to figure out how to get dependencies installed.

Furthermore. It doesn't integrate into the menu system or become a friendly double-clickable application from GUI if run from local git.

What's the chance you can package as an [AppImage](http://appimage.org/) for linux? That would be tremendously helpful. It also means never having to deal with distro packaging.

**Comment by olivierkes** [comment]
Thanks,

I tried to offer "friendly double-clickable" application in the past with pyInstaller (you can still get 0.3.0 this way on http://www.theologeek.ch/manuskript/download/), thing is that as soon as it is obsolete i get dozens of bug requests for features that have been corrected, because i don't have the time to update packages all the time...

Especially now that manuskript is in development, this is not a priority.

But i'll look into AppImage in the future, thanks.

**Comment by ParaplegicRacehorse** [comment]
Ok. I created a branch on my local and I'll start doing some work on it.

Incidentally, version control (git?) integration in the program would be wonderful!

**Comment by olivierkes** [comment]
There's a system of "version control" within the program (called "revision", though i think i should change that). Also you can save your whole project in plain text, in a VSC-friendly format: http://www.theologeek.ch/manuskript/2016/03/31/open-plain-text-file-format/

**Comment by olivierkes** [comment]
As for the AppImage thing, if anyone wants to try it that would be great !

**Comment by fethomm** [comment]
There is also Flatpak and Snap, which should offer more security and slightly smaller packages than AppImage.

**Comment by taw00** [comment]
I'm on Fedora. And I thank you for the Fedora native packaging. Thank you, thank you, thank you!

On my to-do list is to convert an RPM I currently maintain into a flatpak (note: I think of all the container-ish formats, flatpak is superior -- my opinion). If I have time (and that is a big if), I will flatpak-ify manuskript as well. Regardless, thanks for what you are doing. -t

**Comment by TheJackiMonster** [comment]
The flatpak package was now accepted on flathub (as mentioned in #958). So I would now close this issue. Problems with the current snap or flatpak package can be reported separately.

**Comment by ParaplegicRacehorse** [comment]
I don't know if this project is using Github actions for automated builds, but:

https://github.com/AppImageCrafters/build-appimage

Docs: https://appimage-builder.readthedocs.io/

**Comment by TheJackiMonster** [comment]
@ParaplegicRacehorse I'm unsure if we still need an additional appimage but I will have a look. Thanks for the hint.
