### ISSUE TITLE
word count

### ISSUE THREAD

**Issue by queuingforsarnies** [olivierkes/manuskript#72]
This is a great project and 0.3 has worked out of the box for me on LinuxMint 17.2 Mate. Thank you!

My current project requires a precise word count and I have noticed that Manuskript's totals are different to other text editors. Spaces at the end of paragraphs and blank lines (carriage returns) appear to count, when in my view they shouldn't. 

Thanks again!

**Comment by olivierkes** [comment]
Thanks. 
To make things quicker, can you provide explicit examples with wrong word count and expected word count?

**Comment by queuingforsarnies** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/24740577/21466948/bef859f8-ca2a-11e6-8c75-0a60dc76c0bf.png)

See attached -- you can see that the spaces indenting the lines in manuskript deliver a significantly higher word count! thanks.

**Comment by olivierkes** [comment]
Thanks, fixed in develop.
