### ISSUE TITLE
Can someone create a Facebook Group for Manuskript users to share tips and techniques 

### ISSUE THREAD

**Issue by DrKMRice** [olivierkes/manuskript#720]
I have been working to learn Manuskript for a month. There are a number of things that I do not know how to do that someone may be able to share or identify are not possible. I things GitHub is great for coders but I am not a coder I am a writer.

**Comment by gedakc** [comment]
Have you looked at the [Wiki](https://github.com/olivierkes/manuskript/wiki) where we share tips and tricks?  See also issue #656.

The product mentioned in the title is proprietary and does not align with free software goals.

**Comment by DrKMRice** [comment]
Mike would you mind if I started a group. This might also help build a bit
of publicity for the software and attract some new coders to help improve
the software.
