### ISSUE TITLE
[Feature Request] Word counter in full screen mode

### ISSUE THREAD

**Issue by Nasgarath** [olivierkes/manuskript#723]
I was surprised not to see the word counter in full screen mode.

If I set myself a goal to write until I reach, say, 200 words, I'm gonna want a way to know when I reach that goal without having to constantly switch out of full screen.

**Comment by obw** [comment]
This exists, just move you mouse to the bottom of the screen!

There will be the Wordcount, Theme selector and a clock, also with the Popup Menu you can deactivate the 'automatic disapear', I run it in German so I don't know exactly how it is labeld.

**Comment by Nasgarath** [comment]
Nice! Thank you ;)
