### ISSUE TITLE
[Feature Request] Alternate character counter

### ISSUE THREAD

**Issue by Nasgarath** [olivierkes/manuskript#725]
I write in both French and English. While the English market works with word counts, the French market is entirely focused on characters (spaces included).

It's not vital, because the word count would still give me a good sense of progress and once the piece is done I can open it in Word and get the character count from there... But it'd definitely be a nice and very convenient feature ;)

**Comment by obw** [comment]
This proposal exist with #607 Chinese/Korean and Japanese also need Charcount...

So this is a dupe...
