### ISSUE TITLE
Missing module when launching from github [Xubuntu 16.04.1 LTS]

### ISSUE THREAD

**Issue by Renkineko** [olivierkes/manuskript#73]
Hi,

I have some issues when I try to launch the project from the repository clone.

I probably haven't installed good packages, but I don't know a lot about python, pyqt, all of this stuff, so a bit of help (and maybe a documentation with this kind of problem and how to fix them) would be welcome.

I'm doing an issue because I suppose other people will want to try this amazing and promising project, and will probably run into the same problems.

So, let's begin : 

According to the documentation [found here](http://www.theologeek.ch/manuskript/download), I installed python3, python3-pyqt5 (and just in case, python3-pyqt5-dev) and python3-lxml packages. i then cloned the repository, and tried to launch bin/manuskript.

First error, I had "ImportError: No module named PyQt5".

I looked around the Internet, not a lot of solution according to my problem (the error is quite generic), so I tried to install pyqt4 just in case. Now, I have another error, but I don't know if it's a better one or not : 

ImportError: No module named 'PyQt5.QtWebKitWidgets'

(If you want all the stacktrace, ask, I can copy it anytime). According to [this thread](http://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5) it seems QtWebKitWidgets is going to disappear, so maybe I already have the disappeared version (but I don't know how to check which pyqt I use exactly).

EDIT: It seems I have the pyqt5 5.5.1, so I don't have the package with PyQt5.QtWebKitWidgets removed. So I don't understand why I have this error. END EDIT.

I also found that when I do "python", it links to python2.7 and not python3, but even when I did an alias for "python" to link it to python3, it doesn't change anything. I'm pretty sure I just did a lot of shit, so I'm asking humbly to your help.

Note: the version 0.3.0 is fully usable and I use it in the meantime, I would just like to test the develop version to see the ongoing changes. I don't want to create issues if they are already fixed by the dev without being listed in the issue list (like the formatting buttons not implemented yet, maybe you should just hide them until they are coded because it's a source of frustration to try the buttons and have no reaction :p and if you don't think to look at the console, you don't even know it's not implemented, you just think it's a bug or you're doing something wrong ^^).

Anyway, good job, I don't really understand all the software but i'll see and/or ask this later.

**Comment by Renkineko** [comment]
It seems I have the pyqt5 5.5.1, so I don't have the package with PyQt5.QtWebKitWidgets removed. So I don't understand why I have this error.

**Comment by Renkineko** [comment]
Okay, I just feel very dumb. I just had to install python3-pyqt5-webkit to make it works =_=

But, i have another error and it seems more linked to the engine itself: 

```
Found translation in settings: /home/detritus/projects/manuskript/i18n/manuskript_fr.qm
Loaded translation: /home/detritus/projects/manuskript/i18n/manuskript_fr.qm.
Traceback (most recent call last):
  File "bin/manuskript", line 13, in <module>
    main.run()
  File "/home/detritus/projects/manuskript/bin/../manuskript/main.py", line 63, in run
    launch()
  File "/home/detritus/projects/manuskript/bin/../manuskript/main.py", line 67, in launch
    from .mainWindow import MainWindow
  File "/home/detritus/projects/manuskript/bin/../manuskript/mainWindow.py", line 24, in <module>
    from manuskript.ui.mainWindow import Ui_MainWindow
  File "/home/detritus/projects/manuskript/bin/../manuskript/ui/mainWindow.py", line 1327, in <module>
    from manuskript.ui.cheatSheet import cheatSheet
  File "/home/detritus/projects/manuskript/bin/../manuskript/ui/cheatSheet.py", line 12, in <module>
    from manuskript.ui.cheatSheet_ui import Ui_cheatSheet
ImportError: cannot import name 'Ui_cheatSheet'
```

**Comment by olivierkes** [comment]
Do you still have that error?

**Comment by Renkineko** [comment]
Not anymore, both develop and 0.3 version works perfectly. Thanks :)

**Comment by Emstanif** [comment]
How did you install python3-pyqt5-webkit to fix that error? I can't seem to find anything on it. I'm getting
ImportError: No module named 'PyQt5.QtWebKitWidgets'

**Comment by gedakc** [comment]
For Debian/Ubuntu users, install PyQt5.QtWebKitWidgets with:

`sudo apt install python3-pyqt5.qtwebkit`

For more information on other OSes, see the articles on _Running Manuskript from Source Code_ on the [Manuskript Wiki](https://github.com/olivierkes/manuskript/wiki).

**Comment by Emstanif** [comment]
I followed the instructions for mac os but still get the error 
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
When I try to brew the webkit:
brew install python3-pyqt5.qtwebkit
but brew can't find it. So I can't run 0.4.0 I haven't tried 0.3.0 yet.
I'm sure I'm missing something simple but I'm new to installing from source files.

**Comment by gedakc** [comment]
I think Mac OS X no longer has QtWebKitWidgets.  See [Issue 35 - Not Working on Mac](https://github.com/olivierkes/manuskript/issues/35).

More importantly scroll down near the bottom of Issue #35 and you will find a PyInstaller package created by @katafrakt.  Please try the package and comment in that issue thread.

**Comment by olivierkes** [comment]
Did you follow the instructions from the wiki? https://github.com/olivierkes/manuskript/wiki/Run-manuskript-on-OS-X because `brew install python3-pyqt5.qtwebkit` is not part of it. 

Be sure to try the test version (at the very bottom of the wiki page).

**Comment by katafrakt** [comment]
@Emstanif Please try the package @gedakc mentioned or try to run from `develop` branch.

However, if you insist on trying QtWebKit, you can build it with `brew install qt --with-qtwebkit`, but be warned that it takes a couple hours (5 on my MacBook Pro). There is also another package with qt presumably prebuilt, but I haven't tried that: https://github.com/ninech/homebrew-qt

Anyway, it would just be for the best if non-QtWebKit version worked for you :wink:
