### ISSUE TITLE
Creating multiple worlds

### ISSUE THREAD

**Issue by DrKMRice** [olivierkes/manuskript#734]
I am working on a trilogy that has multiple worlds. Is there a way to create multiple worlds with this program? Based on what I am seeing it cannot be done. Does anyone have a suggestion?

**Comment by obw** [comment]
I'm also preparing somthing with different realities, my Solution is:
**Realities**
- Reality 1
  - Rules
    - Rule 1
    - ...
  - Worlds
    - World 1
    -...
- Reality 2
  - Rules
    - Rule 1
    - ...
  - Worlds
    - World 1
    -...
- Reality 3
  - ...

You can a Tree of nearly invinity deoth;)

**Comment by TheJackiMonster** [comment]
Should be possible to do that since you can use custom structure in your plot. Do you miss any feature for that in particular? Otherwise this issue could be closed.
