### ISSUE TITLE
Error on export when using pandoc

### ISSUE THREAD

**Issue by StraightupNope** [olivierkes/manuskript#736]
I'm using Manjaro, everything is up to date.
Given my results when putting the error into a search engine. It's probably pandoc being updated which is causing this issue. (seems the function in question is now deprecated. 
Anyway, this happens exactly the same regardless of what file type I try to export to, so long as it uses pandoc. I've tried this with multiple projects to test if it's not something goofy I've done; same result each time.
I also tried to roll back pandoc to an earlier version, but that just causes manuskript to crash when trying to load the compile window. I'm guessing I need to roll back more than just the pandoc package itself, but I don't have a clue which ones else. It's doing my head in.

```
ERROR on export
Return code: 0
Command and parameters:
['pandoc', '--from=markdown', '--to=odt', '--toc-depth=1', '--base-header-level=1', '--output=/home/nope/Documents/ttt.odt', '--variable=title:An Album', '--variable=author:Nope', '--metadata=title:An Album']
Stderr content:
[WARNING] Deprecated: --base-header-level. Use --shift-heading-level-by instead.
```

**Comment by tomwardill** [comment]
Do you know if you have manuskript installed from snap? (You can check with `snap list`).
This looks similar to https://github.com/olivierkes/manuskript/issues/709

**Comment by StraightupNope** [comment]
It's definitely not from snap. I don't even have snap installed.
The version of manuskript I have is from the AUR, (which is currently the one on Git, 0.11. <long string of numbers>)
As I said, it seems to be related to a change introduced in Pandoc 2.8. (I found some info here: [https://ci.stackage.org/package/pandoc](url)
Also, according to that page, said change was rolled back in Pandoc 2.8.1, but the Pandoc currently on the repo (which I have) isn't up to that version yet. I'm gonna try upgrading Pandoc and see what happens.

**Comment by StraightupNope** [comment]
Okay, updating Pandoc to 2.9.1 (or whatever the latest currently is) did nothing. I got the exact same error as before.
But, after much frustration and effort. I managed to install an older version of Pandoc (2.7.2) and everything works fine. 
Please note: I did not update, reinstall, or otherwise change Manuskript itself. It seems the issue is indeed as described in the error itself. base-header-level function (whatever that is) now being depreciated could spell trouble if and when other distros update pandoc in their repos. I searched around, and it seems most others (Ubuntu, Debian, Fedora) are no higher than pandoc 2.5 while Arch (and thus, Manjaro)  has Pandoc 2.8 (and 2.9.1 in the AUR)

**Comment by Macte-Kodama** [comment]
Hi, 

I'm facing the same error, with the same error message. In addition, I have to say I cannot export in any format at all: if I choose HTML export for instance (with the the native tool) nothing actually happens when I click on "Save", after choosing directory and file name. 
I am clearly less advanced than you are on understanding how to install a previous version of pandoc or fixing these kinds of issues by myself, is there anyone who could explain me how to solve this problem? Right now, I cannot use this promising software if I cannot export anything.
I am running on Eoan 19.1, GNOME 3.34.2 64bits. 
Sorry if I don't provide enough details about my situation, please let me know if I can add something (and how to do it!).

**Comment by rafaelteb** [comment]
Hello there! 
Im having the same problem. Got Arch Linux and GNOME. Can send more details when you need them! Only pandocs does not seem to work. Plain text, html and markdown are good. I love manuskript!
xx

**Comment by StevenDStanton** [comment]
I am using Manuskript on Windows 10 Pro and when I export the export works but I get the same error

ERROR on export
Return code: 0
Command and parameters:
['pandoc', '--from=markdown', '--variable=documentclass:article', '--variable=linestretch:1', '--standalone', '--base-header-level=1', '--pdf-engine=pdflatex', '--variable=papersize:letter', '--variable=fontsize:12pt', '--toc-depth=3', '--to=latex', '--output=D:/Projects/writing/x/compiled/RD 1.pdf', '--metadata=title:']
Stderr content:
[WARNING] Deprecated: --base-header-level. Use --shift-heading-level-by instead.

**Comment by FlawlessMiner** [comment]
I am experiencing this too.

OS: Arch Linux (`Linux primary 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux)
Pandoc version: `pandoc 2.10.1 Compiled with pandoc-types 1.21, texmath 0.12.0.3, skylighting 0.8.5`
Manuskript version: `0.11.0.r0.g12defa8-2` (from Git/AUR) AND `0.11.0` (checked both version, doesn't work on either)

**Comment by Spounka** [comment]
Same problem here, I get this
ERROR on export
Return code: 0
Command and parameters:
['pandoc', '--from=markdown', '--standalone', '--toc-depth=3', '--base-header-level=1', '--pdf-engine=pdflatex', '--variable=papersize:letter', '--variable=fontsize:12pt', '--variable=documentclass:article', '--variable=linestretch:1', '--to=latex', '--output=/tmp/msk_pdfpreview.pdf', '--variable=title:Rebirth', '--variable=subtitle:The mystery of life', '--variable=author:xxx', '--metadata=title:xxx']
Stderr content:
[WARNING] Deprecated: --base-header-level. Use --shift-heading-level-by instead

Note: I changed the author and title content to xxx from the original ones

My System:
Linux VonSchpeiner 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux

Manuskript: 0.11.0
Python 3.8
PyQt 5.15
Qt 5.15.1

pandoc --version:
pandoc 2.11.0.4
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10,
citeproc 0.1.1, ipynb 0.1.0.1

**Comment by emgineering** [comment]
If anyone else runs into this: it's only a warning, not a fatal error. The files should have exported to the designated location anyway (I tried exporting to docx and pdf and was able to open both, despite getting a dialog with the same error come up on exporting)

Once it's accepted, pull request #790 will probably resolve the dialog appearing.

**Comment by Spounka** [comment]
I solved it by modifying the code to use the new function
I can post it here if anyone's interested

**Comment by obw** [comment]
> I solved it by modifying the code to use the new function
> I can post it here if anyone's interested

@Spounka: I think a lot of People love to see this solution!

**Comment by Spounka** [comment]
@obw Here's my fix:
- Open up /usr/share/manuscript/manuskript/exporter/pandoc/abstractPlainText.py
- Go to line 111 ( where it says "base-header": pandocSetting
- Change "--base-header-level=" to "--shift-heading-level-by="
You will no longer see errors
There seems to be one small issue, where trying to preview pdf when using binaries from my repo i get no preview, but when i use the binaries from this repository, i can get pdf preview easily

**Comment by FirstHokage** [comment]
> 
> 
> @obw Here's my fix:
> 
>     * `Open up /usr/share/manuscript/manuskript/exporter/pandoc/abstractPlainText.py`
> 
>     * Go to line 111 ( where it says `"base-header": pandocSetting`
> 
>     * Change `"--base-header-level="` to `"--shift-heading-level-by="`
>       You will no longer see errors
>       There seems to be one small issue, where trying to preview pdf when using binaries from my repo i get no preview, but when i use the binaries from this repository, i can get pdf preview easily

Can't find the same file in Windows version. There's only 99 MB pandoc executable.
