### ISSUE TITLE
Character Importance

### ISSUE THREAD

**Issue by qantravon** [olivierkes/manuskript#739]
The way of changing character importance is a little counter-intuitive, especially when taken as a whole with the rest of the program. In World or Outline, we can just drag+drop things into whatever category we need them in, but Characters have a slider on each one that changes their category. It would be more consistent if we could just drag the character into the desired category from the list.

Additionally, it would be useful if, when adding a character, it would take the currently selected category into account (for example: if I click on Major before clicking the + button, it should add the new character to the Major category).

**Comment by TheJackiMonster** [comment]
The first part was also mentioned in this earlier issue  #321. But the changes to adding a character are new and would be quite useful.

**Comment by TheJackiMonster** [comment]
The first part of this issue is a duplicated of #321. So I would close this issue here already because the second part was implemented.
