### ISSUE TITLE
Can't run Manuskript

### ISSUE THREAD

**Issue by nitishabharathi** [olivierkes/manuskript#742]
I tried to run manuskript source file by following the instructions given in Wiki(https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows)
I am unable to do it
I get the following error

File "manuskript", line 11, in <module>
    from manuskript import main
  File "E:\sem8\oss\manuskript\bin\..\manuskript\main.py", line 8, in <module>
    import manuskript.ui.views.webView
  File "E:\sem8\oss\manuskript\bin\..\manuskript\ui\views\webView.py", line 34, in <module>
    from PyQt5.QtWidgets import QTextEdit
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by gedakc** [comment]
What version of Windows are you using?

Which install steps did you use?   [The ones at the start of the wiki](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows#installation), or those in the [wiki appendix](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows#appendix-a--install-required-software-packages-on-windows-7-and-higher)?

Did you install 32 bit packages or 64 bit packages (all packages must match)?

Without additional details it is difficult to help.

**Comment by nitishabharathi** [comment]
I am using Windows 10 64 bit Operating System and I followed Appendix A.
packages installed are also for 64 bit but my Python version is 3.7
Could it be because of the Python version?

**Comment by gedakc** [comment]
It is possible there is an issue with the Python package version.  Personally I use the package versions that I specified in the [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) wiki.

The error message seems to imply an incompatibility between 64 bit and 32 bit packages.  The packages must either be all 32 bit, or all 64 bit to work.
