### ISSUE TITLE
Metadata: References

### ISSUE THREAD

**Issue by sirtinypup** [olivierkes/manuskript#756]
First off just started using manuskript and it is amazing.  As I am figuring more items out and work with the storylines and metadata references I have 2 issues.  First when I right click for insert references or ctrl + space, the references open with what appears as a search bar.  Now just say I type in "Characters" no search actually happens if it is a title item so same for "Plot" and if you hit enter with nothing selected and just the searched term this closes the entire program down.

**Comment by TheJackiMonster** [comment]
> this closes the entire program down.

Do you mean it crashes? Can you start manuskript via terminal or command line to post the output if it crashes?

**Comment by TheJackiMonster** [comment]
I can't reproduce a crash like this. Please reopen if you still encounter the issue.
