### ISSUE TITLE
Can't open any file

### ISSUE THREAD

**Issue by RedStudio-21** [olivierkes/manuskript#758]
Hello,

I've a PC desktop with Kubuntu 20.04 LTS.
Manuskript has always gone well without problems, I used it on windows 10 and also Ubuntu 20.04 LTS. 
 Today I tried on Kubuntu (SO and everything installed as new): after downloading the packages from the site and installing manuskript-0.11.0-1.deb, when I opened the program, in the initial screen I cannot open any file, neither new nor saved.
At the bottom of the window it says that the file has loaded, but nothing opens.
 I tried to uninstall and reinstall it from the site package, and also from the software center... but no results.

Any ideas?

I attach screenshots:

![Screenshot 1](https://user-images.githubusercontent.com/60318338/80288456-5b6cd980-8738-11ea-9008-d20aef29a16b.png)

![Screenshot 2](https://user-images.githubusercontent.com/60318338/80288477-8c4d0e80-8738-11ea-9ca8-f72bf158383d.png)

Thanks

**Comment by gedakc** [comment]
You might try opening a terminal window (Konsole), run `manuskript` from there, and then provide the console output to help troubleshoot the issue.

Manuskript worked for me when I tested installing it on Kubuntu 20.04.  I followed the steps on the [Manuskript Download](https://www.theologeek.ch/manuskript/download/) page.

For me the steps were:
```
sudo apt update
sudo dpkg -i ~/Downloads/manuskript-0.11.0-1.deb
sudo apt install -f
sudo dpkg -i ~/Downloads/manuskript-0.11.0-1.deb
```

Next I started manuskript, selected **Novel** for a template, clicked the **Create** button, typed in a project name, clicked **Save**, and the new project opened up in Manuskript.

**Comment by RedStudio-21** [comment]
Thanks for the quick answer!
But I still have some problems...

-At the first step, I did as you said:
![Screenshot 1](https://user-images.githubusercontent.com/60318338/80293838-89b3de80-8763-11ea-8598-d7c1c8c94f5a.png)

-Then I created a new document (novel), which I called Test;
I managed to create and save it, but when I close the program and reopen the document (Test), it gives me the same error. I tried again, trying to open my own project:
![Screenshot 2](https://user-images.githubusercontent.com/60318338/80293854-c2ec4e80-8763-11ea-94c2-cd40ba3be81c.png)
![Screenshot 3](https://user-images.githubusercontent.com/60318338/80293874-d3042e00-8763-11ea-9309-26e210902031.png)

In screenshots 2 and 3 I see that there are problems, but I don't know a solution ...Sorry but I'm not very experienced in these things, am I wrong to do something?

Until now I have always used Manuskript on Ubuntu without problems.
The only change I made was to format the PC and install Kubuntu in dual boot with Windows 10; apart from this problem with Manuskript, everything is fine.
The archive of my projects is always the same as before, what did I do wrong?

Thanks again ;)

**Comment by gedakc** [comment]
From looking at the screen shots there appear to be two problems.

The first problem is the `SyntaxWarning: "is not" with a literal. Did you mean "!="?`.  This warning does not stop manuskript from running, but does indicate an issue with the manuskript code base that will need to be addressed to work with Python 3.8.2 that ships with Kubuntu 20.04.

The second problem, and the reason why manuskript fails to load the project, is the `Warning ! There are some items with same id ...`.  These duplicate ids are a problem for manuskript because each piece of the project (for example a chapter or a scene) **must** have a unique identifier so that manuskript can keep these separate.  There is at least one known outstanding bug that can cause this problem - see Issue #324.

If you have your project stored in a single file, then to get direct access to your work you can copy the project.msk file to project.zip and then unzip the project.zip.  If; however; you have the setting [Manuskript General Setting - Save to one single file](http://gedakc.users.sourceforge.net/display-doc.php?name=manuskript-novel-writing#t) disabled, then you can go directly into the project directory to access your work.

Unfortunately I don't have a simple answer for getting manuskript to load the project file to load again.
- Either the duplicate id issue will need to be manually corrected (a time intensive task that requires understanding the storage structure),
- Or you might consider recreating a new project and copying and pasting the text content of each scene, etc (also a time consuming task).

**Comment by RedStudio-21** [comment]
On this pc, I can only create a new project with the method you wrote, no backup or saved project opens.

If it can be useful: my project folder is organized in a tree; each .msk file is in its own folder:
Documents
|
Main folder of projects
|
Specific project folder
|
.Msk file

The strange thing is that I have a laptop (much older and much less performing than the desktop PC) in which I installed the same Linux distribution, using the exact same archive of .msk projects, and there manuskript works perfectly ...

Out of curiosity, can you tell me why?

I believe that for the moment I will continue to use the laptop, until a more comfortable solution is found

Fortunately this laptop is not dead yet;)

If you find something, keep me updated.
Anyway thanks for the answers

**Comment by gedakc** [comment]
> Out of curiosity, can you tell me why?

If both PC's are using the same operating systems and versions and the same Manuskript project version, then there must be something else different such that one works (no duplicate IDs) and the other does not work (has duplicate IDs).  You might try completely erasing the project from the PC that is not working, and then copying the project from the good PC to the non-working PC.

**Comment by RedStudio-21** [comment]
I have already tried to delete all the projects and copy them as you said, but it still doesn't work.

Anyway, just to report it, maybe I have found a way; now I describe step by step:

. I open manuskript from the terminal,
. From the initial interface I create a new 'Novel' document that I call "Test", and save it as a multiple file (save to one single file -> disabled) in a new folder called Test, in the manuskript folder, in documents,
. I close manuskript,
. I reopen manuskript from the terminal,
. I click Open and load an old project of mine called Struttura.Saggio.msk

![Screenshot 1](https://user-images.githubusercontent.com/60318338/80318516-09e14f00-880b-11ea-92f0-ab110df1bdaf.png)

This works with only that file.

I was thinking that my last option would be to format the partition with Kubuntu 20.04 and reinstall it as new.

Do you think it could be useful?

**Comment by gedakc** [comment]
I wonder why the method you tried in the post above was able to open the project without any duplicate IDs?

You might check to ensure that your userid has write access to the [Configuration Settings Storage Locations](https://github.com/olivierkes/manuskript/wiki/Configuration-Settings-Storage-Locations) before trying to re-install Kubuntu 20.04.

**Comment by RedStudio-21** [comment]
> You might check to ensure that your userid has write access to the Configuration Settings Storage Locations before trying to re-install Kubuntu 20.04.

I checked, user id has write access, I also tried with: "On GNU/Linux and Windows I have tried deleting these files / registry hive locations and by doing so I was able to reset Manuskript back to the default settings on the next startup of Manuskript."; but nothing changes...

**Comment by gedakc** [comment]
If you are willing to do do a re-install then it might be worth it.  Especially if a similar install of Kubuntu 20.04 worked on a different PC.  Somehow there must be a difference between the two PC's that we are not aware of.

**Comment by RedStudio-21** [comment]
Today I formatted the Kubuntu partition, I reinstalled manuskript and everything is going great!
Thank goodness I can reopen all the projects.
It may have been the fault of a bad installation of the operating system, or in any case of some errors during the setting phase.

I installed the program from the terminal, as recommended above, but unfortunately I forgot to take a screenshot. In any case the files open again, and I'm already happy.

If the same problem occurs again, can I report it here, or do I open a new post?

I thank you for the time and patience spent on this problem; I hope someone else can benefit from this post.

**Comment by gedakc** [comment]
Thank you for reporting back that a new OS install fixed the problem.  I guess something must have been amiss with the prior installation.  Anyway it's good to hear that Manuskript is working for you again.

> If the same problem occurs again, can I report it here, or do I open a new post?

Please feel free to open a new post if the problem occurs again.  I will close this report as you have resolved the issue (though whatever caused it we might never know).
