### ISSUE TITLE
Help! Can't open MSK.file

### ISSUE THREAD

**Issue by IceElf07** [olivierkes/manuskript#759]
Hi,

I downloaded manuskript a few days ago and began work on importing my file. It worked fine yesterday; however, when I tried to open it today the command box opened fine and then stopped. The text disappears too fast for me to read the issue. 

I've tried opening through the command portal but it just opens the new file screen rather than my project. It seems to be failing fairly early on at the translation stage. 

Please let me know if I can give any more information that might help? I'm desperate to get this file back.

**Comment by gedakc** [comment]
Please provide the operating system name and version you are using in addition to the manuskript version.

Based on your description I'll assume you are using Windows. 

If running on Windows, open a command prompt and invoke the manuskript.exe program from the command line and try to load your project.  Then copy the console messages from the command prompt and post them is this issue report so we can see what is happening.

**Comment by IceElf07** [comment]
I'm on Windows 10, using version 0.11.0

What would I need to type into command to get it to open a specific file? I can get it to open manuskript but that just takes me to the create a new project screen without any console messages. It won't open my file.

**Comment by gedakc** [comment]
1. Open a command prompt (Windows)
2. Change into the directory where you installed manuskript.  This is the directory in which the `manuskript.exe` executable can be found.  For example:
   ```
   cd C:\path\to\manuskipt
   ```
3. Invoke manuskript
   ```
   manuskript.exe
   ```
4. Try to load your project from the Manuskript GUI.

5. Copy and paste the output from the command prompt into this issue report so we can see what is occurring.

**Comment by IceElf07** [comment]
Thanks!

See below

Microsoft Windows [Version 10.0.18362.778]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Sara> cd C:\Users\Sara\Downloads\manuskript

C:\Users\Sara\Downloads\manuskript>manuskript.exe
Debug: Web rendering engine used: QWebView
Running manuskript version 0.11.0.
Preferred translation: ['en-GB', 'en-US'] (based on available ui languages)
Loaded translation: manuskript_en_GB.qm
Last accessed directory "C:/Users/Sara/Desktop" loaded.
Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 163, in openFile
  File "manuskript\mainWindow.py", line 572, in loadProject
  File "manuskript\mainWindow.py", line 861, in loadDatas
  File "manuskript\loadSave.py", line 58, in loadProject
ValueError: invalid literal for int() with base 10: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0

C:\Users\Sara\Downloads\manuskript>

**Comment by gedakc** [comment]
Because one of the console output lines indicates an error with `File "manuskript\loadSave.py", line 58, in loadProject` I assume that you have the manuskript general setting **Save to one single file** disabled.  Is this correct?

If so, have any non-manuskript files been placed in the _project_ folder (which should be at the same directory location as the _project_.msk file)?

If not, then the project exists in a single _project_.msk file.  You might try copying the project.msk file to project.zip to see if you can extract the contents to get direct access to your work.

**Comment by IceElf07** [comment]
When I open up a new project, the box for save to one single file is checked - I'm assuming that means its enabled?

I'm not sure what you mean by copying the file to a .zip file. It doesn't seem to be giving me the option to change the file type anywhere. Sorry - I'm a little confused.

**Comment by gedakc** [comment]
> When I open up a new project, the box for save to one single file is checked - I'm assuming that means its enabled?

Yes that means it is enabled, and hence all project data is stored in a single _project_.msk file.  This is the default Manuskript setting.

> I'm not sure what you mean by copying the file to a .zip file.

This is done outside of manuskript.  We are trying to determine if there is corruption in the project.msk file.

1. First close down manukript if it is running
2. Open a Windows Explorer (**Win**+**E**)
3. Navigate to where your _project_.msk file exists
4. Copy it and paste into the same location.  It should prompt for a new name.  call it _project_.zip
5. Now try double clicking on the _project_.zip file to see if it will open.
6. If not then the zip file is corrupted and will need to be repaired.

**Comment by IceElf07** [comment]
It's not prompting for a new name  - just automatically calling it file-copy.msk

**Comment by gedakc** [comment]
Okay, then try renaming file-copy.msk to file-copy.zip.  Then try double-clicking it to see if it will open.  If it does then it is a valid zip file format.

**Comment by IceElf07** [comment]
I'm getting a note saying that the archive is in an unknown format or damaged.

**Comment by gedakc** [comment]
Unfortunately that means that the file has somehow become corrupted, and is the reason why Manuskript can no longer load it.

The next step is to try run zip repair software on the file-copy.zip file to see if it can be repaired.  I don't use Windows, so can't suggest a tool to repair the file.  I suggest and Internet search on "Windows repair zip file" to find software to do this. Way back when I did use Windows I think I used a project called WinZip.

**Comment by IceElf07** [comment]
How that's happened between me saving and closing last night and trying to open this morning, I have no idea. 

Having so many regrets about downloading this software right now. 

I've tried to repair it using a couple of different software; however, when I try to extract the recovered file it says that it's empty.

**Comment by gedakc** [comment]
If the attempts to repair the file have all failed, then it doesn't look good for recovering the contents.  :-)(

If you have a backup of your project from when it was working then you might consider using that going forward.

**Comment by IceElf07** [comment]
Sadly, I'd not got round to backing it up. 

I've older versions, but they're so far back that it's depressing considering rewriting them. I've wasted three days and have nothing to show for it. 

Certainly won't be using Manuskript again.

**Comment by gedakc** [comment]
It sucks to lose work.  I can sympathize with your position.

Best wishes with your future writing endeavours.

**Comment by Mannshoch** [comment]
May a bit to late and as a general information. If [Shadow Copy](https://en.wikipedia.org/wiki/Shadow_Copy) is active on Windows 10 you are may able to get an older version of you files.
