### ISSUE TITLE
Is there a way to configure which dash and quote mark to use?

### ISSUE THREAD

**Issue by chloebrqt** [olivierkes/manuskript#764]
I've installed Manuskript yesterday and have started to use it, but I haven't found anywhere a way to configure which dash or quote mark to use. For the dialogues I'd like to use French quote marks (as I write in French) and em dash (instead of hyphen), and I would like it to be automatic (I don't want to use Ctrl+Alt+Something each time I want to use a quote mark or a dash). Is there a way to configure this in Manuskript?

I'm on Linux, Ubuntu (latest version), and use latest version of Manuskript (0.11.0).

**Comment by gedakc** [comment]
Manuskript uses [markdown](https://daringfireball.net/projects/markdown/).  Formatting occurs when the project is **Compile**d/exported.  See **Transformations** for handling ellipsis, em dash, or adding your own custom transformation.

![Manuskript-File-Compile-Transformations](https://user-images.githubusercontent.com/10405019/80919382-e5173b00-8d26-11ea-9343-5c99f63fd1ea.png)

**Comment by chloebrqt** [comment]
Ohh ok! Since I'm nowhere near to be ready exporting what I'm writting, I wouldn't have thought to look there. I'm glad to learn it's configurable.

Thanks for your fast answer! :)
