### ISSUE TITLE
Compile dialog issues: cancel doesn't seem to do anything, default ouput directory wrong

### ISSUE THREAD

**Issue by szopeno** [olivierkes/manuskript#77]
(1) I would suggest changing "compile" into "export". I am a programmer and I did wrote things in latex/lyx, so I guessed finally that "compile" will mean exporting into html/odt, but initially I searched all the options for few minutes, looking for a way to export into .odt 

(2) The initial default output directory "/home/olivier/Documents/Travail/ ... " should be changed in something sensible, for example "/home/${USERNAME}/Documents/

(3) After exporting, nice thing would be to actually fire up the external application (output dependent, e.g. firefox for html, soffice for .odt) to see the effect.

(4) In case of errors, a dialog should warn the user the error happened. Initially I clicked "compile", I saw no results and after scratching my head and examining the terminal output I find out the default output directory was wrong and hence, export failed.

(5) Cancel button does not seem to do anything.

**Comment by szopeno** [comment]
Also, after compiling, the mouse cursor changes into indicating something is happening, but is not changing back - actually, sometimes it does change back, but no idea whether it depends on something

**Comment by olivierkes** [comment]
Hi,
I guess you're using Manuskrip 0.3.0? The export dialog has been completely rewritten for 0.4.0. You can test it in the develop branch. It can use [pandoc](http://pandoc.org/) to export to many formats. And looks better :)

![export-preview](https://cloud.githubusercontent.com/assets/1192933/21864332/94e1fb68-d841-11e6-88d7-32a99ecef7ba.jpg)
