### ISSUE TITLE
Number of characters instead of number of words?

### ISSUE THREAD

**Issue by antigosa** [olivierkes/manuskript#774]
Hi, 
is there a way to also show the number of characters? At the moment, I can only see the number of words, which is nice and useful, but I would also be useful to see the number of characters. 

Great program, by the way, thanks a lot!

**Comment by obw** [comment]
see #607 
This Feature will be added in the next Versions... I think there is one Patch which does exact this..

**Comment by TheJackiMonster** [comment]
This is implemented and merged with PR https://github.com/olivierkes/manuskript/pull/746.
