### ISSUE TITLE
Feature Request: Implementation and visualization of family trees

### ISSUE THREAD

**Issue by SirJohnsonLebaws** [olivierkes/manuskript#784]
Hey, 
I've just stumbled upon Manuskript today and have started, or tried to transcribe my current project into Manuskript and I've been very happy with it so far. The only thing that I'm really missing is some sort of way to organize characters in Families.
I've got lots of characters and some of them have quite intricate family relations and a way to just mark someone as "Son of XYZ" with some way to then view the family tree would be incredibly helpful!
At the moment I've settled with a visualization via colour coding but that method is quickly getting out of hand...
Either way, keep up the great work! :)

Edit: Beeing able to organize characters in a folder structure would be great as well! For example having all characters of the same race or from the same country/city in their own folder with "Main, Secondary and Minor" beeing subcathegories.

**Comment by obw** [comment]
This was requested by me some time ago, see #144

**Comment by TheJackiMonster** [comment]
I would close this as duplicate. But your ideas are noticed for implementation.
