### ISSUE TITLE
Dragging files can delete.

### ISSUE THREAD

**Issue by Biep** [olivierkes/manuskript#796]
I created a new file in the editor view.  It ended up at the second place, so I dragged it up to first place.  This replaced the first file by another empty one called "New".  So "Text - New - More - End" became "New - New - More - End", and the contents of "Text" were lost.  I had to retrieve them from a backup.

This is a very serious bug, leading to data loss - especially if it turns out the same can happen with folders.

**Comment by bartart3d** [comment]
Could it be the same as what happens in my bug report? 
Here it is: [outliner folder gets renamed and contents replaced when dragged over other folder, only in upward direction](https://github.com/olivierkes/manuskript/issues/719#issue-554663816) .

**Comment by Biep** [comment]
Yes, my case seems to be an instance of that.  Thanks for your extended report there - even including animated GIFs!

**Comment by Biep** [comment]
Let me close this one.
