### ISSUE TITLE
Installation - Qt platforn plugin "xcb" not found

### ISSUE THREAD

**Issue by FergusMagus** [olivierkes/manuskript#8]
$ ./manuskript
This application failed to start because it could not find or load the Qt platform plugin "xcb".
Reinstalling the application may fix this problem.
Fatal Python error: Aborted

Current thread 0x00007fecb4108740 (most recent call first):
  File "manuskript/main.py", line 18 in run
  File "<string>", line 13 in <module>
Aborted

Netrunner 14.04

**Comment by olivierkes** [comment]
Thx for reporting.

I guess you're running manuskript-0.2.0, the linux package.

Can you run `ldd` on` qt5_plugins/platforms/libqxcb.so` and paste the output?

**Comment by FergusMagus** [comment]
Is this what you wanted?

andy@andy-n-14:/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms$ ldd libqxcb.so
        linux-vdso.so.1 =>  (0x00007ffe30df8000)
        libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fd7882dd000)
        libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fd7880cd000)
        libxcb-render-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007fd787ec9000)
        libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fd787cc1000)
        libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fd787aa5000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd7878a1000)
        libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fd78768a000)
        libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fd787481000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd787262000)
        libxcb-image.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007fd78705d000)
        libxcb-icccm.so.4 => /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007fd786e58000)
        libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fd786c52000)
        libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007fd786a4b000)
        libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fd786848000)
        libxcb-randr.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007fd78663b000)
        libxcb-keysyms.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007fd786438000)
        libxcb-shape.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007fd786234000)
        libxcb-xkb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007fd78601a000)
        libxkbcommon-x11.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0 (0x00007fd785e12000)
        libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fd785bd8000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fd78599c000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fd7856f9000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd7853f1000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fd7851e7000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fd784eb2000)
        libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007fd784c33000)
        libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fd7845e6000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fd783f40000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fd783cda000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd783abc000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd7837b8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd7834b2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd7830ed000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fd782edb000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fd782cd6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd78878c000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd782ad2000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd7828cc000)
        libxcb-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-util.so.0 (0x00007fd7826c5000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fd78249b000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd782282000)
        libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fd78205c000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd781e1e000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fd781bd9000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fd781984000)
        libicui18n.so.52 => /usr/lib/x86_64-linux-gnu/libicui18n.so.52 (0x00007fd78157d000)
        libicuuc.so.52 => /usr/lib/x86_64-linux-gnu/libicuuc.so.52 (0x00007fd781204000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd780ffc000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd780de6000)
        libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fd780bbf000)
        libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fd7809bc000)
        libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fd7807b6000)
        libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007fd7805b1000)
        libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007fd7803ae000)
        libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007fd7801ab000)
        libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007fd77ffa9000)
        libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fd77fda3000)
        libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fd77fb96000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fd77f97a000)
        libicudata.so.52 => /usr/lib/x86_64-linux-gnu/libicudata.so.52 (0x00007fd77e10d000)


And yes it is the manuskript-0.2.0 zipped package.

I haven't tried compiling from source yet.

Andy

**Comment by olivierkes** [comment]
Ok, no clues.
This might be a bug in pyInstaller (the tool that generates package), I'll look into it.

Best option for you would be to run manuskript from source (no need to compile).

1. Install Python 3 (`python3`), PyQt (`python3-pyqt5`), and lxml (`python3-lxml`). (The package names are those of Kubuntu 15, I don't know if NetRunner changes them).

    Do you know how to do that?

2. Download source: [0.2](https://github.com/olivierkes/manuskript/archive/0.2.0.zip) or [develop](https://github.com/olivierkes/manuskript/archive/develop.zip)

3. Extract and run `bin/manuskript` from console

:)

**Comment by FergusMagus** [comment]
Those package names apply to Netrunner.
Manuskript runs. Looks OK so far, although the default location for 
compilation is 
"/home/olivier/Documents/Travail/Geekeries/Python/manuskript/ExportTest/test.html".

Andy

**Comment by olivierkes** [comment]
Great !

Yeah, the compilation / export part is really suboptimal right now.
In 0.3.0 there will be some major changes under the hood (most importantely, the file format will change, and markdown will be the default text format), then I'll work on exporting.
