### ISSUE TITLE
Export into text? [feature suggestion]

### ISSUE THREAD

**Issue by szopeno** [olivierkes/manuskript#80]
It would be nice if in addition of saving as .msk or exporting to .odt and .html, the project would allow the user to export whole project into a folder with set of simple text files (i.e. not just book, but also character info, world, outline etc).

**Comment by olivierkes** [comment]
This was added... can't remember when. In settings > General, you can uncheck "save to one file".
The whole project will then be saved as a folder with simple text files for everything.

![save-to-one-file](https://cloud.githubusercontent.com/assets/1192933/21864728/63fb4124-d843-11e6-876e-1ce50be220f9.jpg)

You can also export to text with the new export dialog.

**Comment by olivierkes** [comment]
More infos on that here: http://www.theologeek.ch/manuskript/2016/03/31/open-plain-text-file-format/
