### ISSUE TITLE
POV selection changes if character is deleted and a new one is added

### ISSUE THREAD

**Issue by BorisRabit** [olivierkes/manuskript#808]
Happened in both single file projects and folder based. If a character is selected for a section from the POV dropdown in the outline, this character's ID number appears to be associated with that section, readable in a text editor. If that character is then deleted, the reference to that ID number still exists for that section.

If a new character is created, it ends up with the now unused ID number, and now the POV shows as if that new character was the choice for that section in the outline.

Can Manuskript be made not to reuse ID numbers of deleted characters, or to delete the character ID reference from the section when the character is removed?

**Comment by TheJackiMonster** [comment]
> or to delete the character ID reference from the section when the character is removed?

Yes, this should be possible. I have added a feature with a similar check not long ago.

**Comment by TheJackiMonster** [comment]
The issue has been fixed with commit 77eee85  for the next release (0.13.0).
