### ISSUE TITLE
Manuskript running into an error immediately after launch

### ISSUE THREAD

**Issue by a-shroom** [olivierkes/manuskript#815]
Hi,
I've been looking at the themes available in Manuskript. I've clicked on one of them (I believe it was the first dark theme from top) and it crashed pretty much right away. Every time I try to open it it crashes right away. I've reinstalled it three times, wiped everything I could each time, still crashing.

Linux terminal gives this report:
```
Debug: Web rendering engine used: QWebView
qt5ct: using qt5ct plugin
Running manuskript version 0.11.0.
Preferred translation: ['en-GB'] (based on available ui languages)
Loaded translation: manuskript_en_GB.qm
qt5ct: D-Bus global menu: no
Loading: /home/frog/Desktop/Writing/NaNoWriMo Story.msk
Detected file format version: 1. Zip: True.
Project /home/frog/Desktop/Writing/NaNoWriMo Story.msk loaded.
Fatal Python error: Segmentation fault

Current thread 0x00007f758854c740 (most recent call first):
  File "/usr/share/manuskript/manuskript/ui/views/treeDelegates.py", line 41 in paint
  File "/usr/share/manuskript/manuskript/main.py", line 221 in launch
  File "/usr/share/manuskript/manuskript/main.py", line 234 in run
  File "/usr/bin/manuskript", line 30 in <module>
```

Any help as to what might be going on? Peering into the code, I'm assuming it's still the theme acting up in some way, but I don't know where it's stored or how to change it without opening up Manuskript.

Thanks in advance.

**Comment by obw** [comment]
Looks like #800 strikes again...

**Comment by a-shroom** [comment]
Well opening Manuskript without a project opens it up fine, except the theme prevents me from opening up settings or anyhow changing the theme, and it's pretty much unusable... Does _anyone_ know where I can change the theme from outside Manuskript? Or where the setting is saved, or just anything that'd allow me to get the default theme back on?

**Comment by siliconserf** [comment]
This may work - Manuskript saves the theme for each project in settings.txt. Edit the project file line entry "fullScreenTheme":     
   "fullScreenTheme": "writingdesk",

**Comment by a-shroom** [comment]
@siliconserf Well I was able to open up a project and change the theme with that, so it worked well! Thanks a lot! As #800 is similar to this, don't think I need to keep this open.
