### ISSUE TITLE
Increase editor font size

### ISSUE THREAD

**Issue by sonofben111** [olivierkes/manuskript#820]
I was able to increase the font size for the menus etc, but I cannot find any control for making the font bigger as I type, on the page I am typing. Is it possible to do this now? Is it something coming? many thanks!

**Comment by obw** [comment]
CTRL + scrollweel

**Comment by sonofben111** [comment]
thank you for replying. I went through Settings-Font Size and  this increased the font size of everything except the editor window. the font stays the same size. 
I'm not sure about the ,CTRL - scroll wheel - but I pressed CTRL and dragged my finger across the synaptics mouse pad on my laptop...it just highlights. the font in the editor window won't budge.

**Comment by sonofben111** [comment]
...just figured it out: Settings - View - Text Editor - and then you see where you can change the font in the editor window per se. Thanks again. all the best.
p.s. while playing around I accidentally deleted a scene. Couldn't get it back. The computer user's best buddy is the UNDO button :)
