### ISSUE TITLE
Search function not working properly

### ISSUE THREAD

**Issue by gebeleizis** [olivierkes/manuskript#824]
Hi,

I tried to work on one of my projects on Manuskript and at some point needed to search for a word in the text. The search function only shows me the chapters, but never where the word is located. Of course, I could copy-paste it into notepad and find it, but this is cumbersome and takes time. Is there any way to make the search function work? Thank you very much in advance!
I'm using the program under Windows 10.

**Comment by obw** [comment]
See also:
  * #376
  * #309 
  * #145 
  * #480

**Comment by gebeleizis** [comment]
Oh, I see. So it's been a problem since years ago and still wasn't fixed. I suppose it won't get fixed any time soon. Thank you very much for the reply!

**Comment by SConard** [comment]
I could be mistaken, but it appears that someone has worked on a search function. I'm hoping it would be a part of the next release.
[#717](https://github.com/olivierkes/manuskript/pull/717)

**Comment by TheJackiMonster** [comment]
I would close this issue because it's a duplicate. However getting the newly implemented search functionality into the project is currently in progress. So a next release should fix your issue.
