### ISSUE TITLE
Small typographic error in the README

### ISSUE THREAD

**Issue by alecsatin** [olivierkes/manuskript#84]
Debian based (Ubuntu, Linux Mint, etc.): sudo apt-get install python3-pyqt5 libqt5svg5 python3-lxml python3-enchant **zlibg1**

Should read:

Debian based (Ubuntu, Linux Mint, etc.): sudo apt-get install python3-pyqt5 libqt5svg5 python3-lxml python3-enchant **zlib1g**

Very much looking forward to trying manuskript.  Thanks so much for putting so much effort into this tool AND supporting linux.

Alec

**Comment by olivierkes** [comment]
Thanks !
