### ISSUE TITLE
Linux missing dependency?

### ISSUE THREAD

**Issue by DonEdwards** [olivierkes/manuskript#847]
Running 0.11.0 on Linux Mint 19.3 (Debian descendant)

Assorted window controls are missing. Example: if I go to Edit, Settings, I have no way to close the resulting dialog - except by killing the entire program.

I suspect there's something missing in my installation. But if so, it really should be tagged as a dependency in the .deb install package.

Note: launching the program from a terminal window gets no useful information.

**Comment by DonEdwards** [comment]
Attached is list of all my installed packages

**Comment by DonEdwards** [comment]
Let's try this again in a different browser
[installed.txt](https://github.com/olivierkes/manuskript/files/6254991/installed.txt)

**Comment by TheJackiMonster** [comment]
I think if there was a dependency missing the program should actually report something in the output stream. Also the program would probably crash instead of acting weird.

**Comment by TheJackiMonster** [comment]
@DonEdwards At least comparing to the dependencies listed in the [Arch repository](https://archlinux.org/packages/community/any/manuskript/) (which work for me definitely ^^'), the only thing you are potentially missing is PDF.js (which is optional).

**Comment by DonEdwards** [comment]
Well, my (very tentative) hypothesis is that there's a dependency which should be listed, but isn't. And an over-enthusiastic bit of error-handling code catches the exception and says "Okay, no problem!" Having written one or two such error handlers myself...

**Comment by catthou** [comment]
@DonEdwards This may be a theme issue; themes for Gtk3 don't show the window controls on settings dialogs because they're not meant to be normal windows. Can you try this for me?
Launch Nemo file manager(`nemo` from command line if you don't know how)
Select Edit from the top menu bar.
Select the Preferences option at the bottom of the drop down list.

Does this preferences window have the window controls that you would expect?

**Comment by DonEdwards** [comment]
"Launch Nemo file manager(nemo from command line if you don't know how)"

** (nemo:9911): WARNING **: 15:47:43.206: Current gtk theme is not known to have nemo support (Adwaita) - checking...

** (nemo:9911): WARNING **: 15:47:43.330: The theme appears to have no nemo support.  Adding some...

"Does this preferences window have the window controls that you would expect?"

No, it doesn't.

I recently found that if I right-click on the window's title bar, I can close it... Hope I don't get one of these that is supposed to have "OK" and "Cancel" buttons...

**Comment by catthou** [comment]
This bug report can be closed then, since its a Gtk/Theme problem and not a manuskript problem!

**Comment by DonEdwards** [comment]
Agreed
