### ISSUE TITLE
Improving user-friendliness of log files

### ISSUE THREAD

**Issue by worstje** [olivierkes/manuskript#852]
With #667 finally merged, the final comments left there made me think that while it is a definite improvement in regards to overall code health, it isn't everything it could be yet for our users. Because that PR was originally started to preserve developer sanity and improve codebase health, ease-of-use for our end users had fallen through the cracks a little as a concern...)

The default log file is wiped by default.
---

Because the log file kept swelling immensely while I was testing (there are a lot of debug statements everywhere in the code) I implemented it to wipe the file every time we started logging a new session. (I could already anticipate people submitting log files of 1GB in size from their many writing sessions! 😂 )

This has the following problems:

❌ ❓  Running two Manuskript instances simultaneously without overriding the log file location might throw an error, strangely mix the logs or just make one disappear. _(I remember vaguely that Windows and Linux behave differently in regards to the way they handle open files, and although writing should work similarly, paranoia is a good thing...)_

❌ ❌ ❌  Users recovering from a crash by restarting Manuskript are likely to wipe the log file that could shine light on the issue they ran into.

I am not sure what the desired default behaviour should be, either.

💭  Do we want to implement some sort of builtin logrotate where we maintain our own default logs folder?

💭  Is there a proper way to detect a logfile that is currently in use for writing to perhaps skip over that one?

💭 ❕ ❕  Should we just do TIMESTAMP-PID.log files and delete ones older than 30 days?

💭 ❔  Maybe ignore the issue and leave it to some other software tool on the users system to handle... but is that even an option given our cross-platform nature? (A silently ballooning log file folder isn't nice for users.)

Accessibility
---

We probably want to offer a help menu option that shows either the log file in a file manager, opens it in an editor, and/or outright displays it in action... or a combination thereof. Log files are useless if they are hard to use for reporting issues.

I'm fine with simple solutions. As long as they are useful.

Reporting issues
---

We probably want to update some wiki templates or whatever other knows and documentation we have to clearly document the best ways to report bugs and get their hands on Manuskript.

I originally intended to just code up something for the most pressing issue of overwriting default log files, but since I don't know the preferred method, I figured it was best suited for a community discussion. I think a `(data-dir)/logs/` folder with `TIMESTAMP-PID.log` files would be most suitable when combined with a simple check that purges old logs, but I am not sure if anyone else has strong feelings on the way to approach this.. or any of these subjects, for that matter.

Coding something on relatively short notice is something I can do assuming there is a consensus on how Manuskript should behave, but the other aspects are a bit beyond my comfort zone to tackle. It would probably be good if another person was involved in the interaction and community-facing aspect of it all.

**Comment by TheJackiMonster** [comment]
Mhmm, I think we could also make use of an option to enable or disable certain type of logging. For example from other projects I'm used to explicitly enable logging by providing a debug level (errors only, include warnings, include debug messages as well or verbose including everything).

>  Is there a proper way to detect a logfile that is currently in use for writing to perhaps skip over that one?

I think every operating system has some kind of detection if a given file is in use/is used for writing. Especially Unix bases systems are known for using files as locks for multiple processes. So that should be possible if be keep the file handle opened during runtime.

**Comment by worstje** [comment]
The current idea behind logging everything is simply because unpredictable crashes were a thing for quite a while between 0.6-0.10. Much of it has been ironed out, but the logic of logging as much as possible was (for me at least) an obvious move since disk logging doesn't get in the way when actually curated decently. Spamming **-v** options indeed allows the sort of granularity you mention in regards to what is printed to the terminal, but for a log file we as a developer can patiently read or grep through, it didn't seem reasonable. Whatever there exists that is too much can quickly be gotten rid of while analyzing.
