### ISSUE TITLE
Overlapping IDs repeating

### ISSUE THREAD

**Issue by jcastp** [olivierkes/manuskript#865]
I'm working on a project and I am creating and moving some files and folders as new scenes and ideas unfolf, and I'm finding that some files keep getting assigned an already used ID, that result in the message: 
`WARNING> There are some items with overlapping IDs`

Example:
![imagen](https://user-images.githubusercontent.com/609376/115160460-7f87a000-a098-11eb-8bb3-5fcfc9a334dd.png)

I create another file, called test01:
![imagen](https://user-images.githubusercontent.com/609376/115160439-68e14900-a098-11eb-915b-76ff65edc873.png)

I, then, create another file, called test02:
![imagen](https://user-images.githubusercontent.com/609376/115160480-afcf3e80-a098-11eb-9dbb-14e4359f03b2.png)
![imagen](https://user-images.githubusercontent.com/609376/115160500-c4133b80-a098-11eb-8299-86c3dcc47258.png)

And with another file, test 03:
![imagen](https://user-images.githubusercontent.com/609376/115160534-00df3280-a099-11eb-8706-a5014f475446.png)

As you can see, the numbers are being duplicated. Is the ID really important, or is it a minor thing and I can keep going?

Thanks!

**Comment by TheJackiMonster** [comment]
Do you use the current state from the Github 'develop' repository or 0.11.0? Because there have been changes to generating unique IDs lately which would come to 0.12.0, hopefully fixing this.

**Comment by jcastp** [comment]
Hello, I'm using the GitHub "develop" branch with the latest commits, but started the project around a couple of months ago, so I pulled some commits in the meantime.

So far, I'm only writing, not doing any compilation or other processes, so the only sign is the Warning message. Do the duplicated IDs affect any other functionality? Can I keep writing "safely"? (I know safely is a relative term, and the product, which is awesome, is as it is).

Thanks for your work!

**Comment by TheJackiMonster** [comment]
So I was referring to this PR here: https://github.com/olivierkes/manuskript/pull/827

You could backup your project and try pulling latest changes from Github then. So maybe this will fix your issue. At least it should also include the changes integrating logging. So it will probably help finding the problem. ( Also the latest changes should not break any older project. I just suggest a backup to be sure. ^^' )

**Comment by TheJackiMonster** [comment]
This should be solved once #324 is solved.

**Comment by jcastp** [comment]
Hello, I reviewed the [#324 ](https://github.com/olivierkes/manuskript/issues/324) bug and its problem is related to copying folders or scenes, that it is still an ID related problem, while this one is when you create a new scene under some particular circumstances.

Disclaimer: Although I know some python (enough to do some scripting), I struggle to understand all the code here, so perhaps I'm missing something. Sorry about that.

In this particular case, the problem is when you create a new scene and there are gaps in the sequence of IDs, as for example, if you have deleted a previous scene.

I've been digging in the code, and I have done a couple of modifications to see if I understood how the IDs are assigned to the scenes. These are the changes:

```
diff --git a/manuskript/models/abstractItem.py b/manuskript/models/abstractItem.py
index 92aa7cb..8416c6e 100644
--- a/manuskript/models/abstractItem.py
+++ b/manuskript/models/abstractItem.py
@@ -235,6 +235,7 @@ class abstractItem():
         IDs = [self.ID()]
         for c in self.children():
             IDs.extend(c.listAllIDs())
+        print(IDs)
         return IDs

     #######################################################################
diff --git a/manuskript/models/abstractModel.py b/manuskript/models/abstractModel.py
index 2ed4bd7..c5a7c80 100644
--- a/manuskript/models/abstractModel.py
+++ b/manuskript/models/abstractModel.py
@@ -54,6 +54,8 @@ class abstractModel(QAbstractItemModel):
     def requestNewID(self):
         newID = self.nextAvailableID
         self.nextAvailableID += 1
+        print(f'new ID: {newID}, next Available ID: {self.nextAvailableID}')
         return str(newID)
```

- **abstractItem.py/listAllIDs** function is able to capture all the existing IDs recursively and add them into a list (that will be printed with the changed code above when starting Manuskript).
- **abstractModel.py/requestNewID** function will print the current ID for the scene and the next one to be used (this I assume, see disclaimer above), and will be printed when starting Manuskript, and when a new scene is created.

And this is how you can reproduce the bug reported here (this has been tested with the develop branch, last commit 77eee85):

1. Create an empty project
2. Create 5 basic scenes. This will print the following output, by requestNewID:
```
new ID: 1, next Available ID: 2
new ID: 2, next Available ID: 3
new ID: 3, next Available ID: 4
new ID: 4, next Available ID: 5
new ID: 5, next Available ID: 6
```
3. Close Manuskript
4. Open Manuskript. The output shows the IDs when loading the scenes and the listAllIDs print statement.
```
new ID: 1, next Available ID: 2
new ID: 2, next Available ID: 3
new ID: 3, next Available ID: 4
new ID: 4, next Available ID: 5
new ID: 5, next Available ID: 6
['1']
['2']
['3']
['4']
['5']
['0', '1', '2', '3', '4', '5']
```
5. Delete scene with ID 4
6. Close Manuskript
7. Open Manuskript. As we have deleted scene ID: 4, listAllIDs correctly shows the gap, while the requestNewID seems to ignore it and assigns sequential numbers.
```
new ID: 1, next Available ID: 2
new ID: 2, next Available ID: 3
new ID: 3, next Available ID: 4
new ID: 4, next Available ID: 5
['1']
['2']
['3']
['5']
['0', '1', '2', '3', '5']
```
8. Create another scene. As you can see, requestNewID has used the first empty ID, that was 5, that is already in use by another scene.
```
new ID: 5, next Available ID: 6
```
9. Close Manuskript
10. Open Manuskript. Here we see the requestNewID sequential generation, while listAllIDs gets the duplicated IDs.
```
new ID: 1, next Available ID: 2
new ID: 2, next Available ID: 3
new ID: 3, next Available ID: 4
new ID: 4, next Available ID: 5
new ID: 5, next Available ID: 6
['1']
['2']
['3']
['5']
['5']
['0', '1', '2', '3', '5', '5']
WARNING> There are some items with overlapping IDs: ['5', '5']
```

What I think it happens is that while listAllIDs function is able to capture all the existing IDs, including the gaps, the requestNewID function does not have this into account and the only mechanic to assign new IDs is to increment by one the old one. If we are creating only new scenes, that should not be a problem, but if you delete some, then the gaps are not taken into account, and thus the problem of duplicated IDs.

Possible solutions here:
- After listAllIDs function ends, perhaps requestNewID should set self.nextAvailableID to the biggest number in the listAllIDs, so we are sure all the new scenes will be beyond the gap.
- Having a global set of IDs and checking against it when assigning a new ID. Since scenes usually won't go over 1000, it's not something I expect to be very cumbersome.

As I stated, there is a lot of code I don't understand, so sorry if I'm doing something wrong. I just want this amazing piece of software to be even better.

**Comment by TheJackiMonster** [comment]
I could reproduce the issue and find the actual source of the caused problem. The constructor of abstractItem did not increase the availableID counter even though it allows setting the ID of an item. It's really unfortunate that Python seems to have issues calling setter-methods from the constructor because some attribute-fields might be undefined during such calls.

So it might be fixed now but the code still looks quite inconsistent and a similar issue might appear in the future. We definitely need to cleanup this code in the future. The object-oriented structure just might be sub-optimal hiding such problems.

**Comment by jcastp** [comment]
Thanks a lot for fixing it so quick. The change solves the problem.

Thanks again, for your time and support!
