### ISSUE TITLE
Plots, resolutions steps screen: columns not sizeable.

### ISSUE THREAD

**Issue by jcastp** [olivierkes/manuskript#87]
In the plot tab, in the Resolution Steps, once you exit the tab to do something else, and come back, the columns size of the Resolution steps created is fixed, and some properties are missing (ID, description).

I've created a test project to show this, but it happens across all my projects.

Creating the resolution steps gives no problem, and everything shows as expected. As you can see, the pointer shows the moving/resizing arrows:

![manuskript_plot_steps_01](https://cloud.githubusercontent.com/assets/609376/23341508/32cc576c-fc49-11e6-9906-97eea62fcfbf.png)

Then, change the view to something else, like Characters, or anything, and returning back to the Resolution Steps, we get the following:

![manuskript_plot_steps_02](https://cloud.githubusercontent.com/assets/609376/23341510/39abe02a-fc49-11e6-9503-6a682b6fb7b2.png)

Now, we miss some columns, and the pointer doesn't change to anything on the border of the column header.

This happens using any theme.

If you need more information, please, dont hesitate to contact me.

OS: Ubuntu 16.10.

**Comment by jcastp** [comment]
As a workaround, the subplots can be seen and edited in the debug tab.

**Comment by olivierkes** [comment]
Hi,
Actually, the bottom view is how it's supposed to look: you're not supposed to change the ID, and the summary is edited in the textbox under.
I made a tweak so that the first view never appears.
Thanks !
