### ISSUE TITLE
Bug in character section

### ISSUE THREAD

**Issue by AspiringWriter** [olivierkes/manuskript#875]
When I try to add a new value to the detailed information section. It lets me add one, but when I try to add another, the app crashes.

**Comment by TheJackiMonster** [comment]
This seems to be the same bug as #843. Is this correct? Can you get the log file from a crash? (You can find your log files through the Help-menu).

**Comment by AspiringWriter** [comment]
Yes! It seems to be. I got the log file, what should I do with it? 
![IMG_20210512_133011](https://user-images.githubusercontent.com/84095738/118026251-35f04500-b326-11eb-95fb-85c4b5270dac.jpg)

**Comment by TheJackiMonster** [comment]
This helps already, showing the exception and the lines of code. ^^

**Comment by AspiringWriter** [comment]
I'm glad.

**Comment by TheJackiMonster** [comment]
I would close this issue here to avoid duplicates though. But I've linked the screenshot and this issue in the older issue. So the information can be used to fix it.
