### ISSUE TITLE
IndexError in characterModel.py

### ISSUE THREAD

**Issue by JoelMon** [olivierkes/manuskript#896]
Hello,

I would like to report a bug in characterModel.py in version 0.12.0. There's an index error that crashes Manuscript. It happens when you go to Characters > Click on a character > Detailed Info > click the "+" to add new detail.

![Peek 2021-06-27 17-14](https://user-images.githubusercontent.com/6587811/123559721-be5a6600-d76b-11eb-8876-a9fe520ff3ef.gif)

I unchecked the `Save to a single file` option in `Settings`. 

Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy

**Comment by worstje** [comment]
Behaviour confirmed, cause hunted down and bug extinguished on my local branch. A pull request with assorted fixes will happen later this weekend.

Thank you for reporting this bug!

**Comment by JoelMon** [comment]
> Behaviour confirmed, cause hunted down and bug extinguished on my local branch. A pull request with assorted fixes will happen later this weekend.

Awesome! Thank you very much!
