### ISSUE TITLE
Compile not honoring check marks

### ISSUE THREAD

**Issue by ramonskovitch** [olivierkes/manuskript#90]
I have tried to get the compile function to work properly. It does compile both html and libreoffice, however, it does not respect the check marks for compile/do not compile in the outline. Those unchecked are still compiled, it does the whole folder tree.
Additionally, a simple compile to plain text (or markdown) that concantenated the separate checked files would be useful.

I don't know what arborescence is (except for the "tree" definition). It doesn't work at all and crashes the compile function.
Separately, as I begin to use manuskript as my sole tool I am continuously impressed with what it does (coming from an experienced Scrivenere user). Anyrhing I can do to ensure its continued development please ask!

**Comment by olivierkes** [comment]
Hi,
This has been fixed in 0.4.0 (currently the develop branch), as the whole export/compile window has been rewritten.
Please see here: https://github.com/olivierkes/manuskript/issues/77#issuecomment-271978813
