### ISSUE TITLE
Ubuntu 21.04, Manuskrip not installing or working with .deb snap or repository.

### ISSUE THREAD

**Issue by garyx** [olivierkes/manuskript#900]
I am on Ubuntu 21.04 and I am have been trying to install Manuskript with varying degrees of failure. 

The 0.12 deb package refuses to install dependant package issues. When I try with dpkg I get the following: 
`$ sudo dpkg -i manuskript-0.12.0-1.deb 
Selecting previously unselected package manuskript.
(Reading database ... 200998 files and directories currently installed.)
Preparing to unpack manuskript-0.12.0-1.deb ...
Unpacking manuskript (0.12.0-1) ...
dpkg: dependency problems prevent configuration of manuskript:
 manuskript depends on python3-pyqt5; however:
  Package python3-pyqt5 is not installed.
 manuskript depends on python3-pyqt5.qtwebkit; however:
  Package python3-pyqt5.qtwebkit is not installed.
 manuskript depends on python3-enchant; however:
  Package python3-enchant is not installed.
 manuskript depends on pandoc; however:
  Package pandoc is not installed.

dpkg: error processing package manuskript (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.26-1ubuntu1) ...
Processing triggers for mailcap (3.68ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Errors were encountered while processing:
 manuskript
`

When trying to install with the 0.11 file from the Ubuntu repositories I get the these errors after successfully installing but will not start: 

`$  manuskript 
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 28, in <module>
    from manuskript import main
  File "/usr/share/manuskript/manuskript/main.py", line 8, in <module>
    import manuskript.ui.views.webView
  File "/usr/share/manuskript/manuskript/ui/views/webView.py", line 34, in <module>
    from PyQt5.QtWidgets import QTextEdit
ImportError: /usr/local/lib/python3.9/dist-packages/PyQt5/QtWidgets.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
`

After installing from snapcraft it installs but it gives an error and never starts. 

`$ manuskript 
Qt: Session management error: Could not open network socket`

Only thing I haven't tried is to build locally, might be tempted but at the moment just installing a package would be the preferred way.

**Comment by garyx** [comment]
Never mind, at last figured out eventually the dpkg with the downloaded will work with fixing the dependencies. 

`sudo apt --fix-broken install`

But the other two ways did not work.

**Comment by Mannshoch** [comment]
Have this error on Ubuntu 21.04 with snap. 
```
snap list|grep manus
manuskript               0.11.0                         370       latest/edge      twom              -
```
Even the error `Qt: Session management error: Could not open network socket` appear in terminal . the ap itself seems still running 
I have to kill it with `killall python3`
