### ISSUE TITLE
error at startup

### ISSUE THREAD

**Issue by cykAaAaAaA** [olivierkes/manuskript#906]
![проблема](https://user-images.githubusercontent.com/29813778/126044311-d6dacbeb-aee6-4ade-a8cb-e25606cde811.PNG)
I've been using your program for a while, and I was happy with it. But today I could not start it, restarting the computer did not help. What should I do with this error ? [machine translation]

**Comment by TheJackiMonster** [comment]
I haven't seen this before. I think somehow your files used a different codec to save. Did you open the text files in a different editor, changed operating system or anything like that?

Otherwise, have you any backup of that file?

**Comment by cykAaAaAaA** [comment]
I didn't open it in another text editor, I didn't change the operating system, and nothing like that.  I just had it turned on, and then it just turned off.

слава богу у меня было резервное сохранение файла.

**Comment by TheJackiMonster** [comment]
I'm not sure what causes this but the load & save system is currently in development. So in the future this should be fixed.

**Comment by cykAaAaAaA** [comment]
that's fine, but how do I run the manuscript ? just now, when it starts, it writes to me what is in the photo.

**Comment by TheJackiMonster** [comment]
Ah, right. So it's not starting because the default project it tries to load is corrupted. So just move the project to another directory or delete it. Then it shouldn't try to load it.

**Comment by cykAaAaAaA** [comment]
thank you!
