### ISSUE TITLE
Issues pertaining to the wrong table being referenced in the "Detailed info" tab on the "Characters" pane

### ISSUE THREAD

**Issue by CreativityTheEmotion** [olivierkes/manuskript#910]
1) Whenever a character is deleted, if "Detailed info" is viewed at the time, it is populated with the character list; "Name" displays the character color and name, while "Value" displays the character ID.

2) One cannot add more entries to the "Detailed info" list than there are characters; upon trying to do so, Manuskript instantly crashes. This has a workaround, by editing the files in the `.msk` archive directly; however, this causes a crash when _any_ item in the "Detailed info" list is edited.

**Comment by TheJackiMonster** [comment]
I think the second issue could be fixed via PR #901. So I recommend running the application from source code checking if the current state has fixed it. I'm not sure about the first one though.

**Comment by CreativityTheEmotion** [comment]
Confirming the first issue has also been fixed with the PR mentioned.
