### ISSUE TITLE
calling pandoc 2.5 is broken with the later versions

### ISSUE THREAD

**Issue by bertput** [olivierkes/manuskript#922]
Later versions of Manuskript use "--shift-heading-level-by=" when calling pandoc.
The parameter used to be "--base-header-level=" which is appropriate for pandoc v2.5 but must have changed at some point.

The issue is in abstractPlainText.py.

This is for Manuskript github development branch v0.12.x.

This is more FYI than for action; maybe we can have more flexibility in specifying arguments to i.e. pandooc?

**Comment by magicvince** [comment]
I confirm, impossible to compile a pdf due to --shift-heading-level-by=1 option. (Manuskript 0.12 (deb or snap) Pandoc 2.21 in LinuxMintDebianEdition)

**Comment by TheJackiMonster** [comment]
I've just pushed a commit ( 25adfd2 ) which should fix the problems with Pandoc once for all ( at least I hope so ). It will now check the installed version and decides to give you options depending on the actual support. So newer releases of Manuskript should not have this hassle with getting the proper Pandoc version installed anymore.

**Comment by bertput** [comment]
The thread is closed, but I can confirm the bug is fixed. :-)
