### ISSUE TITLE
Installed on chromebook (linux), no issues, opened it up and it has no words?

### ISSUE THREAD

**Issue by Valdus92** [olivierkes/manuskript#925]
The program was working fine, then I opened it up later and got the screen with no words? Am I missing something. Here is a pic 

![image](https://user-images.githubusercontent.com/26496870/130480444-623768f2-bf4f-4ca2-b50f-5d3344bea048.png)

**Comment by Valdus92** [comment]
Anything I can do?

**Comment by TheJackiMonster** [comment]
Could it be resolved? Can you add how the issue was solved in case of others having the same issue?

**Comment by Valdus92** [comment]
True, true, I think the font in general settings was set to 1 or something. I brought up the general tab and increased the over all font size, worked very well. BUT

On Chromebook there are so many buttons that simply crash the program. I will try to begin a list. I could really use this program on chromebook.
