### ISSUE TITLE
File creation fails and causes Manuskript to crash

### ISSUE THREAD

**Issue by jasongeorge1975** [olivierkes/manuskript#93]
I got the app to load on OpenSUSE after cloning the repository. I've downloaded and installed all the dependencies the program asked for and got to the start of the screen. When I try to create a new file (or save or project, or whatever), the program opens a dialogue where I can browse for a folder to save in. Typically, I try to save it in my Home directory. As soon as I give the project a name and hit save the program crashes. Upon looking into the directory where I tried to save my file, nothing is written, so the program failed to save the file.

This has happened in OpenSUSE, but I also tried running the Windows version in WINE and got the exact same crash. Both Linux and Windows programs were version 0.30.

I like the screenshots I've seen of manuskript and I would love to give it a go, but seeing as how I can't even get past the project save screen, that doesn't seem possible...

Hope this helps with your development. I'm defintely hoping that manuskript keeps improving!

**Comment by jasongeorge1975** [comment]
Update: I happened to look in my terminal where I launched manuskript from, and here is the output:

Traceback (most recent call last):
  File "/home/jason/manuskript/bin/../manuskript/ui/welcome.py", line 159, in createFile
    self.loadDefaultDatas()
  File "/home/jason/manuskript/bin/../manuskript/ui/welcome.py", line 344, in loadDefaultDatas
    t = [i for i in self.templates() if i[0] == self.template[0]]
  File "/home/jason/manuskript/bin/../manuskript/ui/welcome.py", line 344, in <listcomp>
    t = [i for i in self.templates() if i[0] == self.template[0]]
IndexError: list index out of range
Fatal Python error: Aborted

Current thread 0x00007fec20a2b700 (most recent call first):
  File "/home/jason/manuskript/bin/../manuskript/main.py", line 72 in launch
  File "/home/jason/manuskript/bin/../manuskript/main.py", line 63 in run
  File "bin/manuskript", line 13 in <module>
Aborted (core dumped)

hope this helps

**Comment by gedakc** [comment]
Recently I began using manuskript too and have been impressed at what has been accomplished to date.

Are you running the **master** branch of the cloned repository?

If so then I too was unable to create a new project with the current master.
See [Issue #37 - 0.3.0 File Creation Issues](https://github.com/olivierkes/manuskript/issues/37)

Did you select a **Fiction**, **Non-fiction**, or **Demo Projects** type when selecting a new project file name?

If I recall correctly I saw a report of save issues when no project type was selected.  Unfortunately I can't seem to find this reference at the moment.

When I checked out the **develop** branch, and selected a project type, then I was able to create new projects.
`git checkout develop`

Hope that helps.

**Comment by jasongeorge1975** [comment]
I'm not sure, but I do believe it's the **master** branch that I'm running. Basically, I just did a straight up git clone command with the url copied directly from the "clone or download" button on the home page.

I've tried selecting several versions of the **Fiction** project (can't remember the types at the moment but there were several), as this is what I was most interested in. I even tried opening the sample project and that crashed as well.

I would be willing to try the Develop branch, but being I'm so new to Linux I'm not sure what the commands for that would be. If you could show me the commands I'll try it out, see how it works. I'm running OpenSUSE Tumbleweed, but if I recall I do have a bash shell installed as default, so hopefully the commands would be the same.

**Comment by gedakc** [comment]
When you are in the manuskript git directory, use the following command to switch to the **develop** branch:
`
git checkout develop`

You can switch back to **master** with:

`git checkout master`

**Comment by jasongeorge1975** [comment]
Got it. Just installed and was able to save the new project. Thanks for your help gedakc! I know some people don't like answering newbie-type stuff (a lot of the linux forums seem like that sometimes), but I'm always willing to learn!

**Comment by gedakc** [comment]
'Glad to hear that worked.  :-)

Currently I'm working on a project to take text files exported "compiled" from manuskript and convert these into EPUB, MOBI, and DOC files.  If you are curious, take a look at [EBookGenTools](http://ebookgentools.sourceforge.net).

I'm new here too so hopefully someone else can mark this issue as solved.

**Comment by gedakc** [comment]
**Suggestion for Maintainer/Developer of Manuskript**:
_Release a new version with a fix for this project creation fails issue as soon as possible._

The fact that the current 0.3.0 release is unable to create new projects is a serious issue.  It means that new users will immediately be discouraged from using manuskript.  To increase the popularity of manuskript this issue must be fixed in an officially released version.

If you require help with testing a new release, then please feel free to ask.  I would like to help.

Curtis

**Comment by jasongeorge1975** [comment]
Thanks again gedakc for your help. I agree with you on the issue of not being able to save files. It is serious. The only reason I stuck with it is because I was stubborn and determined to learn a few things that I didn't know before, but sometimes I just want a program to work. I'll check out your ebookgentools soon as I get a chance (I don't have anything to publish yet, but hopefully I can do a few short stories between now and end of summer).

I still believe that this project has a lot of potential. It's still in its early stages, so patience will be key.
