### ISSUE TITLE
Feature suggestion: Timeline (Not urgent - just interesting idea)

### ISSUE THREAD

**Issue by Vidyut** [olivierkes/manuskript#933]
It would be useful to have the ability to set a date for various chapters/scenes, that could be displayed on a timeline of events. Similar to the storyline with plots, etc, but the sequence of folders/texts would be arranged by chronology rather than storytelling. (For example, flashbacks would show in the past, rather than during current events, even if the flashback is narrated in the middle of current events)

Probably a complicated feature to create. Was just a thought.

**Comment by obw** [comment]
Looks like my suggestion in #155

**Comment by TheJackiMonster** [comment]
@obw  Yes, this sounds like a duplicate. So I will close this here to have only one discussion in #155.

**Comment by TheJackiMonster** [comment]
@Vidyut If you don't want to wait for this feature and #930, I recommend trying Bibisco by the way. It's a different application but it's free and open-source as well. ^^'
