### ISSUE TITLE
It crashes when I double click characters name's frame

### ISSUE THREAD

**Issue by Binholink** [olivierkes/manuskript#937]
It crashes every time I double click that area.

![image](https://user-images.githubusercontent.com/13907495/133846268-e15a034b-3cc3-4c30-9232-5f0cc5fcdf87.png)

**Comment by TheJackiMonster** [comment]
I think this could be fixed already in the current state on our `develop` branch because the characters list caused a bunch of issues. But I will look into it.

**Comment by TheJackiMonster** [comment]
The problem is now solved and the next release (0.13.0) shouldn't cause this crash anymore.
