### ISSUE TITLE
Ubuntu snap on edge channel not updated with v12

### ISSUE THREAD

**Issue by Mannshoch** [olivierkes/manuskript#955]
Current version on snapcraft is 11 on edge channel.

I propose to 

- update edge and candidate to 12
- set stable to 11

```
name:      manuskript
summary:   Manuskript is an open-source tool for writers.
publisher: Thomas Wardill (twom)
store-url: https://snapcraft.io/manuskript
license:   unset
  ...

channels:
  latest/stable:    –                             
  latest/candidate: –                             
  latest/beta:      –                             
  latest/edge:      0.11.0 2021-10-26 (397) 244MB -

```

**Comment by TheJackiMonster** [comment]
I've now looked into the snap package and it seems to be possible building a new version on Manjaro. So as soon as it's possible I will update the snap.

**Comment by TheJackiMonster** [comment]
Good news. The [snap package](https://snapcraft.io/manuskript) is now updated as you proposed. I will release the next version (0.13.0) soon as well but you can expect the snap version being in sync this time. I'll just need to solve some remaining issues to make each version as good as possible before release.

Also please notice issue #969 in case you install the snap on an Ubuntu distribution (it should also be possible to set the required permission right through the store). Let me know if there are any issues left.
