### ISSUE TITLE
Critical error when running on Fedora 35 (manuskript won't start)

### ISSUE THREAD

**Issue by hp1706** [olivierkes/manuskript#957]
I get a critical error on Fedora 35. To get manuskript running on Fedora 35, I installed the .rpm as I have done successfully in the past, but no success when running the app.

Below is the error I get when trying to run the app. Not sure if I should install differently or if this is an incompatibility with this new Fedora release?

$ manuskript
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 291, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/manuskript/main.py", line 170, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 23, in <module>
    from manuskript.models.worldModel import worldModel
  File "/usr/share/manuskript/manuskript/models/worldModel.py", line 11, in <module>
    from manuskript.ui import style as S
  File "/usr/share/manuskript/manuskript/ui/style.py", line 36, in <module>
    highlightLight = F.mixColors(highlight, window, .3)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 197, in mixColors
    return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'

**Comment by TheJackiMonster** [comment]
I assume your Fedora uses a newer version of Qt or PyQt than what's known to work. Maybe you have only Qt6 installed and it tries to resolve PyQt5 functions with it.

But I think then I should get similar issues on Arch if this was an API version mismatch... So maybe it's something else. I will setup a Fedora 35 VM and try to reproduce/solve it. ^^'

**Comment by TheJackiMonster** [comment]
Interestingly enough it seems to be rather an issue with Python than Qt. So the Qt5 spec states that QColor expects integer values and no floating point values. But on my Arch setup Python just implicitly casts the float values to integers and Manuskript's `mixColors()` function works fine without even a warning. However this code is technically very wrong. ^^'

So I uploaded a fix (commit 15edb6e) now which should solve this issue. I recommend using the way described in the wiki to [run Manuskript from source](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux) for now. But the next version should work fine out of the box again (hopefully ^^').

**Comment by hp1706** [comment]
Thank you for your helpful analysis and solution! Much appreciated.
