### ISSUE TITLE
Character Detailed Info Crash

### ISSUE THREAD

**Issue by Tatsuya0200** [olivierkes/manuskript#971]
I'm using Manjaro KDE Plasma, and I've recently started using Manuskript.
The program crashes whenever I try to add a new entry to the "Detailed Info" tab on Characters.
It works just fine for the first item, meaning when it's empty, i can create the first entry. But then, whenever I click again it crashes.

This is where I click:
![image](https://user-images.githubusercontent.com/72259354/145725149-3b053380-3736-4e72-83b6-cd58630f1f4b.png)

is there a solution for this?
Thank you.

**Comment by TheJackiMonster** [comment]
I assume this should be fixed in the develop branch already. Can you try [running it from source](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux)?

**Comment by Tatsuya0200** [comment]
> 

You're right! I tried running it from the source as you suggested, and it works now. 
Thank you very much!
