### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by pvphome** [olivierkes/manuskript#990]
Hello
I translated the interface of Manuskript into Russian (Русский), file [manuskript-translations-ru.ts.zip](https://github.com/olivierkes/manuskript/files/7833300/manuskript-translations-ru.ts.zip)
 attached. Translated all lines published on Weblate. Please check it.
When translating, I noticed that not all of translated strings are shown in Russian when I use translated file downloaded from Weblate. For example, the contents of the "Settings"-"Status" or "Settings"-"Labels" window are shown in English, although the corresponding terms were translated. Besides, some lines are not published on Weblate, for example, the word "Internal" from the import dialog box. Perhaps the lines on Weblate are irrelevant, then please update them so that I'll complete the translation.
P.S. I am using version 13.1 under Manjaro, sorry, forgot to write. :)

**Comment by TheJackiMonster** [comment]
Thank you. You can also open a pull request to commit such changes or make changes via weblate directly. I think weblate is the best way to do that because I personally can't really check if the translations are correct or preferred. Other translators might do that though in discussions. ^^'

But it might be true that certain labels will not be translated depending on the code. This might need some changes then. So thanks for that feedback as well.

**Comment by pvphome** [comment]
> 

I already edited translation on Weblate, this file was made from .ts file downloaded from Weblate.

**Comment by TheJackiMonster** [comment]
Ah, I see. Thanks.

**Comment by pvphome** [comment]
Hi
I've improved a few strings slightly, I won't upload translation in a file again. Please note that the latest version of the Russian translation is the Wordle version. 
And cjuld you tell me when the next version is planned? Maybe I can improve something else before this time. :)

**Comment by TheJackiMonster** [comment]
I will probably look for releasing the next version in March or April because I'm currently kind of busy with other stuff. I usually merge all translations from weblate some weeks before. So everything done there should get into the next release without issues.

**Comment by AndrewDemidov** [comment]
> Hello I translated the interface of Manuskript into Russian (Русский), file [manuskript-translations-ru.ts.zip](https://github.com/olivierkes/manuskript/files/7833300/manuskript-translations-ru.ts.zip) attached. Translated all lines published on Weblate. Please check it. When translating, I noticed that not all of translated strings are shown in Russian when I use translated file downloaded from Weblate. For example, the contents of the "Settings"-"Status" or "Settings"-"Labels" window are shown in English, although the corresponding terms were translated. Besides, some lines are not published on Weblate, for example, the word "Internal" from the import dialog box. Perhaps the lines on Weblate are irrelevant, then please update them so that I'll complete the translation. P.S. I am using version 13.1 under Manjaro, sorry, forgot to write. :)

Looks good. Way better, than the current most-likely-Google-translated version! But some translations could be better, I think. The string "Volume", for example, most likely refers to a separate book ("Том"), rather than the space taken ("Объём") etc..

Does anyone mind, if I join?..

**Comment by AndrewDemidov** [comment]
As a general note: for the purposes of internationalisation counted nouns should be treated specially.

Even though in English only "1 thing/multiple things" are distinguished, it is a good idea to have variations for:
* 0 things;
* 1 thing;
* 2, 3 and 4 things;
* 5 -- 20 things;
* 21 **thing** (not all languages);
* etc..

There should be a way to enable the translators to define different versions for counted nouns.
Example: "translate this message {} times". The "times" should be instead a macro of sorts: 'plural(nThings, {0: "times", 1: "time", 2: "times", 5: "times"})' -- that substitues the correct form depending on nThings.

See also:
* https://upload.wikimedia.org/wikipedia/commons/7/78/How_to_i18n_your_code_-_presentation_for_DevCamp.pdf (particularly page 27 and further);
* https://www.mediawiki.org/wiki/Manual:Messages_API#Be_aware_of_PLURAL_use_on_all_numbers (and down the page);
* https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Plural-forms.html;
* [info in gettext manual -- with helpful formulae!](https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Plural-forms.html)
* [also this!](https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Translating-plural-forms.html#Translating-plural-forms)
* [from translatewiki.net](https://translatewiki.net/wiki/Plural).

Phew, that's a lot of sources...

**Comment by TheJackiMonster** [comment]
> There should be a way to enable the translators to define different versions for counted nouns.
> Example: "translate this message {} times". The "times" should be instead a macro of sorts: 'plural(nThings, {0: "times", 1: "time", 2: "times", 5: "times"})' -- that substitues the correct form depending on nThings.

I think gettext supports that but I assume it would need implementation. We currently use the translate function from Qt with QML. Maybe that supports a similar feature as well.

**Comment by pvphome** [comment]
> 

Yes, I agree. I've corrected it. 
If there are suggestions for translations of terms, let's discuss them here. And it's probably better to do it in Russian, if TheJackiMonster doesn't mind. :)

**Comment by AndrewDemidov** [comment]
> > The string "Volume", for example, most likely refers to a separate book ("Том"), rather than the space taken ("Объём") etc..
> 
> Yes, I agree. I've corrected it. If there are suggestions for translations of terms, let's discuss them here. And it's probably better to do it in Russian, if TheJackiMonster doesn't mind. :)

Then a discussion we'll have!
@TheJackiMonster , if you can hear us... we probably need to discuss matters in different langs... Don't feel left out, please...

HTTP/1.1 101 Switching languages
Connection: upgrade
Upgrade: ru

Хи-хи. Но шутки в сторону.

В прикреплённом раннее архиве я усмотрел интересный перевод термину "world": "окружение". Вроде удачно подобрано, но интересно, почему, например, не "выдуманный мир" или типа того. Вызывает ли "окружение" тот же образ, что и оригинал?

(Или вот например вариант: "Вселенная".)

Также в болваночном скелете "окружения" есть "Волшебные места" и "Магические предметы". Имеет ли смысл их унифицировать или использование разных прилагательных продиктовано некоторой логикой?

Также там был элемент "Organisation", вложенный в "Magic system". Насколько я понимаю, смысл этого элемента -- "как устроена магия" или типа того. Однако в переводе пока даётся: "Организации".

"Гендерные роли"... К чему это слово "гендерные"? Насколько я понимаю, заложенная в это суть -- кто и чем в этой вселенной занимается (кстати, "World" можно перевести и как "Вселенная"...). Получается что-то типа: "Занятия мужские, занятия женские"... А?

"Правительство", возможно, не лучший вариант, я сравниваю с общей картиной, и ближе выходит "Государство", типа "Государственное устройство". Похоже, смысл был в этом.

Насчёт "Этики" неуверен, но понять, что тут не так, сложно... И насчёт "Жестов" тоже... Может, всё-таки оставить "Язык тела"?

Ещё там было "Customs", переведённое как "Разное", но мне кажется, что это всё-таки "Обычаи" (уж во всяком случае не "Таможня", как в текущей версии).

Категории "Physical" и "Cultural"... Если "Культура" вроде бы ничего, то "Физика" мне кажется немного странным выбором...

Может, лучше не "Болезни", а "Заболевания"?

Упс, ещё "Расы магов". Я автоматом думаю: расы людских магов. А там, похоже, имеется в виду: какие существуют виды волшебных/магических существ?

Пока всё.

**Comment by pvphome** [comment]
> (Или вот например вариант: "Вселенная".)
Давайте на нем и остановимся. Плюс синонимы "вымышленный мир" и "мир" просто, а то "обычная вселенная" как-то неправильно звучит. Поправил.

> Также в болваночном скелете "окружения" есть "Волшебные места" и "Магические предметы". Имеет ли смысл их унифицировать или использование разных прилагательных продиктовано некоторой логикой?

Унифицировал до "волшебных".

> Также там был элемент "Organisation", вложенный в "Magic system". Насколько я понимаю, смысл этого элемента -- "как устроена магия" или типа того. Однако в переводе пока даётся: "Организации".

Да, это косяк. Предлагаю вариант "принципы", "в лоб" это все равно не переводится.

> "Гендерные роли"... К чему это слово "гендерные"? Насколько я понимаю, заложенная в это суть -- кто и чем в этой вселенной занимается (кстати, "World" можно перевести и как "Вселенная"...). Получается что-то типа: "Занятия мужские, занятия женские"... А?

Ну, имелись в виду именно "гендерные", которые шире по смыслу, чем "половые". Благодаря всякой там повесточке выражение вошло в оборот, так что думаю, лучше оставить. И потом: мы переводим интерфейс программы, так что "занятия..." могут этот интерфейс порвать, если, к примеру, тот элемент, на котором надпись выведена, не предполагает переносов. Ну или у него может быть фиксированная высота, и просле переноса обрежется верх первой строки и низ второй. В общем, строки перевода должны быть примерно той же длины, что и оригинала. Для русского этого обеспечить нельзя, у него фразы в среднем раза в полтора длиннее, чем в английском. Но "занятия..." -- это все-таки оооочень длинно.

> "Физика" мне кажется немного странным выбором...

Да. По контексту больше подходит "природа", наверно.

> похоже, имеется в виду: какие существуют виды волшебных/магических существ?

Поменял на "Виды существ". 
"Правительство", "жесты", "Customs", "Болезни" поправил.

**Comment by AndrewDemidov** [comment]
> > (Или вот например вариант: "Вселенная".)
> 
> Давайте на нем и остановимся. Плюс синонимы "вымышленный мир" и "мир" просто, а то "обычная вселенная" как-то неправильно звучит. Поправил.

Пускай так и будет. А если в будущем будут новые, более удачные варианты -- изменим.

> > Также в болваночном скелете "окружения" есть "Волшебные места" и "Магические предметы". Имеет ли смысл их унифицировать или использование разных прилагательных продиктовано некоторой логикой?
> 
> Унифицировал до "волшебных".

Прекрасно...

> > Также там был элемент "Organisation", вложенный в "Magic system". Насколько я понимаю, смысл этого элемента -- "как устроена магия" или типа того. Однако в переводе пока даётся: "Организации".
> 
> Да, это косяк. Предлагаю вариант "принципы", "в лоб" это все равно не переводится.

Типа "принципы действия"? Или, может, "принципы работы"? Хотя там уже есть пункт "Правила"...

Может, всё-таки "Принципы действия"...

> > "Гендерные роли"... К чему это слово "гендерные"? Насколько я понимаю, заложенная в это суть -- кто и чем в этой вселенной занимается (кстати, "World" можно перевести и как "Вселенная"...). Получается что-то типа: "Занятия мужские, занятия женские"... А?
> 
> Ну, имелись в виду именно "гендерные", которые шире по смыслу, чем "половые". Благодаря всякой там повесточке выражение вошло в оборот, так что думаю, лучше оставить. И потом: мы переводим интерфейс программы, так что "занятия..." могут этот интерфейс порвать, если, к примеру, тот элемент, на котором надпись выведена, не предполагает переносов. Ну или у него может быть фиксированная высота, и просле переноса обрежется верх первой строки и низ второй. В общем, строки перевода должны быть примерно той же длины, что и оригинала. Для русского этого обеспечить нельзя, у него фразы в среднем раза в полтора длиннее, чем в английском. Но "занятия..." -- это все-таки оооочень длинно.

Ну, если дело в длине...

Но эти самые "роли" всё равно в итоге получаются не понятными интуитивно. Я вот вдумываюсь как могу, и такое ощущение, что: в этот пункт предполагается вписывать, чем занимаются представители различных полов (включая и выдуманных бесполых персонажей, если уж на то пошло...). Типа: "все мужчины были воинами; все женщины сидели с детьми" -- или ещё поколоритнее. А если книжка про космос, всё становится ещё более разнообразно.

Если же внутри каждого пола всё дробится ещё более мелко (только часть мужчин -- воины, плюс валькирии-воительницы), начинать всё равно нужно с простого: с полов.

Впрочем, дело тут, похоже, во слове "роли": Господь с ними, с "гендерными", но "роли"? Почему обязательно "роли"? Люди ведь в обществе не роли играют... А если назначение пункта будет неочевидно, выходит, зря старались...

> > "Физика" мне кажется немного странным выбором...
> 
> Да. По контексту больше подходит "природа", наверно.

А как же всё, что туда вложено? Все эти "Климат", "Топография", "Астрономия"? Вроде бы всё это -- "Природа"; но "История", "Расы" и "Заболевания" внутри "Природы"?

> > похоже, имеется в виду: какие существуют виды волшебных/магических существ?
> 
> Поменял на "Виды существ". "Правительство", "жесты", "Customs", "Болезни" поправил.

Тогда уж "Виды _волшебных_ существ"?

**Comment by AndrewDemidov** [comment]
> > Может, всё-таки "Принципы действия"...
> 
> Ну, или так. Поправил

Чудесненько.

> > Если же внутри каждого пола всё дробится ещё более мелко (только часть мужчин -- воины, плюс валькирии-воительницы), начинать всё равно нужно с простого: с полов.
> 
> Это у "пола" только две опции верхнего уровня. У "гендера" все дробится прямо на этом уровне и на сколько угодно вариантов. И потом: в оригинале именно "гендер" имелся в виду. И термин вполне устоявшийся в русском: https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BD%D0%B4%D0%B5%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%BE%D0%BB%D1%8C

Это всё равно кажется неочевидным, а тем более без ссылок. Пользователь, конечно, может этим пунктом и не пользоваться вовсе, однако неприятное ощущение должно остаться: трудно было занятия разделить по полам? Вот и объясняй ему потом...

> > А как же всё, что туда вложено? Все эти "Климат", "Топография", "Астрономия"? Вроде бы всё это -- "Природа"; но "История", "Расы" и "Заболевания" внутри "Природы"?
> 
> Я не вижу более подходящего короткого термина, который включал бы в себя все вложенные пункты. Ну, может, "естественное", т.е., не созданное человеком, в противоположность "культуре". Но это коряво.

Ну тут я тоже не знаю... Тогда, может, позже что-нибудь придумается...

> > Тогда уж "Виды _волшебных_ существ"?
> 
> Опять длинно. Это будет тогда самый длинный термин будет. А это у нас по факту боковое меню, у которого задача -- предоставить доступ ко всем параметрам "вселенной". Т.е., из-за одного пункта оно у нас раздвинется и отожрет лишнее место на экране.

Тут просто, если не упоминать, что существа волшебные, кажется, что они никакого отношения к магии не имеют. Вот будет список под заголовком "Магия": "Правила, принципы действия, волшебные предметы, волшебные места... и виды существ". Создаётся впечатление, будто бы последний пункт там по ошибке.

**Comment by TheJackiMonster** [comment]
Since the translation into Russion looks complete on Weblate, I would close this issue. Otherwise feel free to open an issue for discussions (I will tag it as discussion then) or discuss translations on Weblate. The translation will make it into the next release then (should come in a few days, I think).
