### ISSUE TITLE
Crash when changing index card style

### ISSUE THREAD

**Issue by amconners** [olivierkes/manuskript#992]
Clicking the "Old style" option in Settings -> Views -> Index Cards causes Manuskript to instantly crash with the following output:

```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/views/corkDelegate.py", line 214, in paint
    self.paint_v1(p, option, index)
  File "/usr/share/manuskript/manuskript/ui/views/corkDelegate.py", line 491, in paint_v1
    r = self.mainLineRect.adjusted(-m, -m, m, m / 2)
TypeError: adjusted(self, int, int, int, int): argument 4 has unexpected type 'float'
WARNING> QPaintDevice: Cannot destroy paint device that is being painted
```
This was in Manuskript 0.13.1 on Arch Linux, installed via the package repository.

**Comment by siliconserf** [comment]
It didn't happen when I exercised the options on my Windows 10 machine, suggesting the issue is in the Linux interface.

**Comment by TheJackiMonster** [comment]
It's probably related to the changes in newer Python. The Windows version uses an older Python version to stay compatible with older Windows versions. This will probably just require an explicit cast to int which older Python versions handle implicitly.
