### ISSUE TITLE
Don't open msk from command line

### ISSUE THREAD

**Issue by Mte90** [olivierkes/manuskript#993]
```
$ manuskript romanzo.msk 
usage: manuskript [-h] [--console] [-v] [-L LOGFILE] [FILENAME]
manuskript: error: unrecognized arguments: romanzo.msk
```
An example of what I get.
Instead if I open the program and use open feature everything is fine.

**Comment by katafrakt** [comment]
What system are you using and how did you install manuskript? I have just checked on Linux and manuskript from git and it seems to work as expected (opens a project).

**Comment by Mte90** [comment]
I tried with the debian one and the code of this repository (I am using that now)

**Comment by katafrakt** [comment]
So you actually call `bin/manuskript` from repository root or `manuskript` from `bin` directory? Or do have it added to `PATH`?

**Comment by Mte90** [comment]
So In the laptop I have the one from the debian repository and I have the issue.
When I had the dev version I think that I had the same issue but i don't remember now.

**Comment by TheJackiMonster** [comment]
Seems to work fine with release 0.14.0 and newer... so I'll close this because I can't reproduce the issue.
