### ISSUE TITLE
An unhandled exception has occurred! on cheatsheet

### ISSUE THREAD

**Issue by Mte90** [olivierkes/manuskript#994]
```
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/cheatSheet.py", line 162, in linkHovered
    QToolTip.showText(QCursor.pos(), Ref.tooltip(link))
  File "/usr/share/manuskript/manuskript/models/references.py", line 519, in tooltip
    return qApp.translate("references", "World: <b>{name}</b>{path}").format(
KeyError: 'nome'
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/cheatSheet.py", line 162, in linkHovered
    QToolTip.showText(QCursor.pos(), Ref.tooltip(link))
  File "/usr/share/manuskript/manuskript/models/references.py", line 519, in tooltip
    return qApp.translate("references", "World: <b>{name}</b>{path}").format(
KeyError: 'nome'
```
I am using manuskript in italian and `nome` means `name` maybe there are some localization issues?

**Comment by Mte90** [comment]
The issue is in the Italian localization:
![immagine](https://user-images.githubusercontent.com/403283/149588375-f5512496-5093-4416-bf54-de13d6b400bf.png)

I already fixed the issue on weblate :-)

**Comment by Mte90** [comment]
Italian localization downloaded and qm file generated and now is not crashing anymore.
With the next update I guess that the issue will gone (I checked also for similar issues in italian and I didn't found anything else).

**Comment by TheJackiMonster** [comment]
Maybe we should add some exception handling around the Qt translate() call. It's very unfortunate that Qt handles a lot of things just by throwing exceptions during runtime. ^^'

Thank you for looking into it and providing a fix.

**Comment by TheJackiMonster** [comment]
Okay, I added (a33249f) a function to safely use the translate() functionality of Qt and catching errors just in case. So the app should not crash anymore because of problems with the translations but put in the original English values from the code instead.
